packages/cozy-harvest-lib/src/components/hooks/useAppLinkWithStoreFallback.jsx

revert this commit https://github.com/cozy/cozy-libs/commit/b9d1fad26ffbcfbf5cbbfe69e685519f837371f3 because of this issue https://github.com/cozy/cozy-client/issues/931
**Contexte :** sur la Home, le bouton "ouvrir les documents" de la modale d'un konnecteur ne fonctionne pas après ouverture/fermeture/ouverture de la modale. Ayant passé du temps pour identifier le problème précisément (et le contourner, voir https://github.com/cozy/cozy-libs/pull/1308), la solution retenue, pour l'instant, est finalement de revert l'utilisation de requête nommée.

fix: Revert using named query for useAppLinkWithStoreFallback

---

packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js

In the Natixis example, there is no value
in the number attribute of the account.
And so when matching the accounts the score
was 0 (no matching).
As a result we had duplicate accounts.
A “rule” has been added which allows to take into
account the case where the "number" attribute
is null.
In this case we use the account ID which
allows for a correspondence.

fix: When no number or null, use id attribute

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx
packages/cozy-harvest-lib/src/components/AccountForm/Field.jsx
packages/cozy-harvest-lib/src/components/AccountForm/__snapshots__/index.spec.jsx.snap
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/__snapshots__/AccountField.spec.js.snap

In previous attempt to handle the overflow, we
decided to calculate the size of the select box
by measuring the size of the Select's container
and calculating the available space.
See #240
But if the SelectBox is near to the bottom of the
container, its size is not big enough.
To fix that issue, we use the fixed position of
ReactSelect to overflow the content and use a
default max-height to 300px.
Since the "container" props was added by the PR
we "revert", I removed them.
After:

fix: Use menuPosition fixed to handle overflow

---

packages/cozy-flags/package.json

The browser entrypoint was removed by error in a unrelated commit.
The commit in question a0856a5fc4b1701376dddabe9065b521a6a0294a
This had the consequence that we could not access browser only methods
after updating cozy-flags.

fix: Revert change on removal of browser

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

There was an error in the naming of the sendTwoFa function
in the BI policy.
This caused 2FA codes not to be sent to BI and harvest was keeping
asking a new code indefinitely.

fix: BI Two FA naming error

---

packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx

The bug was: after opened the viewer, if I touch the "ESC" we close the
"first modal" aka the Harvest one (containing herself this Overlay).
We can pass an `onEscape` props on the `Overlay` component, but in fact
Overlay is below the `Harvest Modal` as you can see we cheated with a
zIndex to display it in top. Since the Modal is "first", then when we
espace, we close the modal (and since the modal contains the Overlay
it closes all the stuff).
To fix that, we use the Modal component from M-UI. Like that, M-UI
handles the "stack component" for us, so the latest opened modal get the
priority for events.
I now import Modal from m-ui itself, but like that I do not need to
update UI. Will do that later.

fix: esc touch does the same as the back button.

---

packages/cozy-harvest-lib/src/components/AccountForm/index.spec.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/CreateAccountButton.jsx
packages/cozy-harvest-lib/src/components/Maintenance/MaintenanceHeader.jsx
packages/cozy-harvest-lib/src/components/Maintenance/MaintenanceIcon.jsx

This way, we do not import the whole cozy-ui. This is particularly 
useful so that the PdfJsViewer file is not imported and thus, there
is no pdfjs worker file; this pdf worker file would cause problems when
developing locally on Chrome due to security measures.
```
Uncaught DOMException: Failed to construct 'Worker'
```

feat: Use deep imports

---

packages/cozy-harvest-lib/src/components/AccountForm/Field.jsx

Before, we set the fontSize to 0 in order to not display the
ObfuscateChar. But by doing so, I do know why, but the
height of the label is not the good one at least on Chromium's
based browser.
To avoid this issue, let's use display none. It will be easier
for Password manager to detect our trick, but we already have
an aria-label saying the same thing. So ...
Before
After

fix: Label height for Account Form

---

packages/cozy-sharing/src/components/ShareDialogCozyToCozy.jsx
packages/cozy-sharing/src/components/ShareModal.jsx

Related to https://trello.com/c/AiQg5Cjr/16-%F0%9F%93%9D-notes-partage-cozy-%C3%A0-cozy-notes-4j
Notes Sharing modal can now use the email feature.

feat: Allow email sharing in Notes

---

packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.spec.jsx
packages/cozy-harvest-lib/src/helpers/triggers.js
packages/cozy-harvest-lib/src/helpers/triggers.spec.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/services/softDeleteOrRestoreAccounts.js
packages/cozy-harvest-lib/src/services/utils.js
packages/cozy-harvest-lib/src/services/utils.spec.js
packages/cozy-harvest-lib/test/fixtures.js

This adds a call to any react native launcher if :
1. the window.cozy.clientSideSlugs property contains a value corresponding to the current connector slug
2. window.ClientConnectorLauncher is initialized with `react-native` value
1) Won't be needed when the stack will handle the "clientSide" attribute in the manifest.
The call to the launcher provides the following values : 
- connector manifest
- account
- trigger
- job
Another addition : for client side connectors, the redirect to the success modale is deactivated when the connector finishes or sends the LOGIN_OK signal

feat: Add client side connector launcher

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json

`Fingerprint phrase` is replaced by `Security code` and 2steps-confirmation instructions have been simplified

feat: Reword contact confirmation dialog

---

packages/cozy-harvest-lib/package.json
yarn.lock

To get a correct BI slug for the Palatine bank
We will also need the 1.1.75 version of the palatine bank connector to
be published before the release of this new harvest in the home or banks
or maif application.

feat(Harvest): Upgrade cozy-bi-auth to v0.0.23

---

packages/cozy-sharing/src/components/Recipient.jsx

Related to: https://trello.com/c/AiQg5Cjr/16-%F0%9F%93%9D-notes-partage-cozy-%C3%A0-cozy-notes-4j
Harmonize styling between cozy to cozy sharing button and by link sharing button, using the same `Typography `variant.

feat: Harmonize `DropdownButton` typography

---

packages/cozy-sharing/src/index.jsx

**Problem**: we need `useSharingInfos` in `cozy-drive`, there is no way around that.
**Solution**: no choice but to expose the hook in `cozy-sharing` in the public API.

feat: Expose useSharingInfos hook as public API

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/Recipient.spec.jsx
packages/cozy-sharing/src/components/ShareDialogCozyToCozy.jsx
packages/cozy-sharing/src/components/ShareDialogCozyToCozy.spec.jsx
packages/cozy-sharing/src/components/ShareDialogTwoStepsConfirmationContainer.jsx
packages/cozy-sharing/src/components/ShareDialogTwoStepsConfirmationContainer.spec.jsx
packages/cozy-sharing/src/components/WhoHasAccess.jsx
packages/cozy-sharing/src/components/recipient.styl
yarn.lock

~~⚠️  this PR cannot be merged yet as it depends on https://github.com/cozy/cozy-ui/pull/1905~~
Instead of displaying `confirm` and `reject` buttons, now a `verify`
button is displayed
The opened dialog now allows to accept or reject the user

feat: Improve two steps confirmation user experience

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/src/ConfirmTrustedRecipientsDialog.jsx
packages/cozy-sharing/src/components/ConfirmTrustedRecipientsDialog.jsx
packages/cozy-sharing/src/index.jsx

⚠️ this PR must not be merged on `feat/redesign_2steps_confirmation` but on `master`. The target branch will be edited after `feat/redesign_2steps_confirmation` merge
⚠️ this PR should not be merged before `feat/redesign_2steps_confirmation`
____
Add a `ConfirmTrustedRecipientsDialog` component that allows the user
to see contacts who need their identity to be confirmed and then
confirm or reject those contacts
`ConfirmTrustedRecipientsDialog` should receive confirmation related
methods in `twoStepsConfirmationMethods` prop
`ConfirmTrustedRecipientsDialog` can retrieve a list of contacts who
need to be confirmed by calling `getRecipientsToBeConfirmed` from those
props. It displays a loading spinner while this method is beeing
processed
`ConfirmTrustedRecipientsDialog` can display a custom …

feat: Add confirm trusted recipients dialog

---

packages/cozy-sharing/src/components/WhoHasAccess.jsx

⚠️ this PR must not be merged on `feat/redesign_2steps_confirmation` but on `master`. The target branch will be edited after `feat/redesign_2steps_confirmation` merge
⚠️ this PR should not be merged before `feat/redesign_2steps_confirmation`
____
When WhoHasAccess is displayed from `SharingDetailsModal`, then no
`recipientsToBeConfirmed` is passed to the component

fix: Set `recipientsToBeConfirmed` default to `[]` on `WhoHasAccess`

---

packages/cozy-sharing/src/components/Recipient.jsx

`<Recipient>` may now be used in not sharing related contexts
This is the case on cozy-pass where the user can display a list of
users that are waiting for identity confirmation (this uses
`ConfirmTrustedRecipientsDialog`)
In this scenario, there is no `avatarPath` to provide as the stack only
supports avatars on the
`/sharings/${sharing.id}/recipients/${recipient.id}/avatar` route
So we want to set `null` image in props instead of an url formatted
with missing attributes. By setting `null` image, then the `Avatar`
component will display the text attribute instead

fix: Display Recipient's initials if no avatarPath or status is provided

---

packages/cozy-app-publish/package.json
yarn.lock

cozy-app-publish uses `verror` package but until today it was installed
from some dependencies of dependencies
This commit force verror installation to ensure it will be available
even if it is removed from dependencies's dependencies
_________
This PR is needed to fix cozy-pass-web CI as it calls `yarn add cozy-app-publish` during the CI and there is no `yarn.lock` file for this project (it uses a npm-lock file instead).

feat: Add verror in cozy-app-publish dependencies

---

packages/cozy-harvest-lib/package.json
yarn.lock

Updating cozy-bi-auth in harvest to add 3 new mapping of connecteurs (2 maif/socram and nalo)

feat: Add new connectors mapping in harvest

---

packages/cozy-harvest-lib/src/datacards/GeoDataCard.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/models/getRelatedAppsSlugs.js

We introduce here a 'harvest.datacard.coachCO2' flag, used to display
the AppLinkCard or AppLinkButton for the CoachCO2 app.
The display rules are the following:
- When there is no data and the flag is enabled: show the AppLinkCard
- When there is no data  and the flag is not enabled: show nothing
- When there is data and the flag is enabled: show the AppLinkButton

feat: Change AppLinkCard behaviour for geojson data

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/appLinksProps.jsx
packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx
packages/cozy-harvest-lib/src/datacards/GeoDataCard.jsx

We now:
- Do not display AppLinkButton for GeoCard
- Display the AppLinkCard below the DataGeoCard (it used to be above)

fix: Change UI for geocard

---

packages/cozy-harvest-lib/src/components/hoc/withKonnectorLocales.jsx

Relying on of non "lifecycled" react variable
is pretty always a bad idea.
Here, we have a bad sync between runtime variable
and react state.
Now the I18n stuff is unmounted when we close the
Modal, but we didn't remove the konnector from
the already loaded konnector. The result was that
when we opened again the modal after having
closed it once, we didn't have the translation loaded.
Let's remove this stuff.

fix: Harvest Konnector translation

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js

In ConnectionFlow, this.konnector can be undefined.
I don't see any justification for that but it won't have any
other nagative effect on the connector exection.
This causes a fatal error on all applications using
harvest and trying to configure an OAuth connector
This is a hotfix.
We will check why this variable is undefined in later investigation

fix: Handle undefined this.konnector for OAuth connectors

---

packages/cozy-flags/README.md

- Import of FlagSwitcher:
We could re-export from the index, to match the current doc, but that would cause a Breaking Change.
I don't know if it's really better
- Condition of flag('switcher'):
The condition does not return `undefined` but rather `null`
(see: https://github.com/cozy/cozy-libs/blob/master/packages/cozy-flags/src/store.js#L35)

fix: Informations on readme

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

In some (too many) case, BI can take more than 30s to give response.
This leads to timeout error message to the user which occur in their
first connection or when renewing their connection.
And since these errors occur in the browser, they are not visible
in our usual connector error dashboard.
We saw that when BI is long to respond, it takes usually 35s to 40s but
in most cases it takes 2s to 3s.

fix: Change timeout to get BI temporary token

---

packages/babel-preset-cozy-app/package.json
yarn.lock

Having a different babel-core version in the babel-preset created a lot of issues when the CI pushed the deploy commit. We now had a difference between packages.json and the lock file. Creating the lock file from scratch broke a lot of libs. Trying to fix every lib one by one has proven to be difficult.
The better way to handle the issue was simply to update the yarn.lock with only one lib (babel-core here). To sum up, never delete and recreate the yarn.lock of a monorepo

fix: Downgrade babel-core in babel-preset

---

packages/cozy-harvest-lib/src/components/AccountForm/__snapshots__/index.spec.jsx.snap
packages/cozy-harvest-lib/src/components/infos/TriggerErrorInfo.jsx
packages/cozy-harvest-lib/src/components/infos/TriggerErrorInfo.spec.js
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

This will display the expected support mail in the message according to
the context.
I had to convert the TriggerErrorInfo to a Component class since it now
needs asynchronous information from io.cozy.settings.

feat: Use configured support address in UNKNOWN_ERROR message

---

packages/cozy-device-helper/src/index.js
packages/cozy-device-helper/src/index.spec.js
packages/cozy-device-helper/src/platform.js

Naive check based on the belief that the react-native app will correctly inject a flag in the webview window

feat: Add a check for flagship app in device-helper

---

packages/cozy-sharing/src/ShareButton.jsx
packages/cozy-sharing/src/ShareButton.spec.jsx

Should remove those warnings in Drive:

fix(sharing): ShareButton should not pass I18n props to Cozy-UI Button

---

packages/cozy-intent/.babelrc
packages/cozy-intent/.eslintrc
packages/cozy-intent/.gitignore
packages/cozy-intent/.npmignore
packages/cozy-intent/package.json
packages/cozy-intent/readme.md
packages/cozy-intent/src/api/constants/index.ts
packages/cozy-intent/src/api/constants/numbers.json
packages/cozy-intent/src/api/constants/strings.json
packages/cozy-intent/src/api/models/environments.ts
packages/cozy-intent/src/api/models/events.ts
packages/cozy-intent/src/api/models/messengers.ts
packages/cozy-intent/src/api/models/methods.ts
packages/cozy-intent/src/api/services/NativeMessenger.ts
packages/cozy-intent/src/api/services/NativeService.ts
packages/cozy-intent/src/api/services/WebviewMessenger.ts
packages/cozy-intent/src/api/services/WebviewService.ts
packages/cozy-intent/src/declarations.d.ts
packages/cozy-intent/src/index.ts
packages/cozy-intent/src/view/components/NativeIntentProvider.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx
packages/cozy-intent/src/view/contexts/NativeContext.ts
packages/cozy-intent/src/view/contexts/WebviewContext.ts
packages/cozy-intent/src/view/hooks/useNativeIntent.ts
packages/cozy-intent/src/view/hooks/useWebviewIntent.ts
packages/cozy-intent/tsconfig.json
yarn.lock

This library allows a react-native and a react app running in a webview to communicate in unidirectional and/or bidirectional fashions. The library is following declarative paradigms and is fully strictly typed. An emphasis has been put on low configuration needs and ease of use.
In a nutshell, one end says what it wants to an other end, and the other end handles it any way it wants. For more information on the underlying systems of this library, see https://github.com/alesgenova/post-me.
The library needs to be installed both in the parent and the children application.
- `yarn add cozy-webview-intent`
- `event`: simple function that sends an event to the listening messenger.
- `intent`: high-level abstraction intended to describe the whole flow of events/methods and the actual result of …

feat: Implement cozy webview intent

---

packages/cozy-intent/package.json
packages/cozy-intent/readme.md
packages/cozy-intent/src/api/constants/numbers.json
packages/cozy-intent/src/api/constants/strings.json
packages/cozy-intent/src/api/services/NativeMessenger.ts
packages/cozy-intent/src/api/services/NativeService.ts
packages/cozy-intent/src/api/services/StaticService.ts
packages/cozy-intent/src/api/services/TypeguardService.ts
packages/cozy-intent/src/view/components/NativeIntentProvider.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx
yarn.lock

Implement secured sync-like handshake initiated by the children when it is ready (this will resolve failed handshake when the Webview takes too long to render)
Implement single localMethods object in ReactNative IntentProvider. All children will use the same method object. This allows all Webviews to call all exposed methods.

feat: Secure initial handshake

---

packages/cozy-codemods/src/transforms/__testfixtures__/transform-radio.input.js
packages/cozy-codemods/src/transforms/__testfixtures__/transform-radio.output.js
packages/cozy-codemods/src/transforms/__tests__/transform-radio.spec.js
packages/cozy-codemods/src/transforms/transform-radio.js

To be able to transform Radio button from old to new API
related to https://github.com/cozy/cozy-ui/pull/1976
Effect: 
```diff
- import Radio from 'cozy-ui/transpiled/react/Radio'
- <Radio
-   value="radioValue1"
-   label="This is a radio button"
-   error={true}
-   disabled={false}
-   gutter={true}
- />
+ import Radio from 'cozy-ui/transpiled/react/Radios'
+ <FormControlLabel
+   value="radioValue1"
+   label="This is a radio button"
+   control={<Radio disabled={false} color="secondary" edge="start" />}
+ />
```

feat: Add codemods for Radio

---

packages/cozy-intent/src/api/models/applications.ts
packages/cozy-intent/src/api/models/methods.ts

Sender can now send app data to the native host in order to open the
native app when available instead of its webview version
---
Related PRs: 
- https://github.com/cozy/cozy-ui/pull/2015
- https://github.com/cozy/cozy-react-native/pull/65

feat: Add `app` parameter to `cozy-intent`'s `openApp` method

---

packages/cozy-intent/package.json

This fixes mismatched versions with other packages
when installing cozy-libs in local env

fix: Pin @babel/core version

---

packages/renovate-config-cozy/package.json

To be able to filter dependencies PR, I suggest renovate add a label called "dependencies"
I follow this documentation:
https://docs.renovatebot.com/configuration-options/#addlabel
Tested in my personal repository:
https://github.com/trollepierre/recontact_travel_blog/blob/dev/.github/renovate.json
And the created PR:
https://github.com/trollepierre/recontact_travel_blog/pull/903

feat(renovate): Add labels dependencies on renovate PR

---

packages/renovate-config-cozy/package.json

We would like to use "fix" as commit type of renovate PR.
According to https://docs.renovatebot.com/semantic-commits/ ,
changing the Semantic Commit type is possible by extending
":semanticCommitTypeAll(fix)" to your extends array.
PR titles and commit messages start with "fix(deps):"

fix(renovate): use fix as commit type of renovate PR

---

packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/src/api/services/NativeService.ts

This PR does two things in cozy-intent:
- Edit `registerWebview` behavior to throw an error if duplicate uri is detected
- This replaces old behavior that only did a silent return
- We prefer to throw an error on those case in order to highlight lifecycle problems
-  Add a `unregisterWebview` method si webviews can unregister themselves when unmounted
- Without this method it would not be possible for a webview to register itself again after being re-rendered (if previously unmounted

Feat: Add unregisterWebview method in cozy-intent NativeServices 

---

packages/cozy-intent/package.json

Use it as devDependencies and peerDependencies
to avoid conflicts with other cozy libs

feat: Update device-help management

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/test/fixtures.js

This defaultFolderPath attribute will be used by the stack recreate the
connector's destination folder if it has been removed by the user.

feat: Add the defaultFolderPath attribute to the account

---

packages/cozy-device-helper/src/index.spec.js
packages/cozy-device-helper/src/platform.js
packages/cozy-device-helper/src/platform.spec.js

It's less confusing to rely on strict boolean retrn value instead of true|falsy value

feat: Ensure isFlagshipApp returns a boolean value

---

packages/cozy-intent/src/api/models/applications.ts
packages/cozy-intent/src/api/models/environments.ts
packages/cozy-intent/src/api/models/methods.ts
packages/cozy-intent/src/api/services/StaticService.ts
packages/cozy-intent/src/tests/mocks.ts
packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx

That way cozy-bar can use the same IntentService as the parent app

feat: Send context to cozy-bar if it exists

---

packages/cozy-intent/src/api/constants/strings.json
packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx

In some instances runtime was trying to read cozy even if undefined and
with an optional chaining operator.
It is now a lot stricter.

fix(cozy-intent): Stricter null-check for cozy-bar

---

packages/renovate-config-cozy/package.json

according to https://docs.renovatebot.com/presets-schedule/#schedulemonthly , I think it's possible to change how renovate works.
After reading, https://breejs.github.io/later/parsers.html#text I updated the value.

fix(renovate): Schedule on Saturday  every month

---

packages/renovate-config-cozy/package.json

This reverts commit bd278a31ef87b584db943e4df2335b319911a9a9.
Because it does not work. :(

Revert "fix(renovate): Schedule on Sunday every month"

---

packages/renovate-config-cozy/package.json

To limit the load of renovate to 5 PRs by repository.

fix(renovate): Limit to 1 PR by hour

---

packages/cozy-intent/src/api/constants/strings.json
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx
packages/cozy-intent/src/view/hooks/useWebviewIntent.spec.tsx
packages/cozy-intent/src/view/hooks/useWebviewIntent.ts

When throwing an error, some race conditions could make an app crash which is very unwanted. Allowing the context to be undefined (which is idiomatic React) is much safer. 
Also reduced the amount of warning output and improved an error message. Updated test file to reflect changes made.

fix(cozy-intent): Allow undefined hook return

---

packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx

Cozy-bar V8 does not have the same API as V7 after further research.
Added an option to inject manually the cozy-bar method to set WebviewContext

fix(cozy-intent): Allow cozy-bar V8 to inject callback

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js

Using CCC, when submiting the form,first the first
time, we don't have any account.
Also, the Cipher stuff will be handled by the flagship
app.

fix(harvest): ConnectionFlow with CCC

---

packages/cozy-intent/src/api/models/applications.ts

Setting the overlay value explicitely is much easier to handle

docs: Update FlagshipUI interface

---

packages/cozy-mespapiers-lib/README.md

En plus du PaperFab fourni par la lib, il est possible d'appeler les 2 modales pour créer un Papier via :
- `/paper/create?backgroundPath=/<currentPath>`: Utilisé par le PaperFab, elle ouvre la modale pour choisir la qualification du Papier avant de commencer la création.
- `/paper/create/<qualificationLabel>?backgroundPath=/<currentPath>`: Elle ouvre directement la modale de création d'un Papier.

docs: Add documentation for calling creation modal

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/BanksLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/DriveLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorUpdateLinker.jsx
packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx

This PR fixes a bug in Flagship app that prevented to open the Store from Home's connector pane when clicking on `See update`.
This is controlled by `KonnectorUpdateLinker` but I reflected the fix on other similar components. This must be tested tomorrow.
I also propagated changes from cozy/cozy-ui#2015 that deprecated `slug` prop from `AppLinker`
---
TODO

Fix harvest's AppLinker usage in order to handle onClick event

---

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json

In the configuration file, we have attribute types on the Information step `Number::12`, which are no longer valid.

fix: Use correct type for define input rules

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/AcquisitionResult.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/AcquisitionResult.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan.spec.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

When we have the option "multipage", cancel the last selected image shows directly the previous one.
From there we can continue to undo the images, select a new image or continue the process (if at least one image exists)
Once on the Acquisition page, save the chosen image directly into the FormDataProvider

fix: Back to Scan step must be displayed file already selected

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js
packages/cozy-harvest-lib/test/fixtures.js

This is a problem especially visible with client side connectors but you can also reproduce it with node connecteur :
When you display the harvest dialog for a trigger which is still running and which runs for the first time, the trigger is marked as not running and the last execution date is "unknown"
For node connecteur, when the LOGIN_SUCCESS event is triggered, we display a popup which explains that authentication is a success and that the user can do someting else, then this bug is not too much pain
But for client side connectors, on LOGIN_SUCCESS, the harvest is displayed and the connector is displayed as not running, which is wrong and suggests an error : 
Now, when a still running trigger is displayed, harvest will mark it a running and watch the corresponding job to get the …

fix: Avoid trigger last execution "unknown" while the connector is still running

---

packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx

Refactoring from 7d06e05cf9cb3647a92c6ab85f2b2262946971c6 introduced a
bug as the `fetchStatus` condition should have been reversed
We didn't notice this error as most of our apps can rely on the
button's `href`
But in ReactNative context, we rely on the onClick behavior in order to
send the correct `openApp` message to the native side
---
Also this PR disable the AppLinkCard's button until `fetchStatus` is `loaded`
to prevent `href` to be called instead of `onClick` if the user clicks on the button
too early

Fix: Correctly handle `onclick` on cozy-harvest-lib's AppLinkCard

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/components/AccountModal.spec.jsx
packages/cozy-harvest-lib/src/components/AccountsListModal.jsx
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/HarvestModalRoot.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/MountPointContext.jsx
packages/cozy-harvest-lib/src/components/MountPointContext.spec.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.spec.jsx
packages/cozy-harvest-lib/src/components/RedirectToAccountFormButton.jsx
packages/cozy-harvest-lib/src/components/RedirectToAccountFormButton.spec.jsx

Using replace instead of push makes things go easier when going back.
But it also means the connector view is one single route
Going back will always go back to the home

feat: Fix back navigation

---

packages/cozy-harvest-lib/package.json
yarn.lock

Upgrade cozy-bi-auth package to 0.0.25. 0.0.24 was published without
building the package

fix: Get correct bi mapping for bnp_es and cic_es

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.spec.jsx

When some connectors have unusual fields, like ovh, this can lead to
have "advancedFields" as identifier field
This is just a protection. The best fix beeing the connector choosing
itself the the best identifer field by adding `role: "identifier"` to
the corresponding field

fix: Avoid to have not sanitized fields as identifier fields

---

packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.jsx
packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.spec.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/ActionMenuImportDropdown.jsx

When a suggestion has the `connectorCriteria` property, we should be able to be redirected to the store (pre-filtered)
As a result of this refactor https://github.com/cozy/mespapiers/commit/f1b8c64, the `currentDefinition` property of the `useStepperDialog` hook is no longer defined in the `ImportDropdown` component.
As we have the `placeholder` object (same as `currentDefinition`) we might as well use it directly

fix: Import choice via connector

---

.travis.yml

Deleting skip-cleanup in https://github.com/cozy/cozy-libs/commit/51ae10dd3411ef0ff8c8434d8d5d02d31ac44722 would make the CI fail when executing the deploy script (i.e. when merging on master)
The observed error is that lerna command is not recognized anymore
and suggests that the node_modules folder doesn't exist anymore
and so skip-cleanup's default behavior doesn't seem
to be applied as described in the travis documentation

fix: Add skip-cleanup to Travis config

---

packages/cozy-mespapiers-lib/src/components/Actions/utils.js
packages/cozy-mespapiers-lib/src/components/Actions/utils.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx

In the options (...) of each line of Paper, on mobile, we want to add the Download action

feat: On mobile, add download action in paper line option

---

packages/cozy-device-helper/src/flagship.ts
packages/cozy-device-helper/src/index.ts

BREAKING CHANGE: flagshipMetadata reference has been replaced with
getFlagshipMetadata().
It returns the same information but adds safety at file init

fix: FlagshipMetadata is now a getter

---

packages/cozy-codemods/src/imports.js
packages/cozy-codemods/src/transforms/__testfixtures__/transform-iconButton.input.js
packages/cozy-codemods/src/transforms/__testfixtures__/transform-iconButton.output.js
packages/cozy-codemods/src/transforms/__tests__/transform-iconButton.spec.js
packages/cozy-codemods/src/transforms/transform-iconButton.js

Simply add `size="medium"` prop if no `size` prop already set.
Ceci dans le but de changer la size par défaut en `large` dans une prochaine version de cozy-ui.
relatif à https://github.com/cozy/cozy-ui/issues/2107

feat: Add codemods for iconButton

---

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json

Cette propriété est utile lors du choix du/des contact(s) à la fin du processus de création d'un papier.

feat: Add multiple prop for select multiple contact if needed

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Home/Home.jsx
packages/cozy-mespapiers-lib/src/components/Home/Home.spec.jsx
packages/cozy-mespapiers-lib/src/components/Home/helpers.js
packages/cozy-mespapiers-lib/src/components/Home/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/ActionMenuImportDropdown.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/FeaturedPlaceholdersList.jsx
packages/cozy-mespapiers-lib/src/components/ThemesFilter/ThemesFilter.jsx
packages/cozy-mespapiers-lib/src/components/ThemesFilter/index.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.spec.js
packages/cozy-mespapiers-lib/src/helpers/queries.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
yarn.lock

On souhaite pouvoir filtrer les papiers sur la home selon les thèmes. Suite à la sélection d'un thème, on affiche tous les papiers correspondants, et toutes les suggestions possible. S'il n'y a aucun papier à afficher, une petite phrase l'indique.
On utilise les nouveaux CircleButton : https://docs.cozy.io/cozy-ui/react/#!/CircleButton

feat: Add papers filter on Home

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/CompositeHeader/CompositeHeader.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputDateAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.spec.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
packages/cozy-mespapiers-lib/src/utils/input.js
yarn.lock

Added the possibility to have an InputMask in the information step when creating a paper, configurable via the configuration file (papersDefinitions.json).
The 2 parameters added are :
- `mask`: To manage the format and the allowed characters.
- maskPlaceholder`: Allows to specify which placeholder to use ("_" by default)
The font used is validated by @joel-costa
PS: je suis preneur de retours mais le dev ayant déjà pris le double du temps estimé...
(Il pourrait, entre autres, avoir plus de tests)

Added the possibility to have an InputMask in the information step

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Home/Home.jsx
packages/cozy-mespapiers-lib/src/components/Home/helpers.js
packages/cozy-mespapiers-lib/src/components/Home/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx
packages/cozy-mespapiers-lib/src/components/SearchInput/index.js
packages/cozy-mespapiers-lib/src/components/ThemesFilter/ThemesFilter.jsx
packages/cozy-mespapiers-lib/src/helpers/queries.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
yarn.lock

On ajoute un change input de recherche afin de faire une recherche sur les papiers de la Home.
Le champ de recherche vient en complément du tri par thème.
Selon les mots tapés dans le champ de recherche, on fait un matching sur le nom du papier ainsi que le label de qualification.

Add search input on Home to filers papers

---

packages/cozy-mespapiers-lib/package.json

no problem with BC of harvest : cozy-keys-lib isn't used here

feat: Synchronize the versions of cozy packages on devDeps/peerDeps

---

packages/cozy-intent/src/api/models/environments.spec.ts
packages/cozy-intent/src/api/models/environments.ts
packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/src/api/services/NativeService.ts

ReactNative webviews can be registered using two forms of sources:
- `source={{ uri }}`
- `source={{ html, baseUrl }}`
Previous code implementation was able to support only the first form
and would crash when a webview is registered with a baseUrl
Not that react-native-webview priorize check on html+baseUrl over uri,
so we chose to implement only `isWebviewSourceBaseUrl` to prevent a
wrong check
More details:
- https://github.com/react-native-webview/react-native-webview/blob/a36394f598944c1ffe288f739b7441830249dc1e/apple/RNCWebView.m#L679-L686
- https://github.com/react-native-webview/react-native-webview/blob/a36394f598944c1ffe288f739b7441830249dc1e/android/src/main/java/com/reactnativecommunity/webview/RNCWebViewManager.java#L513-L518

fix(cozy-intent): Allow to register webviews with baseUrl and no uri

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactList.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactWrapper.jsx

When creating paper, the current user should also be selected by default when multiple selection is enabled at the contact step.

Select current user by default on contact step

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/konnector-policies.js
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

This adds the possibility to create a Budget Insight connection using its [webviews](https://docs.budget-insight.com/reference/webview)
But to activate it, you need to add the harvest.bi.webview flag + specific account_type secrets

feat: Add BI connection creation via BI webview

---

package.json

Since cozy-intent needs a build version of cozy-device-helper to be
built, we update the build command.

chore: Build cozy-device-helper first because of dep in cozy-intent

---

packages/cozy-intent/package.json
yarn.lock

https://app.travis-ci.com/github/cozy/cozy-libs/builds/250570179
When it's a dev-dependency, the publish will fail.
Lerna will not be able to access the typings.
As a real dep, it should be able to.

fix: Add cozy-device-helper as real dependency

---

packages/cozy-intent/package.json
packages/cozy-intent/src/api/models/environments.ts
packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx
packages/cozy-intent/src/view/hooks/useWebviewIntent.spec.tsx
packages/cozy-intent/tests/mocks.ts
yarn.lock

As it's used only once and blocking the CI when publishing,
it is simpler for the time being to decouple the two libs.
We are investigating why is the lerna publishing failing.

fix: Decouple cozy-intent from cozy-device-helper

---

packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/types.js

With BI webviews, we may have multiple bank ids associated to one
connector (ex: crédit agricole) and we don't know in advance what bankid
the user will chose in the BI webview.
Then we save all the list of the bank ids associated to a connector in
the account to let the connector know which banks may have been chosen.
Also, createTemporaryToken is used to translate bankIds to "BI" bank
ids, and bi webview needs all the ids corresponding to a connector, to
propse them to the user. Then createTemporaryToken can know translate
multiple bank ids to bi bank ids
This PR is associated another MR in bi connectors to be able to receive
these multiple bank ids.

feat: Handle banks with mulitple bank ids

---

packages/cozy-mespapiers-lib/src/components/Actions/Items/download.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/forward.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/open.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/select.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/trash.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/viewInDrive.js

Otherwise, when the lib is built, we lose this information essential to the proper functioning

fix: Each action must have a name attribute

---

packages/cozy-mespapiers-lib/src/components/Papers/PaperLine.jsx

The click on a Radio button must call the same function as the parent

fix(cozy-mespapiers-lib): Radio button on multiselect mode

---

packages/cozy-harvest-lib/src/services/biWebView.js

Do not wait the the connector to be run to show the success popup to the
user, since the validity user credentials has already been checked by BI
in the webview.
This is a fix after a feedback on https://trello.com/c/MsGgvX20/397-webview-bi-depuis-une-webview-dans-une-app-native-m%C3%A9canismes-a-rs-avec-browser-inapp-pour-ajouter-un-compte-45-pts

feat: Trigger success sooner for BI webviews

---

packages/cozy-mespapiers-lib/src/components/Contexts/MultiSelectionProvider.jsx
packages/cozy-mespapiers-lib/src/components/Contexts/MultiSelectionProvider.spec.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/ForwardModal.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectViewActions.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

This modal will be mandatory to have the function to transfer to mobile because we can't trigger the native transfer menu asynchronously.
See point 6 for more details: https://w3c.github.io/web-share/#share-method

Feat: Add forward confirm modal

---

packages/cozy-intent/src/api/constants/strings.ts
packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/src/api/services/NativeService.ts

By being too strict when initiating a webview connection,
we made it impossible to handle some edge cases scenarios
who actually need to erase their old session and create a new one
in the same messenger object. Simplest way is to let them
write the new connection over the old one,
indeed the old connection will never be used again

fix(cozy-intent): Allow overriding existing connection

---

yarn.lock

It is no longer necessary or useful to have the import of `mui-bottom-sheet` via `git+` url.
Also it causes confusion in some app updates.

chore: Update main .lock file

---

packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectViewActions.jsx

In multiple selection, if we have only one file selected, no need to create a ZIP file.

fix: Transfer the file directly if only one

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx

Error message : Nothing was returned from render. This usually means a
return statement is missing. Or, to render nothing, return null

fix: Avoid React error message when not in BI webview mode

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/__snapshots__/OAuthForm.spec.js.snap
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/oauth.spec.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.js

A "reconnect" button is now visible when trying to update credentials of
a bi webview connector or any oauth connector.
An addition in io-cozy-account_types secrets is neededed : the
reconnect_endpoint as documented in
https://docs.cozy.io/en/cozy-stack/konnectors-workflow/#reconnect
Implements https://trello.com/c/3UV7zhvJ/448-webview-bi-int%C3%A9gration-dans-le-workflow-de-reconnexion-dune-banque-1-pt

feat: Add BI webview reconnection

---

packages/eslint-config-cozy-app/react.js

Warning: React version specified in eslint-plugin-react-settings must
be a valid semver version, or "detect"; got “latest”

fix(eslint-config-cozy-app): Settings for react

---

packages/cozy-harvest-lib/src/locales/fr.json

For OAUTH apps the wording has to be changed, per the spec
Only account creation is concerned

feat: Update french locale

---

packages/cozy-harvest-lib/src/components/InAppBrowser.jsx
packages/cozy-harvest-lib/src/components/InAppBrowser.spec.jsx

This allows bi webviews or oauth pages to be displayed in inAppBrowser
without user login twice

feat: Add session code inAppBrowser url

---

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx

Causes some errors in banks unit tests and in browser console.

fix: Do not try to display Contract without konnector available

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/helpers.js

to avoid broken tests in Banks, certainly due to obsolete mock

fix(cozy-harvest-lib): Add optionnal chain in some helpers for Contract

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx

This avoids the following behavior in banks

fix: Get proper locale in banks using withLocales

---

packages/cozy-harvest-lib/src/components/KonnectorModalHeader.jsx

The header has 2 width.
One with children, one without children.
It was checking for undefined to decide if it had children or not.
Undefined is not a correct value for a React children,
therefore we now check for the null value.
This allows us to know in sync if we must display the big or the small
icon container.

fix: Fix width flickering in ModalHeader

---

packages/cozy-harvest-lib/src/components/InAppBrowser.jsx

At least on iOS, we have trouble when opening the in app browser. 
It seems that the URL opened by the InAppBrowser contains double encoded character. BI has the good idea to put "/" inside their token. Instead of opening token=t/t or token=t%2Ft we open token=t%252Ft 
We tried a previous fix: https://github.com/cozy/cozy-libs/pull/1685 but it's not working. 
So I add a few logs to have more control over the debug phase.

fix: Do not double encode url

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/connections/triggers.js

Two PR are needed to remove the error message staying, after reconnection of a konnector, this one and https://github.com/cozy/cozy-banks/pull/2404 
The [HarvestBankAccountSettings](https://github.com/cozy/cozy-banks/blob/master/src/ducks/settings/HarvestBankAccountSettings.jsx#L253) give data to HarvestAccountModal using the [HarvestLoader](https://github.com/cozy/cozy-banks/blob/dbc8d428fbeac34bafea11213607fd565e8daed7/src/ducks/settings/HarvestBankAccountSettings.jsx#L179) .
I noticed the data "trigger" that contains `trigger.current_state.status` (knowing if errored or done) was given inside the "accountsAndTriggers" . 
I also modified AccountModal.componentDidUpdate to update the data (flowState), used by harvest lib, to remove the error message displayed. (This PR in …

fix(account): Update trigger while status changed

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.spec.jsx
packages/cozy-mespapiers-lib/src/utils/input.js
packages/cozy-mespapiers-lib/src/utils/input.spec.js

Masked inputs can now be optional, and then any value that matches the start of the mask can be entered.
Also for any optional input, the empty string is now always valid, even if the length does not match min and max length constraints.
This matches the behavior of HTML `<input type="text" />` elements.
This also removes the behavior that swapped `minLength` and `maxLength` when set in the wrong order.

fix(mespapiers-lib): Allow masked inputs to be optional

---

packages/cozy-device-helper/src/flagship.ts

When using ACH in a node environment, isFlaghsipApp is called and throws because `window` does not exist.
Here is the stack-trace when executing ACH on cozy-contacts.
```
yarn run v1.22.17
$ ACH import fixtures/massiveContacts.json
/Users/XXX/.config/yarn/global/nodemodules/cozy-device-helper/dist/flagship.js:21
var flagshipMetadata = ((window$cozy = window.cozy) === null || _window$cozy === void 0 ? void 0 : _window$cozy.flagship) || {};
^
ReferenceError: window is not defined
at Object. (/Users/XXX/.config/yarn/global/nodemodules/cozy-device-helper/dist/flagship.js:21:24)
at Module.compile (node:internal/modules/cjs/loader:1092:14)
at Object.Module.extensions..js (node:internal/modules/cjs/loader:1121:10)
at Module.load (node:internal/modules/cjs/loader:972:32)
at Function.Module.load …
```

fix: Make isFlagshipApp and getFlagshipMetadata work on node environment

---

packages/cozy-mespapiers-lib/README.md

This commit should be theorically in a docs scoped commit.
Currently upgrading cozy-mespapiers-lib is required to validate
Renovate behaviour in our application.

fix(mes-papiers): Fix typos in README.md

---

yarn.lock

This reverts commit b9653bfd22f1525f10d2d88f426bef74e2157213.
Je viens de merger la montée de versions d'handlebars https://github.com/cozy/cozy-libs/pull/1704 . Mais il me semble que cette montée de versions faisait péter les tests à l'époque. Je vais revert. Et je laisserai dependabot recréer la PR. Désolé pour le bruit.

Revert "fix(deps): update dependency handlebars to v4.7.7 [SECURITY]"

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Actions/Items/createPaper.js
packages/cozy-mespapiers-lib/src/components/Actions/Items/select.js
packages/cozy-mespapiers-lib/src/components/Home/Home.jsx
packages/cozy-mespapiers-lib/src/components/MoreOptions/MoreOptions.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectContent.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectPaperList.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectView.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectViewActions.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperCardItem.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperLine.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListWrapper.jsx
packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFab.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
packages/cozy-mespapiers-lib/src/utils/getLinksType.js
packages/cozy-mespapiers-lib/src/utils/getLinksType.spec.js
yarn.lock

Avant:
Le mode de sélection ne permettait que de sélectionner des papiers un par un pour constituer une liste.
Hormis la liste de des fichiers sélectionnés, la navigation pour sélectionner un papier se faisait sans modale.
Les différents composants qui liste les papiers étaient contextualiser.
Après:
Le mode de sélection permet de sélectionner plusieurs papiers à la fois pour constituer une liste.
Tout le parcours se fait dans des modales, une pour lister la sélection en cours(déjà existante) et une autre pour naviguer.
La modale pour naviguer utilise les composants existants pour éviter un maximum de duplication.
Les différents composants qui liste les papiers reste contextualiser.
NB: Le temps alloué sur ce dev est déjà dépassé, du refactor est prévu sur des prochains dev touchant à ses …

Improve Multiselection process

---

packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

BI now allow use to pass a `connection_id` query parameter to directly
open the webview to the management of the given connection id.

feat: Now open the BI manage webview to the correct connection id

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/oauth.spec.js
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

Multiple fixes to the bi webview reconnection :
- Now checkOAuthData and handleOAuthResponse can handle calls without any account id when in reconnection case.
- Do not show identifiers with bi Webviews
- Still run the connector after a full reconnect

fix: bi webviews reconnection

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/components/__snapshots__/OAuthForm.spec.js.snap
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/oauth.spec.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/models/ConnectionFlow.js

The dismiss or cancel action of the user in the oauth window generates
an error message which was not handled by Harvest.
Now, a dismiss action of the user causes the closing of the popup or
InAppBrowser.
This supposes that https://github.com/cozy/cozy-stack/pull/3445 is
merged in cozy-stack to not cause a redirect to the store application.

feat: Handle user dismiss in Oauth window

---

packages/cozy-mespapiers-lib/src/components/Home/Home.jsx
packages/cozy-mespapiers-lib/src/components/Home/Home.spec.jsx
packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx

Au focus du `SearchInput`, `ThemesFilter` doit disparaitre et un `IconButton` apparait à côté du `SearchInput` pour permettre de ré-afficher `ThemesFilter`
En multi-sélection uniquement, `ThemesFilter` ne doit pas apparaitre par défaut, et l'`IconButton` doit être présent.

Manage of the display of filters by theme

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/utils/input.js
packages/cozy-mespapiers-lib/src/utils/input.spec.js

#1695 allowed masked inputs to be optional: the value could be either empty, partial or full, as long as it matched the start of the mask.
This PR restricts this set by disallowing partial values: now only the empty string (for optional inputs) and values that match and fill the entire mask are valid.

fix(mespapiers-lib): Invalidate partial but non-empty values in optional masked inputs

---

package.json
packages/playgrounds/package.json
yarn.lock

After this change #1631, commands like
`yarn start` or `yarn build` on some libs
were causing this error
```
Error: [BABEL]: Cannot find module '@babel/plugin-syntax-jsx'
```
I haven't found out exactly which version fixes this,
but the problem is no longer on version `7.18.6`.

feat: Update @babel/runtime to 7.18.6

---

packages/cozy-doctypes/jest.config.js
packages/cozy-doctypes/package.json
packages/cozy-doctypes/src/banking/BankTransaction.js
packages/cozy-doctypes/src/banking/BankTransaction.spec.js
yarn.lock

We may use this flag with ration to investigate missing transactions
while not generating too many logs

feat: Add warning logs when banking.warn-on-delete flag is activated

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/test/fixtures.js

This caused some regressions in home application. The AccountModal
component would be rerendered infinitely and cause multiple requests
when only updating a trigger

fix: Do not show an error message when the trigger is running

---

packages/cozy-sharing/src/ShareModal.jsx

They do not export any hook, so we just test if they are undefined
If that's the case, the normal props flow will be used instead

fix: Handle old react-routers in ShareModal

---

packages/cozy-sharing/src/components/ShareModal.jsx

Reverting to the code used before email implementation
in Notes share modals

fix: Revert ShareByEmail for Notes

---

packages/cozy-mespapiers-lib/src/components/Home/Home.jsx
packages/cozy-mespapiers-lib/src/components/Home/Home.spec.jsx
packages/cozy-mespapiers-lib/src/helpers/queries.js

La query `buildFilesQueryByLabels` n'était pas optimale avec l'utilisation du sélecteur `$in`
Dernièrement les requêtes pouvaient atteindre 6+ secondes...
Au lieu de lui passer tous les labels de qualification souhaités, il est préférable de retourner tous les fichiers ayant des labels de qualification puis de filtrer dans l'application les qualifications qui correspondent aux labels présents dans le fichier `papersDefinitions.json`
Ainsi le résultat final est inchangé et bien plus performant!

Optimize home query

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js
packages/cozy-harvest-lib/src/types.js

Since this token can last 30 min and can be used many times, and since
there are multiple calls to createTemporaryToken with BI webviews now,
the return value of createTemporaryToken is now cached (29min for
safety)
This make BI webviews interfaces a lot faster
Notes :
* This cache is activated only for bi webview (with harvest.bi.webview
flag set to true
* This cache needs last version of banking connectors which return a
`biMapping` attribute, which allow harvest to translate cozy banks ids
to bi bank ids itself. This value will be cached

feat: Add a cache to BI temporary token

---

packages/cozy-mespapiers-lib/src/components/Viewer/SelectFileButton.jsx

When we select a paper from the Viewer, then we close the multi-selection, we return to the Viewer, but the Viewer does a `goBack` if a history exists (useful to see a selected paper).
But in this present case, we fall into a loop of navigation.
We choose to return to the homepage when closing the multi-selection.

fix: Close the multi-selector returns to the homepage

---

packages/cozy-harvest-lib/package.json

We rely on /lab for some Harvest components. So let's add it to the peerDep section.

chore: Mui/lab has to be in peerDep

---

packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js

Do not update bank accounts when :
- BI account is disabled and there is no corresponding account in stack
- BI account is disabled and there is a corresponding account in stack
which is also disabled
Still do update bank accounts when :
- BI account is disabled and there is a corresponding account in stack
which is enabled

feat: Ignore disabled bank accounts when needed

---

packages/renovate-config-cozy/package.json

Thanks to this commit, Renovate will try to pin only dependencies
Example:
- "react": "16.12.0"
- "cozy-client": "^32.2.0"

fix(renovate): Set caret on cozy-libs, pin on other dependencies

---

packages/cozy-harvest-lib/src/components/InAppBrowser.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/oauth.spec.js

We had a few regressions in our flagship app for our OAuth Konnectors because of the work done for the BI webview: The InAppBrowser was opened but we tried to open it several times resulting an error (because the IAB can be only open once) since fetchSessionCode() was returning an error. 
This PR fix these issues.

Fix Oauth Flow in non intentsApi apps

---

packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

This avoids fatal error when the token in cache is associated to an old BI user.
BI user can change when the user removes all of his BI connections. In that case, the connector will also remove the current BI user.
The next createTemporaryToken job will create a new BI user

fix: Invalidate temporary token cache when there is a change of BI user

---

packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js

If no connector is given by calling app, the Route.jsx wouldn't be able
to display anything and would throw when trying to access connector
props
To allow `cozy-harvest-lib` to display the connector anyway, we can
fetch connector data from cozy-stack based on the new `konnectorSlug`
prop
This scenario may happen in flagship app if RealTime is not active on
`cozy-home` and the app asks `cozy-home` to display a newly installed
connector
However this does not allow to display a not installed connector. If so
`cozy-harvest-lib` would throw as before
___
Implementation is based on https://github.com/cozy/cozy-harvest-app/blob/f4ee79865a9e74bf67f12d1ca9d85f9905e65f4a/src/hooks/useKonnectorWithTriggers.js

feat: Fetch connector from cozy-stack if undefined

---

packages/cozy-harvest-lib/src/components/InAppBrowser.jsx

for inAppBrowser with custom intentsApi
This will avoid an error log

fix: Expect a state attribute in showInAppBrowser result

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/__snapshots__/OAuthForm.spec.js.snap

When the trigger is in a state which needs reconnection and when the
user clicks on the "Reconnect" button, he still needed to click on a
"reconnect" button one more time to display the BI webview.
Now the BI webview is displayed directly.
There are still some screens we don't want to display after the BI
webview but this will be fixed in another PR

fix: Remove a reconnection step

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/OAuthWindow.jsx

- fix: Let OAuthForm component decide when to remove the OAuth window
- feat: Close OAuthWindow only on login success
This avoids to have unwanted previous screen displayed while waiting for harvest to complete the OAuth account creation

fix: Let OAuthForm component decide when to remove the OAuth window

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Contact.jsx
packages/cozy-mespapiers-lib/src/components/Papers/helpers.js

~~The current user and contacts are usually listed together in the app `mespapiers` even if they don't share the same data shape.~~
~~For example, the name parts are missing from the user.~~
The mismatch seems to only happen in dev environnement until the profile for the current user is edited.
~~This PR introduces an helper that either shows the fullname if present, or the display name if not, as a workaround for this mismatch.~~
Using `getDisplayName` directly should be sufficient in production environnement.
This fixes the empty names that could appear by showing an email address if available, and also fixes the save failing for documents not only owned by the current user.

Show the display name instead of the fullname

---

packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/src/utils/input.js
packages/cozy-mespapiers-lib/src/utils/input.spec.js

Après discussions, nous essayons de coller au maximum aux comportements standard de l'`input` de type `text`
A la différence de l'attribut `required` qui, si défini, oblige de renseigner la totalité du `mask`, excepté si il est couplé avec l'attribut `minLength`.
Les contraintes connus aujourd'hui sont les suivantes :
- Ne pas obliger le renseignement
- Obliger le renseignement :
- Obliger la complétion totale du `mask`
- Obliger un minimum de caractères. (Raison: Selon le document, certains renseignements peuvent être plus courts d'une personne à l'autre)
Avant :
- `minLength` : Attribut ignoré
- `required` : 
- `true` : Oblige de renseigner totalement le `mask`
- `false`(ou non présent) : Permet la validation vide ou totale
Après :
- `minLength` : Permet la validation vide ou avec le …

feat: Add minLength constraint to InputMask

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BIContractActivationWindow.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

The goal is to avoid to display the BI manage webview which allows
modify, delete or create other BI connections of the user, which we
cannot handle on cozy side at the moment.
The user will need to enter it's own bank credentials before modifying
accounts synchronization.
The webview will close on its own.

feat: Use BI account creation webview to handle accounts synchonization

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BIContractActivationWindow.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

Before, we detected a reconnect with the presence of a connection id in
the account. But if we use the creation BI webview to handle
synchronizations, there will be a connection id in the account and the
wrong url parameters will be used.
Related to https://github.com/cozy/cozy-libs/pull/1788

fix: RefreshContracts now updates contracts in realtime

---

.travis.yml

Current "test" job is responsible for running build, lint and tests, so
its name is more about building the project than just testing it
This commit renames it "build" to have a clearer intention
___

fix: Rename build job

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactList.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactWrapper.jsx

It is no longer possible to submit the contact step with the ENTER key
when no contact is assigned or when it is covered by another modal.

Prevent implicit submission of the contact form when the submit button is disabled

---

packages/cozy-harvest-lib/README.md

Konnectors doctype is io.cozy.konnectors and not io.cozy.apps

fix: Misleading example konnectors request in readme file

---

packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

In current implementation, when opening Harvest with an application
slug that does not exist, the opened dialog shows a javascript error
When this happens, we want to automatically close the dialog and
display an error message instead
New behaviour (video is a bit laggy but this is due to my computer+recorder):
https://user-images.githubusercontent.com/1884255/186463201-68df1f9d-19ec-429d-95f7-8fa743a7d6fc.mp4

fix(harvest): Handle not existing applications

---

packages/cozy-authentication/package.json
packages/cozy-codemods/package.json
packages/cozy-doctypes/package.json
packages/cozy-interapp/package.json
packages/cozy-logger/package.json
packages/cozy-mjml/package.json
packages/cozy-procedures/package.json
packages/cozy-scanner/package.json

We add issue on a few packages since we have
added a new travis' job. Indeed, the
"repo doctor"'s job is the first one to be run.
So it's also the one to handle the lerna
process to publish. But since this job doesn't
build the package, we can have published package
without all the build stuff in it.
So let's add a prepublish script to all the
repo in order to not have issue and dep with
the job's order.

fix: Add prepublish script

---

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json

The last part was missing a character.
The first part must be alphanumeric.
See https://bit.ly/3PYG9hB for more details

fix: Mask of vehicle registration

---

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

These modifications allow a better understanding for the user when the user tried to create an account with identifiers which are already associated to an existing account.
With BI webviews, it is possible to update contract synchronization for the existing account and we need to be synchronized with it.
- fix: Better msg on ACCOUNT_WITH_SAME_IDENTIFIER_ALREADY_DEFINED error
- fix: Add realtime on bank accounts

fix: Better behavior on ACCOUNT_WITH_SAME_IDENTIFIER_ALREADY_DEFINED error

---

packages/cozy-device-helper/src/flagship.ts

In order to give the webview information about biometry capabilites,
it is necessary that we update the interface so the consuming apps
are aware of the new option and what values it can hold.
The actual injection still has to be done in the native application.

feat: Update FlagshipMetadata interface

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx

This was a regression from BI webview evolution to open oauth window
from reconnect button

fix: Open oauth window for oauth connectors

---

packages/cozy-intent/src/api/models/methods.ts
packages/cozy-intent/src/api/services/NativeService.ts
packages/cozy-intent/src/api/services/WebviewService.ts

Add new method allowing to open the management of the biometry
setting on the react native application.
Please note that this is NOT an implementation,
but merely an API signature.
It has purely no effect except documentation in js files,
and type checking in ts files

feat: Update methods interface for biometry

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx

To transmit this param to OAuthWindow ultimately
This fixes an OAuthPopup which would not open in InAppBrowser without it
when the user clicks on the Reconnect Button from a BI error message.

fix: Add missing intentsApi prop in DumbEditAccountModal

---

packages/cozy-mespapiers-lib/README.md
packages/cozy-mespapiers-lib/babel.config.js
packages/cozy-mespapiers-lib/preprocess.js

BREAKING CHANGE: In order to have the css styles specific to some components of `cozy-mespapiers-lib`, you need to add the following import to the base of your application: `import 'cozy-mespapiers-lib/dist/stylesheet.css'`

Add stylus configuration

---

packages/cozy-harvest-lib/src/services/utils.js
packages/cozy-harvest-lib/src/services/utils.spec.js

We had errors in the logs supposively because an encrypted string was either empty or malformed.

fix: Deal with empty and malformed encrypted values

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
packages/cozy-mespapiers-lib/src/utils/input.js
packages/cozy-mespapiers-lib/src/utils/input.spec.js

Lors de la création d'un papier, on souhaite interdire la possibilité de créer un nom avec seulement des espaces. Dans ce cas, on affiche un message d'erreur, et on interdit la possibilité de passer à l'étape suivante.

mesPapiers : Prohibits putting only spaces in a  document name

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Contexts/ScannerI18nProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/useCurrentEditInformations.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/FeaturedPlaceholdersList.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.spec.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/CreatePaperModal.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialogWrapper.jsx
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.spec.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
packages/cozy-mespapiers-lib/test/mockPaperDefinitions.js
yarn.lock

Maintenant, suite à la version 33.1.0 de [cozy-client](https://github.com/cozy/cozy-client/releases/tag/v33.1.0), nous pouvons spécifier les papiers suivants :
- Carte d'identité (🇫🇷)
- Permis de conduire (🇫🇷)
- Permis de conduire (Étranger)
Les libellés de qualification restes les mêmes, l'ajout de attribut `country` permet de spécifier le pays et ainsi suivre un process de création différent.

Add driver_license paper for the strangers

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.spec.js
yarn.lock

Si l'attribut `country` est présent mais vide("") dans les metadata du fichier, lors de la modification, nous devons bien le considérer comme un papier non FR

fix(mespapiers): Modification of the `country` attribute if empty

---

packages/cozy-realtime/src/RealtimePlugin.js
packages/cozy-realtime/src/RealtimePlugin.spec.js

It is especially needed in harvest to send notification from harvest
to the banks application to know when a job is waited for.
And since the realtime plugin is supposed to expose the same api as
CozyRealtime

fix: Expose sendNotification from cozy-client realtime plugin

---

packages/cozy-intent/src/api/models/methods.ts

Params can be a hashed PIN value for instance.
The type Record<string, unknown> is lax on purpose, I don't know what will be exactly needed so it sounds better to let the developer some freedom here

feat: Add possibility to use params in toggleSetting()

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

via OAuthFormWrapperCompProps and without unmounting/remounting
OauthForm on each rerender
This avoids the disparition of the BI webview in banks when a new job is
expected

feat: Allow to pass custom Properties to OAuthForm wrapper

---

packages/cozy-authentication/src/steps/SelectServer.jsx

Since a few versions, Cozy-UI's input
has been converted to function with a
forwardRef.
It results that the ref callback can
be called after the didMount() method
so calling focus() on it crash the app.
Since cozy-auth is only on "maintenance"
mode, I just remove this focus stuff since
almost all webviews will focus on the input
if there is only one displayed.

fix: This.input is not defined

---

packages/cozy-harvest-lib/src/components/Popup.jsx

When an OAuth popup was blocked, we got "null is not an object" error in
console.
Now we will get "Popup was blocked by browser. Be sure to not call
showPopup asynchronously" which may be more explicit

fix: Add explicit blocked popup message

---

packages/cozy-mespapiers-lib/README.md
packages/cozy-mespapiers-lib/src/components/AppRouter.jsx
packages/cozy-mespapiers-lib/src/components/OnboardedGuardedRoute.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListWrapper.jsx

Cette PR traite 2 sujets autour du routeur de la `cozy-mespapiers-lib` :
- Lors de la mise à jour du routeur, nous avons changé les redirections sur la page d'accueil de `/paper` à `/`, sans raison particulière. Mais en conséquence, c'était la route de redirection du côté de l'application qui était trigger, et cela provoquait un démontage/remontage de la lib.
- Depuis la mise à jour du routeur, les applications n'étaient plus forcées d'utiliser la route `/paper` pour consommer la lib. Ce changement n'était pas prévu. Avec cette correction, nous retrouvons l'ancien comportement attendu. A la différence de l'ajout du `/*`comme ceci `/paper/*` requis avec le nouveau routeur.
Exemple :
```
<Route path="/paper/*" element={<PaperView />} />
```

Fixes path of the redirections

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

This commit reapplies 8a6f02b9e9c161622afedff88ba4805468ee6f59 that has been removed in 439e603cef915e9fede72ae293ae35ca330347eb due to regression on cozy-bank app
Today this regression cannot be reproduced anymore when we reapply the initial commit
So we want to reapply it so we can upgrade cozy-keys-lib to latest version

fix: Reapply useVaultClient hook call in LegacyTriggerManager

---

packages/cozy-app-publish/README.md

This PR documents how to publish beta versions of an app in `cozy-apps-registry` using `cozy-app-publish`

docs: Document publishing beta versions

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BIContractActivationWindow.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/oauth.spec.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/types.js

When the user wants to manage his own account and then displays the BI "manage" url, he may remove the BI connection from it.
If the connection is removed, the corresponding account and trigger will also be removed via webhooks.
This is why it is not possible to go back to the display of the current account if the connection has been removed.
How it works :
The BI webview adds a connection_deleted parameters to the redirect uri, this parameter goes to OAuthWindow via realtime, and then BIContractActivationWindows
And in this case, BIContractActivationWindow displays a dialog to explain the situation to the user and then closes the harvest dialog.

feat: Close Harvest when BI connection is removed in webview

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/VaultUnlockProvider/index.jsx

In cozy/cozy-keys-lib@1e715624654bcd7c66f6fe7d6558d782f336d0fd we
refactored `<VaultUnlockProvider />` so we can inject
`checkShouldUnlock` into it
This method should allow the component to check if the Cozy's vault
need to be unlock before accessing Harvest
We choose to inject it from the parent component as we expect some
scenario to implement their own verification process (i.e: cozy-drive
for folder encryption)
Here we don't need a custom implementation, so we use the one provided
by CozyUtils

fix: Make cozy-harvest-lib works with cozy-keys-lib V4

---

packages/cozy-device-helper/src/flagship.ts
packages/cozy-intent/src/api/models/methods.ts

On iOS with FaceID the biometry feature is guarded by OS level authorizations
If the user reject the authorisation process, then the application won't be able to use FaceID anymore until the user re-authorizes it from the OS settings
We want this information to be available from the settings cozy-app and to be able to redirect the user to the OS settings
so they can re-autorize the biometry
___
- https://github.com/cozy/cozy-settings/pull/512
- https://github.com/cozy/cozy-flagship-app/pull/457

feat: Handle denied biometry access on iOS

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx

This store update will espacially allow banks to update the
connected/disconnected status of it's accounts without adding realtime
on accounts, which causes more troubles for OAuthWindow component which
will unmount.
This is a quick fix. A better approach is in progress to make
OAuthWindow independent of Harvest components tree

fix: Dispatch account deletion after BI connection deletion

---

packages/cozy-sharing/package.json
packages/cozy-sharing/src/ShareButtonWithRecipients.jsx
packages/cozy-sharing/src/SharingProvider.jsx
packages/cozy-sharing/src/index.jsx
yarn.lock

In the cozy-notes with a lot of notes and sharing, there are some late requests. The ShareButton button doesn't wait for everything to be finished to appear. The user may be confused because an already shared note appears unshared first. I take this opportunity to pool two components in order to manage their state together.
- https://github.com/cozy/cozy-ui/pull/2286

Feat: Add share button with recipients

---

packages/cozy-harvest-lib/src/services/biWebView.js

When an account is created by stack after a BI webhook, it does not have
the `oauth.query.connection_id` attribute but in `data.auth.bi.connId`.
We keep the handling of `oauth.query.connection_id` for compatibility
while bi webhooks are not fully deployed.
- fix: BiWebview handle accounts created after bi webhooks
- fix: Mistake on harvest.bi.fullwebhooks flag

fix: BiWebview handle accounts created after bi webhooks

---

packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx

La façon d'utiliser les List de cozy-ui a changé (la doc https://docs.cozy.io/cozy-ui/react/#!/List là-bas est à jour) donc petit correctif ici pour ajuster.

fix(mespapiers): Fix spaces in and around paper  list

---

packages/cozy-harvest-lib/src/components/CozyConfirmDialogProvider/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BIContractActivationWindow.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
packages/cozy-harvest-lib/src/components/OAuthService.js
packages/cozy-harvest-lib/src/components/OAuthService.spec.js
packages/cozy-harvest-lib/src/components/PopupService.js
packages/cozy-harvest-lib/src/components/PopupService.spec.js
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/helpers/windowWrapper.js
packages/cozy-harvest-lib/src/helpers/windowWrapperMocks.js
packages/cozy-harvest-lib/src/index.js

Creation of a new OAuthService class to handle all OAuth communiction
without depending on React component tree
We had to transform Popup.jsx and OAuthWindow.jsx into functions to
avoid to be blocked by browser when opening a popup (Too many useEffect
with render tend to block the popup)- feat: Use independant OAuth window
- feat: Add independent confirm dialog
Still to do :
- migrate OAuthForm to OAuthService
- migrate KonnectorAccountTabs to OAuthService
- remove OAuthWindow.jsx and Popup.jsx

feat: Use independant OAuth window

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
yarn.lock

Adding support of resume, health insurance card, tax timetable and other invoice papers
BREAKING CHANGE: you need to upgrade `cozy-client >= 34.2.0` . Update needed to get https://github.com/cozy/cozy-client/pull/1275 for "other invoice" support
comportement validé en local avec @BenjaminMty

MesPapiers: upgrade cozy-client and add new paper support

---

packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/components/FlowProvider.spec.jsx

This information is needed by a b2c app

fix: Add konnector slug in fake trigger passed to onLoginSuccess

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/OAuthService.js
packages/cozy-harvest-lib/src/components/OAuthService.spec.js
packages/cozy-harvest-lib/src/components/PopupService.js

Instead of OAuthWindow component
The OAuthService service is not subject to multiple rerenders of the component tree.
In this case, it especially avoids calling the display of inApp Browser multiple times in b2c app depending on rerenders of OAuthForm component
- docs: Fix PopupService jsdoc
- refactor: Export constants for OAuthService result types
- feat: Use OAuthService in OAuthForm
- feat: Use OAuthService in KonnectorAccountTabs

feat: Use OAuthService in OAuthForm and KonnectorAccountTabs

---

packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

As said in the dialog description, the deletion is made in parallel to the dialog opening.

fix(harvest): Update wording for Bank disconnect dialog close button

---

packages/cozy-harvest-lib/src/services/biWebView.js
packages/cozy-harvest-lib/src/services/biWebView.spec.js

Since, BI ACCOUNT_ENABLED and ACCOUNT_DISABLED webhooks can also
trigger the update of banking accounts. We can face 409 update
conflicts with a client.save if it involves a lot of banking accounts.

fix: Only update cozy-client store when refreshing contracts

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js

We initially grouped by `sourceAccount` which is the id of the account used by a connector. However, if we disconnect an account from a connector, it is deleted. So when you reconnect, you create a new account, with a new `sourceAccount`. So we can't gather the documents according to this.
We now rely on the slug of the connector and the `sourceAccountIdentifier` (which is usually the login of the account) to avoid gathering documents with the same login but from different connectors.

fix(mespapiers): Group papers by connector identifier

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Papers/ExpirationAnnotation.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
yarn.lock

This will be on top of cozy/cozy-client#1274 and cozy/cozy-ui#2294 and thus will need an update of `cozy-client` and `cozy-ui`.

Add expiration annotation to cozy mespapiers lib

---

packages/cozy-mespapiers-lib/src/helpers/queries.js

This allows to display expiration annotations in paper items while searching or filtering by theme without having to open them first to populate the file objects with these attributes.

Query expiration attributes for search and theme

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js

Some old bank accounts, without any associated running connector, may
have no "connection" relationship.
Adding a protection against this.

fix: Error on bank accounts without connection relationship

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

Changement du texte d'en-tête présent dans la liste des papiers pour les fichiers provenant de connecteur (et n'ayant pas de contacts associés)

feat(mesPapiers): Change the wording of the parpersList header

---

packages/cozy-sharing/src/components/ShareModal.jsx
packages/cozy-sharing/src/components/ShareModal.spec.js

The previous check was too strong and the Share modal disappeared in some apps like Drive.
I also added unit test to check the good behavior because it can make crazy.

fix: Reactive share modal for all apps

---

packages/cozy-authentication/src/steps/ButtonLinkRegistration.jsx

We removed Matomo so pk_campaign query string are not useful anymore.
```
- Remove pk_campaign query string in links in cozy-authentication
```

feat: Remove pk_campaign query string in links

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Papers/ExpirationAnnotation.jsx
yarn.lock

This basically removes the "about" / "environ" before some durations.

Use `formatLocallyDistanceToNowStrict` for expiration annotations

---

packages/cozy-authentication/package.json
packages/cozy-authentication/src/MobileRouter.jsx

This adds an alternate implementation for `MobileRouter` to help to upgrade React Router in apps consuming `cozy-authentication`.
This new one is written with `react-router-dom@6`, while the previous one, written with `react-router@3` is kept for retro-compatibility.
Apps can opt for the new implementation by omitting the `history` prop which is then mocked with modern hooks internally.
(untested for now, so kept as a draft)

Support React Router DOM V6 in cozy authentication

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js

Files both created by a connector and linked to some contacts used to be grouped based on contact information only.
Now only connector information matters for them.
The display order of paper sections remains unchanged (connectors first, then contacts and finally unspecified papers).

Mes Papiers : Group papers under their source account, even if they have an owner 

---

packages/cozy-sharing/src/SharingProvider.jsx
packages/cozy-sharing/src/queries/queries.js

findApps is now deprecated on Cozy-Client
(cozy/cozy-client#1293)
So let's use a named query with a fetchPolicy
in order to leverage CozyClient cache.

fix: Don't call PermissionCol.findApps

---

packages/cozy-authentication/src/MobileRouter.jsx

Apps may want to redirect the user once logged in or logged out.
They need the `history` object for that, so it is passed back to `onAuthenticated` (for Banks and Drive) and `onLogout` (for Drive).

Authentication: Pass the `history` object back to `onAuthenticated`

---

packages/cozy-sharing/src/components/badge.styl

The portage color has been remove from cozy-ui (cc: https://github.com/cozy/cozy-ui/commit/5fd473af94b9febeef8523bdc42375930cdea11c)

fix: Color for badge with me

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx

This adds a menu to the new `LaunchTriggerAlert`. The only action in the menu for now is "Synchronize" (still called "Run again now") which does the same thing as the button that is already in the alert. More actions will be added such as "Configure".

Add `LaunchTriggerAlert` menu with the first action

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalContentWrapper.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalHeader.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalWithoutTabs.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/Error.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/OpenOAuthWindowButton.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/TriggerError.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/TriggerErrorAction.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/helpers.js
packages/cozy-harvest-lib/src/components/Routes/RoutesV6.jsx
packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/helpers/accounts.js

Dans cette PR nous ajoutons 2 routes pour afficher une version de la modale `AccountModal`, sans la navigation par tabs mais par URL (`accounts/:accountId` & `accounts/:accountId/config`).
Ces nouvelles routes ne seront disponibles qu'avec le flag `harvest.inappconnectors.enabled` activé et sur les apps qui seront compatibles avec `react-router-dom@6.x.x`

Feat(Harvest): Split Modal Account into 2 separate routes

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/AcquisitionResult.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/AcquisitionResult.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.spec.js

On iOS, taking a photo with `FileInput capture="environment" />` will always return a file named `image.jpg`
In previous implementation we compared the image's name to prevent duplication which would not work on iOS as all files would have the same name. Result is that we wouldn't be able to upload multiple photo
To prevent this we also want to compare the image's `lastModified` field that should be unique for each photo capture

fix(mes-papiers-lib): Check file's `lastModified` field on file upload

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/FovV4Router/AccountModalContentWrapper.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/FovV4Router/AccountModalWithoutTabs.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/Routes/RoutesV4.jsx
packages/cozy-harvest-lib/src/components/Routes/RoutesV6.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx
packages/cozy-harvest-lib/src/components/hoc/withRouter.jsx
packages/cozy-harvest-lib/src/components/hoc/withRouter.spec.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

On souhaite ajouter dans le menu des options de bandeau d'état d'un connecteur, 
le possibilité d'afficher les configurations. Or nous avons précédemment 
découpé le composant pour rendre la partie data et config accessible via une 
route, mais uniquement pour le router v6. Ici il a fallut donc faire de même 
pour la v4 du router avant d'ajouter l'option.

Add configuration menu in LaunchTriggerAlert

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx

A better way to do this would be to initially see in the mockups that
the Alert component was not used as proposed by cozy-ui. Since this
is an isolated case (and we don't have time to review the specs and fix
it on the cozy-ui side) for now let's do an application side fix.

fix(harvest): LaunchTriggerAlert text vertical alignement

---

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

Apply the same text present in the information step (referencedDate) of otherInvoice for all invoices

feat(mespapiers-lib): Change wording on information step for invoices

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Views/Home.jsx
yarn.lock

Depuis [cozy-client@34.6.2](https://github.com/cozy/cozy-client/releases/tag/v34.6.2), envoyer une valeur non booléenne à l'option `enabled` de useQuery cause une erreur.
Ce fix sur cozy-client permettra de mieux comprendre et cibler la cause de l'erreur
https://github.com/cozy/cozy-client/pull/1306

Fix(mespapiers-lib)/Activation condition of contact query at Home component

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalContentWrapper.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalWithoutTabs.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/FovV4Router/AccountModalContentWrapper.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/FovV4Router/AccountModalWithoutTabs.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/OpenOAuthWindowButton.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/TriggerError.jsx
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/TriggerErrorAction.jsx

Il manquait dans la nouvelle version de l'AccountModal des props utiles pour une app cliente.
Il aurait sans doute été préférable d'utiliser un contexte depuis ce point d'entrée (`AccountModalWithoutTabs`).
A revoir si/quand on repassera dessus @doubleface @JF-Cozy

feat(harvest-lib): Add missing props to new Account modal

---

packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx

There can be several Accounts on the same Connector, therefore several Triggers.
It is therefore necessary to be able to differentiate each Account with its respective list of papers.

fix(mespapiers-lib): Use the trigger corresponding to the account

---

packages/cozy-sharing/src/share.styl

When it was displayed on mobile, the content was limited to the size of the button which not enough. Not it is limited to the size of the button wrapper.

fix: Allow content to go full size in share by email select box

---

packages/eslint-config-cozy-app/basics.js
packages/eslint-config-cozy-app/package.json
yarn.lock

En accord avec nos échanges internes, le mieux est d'ajouter les 2 règles que l'on souhaitait à la base.
Rien n'empêchera d'en ajouter de nouvelles ou mieux de passer sur la config recommandée.
Les 2 nouvelles règles sont donc : (elles font partie des règles recommandées)
- `'jest/no-focused-tests': 'error'`: [Disallow focused tests](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-focused-tests.md)
- `'jest/no-disabled-tests'`: [Warn disabled tests](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-disabled-tests.md)

chore(eslint-config-cozy-app): Add 2 rules for tests files

---

packages/cozy-harvest-lib/src/components/AccountForm/ConnectionBackdrop.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx

Remove the close icon button introduced in #1929 and thus the ability to close the connection backdrop.

Remove the ability to close the connection backdrop

---

packages/cozy-sharing/src/components/ConfirmTrustedRecipientsDialog.jsx

Due to rsync misunderstandings, I forgot to update an import of a file I moved.

fix: Recipient import path not updated in last update

---

packages/cozy-harvest-lib/src/components/Routes.jsx

This vertically centers the dialog when the flag `harvest.inappconnectors.enabled` is set.
Initially it was aligned at the top to prevent having layout shift when switching tabs, but tabs have been removed behind the flag.
The top alignment is kept when the flag is not set.

Vertically center harvest dialog when not using tabs

---

packages/cozy-harvest-lib/src/components/Routes/RoutesV4.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlertMenu.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/components/cards/helpers.js
packages/cozy-harvest-lib/src/components/cards/helpers.spec.js
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

On souhaite pouvoir afficher le bandeau du connecteur même pour les comptes déconnectés. Dans ce cas on s'attend à certains comportements et wording. Cette PR traite ce sujet.

Deal with disconnected account in LaunchTriggerAlert

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx

With the new synchronization banner, closing the edit modal must redirect to the configuration modal

fix(harvest-lib): Redirection when close EditAccountModal

---

packages/cozy-sharing/src/SharingBanner/hooks/useSharingInfos.jsx
packages/cozy-sharing/src/SharingBanner/index.jsx

By default, previewPath is /preview but we needed to be /preview/ into cozy-notes. That's why, we can add previewPath to SharingBanner

fix(SharingBanner): Add custom previewPath

---

packages/cozy-mespapiers-lib/src/components/MesPapiersLibLayout.jsx
packages/cozy-mespapiers-lib/src/components/Papers/HarvestBanner.jsx

Le problème est que lors du render de LaunchTriggerCard on utilise FlowProvider en wrapper qui instancie un connectionFlow https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/components/FlowProvider.jsx#L54. S'il n'y a pas démontage/remontage de LaunchTriggerCard, il n'y a pas de nouvelle instanciation d'un nouveau connectionFlow, et FlowProvider n'est pas prévu pour gérer le cas de props changeantes (initialTrigger notamment). Donc même si le trigger change (notre cas ici) le connectionFlow reste le même avec l'ancien trigger.
Il faut donc démonter et remonter LaunchTriggerCard pour que ça fonctionne.
Pour faire avancer le sujet côté app (dont on aimerait faire une beta, ceci est le dernier sujet bloquant), je suis donc simplement passé par un state.
@doubleface …

fix(mespapiers): Harvest banner wasn't refresh  after deco or reconnect

---

packages/repo-doctor/examples/repo-doctor.json

According to our [guidelines](https://github.com/cozy/cozy-guidelines), material-ui and moment should not be set as dependencies.
This decision has been taken during Front meeting of 12th April

fix(repo-doctor): Moment and Material-UI should not be dependencies

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/models/withConnectionFlow.spec.jsx
packages/cozy-harvest-lib/src/services/biWebView.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
packages/cozy-harvest-lib/test/fixtures.js

Suite à cette PR https://github.com/cozy/cozy-libs/pull/2010, nous nous sommes rendu compte que la class ConnectionFlow n'était pas branchée sur le temps réel de `io.cozy.triggers`.
De ce fait, elle ne savait pas mettre à jour sa propriété `trigger` lorsque celle-ci était supprimée ou créée.

feat: Add triggers realtime to ConnectionFlow

---

packages/cozy-ci/transifex.sh

Since API v3, [transifex-client](https://github.com/transifex/transifex-client) has been replaced by a [new cli](https://github.com/transifex/cli) (cc: [docs](https://developers.transifex.com/docs/cli))

fix: Migrate transifex from client to cli

---

packages/cozy-ci/README.md
packages/cozy-ci/transifex.sh

You can find more infos on .transifexrc and their config in [transifex cli code](https://github.com/transifex/cli/blob/devel/examples/exampleconf/.transifexrc)

fix(cozy-ci): Use token instead password into .transifexrc

---

packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx
packages/eslint-config-cozy-app/package.json
packages/eslint-config-cozy-app/react.js
yarn.lock

- Upgrade all dependencies (only minor updates)
- Add a new rule which allows using destructuring as a means to delete
- Make unused vars as errors rather than warnings
- Fix resulting errors, but not warnings (approx 70)

feat: Upgrade eslint cozy config

---

packages/cozy-tsconfig/license
packages/cozy-tsconfig/package.json
packages/cozy-tsconfig/readme.md
packages/cozy-tsconfig/tsconfig.json

Currently copy-pasting this config a lot everywhere. Seems a lot better to just add it as a lib, that way we can control TS globally in our apps.
Please note that this config does NOT transpile files to javascript. It's only meant to be used as a declaration file generator, even for JS files. It's also used as a type check config in the IDE and/or during the CI process if opted in.
Please see the [readme](https://github.com/cozy/cozy-libs/blob/feat--Add-cozy-tsconfig-lib/packages/cozy-tsconfig/readme.md) file for more information
Paths don't work at all when extending a tsconfig from node_modules it has been an issue for years. For now, I think the easiest workaround is to let people set the paths themselves on their projects.  It's the solution used by Microsoft themselves: …

feat: Add cozy-tsconfig lib

---

packages/cozy-tsconfig/readme.md
packages/cozy-tsconfig/tsconfig.json

This is important to avoid annoying error messages when consuming
the config (like TS complaining about overwriting d.ts files).
It will not compile anything though. It just helps you write less
in the tsconfig.json especially if your build dir is named `dist`.
You still can overwrite what you want.

feat(cozy-tsconfig): Add `dist` as default outDir/declarationDir

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyNoHeader.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithConnector.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithHeader.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/styles.styl
packages/cozy-mespapiers-lib/src/components/Papers/HarvestBanner.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.spec.jsx
packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx
packages/cozy-mespapiers-lib/src/helpers/queries.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

On souhaite afficher du contenu spécifique pour les différents cas "empty" à savoir quand il n'y a pas de contenu. Quelques exemples : 
Pas de document, et pas de connecteur associé
Pas de doc, mais un connecteur avec un seul compte
Pas de doc, un connecteur, plusieurs comptes

MesPapiers: Refactor HarvestBanner and add Emptys component

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/policies/clisk.js
packages/cozy-harvest-lib/src/policies/clisk.spec.js

When launching an existing trigger
Or else the launcher will recreate a new account and trigger each time

feat: Send account and trigger to the launcher

---

packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialog.jsx

sans l'ellispis cela masquait également l'indicateur d'étape

fix(mespapiers): Ellipsis on step modal title was removed

---

packages/cozy-sharing/src/components/badge.styl
packages/cozy-sharing/src/components/button.styl

Since the removal of the cozy-bar v7, Drive
don't load an old version of cozy-ui. These
variables are not defined anymore
see https://github.com/cozy/cozy-ui/pull/1743
The best way to use absolute color is to
import them from the palette.json
```
palette=json('settings/palette.json', { hash: true })
```
and use this way
```
background-color: palette['barney']
```
I needed to add the `:` because sometimes I had
compilations errors, sometime it was compiling in
cozy-sharing but the classname was not present
in the final bundle...

fix: Colors for shared withMe

---

packages/eslint-config-cozy-app/basics.js

- `prefer async/await to callbacks` **removed** (after using it in a real-world project, it felt like a bad addition)
- `prefer async/await to promises` **removed** (after using it in a real-world project, it felt like a bad addition)
- `**/*.styles` files are now the last group in the import order (this is following cozy-guidelines)

feat(eslint-config-cozy-app): Update rules

---

packages/cozy-mespapiers-lib/src/components/Home/Content.jsx
packages/cozy-mespapiers-lib/src/components/Home/HomeLayout.jsx
packages/cozy-mespapiers-lib/src/components/Papers/CategoryItemByKonnector.jsx
packages/cozy-mespapiers-lib/src/components/Papers/CategoryItemByPaper.jsx
packages/cozy-mespapiers-lib/src/components/Papers/KonnectorsCategories.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/styles.styl
packages/cozy-mespapiers-lib/src/components/Views/Home.jsx
packages/cozy-mespapiers-lib/src/components/Views/helpers.js
packages/cozy-mespapiers-lib/src/components/Views/helpers.spec.js
packages/cozy-mespapiers-lib/src/helpers/queries.js

Dans le cas d'un connecteur installé avec un compte associé, on souhaite pouvoir afficher la catégorie du connecteur même s'il n'y a aucun document récupéré. Dans ces cas là, la catégorie s'affiche sur la home, et un bloc "empty" est affiché à la place des documents

Empty content for installed connectors

---

packages/cozy-mespapiers-lib/package.json

BREAKING CHANGE: You must have `cozy-device-helper >=2.7.0`,
`cozy-doctypes >=1.88.0`, `cozy-harvest-lib >=13.5.0`,
`cozy-intent >=2.9.0`, `cozy-realtime >=4.3.0`, `cozy-sharing >=6.0.4`

feat: Upgrade peer dep to be consistent with dev dep

---

packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/CozyRealtime.legacy.spec.js
packages/cozy-realtime/src/CozyRealtime.spec.js

dans le document retourné par le realtime, il n'y a pas le _type associé au 
doctype, ce qui nécessite côté app une gymnastique lorsque le realtime est 
branché sur différents doctypes.
Grâce à cette amélioration, il suffit juste d'analyser le document pour savoir 
à quel doctype il est associé.
C'est dans le cas où on branche un même callback sur différent subscribes, on ne discrimine alors plus en amont mais en aval via le doc.
L'autre raison est aussi d'uniformiser par rapport au retour de CC qui lui normalize le doc et ajoute ce _type.
fix https://github.com/cozy/cozy-libs/issues/2023

Realtime: Add _type on returned doc by the handlers

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithHeader.jsx

In order to be more resilient, it is better to use the `getAccountName` helper to retrieve the account name

refactor: Use helper for get account name

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx

We don't use `harvest.toggle-contract-sync` anymore.

test: Remove not needed mock

---

packages/cozy-sharing/src/getSharedDocument.js
packages/cozy-sharing/src/getSharedDocument.spec.js
packages/cozy-sharing/src/state.js

The `getSharedDocument` function is only used in cozy-drive at the moment.  Cozy-notes has its own version that comes close to these changes. It may be possible to use the same for both applications in the future.
BREAKING CHANGE: The function now returns the id encapsulated in an object. You can extract the id like this `const { id } = getSharedDocument(client)`

feat: Return also readOnly status from getSharedDocument

---

packages/cozy-mespapiers-lib/src/components/Contexts/PapersDefinitionsProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Search/search.js
packages/cozy-mespapiers-lib/src/constants/papersDefinitionsOld.json
packages/cozy-mespapiers-lib/src/helpers/makeInputsInformationStep.spec.js
packages/cozy-mespapiers-lib/src/helpers/queries.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

Replace `cafFileNumber`, `cardNumber`, `vinNumber`, `ibanNumber` & `passportNumber` by `number`.
And add flag for synchronize migration with other libs/konnectors

refactor: Harmonizes file metadata names

---

packages/cozy-mespapiers-lib/package.json
yarn.lock

BREAKING CHANGE: You must have `cozy-client >=36.1.0`, `cozy-doctypes >=1.88.1`, `cozy-harvest-lib >=13.8.0`, `cozy-sharing >=7.0.` & `cozy-ui >=81.6.0`

feat: Update cozy-packages

---

packages/cozy-flags/src/store.js
packages/cozy-flags/src/tests.js

This commit allows to find value directly in the JSON content of a flag. For example `flag(‘drive.office.enabled’)` will return true if we set `drive.office` with the JSON content `{enabled: true}`

feat(flag): Find value from parameter with nested part into JSON content

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

The `Document` methods make different internal calls depending on the
client being used (i.e. `cozy-client` or `cozy-client-js`).
However, the `cozy-client` calls' responses don't have the same
signature as the `cozy-client-js` ones and were not transformed
leading to errors in (at least) the `BankingReconciliator` when trying
to match transactions with their account.
We now make sure that the `cozy-client` calls returning an object with
a `data` attribute are transformed so that the `Document` methods
always return the content of that attribute (`cozy-client-js` already
does that).

fix: Document methods work with both clients

---

packages/cozy-mespapiers-lib/src/components/Home/Content.jsx
packages/cozy-mespapiers-lib/src/components/Home/ContentFlexsearch.jsx
packages/cozy-mespapiers-lib/src/components/Home/ContentWhenNotSearching.jsx
packages/cozy-mespapiers-lib/src/components/Home/ContentWhenSearching.jsx
packages/cozy-mespapiers-lib/src/components/Papers/CategoryItemByKonnector.jsx
packages/cozy-mespapiers-lib/src/components/Papers/KonnectorsCategories.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/Papers/helpers.js

KonnectorsCategories est le composant qui affiche les konnecteur pour lesquels il y a un compte connecté mais aucun fichier.
le code est plus robuste (c'était inline dans un return de composant) mais on pourrait quand même tester `makeQualificationLabelsWithoutFiles` par la suite (manque de temps ici)

KonnectorsCategories wasn't relied on search filter

---

packages/cozy-mespapiers-lib/package.json
yarn.lock

BREAKING CHANGE: you must have `cozy-ui >= 82.1.2`

feat: Update cozy-ui to 82.1.2

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx

It was hidden, now we fetch the account name
with the Account model from cozy-doctypes.
It is tied to `showAccountSelection` prop, not to clientSide.
Must be wary of that in the future if changing something in this scope

fix(harvest): Show account name in header for CCC

---

packages/cozy-harvest-lib/src/components/Routes/RoutesV6.jsx
packages/cozy-harvest-lib/src/datacards/ViewerModal.jsx

It seems the route used the old router API,
which doesn't work with rr6.
Thus, the viewer would never work.
It is fixed by using the correct rr6 API with useParams hook.
Please note I encountered a rare bug that I was unable to reproduce, might be a problem with hot reloading. But at some point I had a memory leak in ViewerModal and clicking on a file would not update router state unless a page reload occurs

fix(harvest): Use react-router 6 API in viewer route

---

packages/cozy-mespapiers-lib/package.json
yarn.lock

BREAKING CHANGE: you must have `cozy-ui >= 82.5.1`

feat(mespapiers): Update cozy-ui from 82.4.0 to 82.5.1

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js

When (re-)connecting a bank, we try to match existing accounts with
newly fetched ones.
When we find matches, we update the existing accounts with the fresh
data and set the connection id with the new one.
We also update the connection id of other bank accounts that were
sharing the same old connection id with the matching bank account.
e.g. :
Say we have
- bank account `#1` with connection id A
- bank account `#2` with connection id A
- bank account `#3` with connection id B
And we fetch
- bank account `#1` connection id C
Then we'll make these updates
- bank account `#1` gets connection id C
- bank account `#2` gets connection id C
Now, if an existing bank account matches with a fetched one but did
not have a connection id anymore, we'll use the new connection id as
well.
However, the …

fix: Set connection id of current bank's accounts

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx

Previously the history was mutated so we couldn't go back. Now it's correctly updated so we can go back

Fix(harvest): handle navback from edit dialog

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/cli/cli.js
packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx
packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BIContractActivationWindow.spec.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.spec.jsx
packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx
packages/cozy-harvest-lib/src/datacards/GeoDataCard.jsx
packages/cozy-harvest-lib/src/jest.setup.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/policies/clisk.js
packages/cozy-harvest-lib/test/fixtures.js
yarn.lock

When the konnector is a clisk konnector and before LOGIN_SUCCESS
And on first run (account creation or identifiers update or action needed error state) for other types of konnectors and before LOGIN_SUCCESS
Add the possibility to get LOGIN_SUCCESS event from a launcher event.
- fix: Do not fail on loginSuccess when no job watcher is defined
- fix: Only display backdrop before login success
- fix: Misleading log
- fix: Do not redirect to account if no account
- feat: Get LOGIN_SUCCESS event from flagship app
- feat: Do not wait for LOGIN_SUCCESS event
- fix: Import order
- feat: Upgrade cozy-client harvest dev dependency
- fix: Lint
- fix: Protection in clisk policy
- feat: Backdrop display rules change
- feat: Display backdrop if the error needs an action from the user
- test: Add some …

Feat: Display backdrop only when user is needed

---

packages/cozy-mespapiers-lib/src/components/MesPapiersLibProviders.jsx
packages/cozy-mespapiers-lib/src/components/MesPapiersLibProviders.test.jsx

As long as the user has not validated his onboarding, via the "Let's go!" button, he will not be able to access the features of the app.

fix: Remove Fab button on onboarding page

---

packages/cozy-flags/package.json
packages/cozy-flags/src/flag.js
packages/cozy-flags/src/tests.js
packages/cozy-harvest-lib/src/helpers/konnectors.js
yarn.lock

Instead of just flags and contexts to avoid store issues.
See cozy-client 3a35f4fd34a74b1133bb9fc36a1f915c69e4122f
Hidden goal : chasing and removing deprecated stuff flooding flagship app logs

fix: Use io.cozy.settings.flags and io.cozy.settings.context id

---

packages/cozy-mespapiers-lib/src/helpers/queries.js

In the `viewInDrive` action, we need the `dir_id` attribute of the file.
The files retrieved by the `buildFilesQueryWithQualificationLabel` query being those used during the search, this attribute must be included in the `select`

fix: Redirect link to Drive

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalHeader.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectBox.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectControl.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectorHeader.tsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/MenuWithFixedComponent.jsx

- Go Back
- Only show the account name
- Different styles than the default modal
This was painful to implement because I could not use the CozyDialogs API (used in Figma). So I had to create a sort of custom style for that page. Thankfully didn't need to create any CSS so I think it's ok, but ultimately I think Harvest should be refactored to use CozyDialogs everywhere, so this implementation is not necessary.
Before:
After:

feat(harvest): Update config page header

---

packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js

Now ConnectionFlow ensureTriggerAndLaunch really launches
the job and ConnectionFlow.launch is called alone in clisk context.

fix: EnsureTriggerAndLaunch in oauth context

---

packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx

When the InputSearch is of large size, the focus is not possible beyond 512px, which is a rule imposed by the Input component but that we do not want here.

fix: Override `maxWidth` of SearchInput

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js

A newly binded function was subscribed and unsubscribed. Then the
unsubscription failed. This caused multiple trigger refetch for one job
update.

fix: Unsubscribe of ConnectionFlow.handleCurrentJobUpdated

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/Error.jsx

This Error componenent had the same name as the Error object and this
caused "Maximum call stack size exceeded" error since the Error
component instanciated itself

fix: Error react component

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js

When creating a new account/trigger couple, when the given trigger has
started running, the FlowProvider is reloaded, which means it
unsubscribes from realtime events until it is reloaded.
If the konnector execution is really fast (example: dummy-> 1s), its
execution could end during the FlowProvider reload (which is a little
less than 1s on my development environment).
To fix this issue, I force the ConnectionFlow to refetch the current
trigger if this trigger is in the state "running", in case we missed the
konnector execution end.

fix: Refetch current trigger when it is running

---

packages/cozy-mespapiers-lib/src/components/Home/HomeLayout.jsx
packages/cozy-mespapiers-lib/src/components/Search/helpers.js

Sur des cozy avec beaucoup de documents, dans certains cas de filtrage par catégorie sans mot clé dans la barre de recherche, il n'y a aucun document retourné alors que ça devrait.
La cause étant que flexsearch retourne bien des résultats, mais est limité à 100 résultats par défaut https://github.com/nextapps-de/flexsearch#limit--offset . Comme on lui injectait d'abord les `contacts` puis ensuite les `papers`, et qu'un filtrage comme `identité` retourne tous les contacts, si on a plus de 100 contacts dans le cozy cela vient remplir tous les résultats, ne laissant plus de place pour les papers.
Le correctif est double : injecter d'abord les papers (pour retourner plus prioritairement des papers), augmenter la limite de résultat à `9999` (ce qui ne semble pas être un souci, cf la doc linké …

Fix search result when filtering with no keywords

---

packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx

Suite au changement de `papersByCategories` dernièrement (https://github.com/cozy/cozy-libs/pull/2110), nous avons manqué de mettre à jour une partie

fix: Display of the last Divider

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/AccountModalHeader.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectorHeader.tsx

This pull request addresses an issue with the Account Modal's back button, which previously did not allow the user to navigate back correctly due to using the wrong method (`push` instead of `replace`) and an incorrect redirect path.
- Replaced `pushHistory` with `replaceHistory` in `AccountModalHeader.jsx` and `AccountSelectorHeader.tsx` to use the correct navigation method.
- Updated the redirect path in the `onClick` callback of the `AccountSelectorHeader` component to correctly navigate back to the account details page.
After considering both the `push` and `replace` methods for navigation, the `replace` method has been chosen in this PR, as it provides a more seamless user experience by not creating an additional history entry when navigating back.

fix(harvest): DialogBackButtonon config modal

---

packages/cozy-harvest-lib/src/components/AccountsListModal.jsx

This pull request updates the `AccountsListModal` component to use the `<DialogTitle>` component from Cozy UI, replacing the outdated `<Stack>` component. This change addresses styling issues on desktop, mobile, and mobile native platforms.
- Replaced `<Stack>` with `<DialogTitle>` for improved consistency in header styling
- Updated the component to use `<Typography>` for better text display
- Removed unnecessary styles and classNames
While this PR fixes the immediate styling issues in `AccountsListModal`, it has been noted that there is a lack of consistency in the header styling throughout the Harvest library. Further work may be needed to ensure a more robust and consistent styling solution.

fix(harvest): Update AccountsListModal title

---

packages/cozy-mespapiers-lib/src/components/Papers/CategoryItemByPaper.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx
packages/cozy-mespapiers-lib/src/components/Papers/StackedThumbnail.jsx
packages/cozy-mespapiers-lib/src/components/Papers/StackedThumbnail.spec.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Thumbnail.styl

It replaces the CardMedia component, to display the thumbnails of the papers on the homepage and the paper lists.
Before:
After:

feat(cozy-mespapiers-lib): Add ThumbnailStack component

---

packages/cozy-harvest-lib/src/policies/clisk.js
packages/cozy-harvest-lib/src/policies/clisk.spec.js

Or else some components won't be able to test this error and will create
error :
```
err.isLoginError is not a fonction
```

fix: Create KonnnectorJobError in clisk policy

---

packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js

Instead of realtime.unsubscribeAll which may unubscribe more events
thant expected and handle by the current component

fix: Use realtime.unsubscribe

---

package.json
yarn.lock

v4.0.0 ships with an old version of `node-gyp` which is incompatible
with recent versions of python (v3.11+) and thus prevents installing
`parcel` because its `deasync` dependency needs to be compiled.

fix: Upgrade lerna from 4.0.0 to 5.0.0

---

packages/cozy-realtime/src/CozyRealtime.js

The `WebSocket` API is not implemented in NodeJS so apps such as
Cozy Desktop need to use the `ws` library.
Unfortunately, this library's implementation differs from the
browsers' native ones in some ways such as the behavior when closing
the WebSocket.
In `ws`'s implementation, if the WebSocket is open but not connected
yet, an error event will be emitted causing an unhandled error since
`cozy-realtime` removes the `onerror` listener before attempting to
close the WebSocket.
Since we don't care about such errors anyway, we can use a different
listener that will simply log these errors rather than completely
removing the listener.

fix: Discard errors when closing the websocket

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountWrapper.jsx

This property is already defined in components using this componenent
I checked other overwritten properties and it looks OK.
This fixes an error when trying to delete an account with `harvest.inappconnectors.enabled` flag enabled

fix: Do not overwrite onDeleteAccount in KonnectorAccountWrapper

---

packages/cozy-mespapiers-lib/src/components/Search/search.js
packages/cozy-mespapiers-lib/test/jestLib/setup.js

see https://github.com/nextapps-de/flexsearch#encoders
On souhaite notamment couvrir le cas des mots accentués. Il n'est plus 
nécessaire d'avoir les accents pour avoir un résultat

feat(mespapiers): Add more permissive encoder for flexsearch

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountWrapper.spec.jsx
packages/cozy-harvest-lib/src/policies/biWebView.spec.js

This way we can check regressions on account deletion- test: Add a test for KonnectorAccountWrapper
- fix: Lint issue on imports

test: Add a test for KonnectorAccountWrapper

---

packages/cozy-harvest-lib/src/components/KonnectorIcon.jsx

By using the previous custom method, we were calling the registry by default.
We should let the AppIcon component do the work because it'll first ask the stack and if this request failled, then it'll fallback to the registry.

fix: Load icon from stack first

---

packages/cozy-realtime/README.md
packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/CozyRealtime.spec.js
packages/cozy-realtime/src/RealtimePlugin.js
packages/cozy-realtime/src/RealtimePlugin.spec.js
packages/cozy-realtime/src/utils.js

Node core does not offer a `WebSocket` implementation. Node
applications have to use a third-party package, most likely `ws`, to
create `WebSocket` instances.
Although `ws` defines a global `WebSocket`, its constructor's
signature is different from the native one used in browsers as it
accepts a third, `options`, argument.
Since Node applications might want to pass options to their websockets
(to provide a different `http.Agent` for example), we'll add the
ability to pass a `createWebSocket` function in both `CozyRealtime`
and `RealtimePlugin` options. This function will be used to create
`WebSocket` instances.
A default `createWebSocket` using the globally defined `WebSocket`
without the third argument is used when this option is not provided.

feat: Allow using non-native `WebSocket`

---

packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperLine.spec.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersList.spec.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.spec.jsx

MidEllipsis doesn't support props spreading (I'll fix it) so we can't
use data-testid on it. That's why the span.

feat(mespapiers): Replace ellipsis by midellipsis for document name

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanActionsWrapper.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanActionsWrapper.spec.jsx

This feature must not be effective in the next version of the app (2.2), we must surround it with a flag.

feat: Wrap scanner feature behind `mespapiers.features.v3` flag

---

packages/cozy-mespapiers-lib/src/components/Papers/PapersListToolbar.jsx
packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx

This flashing is due to the fact that the title is displayed before knowing the number of existing files.
It makes sense to always keep the plural here, because we are on the page of papers of the same type, even if there is only one.

fix(mespapiers): Flashing of the title when arriving on the list of a type of paper

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithKonnector.jsx
packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx
packages/cozy-mespapiers-lib/src/components/Views/helpers.js
packages/cozy-mespapiers-lib/src/components/Views/helpers.spec.js
packages/cozy-mespapiers-lib/src/helpers/filterWithRemaining.js

On a list of files with konnector, accounts without files disappear if other accounts with files exist.

fix(mespapiers): All accounts must appear in the file lists

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/InstallAppModal.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

`getPlatform` returns the `android` or `ios` device only under Cordova, so it is completely useless to use this helper here.

fix(mespapiers): Redirect to the correct store

---

packages/cozy-intent/readme.md
packages/cozy-intent/src/api/models/applications.ts

Updated readme with:
Will open a new webview in a Native app with the href provided.
Example 1: With bottomBackground and topBackground set
```js
setFlagshipUI({
bottomBackground: '#ff0000', // Red background for the Navigation Bar
topBackground: '#0000ff' // Blue background for the Status Bar
})
```
Example 2: With all optional parameters set
```js
setFlagshipUI({
bottomBackground: '#008000', // Green background for the Navigation Bar
bottomOverlay: 'rgba(0, 0, 0, 0.5)', // Half-transparent black overlay for the Navigation Bar
bottomTheme: 'light', // Light-themed icons for the Navigation Bar
topBackground: '#ffff00', // Yellow background for the Status Bar
topOverlay: 'rgba(0, 0, 0, 0.5)', // Half-transparent black overlay for the Status Bar
topTheme: 'dark' // Dark-themed icons for the …
```

docs(cozy-intent): Add more info on setFlagshipUi

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js

In the case of clisk konnectors, only ConnectionFlow.launch is called,
without calling handleFormSubmit.
Now the accountError state is reset in launch which is also always
called by handleFormSubmit also.

fix: Reset flow.accountError on launch for clisk konnectors

---

packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/RealtimePlugin.js
packages/cozy-realtime/src/RetryManager.js
packages/cozy-realtime/src/SubscriptionList.js
packages/cozy-realtime/src/config.js
packages/cozy-realtime/src/utils.js

The way `cozy-realtime`'s logger is defined and used does not allow
a user of the library to configure the logger as they see fit.
For example, Cozy Desktop cannot get these logs into its own log
files.
With these changes, we can pass a logger object with the same
interface as `@cozy/minilog` when creating a `CozyRealtime` instance
(either directly or via a `RealtimePlugin` registration).
If this option is not passed, we'll fallback to `cozy-realtime`'s
logger.

feat: Allow passing a custom logger to realtime

---

packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.jsx
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

This option allows to display or not the tooltip present in the second part of the Scan.
Because we don't want a tooltip in all cases where we have a "generic" illustration.

feat(mespapiers): Add `tooltip` property to scan step

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithHeader.jsx

In the case where there are several accounts on the same konnector, those who do not have papers must have the same wording in their subHeader.

fix(mespapiers): Wording of EmptyWithHeader

---

packages/cozy-mespapiers-lib/src/helpers/queries.js

Old cozyFiles do not have the `cozyMetadata` property, and files from old konnectors may not have the `cozyMetadata.uploadedBy` property.
As these are essential data for the proper functioning of Mespapiers, they will not appear in the application.

fix(mespapiers): The cozyMetadata property does not always exist

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyNoHeader.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithHeader.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithKonnector.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithKonnector.spec.jsx
packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx

Manually added files must be taken into account when displaying a connector that has no files.

fix(mespapiers): Display a fileless account with other files

---

packages/cozy-harvest-lib/src/__mocks__/cozy-ui/transpiled/react/Icons/ArrowUp.js
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx
packages/cozy-harvest-lib/src/components/cards/RunningAlert.spec.tsx
packages/cozy-harvest-lib/src/components/cards/RunningAlert.tsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

This PR introduces the `RunningAlert` component and includes unit tests for it. The `RunningAlert` component is designed to display an alert message to the user when a certain condition is met : Konnector running a job, on Flagship App, as a CCC.
- Added `RunningAlert` component under `src/components/cards`.
- Added unit tests for `RunningAlert` to ensure it renders correctly based on the state of `isFlagshipApp`.
- The component uses the `cozy-ui` library for styling and icons.
- It renders an alert with a title and body text which is obtained through the `useI18n` hook from the `cozy-ui` library. This makes it easy to handle translations.
- The visibility of the alert is dependent on the `isFlagshipApp` function from the `cozy-device-helper`. When the app is a flagship app, the alert is …

feat(harvest): Add dismissable alert when running a trigger in CCC+Native

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountsPaywall/AccountsPaywall.jsx
packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.js
packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.spec.js
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.spec.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/helpers/queries.js
yarn.lock

I've found two places that ask you to create an account either with the '/new' route and with an intent that uses TriggerManager from cozy-home. Verification is carried out in both places to limit the opening and closing of successive modals as quickly as possible.
I'll try to optimise the request to retrieve the triggers
- https://github.com/cozy/cozy-client/pull/1356
- https://github.com/cozy/cozy-ui/pull/2452

feat: Add max accounts by konnector paywall

---

packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/OpenOAuthWindowButton.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.spec.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlertMenu.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/konnector-policies.js
packages/cozy-harvest-lib/src/policies/biWebView.js
packages/cozy-harvest-lib/src/policies/clisk.js

Even with harvest.inappconnectors.enabled flag activated.
The difference with previous interface is that the "reconnect" button
and the synchronize button have merge.
When the konnector is a powens one and when the error is solvable via
reconnection, the reconnection action (display the powens webview) is
done instead of just launching the konnector.
The reconnection button has exactly the same style as the
synchronization button.

fix: Display reconnection webview for powens konnectors

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.spec.jsx

Used this dirty fix to avoid blocking a delivery for this message :
```
The ActionMenu component has been deprecated and should be
replaced by ActionsMenu.
More infos: https://docs.cozy.io/cozy-ui/react/#!/ActionsMenu
```

fix: Ignore ActionMenu warning message

---

packages/cozy-harvest-lib/src/helpers/konnectors.js

USER_ACTION_NEEDED state corresponds to 'actionNeeded' state for Powens
and this state states that :
```
Synchronization failed because the user needs to perform an action
directly on the bank website or app (usually, accept new CGUs or
similar one-time actions).
```
source: https://docs.budget-insight.com/guides/handle-scas-connection-states
Then this error cannot be solved with reconnection webview. We should just try to launch again the konnector.

fix: Do not display reconnection webview for USER_ACTION_NEEDED state

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.spec.jsx

Stupid error: the check to display the paywall was too early and was bypassed by the oAuth form

fix: Show accounts paywall for oAuth konnector

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/RadioAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/RadioAdapter.spec.jsx

This `useEffect` had been removed, among other things, during the last evolution of the component.
But it is really necessary for the proper functioning of the functionality (creation/editing).

fix(mespapiers): Step modal with Radio buttons

---

packages/cozy-mespapiers-lib/src/components/CompositeHeader/CompositeHeader.jsx

Removed the `width: fit-content` CSS rule on the `img` tags in `CompositeHeader` component, this rule is no longer useful and even causes problems on Firefox & Safari browsers

fix(mespapiers): Flattened image on some browsers

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx

This close button did not do anything on screen. I think the expected action here is to really close the Harvest dialog.

fix: Close Harvest modal with the close button in error dialog

---

packages/cozy-intent/src/view/components/NativeIntentProvider.tsx

On flagship app, we need to call a intent from a webview inside an intent in the flagship app. To do so, we need to access the native intent service. We can not use useNativeIntent webhook, because in the flagship app we are not in a React component, and we are at the same level of the provider definition.

feat: Expose native intent service

---

packages/cozy-minilog/src/web/index.js

By modifying the library code in this way,
we're ensuring that the more capable
logging backend console.minilog is used
not only when the code is running in a Chrome browser, but also when it's running in a React Native environment. This ensures better compatibility with different running environments without the need for users to modify their global objects (like navigator), resulting in cleaner and more maintainable code.

feat(minilog): Recognize ReactNative as modern env

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

DumbTriggerManager (cf: [code](https://github.com/cozy/cozy-libs/blob/ed9e18998c30701d07292c44cea46534525df182/packages/cozy-harvest-lib/src/components/DumbTriggerManager.jsx#L28)) imported as default in TriggerManager (cf: [code](https://github.com/cozy/cozy-libs/blob/ed9e18998c30701d07292c44cea46534525df182/packages/cozy-harvest-lib/src/components/TriggerManager.jsx#L12)) but just export which lead to white screen in cozy-home

fix: Wrong export for DumbTriggerManager

---

packages/cozy-mespapiers-lib/src/components/Contexts/StepperDialogProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanWrapper.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/ConfirmReplaceFile.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.spec.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialogWrapper.spec.jsx
packages/cozy-mespapiers-lib/src/helpers/buildPapersDefinitions.js
packages/cozy-mespapiers-lib/src/helpers/buildPapersDefinitions.spec.js
packages/cozy-mespapiers-lib/src/helpers/makeFileFromBlob.js
packages/cozy-mespapiers-lib/src/helpers/makeFileFromBlob.spec.js

Cette PR permet de délier l'étape "contact" de la soumission du formulaire, ainsi nous pourrons mettre cette étape avant la création d'une note/aide-mémoire.

Unlink the form submission from the Contact step

---

packages/cozy-sharing/src/SharingProvider.jsx

When using `fetchPolicy`, the `client.query` method does not work correctly,
use `client.fetchQueryAndGetFromState` instead.
Known issue: cozy/cozy-client#931

fix(sharing): Use `.fetchQueryAndGetFromState` instead `.query`

---

packages/cozy-interapp/src/client.js

Bug détecté lors de l'utilisation des intent via IntentIfram de cozy-ui, qui fait que `result` ici https://github.com/cozy/cozy-ui/blob/master/react/IntentIframe/IntentIframe.jsx#L50 contient un object `{ document: undefined, removeIntentIframe: ... }`
On se base sur l'approche de onDone https://github.com/cozy/cozy-libs/blob/2a162e4d4547c506ec6cceb91bc9fabc6e4637d5/packages/cozy-interapp/src/client.js#L53C17-L53C17
Ceci dans le cadre de l'app Notes chargée via intent dans MesPapiers, on souhaite récupérer la note créée dans MesPapiers après création de celle-ci via intent dans Notes, afin d'appliquer la qualification dessus et l'ajout de contact de référence. Feature sur laquelle nous sommes déjà très limite en terme de timing, ajouté à ça la méconnaissance de cozy-interapp, le bugfix ne …

fix(cozy-interapp): The document wasn't returned in onExposeFrameRemoval

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/useCurrentEditInformations.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/useCurrentEditInformations.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/NoteDialog.jsx
packages/cozy-mespapiers-lib/src/helpers/createPdfAndSave.js
packages/cozy-mespapiers-lib/src/helpers/queries.js

Lors de la création d'une aide-mémoire, il faut que celle-ci soit qualifiée et que les contacts de références soient ajoutés. C'est ce qu'on ajoute ici.

Categorize and add contact references on reminders

---

packages/cozy-scanner/src/DocumentCategory.jsx

On Desktop, when selecting a theme, a popper listing the qualifications appears below the theme button. With the recent addition of new qualifications, not all of them are accessible.
In order to have access to all qualifications, we display them on the right side of the theme button instead.

fix(scanner): Displaying qualifications

---

packages/cozy-mespapiers-lib/src/components/InstallAppFromIntent/InstallAppFromIntent.jsx
packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx
packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.jsx
packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.spec.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.spec.jsx
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/helpers/queries.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

Ici on ajoute le contrôle que l'application Notes soit bien installée sur le Cozy avant d'entamer le processus de création d'un aide-mémoire.
Le cas échant, nous proposons de l'installer via Intent.

Feat(mespapiers): Add `InstallAppFromIntent` component

---

packages/cozy-mespapiers-lib/src/components/Actions/Items/copyReminderContent.js

Sur iOS Safari (desktop et Flagship) uniquement, le copy ne fonctionne pas. Alors qu'on utilise la même méthode ailleurs et ça fonctionne bien...
J'ai copié le code de la lib pour voir quand, c'est simplement https://github.com/sindresorhus/copy-text-to-clipboard/blob/main/index.js#L31 qui retourne `false`.
Comme indiqué dans la doc `Must be called in response to a user gesture event, like click or keyup.` j'ai forcé l'usage d'un event listener.
Mais en fait ce n'est pas tant en rapport avec le useEvent, c'est qu'il manque un render... faire le useFetchJSON provoque un render de plus, et faire ensuite classiquement un onClick sur ActionsMenuItem et dedans un const hasCopied = copy(data) fonctionne bien également 🤷‍♂️ 
Bref ça marche avec le code proposé 👍

fix(mespapiers): Copy content on Note wasn't working on iOS Safari

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/helpers/konnectorBlock.js
packages/cozy-harvest-lib/src/helpers/konnectorBlock.spec.js
packages/cozy-harvest-lib/src/helpers/queries.js
yarn.lock

Ce problème est apparu suite à l'utilisation du Viewer sur un fichier provenant d'un connecteur.
A son ouverture, plusieurs requêtes partent du composant `KonnectorBlock`.
Plus précisément, une des requêtes exécuté regarde si le connecteur est en maintenance https://github.com/cozy/cozy-libs/blob/26c25008cf0b145e16e9b971a8c550c7b31e99a6/packages/cozy-harvest-lib/src/helpers/konnectorBlock.js#L224 qui mène à
https://github.com/cozy/cozy-libs/blob/26c25008cf0b145e16e9b971a8c550c7b31e99a6/packages/cozy-harvest-lib/src/helpers/queries.js#L8
A ce moment nous retombons dans le même problème rencontré avec le doctype io.cozy.apps, solutionné ici
https://github.com/cozy/cozy-client/commit/9d010a9943d295b4eeb789bd188d4b4988164382

Fix(harvest): konnectorBlock query

---

packages/cozy-harvest-lib/src/locales/en.json

Or else we get a "Connect %{slug} to your Cozy to synchronize your
account and automatically retrieve all your data." on screen

fix: English locale for oauth connection

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanFlagshipActions.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanMobileActions.jsx

Restrict mime type images, because the process of creating a paper does not accept mime types like `image/svg+xml`, `image/webp`, etc

fix(mespapiers): Restrict mime type images for paper creation

---

packages/cozy-harvest-lib/src/policies/biWebView.js
packages/cozy-harvest-lib/src/policies/biWebView.spec.js

Now powens uuids are used, which removes the need to have different
identifiers according to the current environnement and makes it a lot
easier to add new banks (just need to add the bank to the registry and
add corresponding uuids in the manifest of the konnectors.
But to fully work, this needs to have
https://github.com/cozy/cozy-stack/pull/4082 fully deployed in
production (or else the webview won't open on a correct url)
But since uuids are available in banking konnectors manifest since a long time, this can be deployed without any update in banking konnectors.

feat: Removed the use of powens bank ids -> uuids

---

packages/cozy-mespapiers-lib/docs/AddPaperGuidelines.md
packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/src/components/Contexts/StepperDialogProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/InformationDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/NoteDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanActionsWrapper.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanWrapper.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultCard.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js
packages/cozy-mespapiers-lib/src/components/Placeholders/FeaturedPlaceholdersList.spec.jsx
packages/cozy-mespapiers-lib/src/components/Placeholders/Placeholder.spec.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialogTitle.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialogWrapper.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/StepperDialogWrapper.spec.jsx
packages/cozy-mespapiers-lib/src/components/StepperDialog/helpers.js
packages/cozy-mespapiers-lib/src/components/StepperDialog/helpers.spec.js
packages/cozy-mespapiers-lib/src/constants/PaperDefinitionsPropTypes.js
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/helpers/buildPapersDefinitions.spec.js
packages/cozy-mespapiers-lib/src/helpers/filterWithRemaining.spec.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.js
packages/cozy-mespapiers-lib/test/mockPaperDefinitions.js

This property was added when the project was created.
Its main purpose was to guarantee the order of the steps.
Which is useless in JS because the order of JSON arrays is guaranteed by the language. (https://www.rfc-editor.org/rfc/rfc8259.html#section-1)
This will make it easier to manipulate the steps in addition to making them lighter.

feat(mespapiers): Remove the `stepIndex` property from the config file

---

packages/cozy-intent/src/api/services/NativeService.ts
packages/cozy-intent/src/view/components/NativeIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/NativeIntentProvider.tsx

Previously, the context was recreated each time the localMethods
reference changed.
Now, if this object change, we will just update the existing
context instance with this new localMethods object.
This will optimize the behaviour of the provider because it avoids
destructive rerenders that are not necessary for the intents
to still work and use the updated localMethods with the existing service

feat(cozy-intent): Avoid localMethods rerender

---

packages/cozy-sharing/src/SharingProvider.jsx
packages/cozy-sharing/src/helpers/sharings.js
packages/cozy-sharing/src/state.js
packages/cozy-sharing/src/state.spec.js

When a new share is made, realtime trigger the indexation of all documents in the new sharing as well as the shortcut. If the recipient has not synchronised the sharing, the document does not exist, leading to errors in the indexing script. This is why we only index files if the share is ready, so that the files exist

fix: Skip the document not found during indexing after a realtime update

---

packages/cozy-sharing/src/state.js

We used to use `email` as `codes` attribute for a sharingByLink. But when we use cozy-client to create a Permission, by default the codes attribute is set to `code`. MesPapiers app is using this default behavior... So the sharing by link created by mes papiers didn't appear correctly in cozy-sharing.
This is a bit ugly, we should have a better way to know if this is a sharing by link or not.

fix: BuildSharingLink works also for perm from mes papiers

---

packages/cozy-mespapiers-lib/src/components/CompositeHeader/CompositeHeader.jsx

On mobile, when focusing the text field, the keyboard passes in front and we lose the visual of the field.

fix(mespapiers): The text field must not be hidden by the keyboard

---

packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/src/components/CompositeHeader/CompositeHeader.jsx
packages/cozy-mespapiers-lib/src/components/Contexts/FormDataProvider.jsx
packages/cozy-mespapiers-lib/src/components/Contexts/StepperDialogProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Contact.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactList.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/InformationDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanWrapper.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/ContactAdapter/ContactAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/ContactAdapter/SingleContactPicker.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/ContactAdapter/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.spec.jsx
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/helpers/filterSteps.js
packages/cozy-mespapiers-lib/src/helpers/filterSteps.spec.js
packages/cozy-mespapiers-lib/src/helpers/isOCRActivated.js
packages/cozy-mespapiers-lib/src/helpers/isOCRActivated.spec.js
packages/cozy-mespapiers-lib/src/helpers/isOCRCompliant.js
packages/cozy-mespapiers-lib/src/helpers/isOCRCompliant.spec.js
packages/cozy-mespapiers-lib/src/helpers/makeInputsInformationStep.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json

This first step is to manage the user interface. The next step will be to launch and retrieve the data proposed by OCR. I've put TODOs in places that will need additional code to complete the functionality. The feature is behind a flag called `mespapiers.ocr.enabled`

feat: First step to manage OCR result

---

packages/cozy-intent/src/api/models/methods.ts

Add API method signatures for new OCR feature
`ocr` method's return type is `unknown` to avoid redeclaring the entire `MlkitOcrResult` type from `react-native-mlkit-ocr` module
This should not be a problem for now as this new API should be consumed from JS code
Related PR: cozy/cozy-flagship-app#959

feat(cozy-intent): Add `ocr` and `isOcrAvailable` on API methods

---

packages/cozy-intent/src/view/components/NativeIntentProvider.spec.tsx
packages/cozy-intent/src/view/components/NativeIntentProvider.tsx

This PR introduces a refactor in the `NativeIntentProvider` component to manage the instance of `NativeService` more efficiently, ensuring that it is created only once and preserved across re-renders, while also updating its `localMethods` smoothly upon prop changes.
- **`NativeIntentProvider` Component**
- Introduced a `useRef` to preserve the `NativeService` instance across re-renders.
- Ensured `NativeService` is instantiated once, and then preserved.
- Updated `localMethods` in the `NativeService` instance using a `useEffect`.
These changes provide a more reliable and performance-efficient way of managing the `nativeIntentService`:
- **Stable Instance**: Prevents multiple re-instantiations of the `NativeService`, ensuring better performance and preventing unexpected behaviors.
- …

fix(cozy-intent): Use service as ref, not props

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx

It seems that sometime we can display the `DumbLaunchTriggerCard` component even if the flag is on. The result is that the user doesn't have, in that case, anything to manage the account because elsewhere the flag is read during the React lifecycle.
I think this is why we can't reproduce it everytime, it's a race condition between the loading of the flags and the read we do here.
In order to read the flag when the flag's store is populated, we need to read if within the React Lifecycle.
It should fix the issue.

fix(harvest): Check the flag during React Lifecycle

---

packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/connections/accounts.spec.js

No need to get the current_state (of mapping all the jobs) for the triggers here. So let's make a call to /data/io.cozy.triggers instead

fix: Optimize the request

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/cards/InformationsCard.tsx
packages/cozy-harvest-lib/src/components/cards/RunningAlert.tsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/locales/nl_NL.json

When a opening a konnector, we used to only display the vendor link into the 'Information' section.
We now add a button that redirects to the store, so the user can access the description there.
Here what it looks like: 
Note we mention a "Cozy Cloud Store" but this might eventually change to a dynamic name the day we need to support different names

feat: Add information button redirecting to the store

---

packages/cozy-harvest-lib/src/policies/clisk.js

It was easier at first to be plugged on debug, but this is not ideal anymore since we can have a debug true on a cozy but we don't want to display the worker.

fix: Change flag name to always show the clisk worker

---

packages/cozy-harvest-lib/src/helpers/queries.js

We don't need the current_state of the triggers, so let's call /data/io.cozy.triggers instead of /jobs/triggers. Also use a partialIndex
We had a small "glitch" waiting for the datas to come in before displaying the AccountForm because we need to count the triggers to know if we need to display the AccountForm or the Paywall. 
This is a fix to optimize the query so it should reduce the delay, but a delay should always be there. Maybe we should also display the AccountForm by default and display the paywall only when the check are KO. 
https://github.com/cozy/cozy-libs/assets/1107936/15489559-c06e-4baa-ab4f-e991c5bb1c70

fix: Optimize que buildCountTriggersQuery

---

packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/locales/nl_NL.json

'konnector app' is not very understandable, so we restrict it to 'app'

fix: Store wording

---

packages/cozy-harvest-lib/src/components/Routes.jsx

This modal can be integrated into an Intent modal which already has its own closed button. We add the possibility of hiding the harvest button in favour of the Intent button so that only one is displayed.

feat: Be able to hide the modal close button

---

packages/cozy-intent/src/api/models/methods.ts
packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/tests/mocks.ts

Other isXXXAvailable can not be removed for the moment because they are deployed in production.

feat: Add isAvailable type and remove isOcrAvailable type

---

packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.js
packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.spec.js
packages/cozy-harvest-lib/src/helpers/accounts.js

The main idea behind this flag is to offer user accounts for a given period and a given konnector. This will also be used for migration to CCC so that users have the same number of connectors at the end

feat: Allow to offer account with flag harvest.accounts.offers

---

packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.js

Our internal tool to manage feature flag use json array only for its own use which is why I'm wrapping the list of offers into a json object. 
Old : 
```json
[
{"slug": "*", "offer": 4}
]
```
New : 
```json
{
"list": [
{"slug": "*", "offer": 4}
]
}
```

fix: Wrap offers into json flag instead an array

---

packages/cozy-interapp/src/client.js
packages/cozy-interapp/src/intents.js
packages/cozy-interapp/src/service.js

Some services can handle by themself the display of the cross to close the intent modale. So in order to let them do that, we can now pass an `onHideCross` method to the intent.
```
hideCross(){
this.setState({
closable: false
})
}
<Modal
{...modalProps}
key="modal"
className={styles.intentModal}
closeBtnClassName={styles.intentModal__cross}
dismissAction={this.dismiss}
overflowHidden
closable={this.state.closable}
>
<IntentIframe
action={action}
create={create}
data={options}
onCancel={this.dismiss}
onError={onError}
onTerminate={onComplete}
type={doctype}
onHideCross={this.hideCross}
/>
</Modal>
```
Also add showCross

feat: Add a `hideCross` method

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountModalWithoutTabs/TriggerError.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.spec.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.spec.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlertMenu.jsx
packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.jsx
packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.spec.jsx
packages/cozy-harvest-lib/src/helpers/queries.js
yarn.lock

This PR adds the `harvest.skip-maintenance-for` flag to avoid maintenance for a given konnector.  This is useful for test periods before returning to normal mode.
**Example of flag content :**
```
{ "list": ["slug_konnector1", "slug_konnector2"] }
```
The array is wrap into an object because our tool to manage feature flag only support array for its internal usage.
- https://github.com/cozy/cozy-client/pull/1417

feat: Allow to skip maintenance for konnector with a flag

---

packages/cozy-mespapiers-lib/src/components/OnboardedGuardedRoute.jsx
packages/cozy-mespapiers-lib/src/components/Views/CreatePaperModal.jsx

If we come from the flagship upload,
we don't want to interact with the onboarding
Do not display the onboarding
Set the onboarding to true
Let the app handle the routing to the suited page

feat: Ignore onboarding from flagshipUpload

---

packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx

This modal seems to use an older version of the Cozy UI library
To fix our issue we update the dialog to the new CozyDialogs interface. It comes with minor display variations.
before: 
after updating to CozyDialogs

fix(harvest): Refactor SuggestionModal to standards

---

packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx

The MuiCozyTheme didn't seem to apply the correct theme
variables. Using the CozyTheme provider instead

fix(harvest): Wrap SuggestionModal with theme

---

packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx

As the CozyTheme was in a flex container, it was attributed width and
height. We don't want the container to appear visually
cf commit [c4773585a747866a06e719e7b9ebf3062c753609](https://github.com/cozy/cozy-home/commit/c4773585a747866a06e719e7b9ebf3062c753609)

fix(harvest): Remove SuggestionContainer from flow

---

packages/cozy-mespapiers-lib/src/components/Views/CreatePaperModal.jsx

`stepIndex` no longer starts at 1 but at 0.
As a result, we did not arrive at the right step or it created inconsistencies on the double-sided papers (identity card, etc.)

fix: Saving the upload file in the state of the paper creation process

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/MesPapiersLibLayout.jsx
packages/cozy-mespapiers-lib/src/components/MesPapiersLibLayout.test.jsx
yarn.lock

`CozyDevTools` offers better management of flags, it provides other useful tools in development (visualization of requests, version number of dependencies).
The “switcher” flag is replaced by “debug” to display the `CozyDevTools` component.

feat(mespapiers): Use CozyDevTools instead FlagSwitcher

---

packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/Empty.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithKonnector.spec.jsx
packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyWithKonnectors.jsx
packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx

We can have several konnectors for a paper but we always passed the first on the array resulting we displayed something wrong to the user.
Let's pass all the konnectors & slugs and find the right one.

fix: Display the right konnector

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/OcrProcessingDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/SelectPaperVersion.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js

To improve, the general idea is that for papers with several versions, there is not systematically the SelectPaperVersion modal which appears to ask the user to confirm the version.
But to be able to activate it only for certain papers.
(_no time left_)
The code in place remains useful in the near future, plan for a more dynamic approach when adding future papers with versions.

feat(mespapiers): Add bypass to the SelectPaperVersion modal

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx

Since we can't launch a konnector is maintenance, there is no need to try to update the konnector at this time.
This update button is still needed for manual upgrade (permission changes for instance). Maybe we should only display it in that case because for other case, the konnector will be updated automatically before the launch.

fix: Don't display the KonnectorUpdateButton if maintenance

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js

In https://github.com/cozy/cozy-libs/commit/72e5f5f073d6ddc575cae4cef26b4ca9624efa54 we replaced the mango query to only check the existence of `createdByApp`
But we were using `uploadedBy` later in the code. For old files, we can have a `createdByApp` without a `uploadedBy` attribute.
Since we check the existence of `createdByApp` let's use this field later on the code, like that we are sure that this field exists.

fix: An error when file doesn't have a createdByApp cozyMetadata

---

packages/cozy-mespapiers-lib/src/utils/addFileToPdf.js
packages/cozy-mespapiers-lib/src/utils/image.js

Today we are resizing uploaded images to 900px, for optimization reasons.
It turns out that this resolution is too low, resulting in poor quality PDFs.
We have chosen to push the limit quite high, which should guarantee better quality PDFs.

feat(mespapiers): Increase the maximum size of images before integrating them into PDF

---

packages/cozy-flags/tsconfig.json

The default cozy-tsconfig doesn't have a declarationDir
or can't share it.
We're adding it explicitly in cozy-flags so types are properly created

fix(cozy-flags): Add declaration dir in options

---

packages/cozy-mespapiers-lib/src/components/Search/helpers.js
packages/cozy-mespapiers-lib/src/components/Search/helpers.spec.js

On the connector side, the `email` field of the `Contact` object could be a string instead of an object array.
Issue fixed here: konnectors/libs#987
Pending the propagation of the fix, it is relevant to predict the case here.

fix(mespapiers): `makeContactFlexsearchProps` must handle string emails

---

packages/cozy-mespapiers-lib/src/components/Actions/Items/importAuto.js
packages/cozy-mespapiers-lib/src/components/InstallKonnectorFromIntent/InstallKonnectorFromIntent.jsx
packages/cozy-mespapiers-lib/src/components/Views/PlaceholdersSelector.jsx

When the connector is installed but not connected and there are no papers, when clicking on the "Auto retrieve" button, we must be redirected to the connection modal.
See https://github.com/cozy/cozy-store/pull/884

Fix: Being able to connect to an already installed konnector

---

packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/src/components/Actions/Items/importAuto.js
packages/cozy-mespapiers-lib/src/components/InstallKonnectorFromIntent/InstallKonnectorFromIntent.jsx
packages/cozy-mespapiers-lib/src/components/Views/PlaceholdersSelector.jsx
packages/cozy-mespapiers-lib/src/components/Views/helpers.js
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json

As the query param `category` allows you to filter the Store view, `qualificationLabel` allows you to filter on the connectors having this same label.
see https://github.com/cozy/cozy-store/pull/885

feat(mespapiers): Add `qualificationLabel` option to `konnectorCriteria`

---

packages/cozy-intent/src/api/models/applications.ts
packages/cozy-intent/src/api/models/events.ts
packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/src/api/services/NativeService.ts
packages/cozy-intent/src/utils/index.ts

In the Flagship app we want to implement a new API for FlagshipUI
This new API requires all calls to contains a `componentId` parameter and so we want the CozyWebViews to pass this parameter
To allow this, we want the `tryEmit` to require this parameter. Then it will pass this parameter to `setFlagshipUI` and `setTheme` calls that would trigger the new FlagshipUI on native side

feat(cozy-intent): Add `componentId` parameter to `tryEmit`

---

packages/cozy-logger/index.d.ts

The nested `declare` is not necessary and may cause problems on `cozy-client`.

chore(cozy-logger): Fix types

---

packages/cozy-mespapiers-lib/src/components/Hooks/useReferencedContact.jsx

In this case `data` is `null` and not an empty array.
We therefore make sure to always return the same type whatever the value returned by `data`.
fix of https://github.com/cozy/cozy-libs/pull/2401

fix(mespapiers): Manage the case where we have no contacts referenced

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.spec.jsx

We found out that this brings more confusion than help to the user and
there are more and more error types where it is legit to keep the same
password anyway.

[SCR-64] fix: Do not disable submit buton when password is the same

---

packages/cozy-harvest-lib/src/components/TwoFAModal.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx

When the konnector was asking 2FA code multiple times, the user could
not submit the 2nd code since the submit button was forefever disabled.
This bug was due to the dependency on "konnectorRunning" in the flow
state. I don't know why this dependency was needed and neither the git
history or unit tests would help me.
But with this condition removed, every 2FA code are asked properly.
I also changed the related unit test to have more tests on this case
(which failed silently before).

[SCR-22] fix: No more disabled submit button on 2nd 2FA

---

packages/cozy-mespapiers-lib/src/components/Actions/Items/importAuto.js

After several uses, it appears that the expected action following clicking on "Recover automatically" should not change and should always suggest installing a connector, or connecting an account if it is already installed.

feat: Remove some logic in ImportAuto action

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js

It is necessary to base it on `sourceAccountIdentifier` and not the `sourceAccount`, because the latter is not synchronized between two reconnections of konnector.

fix: Use sourceAccountIdentifier instead sourceAccount

---

packages/cozy-harvest-lib/src/components/Datacards/index.jsx
packages/cozy-harvest-lib/src/datacards/DoctypeDebugCard.jsx
packages/cozy-harvest-lib/src/datacards/datacardOptions.js

- feat: Pass the sourceAccountIdentifier to harvest cards
- feat: Add doctype debug cards for bills, files and identities
- feat: Add realtime to doctype debug cards

[SCR-116] feat: Doctype debug cards integration

---

packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/ShareByLink.jsx
yarn.lock

copy-text-to-clipboard use deprecated command.exec which does not
work anymore on some desktop browser.

 Use navigator.clipboard instead of copy-text-to-clipboard

---

packages/cozy-mespapiers-lib/src/components/Contexts/PapersDefinitionsProvider.jsx

il fallait un refresh de plus pour que l'app prenne correctement la valeur du flag en considération. Maintenant que la var est construite dans le provider (qui fait de multiple rendu) il n'y a plus le souci, la bonne valeur est bien récupérée.

fix(mespapiers): HealthTheme flag value was wrong for paperDef creation

---

packages/cozy-mespapiers-lib/src/components/SearchResult/FlexsearchResultLine.jsx
packages/cozy-mespapiers-lib/src/components/SearchResult/helpers.js
packages/cozy-mespapiers-lib/src/components/SearchResult/helpers.spec.js

When clicking on the search result, we are redirected to the Cozy Contacts app. (Same behavior as the "See in Cozy Contacts" option)

feat(mespapiers): Change behavior when searching a contact

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/ContactEditDialog.jsx
packages/cozy-mespapiers-lib/src/components/Views/ContactEdit.jsx

In case there is only one contact referenced, we want to update the file name if it contains the name of the old contact.

feat(mespapiers): Rename file when referenced contact change

---

packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx
packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/connections/accounts.spec.js
packages/cozy-harvest-lib/src/datacards/DoctypeDebugCard.jsx
packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx
packages/cozy-harvest-lib/src/datacards/useDataCardFiles.js
packages/cozy-harvest-lib/src/helpers/konnectorBlock.js
packages/cozy-harvest-lib/src/helpers/konnectorBlock.spec.js
packages/cozy-harvest-lib/src/helpers/queries.js

Now that datacardOptions component also gives sourceAccountIdentifier,
use it to request the list of files.
This way, the files datacard will find files even when the user
disconnects/connects his konnector account.

[SCR-165] feat: Use sourceAccountIdentifier in files datacard

---

packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js

This fix is related to the problem encounter on the home : https://github.com/cozy/cozy-home/pull/2103
Sift can't replay this type of query. It needs an MongoDB operator before the array.

[VO-524] fix: Avoir losing cozy-client cache after reload

---

packages/cozy-sharing/src/components/Avatar/MemberAvatar.jsx

- A memory leak / bad component rerender in
sharingProvider seems to lose react props when
removing self from a sharing.
As a result, this will cascade in the react tree and end
in an unhandled crash that will kill the app completely (blank page).
- To fully handle this issue there is also something to handle
on cozy drive side
- Still, the root cause of the error has not been found yet.
But the error is severe enough to need this local fix

fix(sharing): Handle memory leak in self removal (VO-370)

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.spec.js
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.spec.js
packages/cozy-mespapiers-lib/src/locales/en.json
packages/cozy-mespapiers-lib/src/locales/fr.json
packages/cozy-mespapiers-lib/test/mockPaperDefinitions.js

Changement de la traduction EN, car "stranger" n'est pas très juste dans ce contexte.

feat(mespapiers): Rename "stranger" by "foreign"

---

packages/cozy-mespapiers-lib/src/components/Actions/utils.js
packages/cozy-mespapiers-lib/src/components/Contexts/PapersDefinitionsProvider.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.jsx
packages/cozy-mespapiers-lib/src/components/Multiselect/ShareBottomSheet.jsx
packages/cozy-mespapiers-lib/src/helpers/copyToClipboard.js

The Alert component has the `standard` `variant` by default, on the app we need the `filled`
The `standard` has a transparency that we don't want to have here.

fix(mespapiers): Change variant Alert

---

packages/cozy-notifications/src/webpack/config.js

cozy-notifications uses mjml to generate mail templates. mjml can not be minimized as is. So previously, we disabled minimize for the whole services configuration. It could lead to huge services bundle but it was working.
We discovered that configuring Terser plugin with keep_fnames to true is enough to allow minimization without breaking mjml. So let's use it to reduce services bundle size.
From the Terser plugin documentation :
keep_fnames (default false) -- Pass true to not mangle function names. Pass a regular expression to only keep function names matching that regex. Useful for code relying on Function.prototype.name. See also: the keep_fnames compress option.

chore: Minimize services when cozy-notifications is used

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js

Replaced by `KNOWN_DATE_METADATA_NAMES` from cozy-client, since version 104 of cozy-ui.
cf: https://github.com/cozy/cozy-ui/releases/tag/v104.0.0

fix(mespapiers): The knownDateMetadataNames constant has no longer exist

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx

Correction rapide, si le besoin doit s'étendre il faudra sans doute voir pour créer un nouveau type (ex `float`)
Amélioration également de la regex pour accepter que ce genre de format : `123` | `123,1` | `123,12` | `123.1` | `123.12`

fix: Change the accepted format for pay_sheet numeric fields

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/banking/BalanceHistory.js
packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccountStats.js
packages/cozy-doctypes/src/banking/BankTransaction.js

Because of this, all fetched transaction where always updated on stack
which caused a large overhead for each banking connector execution

fix: Misspelled checkedAttributes -> checkAttributes for bank objects

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/InformationDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/components/Views/InformationEdit.jsx

Depending on whether we are on the creation or editing component, the current step is not retrieved in the same way.

fix(mespapiers): Use currentStep from props instead hook

---

package.json
packages/cozy-intent/package.json
packages/cozy-intent/src/api/services/NativeMessenger.spec.ts
packages/cozy-intent/src/api/services/NativeMessenger.ts
yarn.lock

We log every error from native side to avoid being in the dark when there is no catch in both native and webview sides.
We use a warn log to trigger a Sentry upload on native side.
On native side : ` WARN  cozy-intent Error during intent to http://photos.zatteo.10-0-2-2.nip.io:8080/ :  {"name":"Error","message":"ABCD"}`
What do you think of this implementation ?

feat: Log every error from native side

---

packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx
packages/cozy-harvest-lib/src/datacards/useDataCardFiles.js

Since https://github.com/cozy/cozy-libs/pull/2447/files we changed the way to fetch the files related to a konnector by using the sourceAccountIdentifier.
But this sourceAccountIdentifier can be the same for other konnectors, so if we had several konnectors with the same sourceAccountIdentifier (since it's generaly your main mail address...) we'll display the wrong files.
We should also filter by konnector slug.

fix: We should request the files for the right slug and account

---

packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/datacards/ViewerModal.jsx
packages/cozy-harvest-lib/src/helpers/queries.js

Parameter of useDataCardFiles change but we didn't update ViewerModal properly. I chose to search this param with a query to io.cozy.accounts as we had already this information without changing route path.  This is a temporary fix and I think we need to refactor the viewer part to have an abstraction to account in this modal

fix: Use sourceAccountIdentifier and konnector slug to show viewer modal

---

packages/cozy-mespapiers-lib/src/constants/papersDefinitions_health.json

It's now possible to create a paper with the qualification `national_health_insurance_right_certificate`

feat(mespapiers): Add a health paper

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Home/ContentFlexsearch.jsx
packages/cozy-mespapiers-lib/src/components/Home/ContentWhenSearching.jsx
packages/cozy-mespapiers-lib/src/components/Home/HomeLayout.jsx
packages/cozy-mespapiers-lib/src/components/Home/SearchHeader.jsx
packages/cozy-mespapiers-lib/src/components/Home/helpers.js
packages/cozy-mespapiers-lib/src/components/Home/helpers.spec.js
packages/cozy-mespapiers-lib/src/components/Papers/KonnectorsCategories.jsx
packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx
packages/cozy-mespapiers-lib/src/components/Papers/helpers.js
packages/cozy-mespapiers-lib/src/components/Search/useSearchResult.jsx
packages/cozy-mespapiers-lib/src/components/ThemesFilter/ThemesFilter.jsx
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.js
packages/cozy-mespapiers-lib/src/helpers/findPlaceholders.spec.js
packages/cozy-mespapiers-lib/src/types.js
yarn.lock

Cette PR ajoute la possibilité de sélectionner plusieurs thèmes dans le filtre de recherche, auparavant bloqué à un seul choix.
J'ai pu remarquer également que la lib `fuse.js` était toujours en dépendance, alors que nous utilisons depuis quelques temps `flexsearch` à la place. Je l'ai donc supprimé, ainsi qu'une fonction inutilisée qui l'utilisait.

feat(MesPapiers): Filter with several themes

---

packages/cozy-mespapiers-lib/src/components/Views/PlaceholdersSelector.jsx
packages/cozy-mespapiers-lib/src/helpers/queries.js

Today for documents that we retrieve via a single konnector we have 2 different behaviors depending on where I perform the action of adding the document.
Case 1: If we add the document from the home page and the konnector is already installed, we are just redirected to the category.
Case 2: If we add the document from the document category this opens the harvest modal.
This commit allows you to open the harvest modal even from the home page.

feat(mespapiers): Homogenize the behavior of `importAuto`

---

packages/cozy-mespapiers-lib/src/components/Papers/helpers.js

This function is called in the `ContentWhenSearching` & `ContentWhenNotSearching` components, in the latter there is no notion of search and therefore `selectedThemes` is not transmitted.

fix(mespapiers): The `selectedThemes` argument of `makeQualificationLabelsWithoutFiles` may be undefined.

---

packages/cozy-app-publish/src/cozy-app-publish.js

This PR will allow me to use manual mode into a Travis CI to complete the continuous deployment on cozy-settings. I use semantic-release to manage tags. The problem is that the version on Travis CI is determined by TRAVIS_TAG which is set before the start of the CI and not during the process.

[VO-591] feat: Allow the possibility to override the mode even on Travis CI

---

packages/cozy-mespapiers-lib/docs/papersDefinitions.md
packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/ModelSteps/InformationDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/RadioAdapter.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/RadioAdapter.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/RadioAdapterItem.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/proptypes.js
packages/cozy-mespapiers-lib/src/components/Views/InformationEdit.jsx
packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
packages/cozy-mespapiers-lib/src/constants/papersDefinitions_health.json
packages/cozy-mespapiers-lib/src/types.js
yarn.lock

Cette PR change les étapes d'informations permettant de renseigner le délai de prévenance avant l'expiration du fichier.
Ces dernières étaient présentées sous forme d'un champs texte, elles sont maintenant présentées avec une liste d'options.
Cette liste d'options est une nouvelle implémentation, appliqué également à la liste d'options des types de contrat du papier `work_contract`.

Feat(mespapiers): Suggest a list of choices for configuring the notice period

---

packages/cozy-sharing/src/components/Recipient/GroupRecipientPermissions.jsx

The prop `document` is needed to revoke a group [here](https://github.com/cozy/cozy-libs/blob/8c480a31c95c93df13d21668a87167e5e9a63103/packages/cozy-sharing/src/components/Recipient/GroupRecipientPermissions.jsx#L45) but I did pass anything so it was crashing. I don't understand why eslint didn't detect this error 🤔

[VO-438] fix(GroupRecipientPermissions): Missing document props

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx

This "can't connect" link displays a link to the vendor website which
has no meaning without any vendor_link

fix: Do not display can't connect link if no vendor link in konnector (SCR-528)

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/DumbTriggerManager.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.spec.jsx
packages/cozy-harvest-lib/src/konnector-policies.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/policies/biWebView.js
packages/cozy-harvest-lib/src/policies/clisk.js
packages/cozy-harvest-lib/src/types.js
packages/cozy-harvest-lib/test/fixtures.js
yarn.lock

The konnector identifiers won't be saved in vault when
the konnector's manifest does not have any vendor_link.
This avoids to have the whole list of identifiers displayed to
the user when he tries to configure a konnector without
any vendor_link, like NextCloud.
- **fix: Minor upgrade of cozy-ui**
BREAKING CHANGE: you must have `cozy-ui >= 103.12.0`

fix: Do not save identifiers in vault when no vendor_link (SCR-531)

---

packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactList.jsx
packages/cozy-mespapiers-lib/src/helpers/fetchCurrentUser.js
packages/cozy-mespapiers-lib/src/helpers/fetchCurrentUser.spec.js

Today if myself doesn't exist, the contact modal in the paper creation process displays nothing and prevents validation of the step.
As it's possible to delete myself in cozy-contacts for example, we must not block the creation of paper depending on its existence.

fix(mespapiers): Create a paper if myself does not exist

---

packages/cozy-harvest-lib/src/components/DumbTriggerManager.jsx

When the user tries to connecteur a server konnector with
wrong identifiers and fix identifiers and retry conection,
the  previous identifier a resent to the konnector and an
io.cozy.account document, not linked to any trigger is also
created for each atempt.
Now the trigger manager will reuse the account from the
the current ConnectionFlow instance when possible.

fix: Transmit correct account identifiers on reconnect (SCR-508)

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/CountryListAdapter.jsx
yarn.lock

Via l'OCR, le valeur provient d'un champs texte, il peut donc y avoir des valeurs comme "fra", "bob", "aa", etc.
Ces cas n'étaient pas gérés et provoquaient des problèmes lors de l'édition.

fix(mespapiers): Ensure country code used for translation is valid

---

packages/cozy-mespapiers-lib/package.json
packages/cozy-mespapiers-lib/src/components/Contexts/FormDataProvider.jsx
packages/cozy-mespapiers-lib/src/components/Contexts/StepperDialogProvider.jsx
packages/cozy-mespapiers-lib/src/components/CreatePaperDataBackupRoute.jsx
packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ContactDialog.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanActionsWrapper.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanFlagshipActions.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanMobileActions.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanWrapper.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/ScanResult/ScanResultDialog.spec.jsx
packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js
packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/SubmitButton.spec.jsx
packages/cozy-mespapiers-lib/src/components/Views/CreatePaperModal.jsx
packages/cozy-mespapiers-lib/src/helpers/paperDataBackup.js
packages/cozy-mespapiers-lib/src/types.js
packages/cozy-mespapiers-lib/src/utils/indexedStorage.js
packages/cozy-mespapiers-lib/test/components/AppLike.jsx
packages/cozy-mespapiers-lib/test/jestLib/setup.js
yarn.lock

During a document scan, the mobile operating system can kill the mespapiers webview if the phone is on low memory. When the document scan end, the flagship app detect that mespapiers has been killed and start it again **from scratch**. So we loose everything we did on the form and we loose the scan. 
So here we make it more resilient by : 
1. remembering before a document scan the state of the form _browser side_
2. remembering after a document scan the result of the scan _native side_
3. when mespapiers is started, mespapiers can check if it needs to restore a form with the data from 1. and 2. to go back to the paper creation modal as if nothing happened :tada:
Linked PR on cozy-flagship-app : https://github.com/cozy/cozy-flagship-app/pull/1208
See it in action (a click on "Cancel" …

Make document scan more resilient

---

packages/cozy-intent/src/api/models/events.ts
packages/cozy-intent/src/api/models/messengers.ts
packages/cozy-intent/src/api/models/methods.ts
packages/cozy-intent/src/api/services/NativeService.spec.ts
packages/cozy-intent/src/api/services/NativeService.ts

When receiving an intent on the flagship app, we want to know which webview sent the intent. Here we inject at the beginning of the `args` array an `options` object with the `webviewUri`.
*Example*
On a front end app, we will do
`webviewIntent.call('multiply', 2, 3)`
On flagship app, we will set a local method
`multiply: (options, arg1, arg2) => return arg1 * arg2`
=> the options object has been added at the beginning of the `args` array
We also add a new NativeMethodsRegisterWithOptions to modelize this new behavior.
BREAKING: A options object has been added in NativeService message args. You need to update your local methods (see example). FLAGSHIP APP ONLY. Nothing to do on a front end app.

feat: Add options object in NativeService args

---

packages/cozy-release/scripts/cozy-release.sh

The user will be warned with the following message :
```
⚠️   You will have to validate this version to make it available
to all users
```
when the editor of the application is not Cozy.
This will prevent the developer from testing the wrong version of the application

feat: Warn the user when editor is not Cozy (SCR-671)

---

packages/cozy-harvest-lib/src/components/TwoFAModal.jsx

I don't understand how this feature could work before, but it worked in
version 1.76.0 of the home application with harvest version 23.0.0.
With this click handler, I cannot detect any double submit of the form.

fix: Submit 2FA form on click (SCR-777)

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/helpers/konnectorBlock.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
yarn.lock

BREAKING CHANGE:
you must have `@sentry/react >= 7.118.0`

feat(harvest): Use Sentry as peerDeps

---

.travis.yml

Since we change the type of npm token to automation, it has no more read access
In future version, this option can be removed because its the default case. You can found more explanation on the command [documentation](https://github.com/lerna/lerna/tree/main/libs/commands/publish#--verify-access)

[VO-1033] chore(lerna): Stop verifying the npm read access on publish

---

packages/cozy-device-helper/src/flagship.ts
packages/cozy-device-helper/src/index.ts
packages/cozy-intent/src/api/models/methods.ts

`flagshipLinkRequest` intent will be used by new `FlagshipLink` link in cozy-client

feat: Add offline related methods to cozy-intent and to cozy-device-helper

---

packages/cozy-viewer/package.json
packages/cozy-viewer/src/NoViewer/DownloadButton.jsx
packages/cozy-viewer/src/ViewersByFile/PdfMobileViewer.jsx
packages/cozy-viewer/src/components/Toolbar.jsx
packages/cozy-viewer/src/helpers.js
packages/cozy-viewer/src/helpers.spec.js

In cozy/cozy-client#1518 we implemented a new `downloadFile()` that allow to download files as before in a browser, but will download files through cozy-intent when hosted in the Flagship app
This commit will replace the old way to download files with the new one using `downloadFile()`
BREAKING CHANGE: `downloadFile()` method has been removed from `cozy-viewer/src/helpers.js`. Use the one from
`cozy-client/dist/models/file` instead
BREAKING CHANGE: cozy-viewer now requires cozy-client >= 49.0.0 (used for offline support)
___
Related PRs:
- cozy/cozy-client#1518
- cozy/cozy-flagship-app#1237
___
TODO:

feat(cozy-viewer): Use new `downloadFile()` method from cozy-client

---

packages/cozy-harvest-lib/src/connections/accounts.js

Using the collection's `.getAll()` method was not compatible with offline mode
Instead we want to use a query with `getByIds()` selector that is compatible with offline mode and also return the same data

fix(cozy-harvest-lib): Use a query for fetching accounts

---

packages/cozy-viewer/package.json

This commit purpose is to trigger a breaking change because I forget it in
a24596a1ec085df5cef9328a649c76c8dab910a9
BREAKING CHANGE: you must now use `cozy-client >= 50.0.0`,
`cozy-harvest-lib >=30.2.0`, `cozy-intent >= 2.26.0` and
`cozy-ui >= 112.2.0`

feat: Update deps and peer deps for cozy-viewer

---

package.json

This commit aims to remove flaky crash on CI build due to node. We follow the solution proposed inside https://github.com/nodejs/node/issues/51555 that disable compile cache on v8
When the build inside CI was running on some package fail with this errors : 
```
#
#
#
#
#FailureMessage Object: 0x7fff3a2df8b0
```
or : 
```
Segmentation fault (core dump)
```

chore: Remove flaky crash on CI build

---

.github/workflows/ci-cd.yml
package.json

Since Lerna didn't have access to the git history, it couldn't determine what changes had been made and assume that all packages had been updated

[VO-1181] chore: Update GitHub Actions to give Lerna access to git history

---

package.json
packages/cozy-viewer/src/ViewersByFile/ImageViewer.spec.jsx
packages/cozy-viewer/src/ViewersByFile/PdfMobileViewer.spec.jsx

Avec ce commit, cozy-ui ne sera PLUS présent dans les node_modules à la racine. Il sera dans chaque node_modules de chaque package.

Add nohoist for cozy-ui

---

packages/cozy-dataproxy-lib/package.json
packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/consts.ts
packages/cozy-dataproxy-lib/src/search/queries/index.ts

We now rely on the checkbox on login to determine whether or not the local search should be used. If the user enable this checkbox, it means he trusts this device and accept to store local data on it. Otherwise, we do not store any private data, and directly query the stack to build the search index.
Note the update mechanism is the same and rely on realtime. The difference is that we do not replicate the document for non local search.

[PRD-600] feat: Use local search only for long-term sessions

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeFile.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeFile.ts
packages/cozy-dataproxy-lib/src/search/queries/index.ts

Say you have a "Foo" directory with a "bar.txt" in it. Let's assume this
bar.txt is duplicated in many locations. You want to search specifically
for it by typing "Foo bar".
It wasn't possible before because of how flexsearch works: it searches
by indexed attributes, here the `path` and the `name`. In this example,
"Foo bar" will not match the name, neither the path.
As a workaround, we now force the path computing at indexing time for
all files. This path is not persisted in PouchDB, as the stack does not
store it for files (but it does for directories).
Note that even though the stack returns the file's path when we query
it, we need to add the file name, as it does not include it.

[PRD-609] Allow search on name and path

---

packages/cozy-dataproxy-lib/src/search/helpers/normalizeFile.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts

With https://github.com/cozy/cozy-libs/pull/2612,
we added the possibility to search on path + name by adding the name in the path, at indexing time.
This breaks the possibility to open file because the path is not what is expected. So we remove the name from the path after search time.

[PRD-609] fix: Broken file path

---

packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts
packages/cozy-dataproxy-lib/src/search/types.ts

This is useful to allow click on subtitle, typically for a directory path below a file result

[PRD-610] feat: Add secondaryUrl to search result

---

packages/cozy-viewer/src/Panel/getPanelBlocks.jsx

When editing the doc from mespapiers, we don't want to display the konnector block.

feat(Viewer): Add filter condition to display konnectorBlock

---

packages/cozy-viewer/src/Panel/getPanelBlocks.jsx

This reverts commit bb59023be43e8ad5c6ca22141ece56529f77f5af.
This commit will hide the konnectoBlock as soon as the document is modified via MesPapiers.
However, we only want to hide the konnectoBlock for documents that have already had the carbonCopy metadata AND if the modification only concerns the binary or the metadata.

revert "feat(Viewer): Add filter condition to display konnectorBlock"

---

packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts

We now have the same behaviour between files and directories, i.e. the subTitle is the parent directory, and the secondaryUrl is the parent url

[DAT-69] feat: Use parent path in secondary url and subtitle

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeFile.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeFile.ts

We noticed a huge performance drop at indexing time: for 44K files, it was taking 20000+ ms to index it.
The issue was in the paths computation, that was hugely sub-optimal for no reason.
Now, the indexing takes ~400ms for 44K files.

feat: Improve indexing time

---

packages/cozy-viewer/src/index.jsx

The need for `SharingButton` comes from the migration of cozy-photos

feat(cozy-viewer): Exposing the components used by apps at the root

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts
packages/cozy-dataproxy-lib/src/search/queries/index.ts
packages/cozy-dataproxy-lib/src/search/types.ts

Flexsearch has a built-in store capability, in order to store the full content of indexed documents.
This is useful, however, this takes extra memory for nothing, as we already have the cozy-client store. All the indexed documents for the search are supposed to exist in cozy-client store, as we query them from Pouch at init, and retrieve updates from realtime, already plugged in cozy-client.

[DAT-70] feat: Do not use flexsearch store

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts

We enable the "reverse" tokenization mode, which allow to search both in forward and backward directions on tokens.
The forward mode allows to search from left to right, while the reverse mode allows the opposite. For example, with the word "example", you can search "exam" in forward mode, and "ample" in reverse.
We measured a 15-20% memory impact on enabling the reverse tokenization, compared to the forward mode.
The "full" mode, allowing searching on all combinations, including in the middle of the word, comes with ~70% memory increase. So, we decided to to not enable it for now, as the cost/benefit ratio of such feature is unclear.
The memory cost of enabling the reverse mode seems however reasonable.

[DAT-70] feat: Use forward and reverse tokenization

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts
packages/cozy-dataproxy-lib/src/search/queries/index.ts
packages/cozy-dataproxy-lib/src/search/types.ts

This reverts commit 104ea850ef9b2bf5ae5094f5d10f81bf8872bcf1. As we dynamically compute the path, that is not stored on PouchDB, it is required to store it in the cozy-client store and thus update all the files accordingly with the path.
However, this is not usual to do so and might lead to unexpected side-effects.
So for safety, we revert this commit for now and might rethink this later.

fix: Revert "feat: Do not use flexsearch store"

---

packages/cozy-realtime/package.json
packages/cozy-realtime/src/CozyRealtime.js

refactor: Remove unused cordova events

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/src/OpenSharingLinkButton.jsx
packages/cozy-sharing/src/OpenSharingLinkFabButton.jsx
packages/cozy-sharing/src/actions/openSharingLink.js
packages/cozy-sharing/src/components/SharingBanner/components/PublicBanner.jsx
packages/cozy-sharing/src/helpers/sharings.js

In some cases, as in the Viewer, we want to display shorter text.

feat(cozy-sharing): Add isShortLabel prop to OpenSharing's buttons

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/getSearchEncoder.ts

Sometimes a search could return surprising results, with no clear match. For instance a "test" search would return a file with the name "dist.pdf".
This is because we used the "balance" encoder, which performs a "literal" transformation on text, e.g. "d" matches "t", "i" matches "e", and so on. Thus, "dist" is transformed into "test", hence the matching.
See all examples here: https://github.com/nextapps-de/flexsearch/blob/master/src/lang/latin/balance.js#L24
This is not wanted in our case, and makes the index bigger, so we disable it and use "simple" encoder instead, that handle case and charset tranformations

[DAT-73] Fix encoder search

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/package.json
packages/cozy-sharing/src/actions/shareNative.js
packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/providers/NativeFileSharingProvider.jsx

Add a provider and a action to expose an ActionMenu action that can share files with mobile device share capabilities.
shareFilesNative from the NativeFileSharingProvider must be passed to the action.
Inspired from code in mespapiers. It will be used in cozy-drive, cozy-notes and mespapiers.

feat: Add NativeFileSharingProvider and shareNative action

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts

A user, that shall remain nameless, experienced a broken search when searching on the specific "test" string.
This is because some users really *love* testing edges cases with malformed documents.
Thus, we now better protect such situations.

fix: Deal with malformed docs

---

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx
packages/cozy-dataproxy-lib/src/search/SearchEngine.spec.js
packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/consts.ts
packages/cozy-dataproxy-lib/src/search/types.ts
packages/cozy-dataproxy-lib/tests/jest.config.js

It is now possible to pass a `doctypes` options to the search, that serves two purposes:
- Specify which doctypes should be searched
- Specify the doctype  order of the results

feat: Enable search options

---

packages/cozy-viewer/src/components/IntentOpener.jsx

Le fait d'utiliser Portal faisait qu'une fois l'intent ouvert, avec un input dans la modale, un onBlur était exécuté de suite après le onFocus. Donc impossible d'éditer le champ.
Ici on utilise le comportement par défaut, à savoir une Dialog, qui elle-même embarque Portal et Backdrop. On remplace simplement le PaperComponent pour avoir le rendu attendu, à savoir uniquement le Backdrop visible.

fix(Viewer): Now use intent inner dialog backdrop instead of custom one

---

packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx

instead of uploadedBy.slug. Because an app can edit the document and so the uploadedBy.slug key will be updated with the name of the app, erasing the konnector slug.
approche validée auprès de @KillianCourvoisier et @doubleface

fix(harvest): Konnector slug now relies on createdByApp in KonnectrBlock

---

config/rsbuild-config-cozy-app/getRsbuildConfig.js

By default Hot Module Rreplacement is configured to work with a localhost dev server
This server is responsible to serve the app and enable HMR
This wouldn't work with our apps because they are meant to be served by a local cozy-stack as a dev environment and so the cozy-app would try to connect to the HMR websocket using the cozy-stack's URL
Also the Rsbuild dev server is configured to serve built files from memory, so the `/build` folder would be empty and the cozy-stack wouldn't see any app
To fix this we can use both `dev.writeToDisk` and `dev.client` configurations
Then in order to benefit from this, the cozy-app should be run using `rsbuild dev` instead of `rsbuild build --watch`
More info:
- https://github.com/web-infra-dev/rsbuild/discussions/4366
- …

feat: Enable HMR on shared Rsbuild configuration

---

packages/cozy-dataproxy-lib/package.json

In consuming apps, we use to import the cozy-dataproxy-lib's stylesheet
Since 512e816cfe71a5087060d6cb001dc4f235b744f4 we use some exports in the package.json that may prevent to import the stylesheet
So we want to add this file to exports options
Related commit: 512e816cfe71a5087060d6cb001dc4f235b744f4

fix: Export `stylesheet.css` in cozy-dataproxy-lib's package.json

---

packages/cozy-viewer/src/ViewersByFile/PdfJsViewer.jsx
packages/cozy-viewer/src/ViewersByFile/styles.styl
packages/cozy-viewer/src/components/PdfToolbarButton.jsx

This PR improves the UX on the Viewer.
- Adjustment of the number of pages(40) to display the PDF in scroll mode (+ addition of a file weight constraint(10MB)).
- As a reminder, `react-pdf` uses web workers.
- Possibility of typing the page number (in page-by-page mode) in the small toolbar.
- Hide toolbar after a short period of inactivity(1s). Unless cursor is over or page number edit field is in focus.

feat(viewer): Improve UX

---

packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js

To be sure to have updated konnector fields displayed to the user.
This is a step backward regarding time optimization but we need to be
sure to have updated konnector fields or this can lead to block
konnector errors.

fix: Force the update of the current konnector (SCR-682)

---

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx

In previous implementation we disabled the DataProxy in Flagship app because this feature was not implemented yet in that environment
We are working on implementing it in the Flagship app, so we want the DataProxyProvider to be able to use the Flagship's implementation
This commit implements this by checking the feature availability on the Flagship app and then by redirecting the DataProxy calls through the webviewIntent
Related PR: cozy/cozy-flagship-app#1279

feat: Make the DataProxyProvider work in Flagship app

---

packages/cozy-viewer/src/Panel/Sharing.jsx
packages/cozy-viewer/src/ViewerContainer.jsx

When sharing a file from Cozy to Cozy, if a doc is not shared but inside a shared folder, the sharing must relies on the folder and not the file

fix(Viewer): Now use the folder as a reference when sharing

---

packages/cozy-viewer/src/Panel/getPanelBlocks.jsx

A new PR will come to adjust this condition with a props in the app

feat(Viewer): Hides sharing panel until sharing is fully functional

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/package.json
packages/cozy-sharing/src/SharingProvider.jsx
packages/cozy-sharing/src/components/Recipient/LinkRecipient.jsx
packages/cozy-sharing/src/components/ShareRestrictionModal/BoxPassword.jsx
packages/cozy-sharing/src/components/ShareRestrictionModal/ShareRestrictionContentModal.jsx
packages/cozy-sharing/src/components/ShareRestrictionModal/ShareRestrictionModal.jsx
packages/cozy-sharing/src/components/ShareRestrictionModal/helpers.js
packages/cozy-sharing/src/components/ShareRestrictionModal/helpers.spec.js
packages/cozy-sharing/src/helpers/permissions.js
yarn.lock

This PR fixes and improves the new share link UX.

feat(sharing): Improve Share by links

---

packages/cozy-dataproxy-lib/package.json
yarn.lock

BREAKING CHANGE: it is now required to have cozy-pouch-link as a dependency for a client to benefit from the local search functionalities.
This was typically always false: https://github.com/cozy/cozy-libs/blob/master/packages/cozy-dataproxy-lib/src/search/SearchEngine.ts#L56 in the flagship app and was forcing online search even though local data was available. As a side effect, the offline couldn't work.

fix: Cozy-pouch-link as peerDep to avoid version conflict

---

packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx

We experienced a crash from cozy-intent in a SharedWorker environment, i.e. from the dataproxy.
It appears it was because of the non-available window object.

fix: Crash on envs without window object

---

config/rsbuild-config-cozy-app/getRsbuildConfig.js

When in dev mode the `output.assetPrefix` value will be ignored, so we should also declare `assetPrefixes` in the `dev` section

fix: Declare assetPrefixes for dev mode in shared Rsbuild configuration

---

packages/cozy-dataproxy-lib/src/search/@types/cozy-client.d.ts
packages/cozy-dataproxy-lib/src/search/@types/cozy-realtime.d.ts
packages/cozy-dataproxy-lib/src/search/SearchEngine.ts

The flagship app already register the RealtimePlugin so the SearchEngine would try to register it a second time
We assume the consuming app should be responsible to do the registration so the solution would be to remove it from the SearchEngine initialization
But in order to ensure backward compatibility, we chose to keep the registration here but protected behind a check so the SearchEngine would register it only if not already registered

fix: Prevent registering RealtimePlugin if it is already registered

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/policies/biWebView.js
yarn.lock

Since harvest is the last using it and this package is not maintained
anymore. Let's keep this error map in harvest itself

refactor: Remove cozy-bi-auth dependency (SCR-297)

---

packages/cozy-viewer/package.json

BREAKING CHANGE: You must have `cozy-sharing >= 21.2.2`

feat(Viewer): Upgrade cozy-sharing

---

packages/cozy-dataproxy-lib/package.json
packages/cozy-dataproxy-lib/src/components/Search/useFetchResult.jsx
packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/consts.ts
packages/cozy-dataproxy-lib/src/search/indexDocs.ts
packages/cozy-dataproxy-lib/src/search/storage.ts
packages/cozy-dataproxy-lib/src/search/types.ts
yarn.lock

Each time a searchEngine is instanciated, we used to rebuild the search
indexes from scratch, i.e. query the local database and compute the
indexes.  This can be quite time consuming, especially in slow mobile
devices. Therefore, we now export the search indexes on disk, and import
them at init time.  We save the lastSeq for each index, to be the
starting point of the next changes batch updates, fetched from the local
database after a remote replication.
Some measures, performed on a 8K files database:
**Redmi Note 10**
- Query all io.cozy.files : 3700ms
- Build files index : 6500ms
- **Total: 10200 ms**
- **Import persisted index: 800 ms**
- Export index: 1057ms
**OnePlus Nord 4**
- Query all io.cozy.files : 2000ms
- Build files index : 2900ms
- **Total: 4900 ms**
- **Import persisted …

feat: Do not rebuild search index from scratch 

---

config/stylus-config-cozy-app/.stylintrc
config/stylus-config-cozy-app/LICENSE
config/stylus-config-cozy-app/README.md
config/stylus-config-cozy-app/package.json
yarn.lock

This configuration is copied from cozy-scripts
Because we are migrating our app bundler from create-cozy-app to Rsbuild, we will remove dependences to cozy-script from our app and so we will lose access to the embeded .stylintrc file
To prevent this we want to extract this `.stylintrc` file to its own config repository. Then Rsbuild project will be able to use it by installing `stylus-config-cozy-app` module

feat: Add a shared Stylus configuration to build cozy application

---

packages/cozy-realtime/src/CozyRealtime.js

This is a good one: after a token refresh made by cozy-client, the handler `onClientTokenRefreshed` is called.
It is supposed to reconnect, as mentioned in the function comments. However, probably due to exhaustion or evil clipboard, the realtime was **revoked** rather than reconnected.
This was probably causing the realtime failures that we noticed before without spotting the source.

fix: Reconnect realtime after refreshed token

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts

This is notably useful to be warned immedialty when the index are ready to be queried

[FRONT-2375] feat: Allow init to be called independently

---

packages/cozy-sharing/package.json
yarn.lock

BREAKING CHANGE: You must have `cozy-client >=57.0.0`

feat: Upgrade cozy-client

---

packages/cozy-sharing/src/components/ShareModal/EditableSharingModal.jsx

We had done this for the Viewer display, but it causes problems for the Drive modal, which also displays the parent folder share instead of the file share. We're changing the approach here, and we'll change it in the Viewer too.

fix(Sharing): Don't rely anymore on parent to show file recipients

---

packages/cozy-external-bridge/README.md
packages/cozy-external-bridge/package.json
packages/cozy-external-bridge/src/container/helpers.ts
packages/cozy-external-bridge/src/container/index.ts
packages/cozy-external-bridge/src/embedded/index.ts

We sent message from iframe to origin infered document.referrer because document.referrer, when in an iframe, is set initially to the iframe URL. But if a redirection happens in the iframe (which happens during an oauth login) document.referrer is updated. So we sent message from iframe to the wrong origin.
Here we introduce a way to ask the parent window, if it exists, his origin. We just take the origin from the parent window answer metadata. We do not trust the parent window.
By doing this, bridge will be able to work even after a reload or a redirection inside the iframe.

feat: Use parent origin instead of document.referrer

---

packages/cozy-dataproxy-lib/src/search/helpers/filePaths.ts

When paths are not sets, they are not kept in memory, hence the cache does not work correctly

fix: Correctly set paths in memory

---

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx

This adds the capacity to request the cozy-client through the DataProxy,
and then relying on local Pouch or remote Stack
:warning: This relies on #2772 that should be merged first

feat: Add support for requestLink

---

packages/cozy-external-bridge/package.json
packages/cozy-external-bridge/src/container/useListenBridgeRequests.ts
yarn.lock

We now create empty Docs file at their creation to avoid any side-effect such as RAG indexation.
We also create Docs file with `.docs-note` extension to avoid any edition of the markdown by an external editor that would be overwritten by Docs.  See https://github.com/cozy/cozy-libs/pull/2789

fix: Upload empty Docs file

---

packages/cozy-search/src/components/Conversations/ChatItemLabel.jsx
packages/cozy-search/src/components/helpers.js
packages/cozy-search/src/components/helpers.spec.js

Apparently, the `ChatItemLabel` can receive label that is not string. That was causing crash on assistant.

fix: Avoid crashing on non-string element

---

packages/cozy-external-bridge/src/container/useListenBridgeRequests.ts
packages/cozy-external-bridge/src/embedded/index.ts

Notifications can not be requested and sent from iframe. So let's expose this API in the bridge so the parent frame can execute these methods.
For the moment in draft to talk about the API.

feat(cozy-external-bridge): Expose notification API

---

packages/cozy-dataproxy-lib/src/search/indexDocs.spec.js
packages/cozy-dataproxy-lib/src/search/indexDocs.ts
packages/cozy-dataproxy-lib/tests/jest.config.js

With the current search setting, this case was not working:
```
filename: "UI-UX Guideline.cozy-note"
search: "UI-UX"
```
This is because the tokenizer takes the `-` as a separator and we end up
with ["UI", "UX"] tokens. As the minimal word length was 3, they were
skipped from the indexation.
So, we now specify a 2 minimal word length to handle this kind of cases.
Note this will slightly increase the index size

Edgecases search

---

packages/cozy-external-bridge/src/embedded/index.ts

To be able to synchronize history between embedded and container apps, we need to patch history.pushState and history.replaceState. But I made a mistake in the patch leading to strange behavior in embedded apps.
Thanks to @Crash-- that spot the issue 🙏

fix: Do not replace replaceState by pushState to avoid strange behavior

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
packages/cozy-dataproxy-lib/src/search/helpers/filePaths.spec.ts
packages/cozy-dataproxy-lib/src/search/helpers/filePaths.ts
packages/cozy-dataproxy-lib/src/search/helpers/normalizeSearchResult.ts

We noticed the search results are not immediatly updated after a file rename.
This is because the files fullpath are stored in-memory in a Map when relying on PouchDB, as paths are not stored, and we want to speed up their retrieval.
We missed a case to update the in-memory Map after a file change.
This PR also include small fixes that were discovered on the road.

Update in-memory fullpaths after file rename

---

packages/cozy-viewer/src/components/ToolbarFilePath.jsx

Set the correct file path in toolbar of file viewer
[cozy/cozy-drive#3470](https://github.com/cozy/cozy-drive/pull/3470)

fix: Set correct link to open shared drive from toolbar :bug:

---

packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/CozyRealtime.spec.js
packages/cozy-realtime/src/utils.js

If you want to activate realtime on a given shared drive : 
```javascript
import CozyRealtime from 'cozy-realtime'
const client = ...
const sharedDriveId = 'myshareddriveid'
const realtime = new CozyRealtime({client, sharedDriveId})
realtime.start()
```
```javascript
realtime.stop()
```
To stop the subscription
cozy-stack will automatically subscribe to shared drive files events
As it is implemented now, it is only possible to subscribe to a given shared drive, one at a time.
Needs https://github.com/cozy/cozy-stack/pull/4559 to be merged

feat(cozy-realtime): Add support for shared drives files

---

packages/cozy-dataproxy-lib/package.json
packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx
yarn.lock

Previously, the rendering of `DataProxyProvider` children were conditioned by the initialization of the dataproxy.
It was because we wanted to avoid timing issues, were the App started to use the DataProxy before it was actually ready.  See https://github.com/cozy/cozy-libs/commit/bdb16705103fa222d631750403d951eee61f4868
We later made it less strict, because if anything make the dataproxy not initialized, nothing is displayed on the app side with no logs, making it hard to debug for the developer.  See
https://github.com/cozy/cozy-libs/pull/2801
However, we still met situations with no rendering, because the dataproxy was not available at all:
- Public sharing: https://github.com/cozy/cozy-drive/pull/3439
- Unsupported shared workers: https://github.com/cozy/cozy-web-data-proxy/pull/36
So …

feat: Always render dataproxy children

---

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx

We noticed some unexplained app crash integrating the DataProxyProvider. The only reported of such cases is on Firefox web, on a Drive with a lot of files.
Let's add defensive protections on the `DataProxyProvider` to avoid app crash if anything goes badly in the dataproxy

Add protections for DataProxyProvider

---

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts

We were not using properly the doctype array option: it is an empty array by default, but we were checking its existence rather than its emptyness

fix: Empty doctype array

---

packages/cozy-sharing/src/SharedDocument.jsx
packages/cozy-sharing/src/SharingProvider.jsx
packages/cozy-sharing/src/state.js

Update the function `hasWriteAccess` in `SharingProvider` to check correct write access in case of shared drive.
[cozy/cozy-drive#3532](https://github.com/cozy/cozy-drive/pull/3532)

fix: Check correct sharing rule in shared drive :bug:
