lerna.json, package.json, yarn.lock
Workspaces are a new way to setup your package architecture that’s
available by default starting from Yarn 1.0. It allows you to setup
multiple packages in such a way that you only need to run yarn install
once to install all of them in a single pass.
[Yarn Documentation](https://yarnpkg.com/lang/en/docs/workspaces/)
=> chore: Use yarn workspace instead of lerna 👾

packages/realtime/src/index.js
~~BREAKING CHANGE: `url` is no more used in config and must be replaced by `domain` and `secure` attributes~~
~~Two informations was passed with the `url` attribute: the security protocol and the cozy domain. But they're was a flaw with url like `http://cozy.tools:8080`. The unsecure protocol was detected correctly, but the domain was not parsed and has `undefined` value.~~
Eventually, this PR just adresses the issue caused by a bad RegExp matching.
=> Realtime: Add `domain` and `secure` to config

packages/realtime/package.json
Simple watch using only babel, based on build task.
=> Add watch task for realtime

CODEOWNERS, README.md, packages/doctypes/.eslintrc, packages/doctypes/package.json, packages/doctypes/src/BalanceHistory.js, packages/doctypes/src/BalanceHistory.spec.js, packages/doctypes/src/BankAccount.js, packages/doctypes/src/BankAccount.spec.js, packages/doctypes/src/BankTransaction.js, packages/doctypes/src/BankTransaction.spec.js, packages/doctypes/src/Document.js, packages/doctypes/src/Document.spec.js, packages/doctypes/src/index.js, packages/doctypes/src/log.js, packages/doctypes/src/testUtils.js, packages/doctypes/src/utils/BankingReconciliator.js, packages/doctypes/src/utils/BankingReconciliator.spec.js, packages/doctypes/src/utils/__snapshots__/BankingReconciliator.spec.js.snap, yarn.lock
This brings the code from cozy-doctypes for working with doctypes
that are shared between several codebases here.
=> feat: add doctypes

packages/doctypes/src/Document.js, packages/doctypes/src/Document.spec.js
We did not wait on fetchAll and deleteAll was not called with the right documents.
=> fix(duplicates): Wait for fetchAll promise

packages/doctypes/src/BankTransaction.js, packages/doctypes/src/Document.js, packages/doctypes/src/utils.js, packages/doctypes/src/utils.spec.js, packages/doctypes/src/utils/BankingReconciliator.js
1. log was at the wrong place and was leading to a false positive
2. Add more debug logs
=> feat: Better logs

packages/doctypes/.gitignore, packages/doctypes/examples/bulk.js, packages/doctypes/package.json, packages/doctypes/src/Document.js, packages/doctypes/src/Document.spec.js, yarn.lock
When bulk updating database was not automatically created
resulting in failures of the balance histories update.
=> Create database when bulk updating

packages/cozy-release/scripts/cozy-release.sh
* Set release and patch branches upstream after push
* Avoid cherry-picking merge commits when ending a patch
=> Enhancements for cozy-release

package.json, packages/commitlint-config/README.md, packages/commitlint-config/index.js, packages/commitlint-config/index.spec.js, packages/commitlint-config/package.json, yarn.lock
On this PR I add limitation (72 chars) on each line on body commit.
I remove unnecessary dependencies and add some documentation.
=> Add limitation on body 📏

packages/interapp/src/client.js, packages/interapp/src/dom.js, packages/interapp/src/helpers.js, packages/interapp/src/intents.js, packages/interapp/src/intents.spec.js, packages/interapp/src/listener.js, packages/interapp/src/testUtils.js
Separate client.js into 
- DOM functionality : iframe insertion, hide/show/remove DOM node : `dom.js`
- Handshake related functionality and message receiving/dispatching : `listener.js`
- Business related functionality : `client.js`
=> refactor: Explode client.js

packages/cozy-release/scripts/cozy-release.sh
After fixing script to make it work in Travis, it was not working under given shell (like MacOS for example)
=> Make shift command works on every shell

packages/cozy-release/scripts/cozy-release.sh
Was not working in fish. Exclamation mark was misplaced.
=> Fix shebang (again)

.eslintignore, .eslintrc, package.json, packages/babel-preset-cozy-app/index.js, packages/commitlint-config/.eslintrc, packages/commitlint-config/package.json, packages/cozy-app-publish/.eslintrc.json, packages/cozy-app-publish/package.json, packages/cozy-device-helper/.eslintrc, packages/cozy-device-helper/package.json, packages/cozy-release/cozy-release.js, packages/doctypes/package.json, packages/eslint-config-cozy-app/basics.js, packages/eslint-config-cozy-app/react.js, packages/eslint-config-cozy-app/vue.js, packages/flags/.eslintrc, packages/flags/package.json, packages/interapp/.eslintrc, packages/interapp/package.json, packages/realtime/.eslintrc, packages/realtime/package.json, yarn.lock
To fix https://github.com/cozy/cozy-libs/issues/15
=> chore: Use eslint global

packages/cozy-release/scripts/cozy-release.sh
It just a matter of manifest extension, after all.
Ping @doubleface :tada:
=> Make cozy-release work with konnectors as well

packages/cozy-release/scripts/cozy-release.sh
The previous command does not work well in Ubuntu and it makes Travis fail.
=> Change semver parsing

packages/cozy-release/cozy-release.js
=> fix: run cozy-release script using bash

packages/cozy-release/scripts/cozy-release.sh
If a `.release-template.md` file is present, a pull-request is made at the end of the start command.
Also a `--pr` option is now available to specify another file containing pull-request description.
=> Add pull-request option for cozy-release start

packages/renovate-config-cozy-app/package.json
You can see renovate documentation [here][doc].
[doc]: https://renovatebot.com/docs/configuration-options/
=> feat: Exclude cozy libraries on schedule

packages/renovate-config-cozy-app/package.json
Regardless of what's currently in the PR, how do we want to handle version ranges?
[Here are our options](https://renovatebot.com/docs/configuration-options/#rangestrategy). Explain what you prefer and why, and we'll implement whatever makes the most sense.
=> [renovate] Handling version ranges

packages/cozy-doctypes/src/BankTransaction.js, packages/cozy-doctypes/src/utils/BankingReconciliator.js
This option will be used to send some events to Piwik.
=> feat(doctypes): Add reconciliate options

packages/cozy-device-helper/README.md, packages/cozy-device-helper/src/apps.js
Add also some context in the logs
=> doc: Update readme about startApp & check App

packages/cozy-release/scripts/cozy-release.sh
Condition checking hub existence was wrong
=> Fix hub condition

packages/cozy-doctypes/src/BankTransaction.js
Log missed transactions date and original bank label
=> feat(doctypes): Add logs

packages/cozy-doctypes/src/BankTransaction.js, packages/cozy-doctypes/src/BankTransaction.spec.js, packages/cozy-doctypes/src/utils/BankingReconciliator.js, packages/cozy-doctypes/src/utils/BankingReconciliator.spec.js, packages/cozy-doctypes/src/utils/__snapshots__/BankingReconciliator.spec.js.snap
* Add meaningful warn logs
* Update options for more efficient tracking
* Fetch all transactions so searching missed transactions is more robust
=> Transaction reconciliation enhancements

packages/cozy-doctypes/src/Document.js
So we know when that case occurs.
=> feat(doctypes): Log when createOrUpdate didn't update anything

packages/cozy-doctypes/src/BankAccount.js, packages/cozy-doctypes/src/BankAccount.spec.js, yarn.lock
Move code from ACH here, to be able to share it between the Linxo connector and the cleaning job.
=> feat: Integrate find duplicates

package.json, packages/commitlint-config-cozy/README.md, yarn.lock
This PR add husky on dependency, it's already essential for commitlint and update documentation
=> Commitlint docs

packages/cozy-doctypes/src/Document.js, packages/cozy-doctypes/src/Document.spec.js
=> feat: Use _changes API

packages/cozy-doctypes/src/Document.js, packages/cozy-doctypes/src/Document.spec.js
The goal is in Banks to remove all this utils. This will help our services
to move to cozy-client.
=> feat: Add query all

packages/cozy-harvest/.babelrc, packages/cozy-harvest/CHANGELOG.md, packages/cozy-harvest/README.md, packages/cozy-harvest/package.json, packages/cozy-harvest/src/Harvest.jsx, packages/cozy-harvest/src/Harvest.spec.jsx, packages/cozy-harvest/src/__snapshots__/Harvest.spec.jsx.snap, packages/cozy-harvest/src/index.js, yarn.lock
First step to initialise cozy-harvest-lib
=> feat(Harvest): init cozy-harvest

packages/cozy-flags/package.json, packages/cozy-flags/src/flag.js, packages/cozy-flags/src/flag.spec.js, yarn.lock
I am going to implement node compatible flags, but there were no tests so I didn't feel comfortable with it.
=> test(flags): Add tests

packages/cozy-release/scripts/cozy-release.sh
When we use operator in a if statement we have to wrap it into double brackets
See https://stackoverflow.com/a/35281824
=> Fix`[: missing ']'` issue

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/Harvest.spec.jsx, packages/cozy-harvest-lib/src/Manifest.js, packages/cozy-harvest-lib/src/Manifest.spec.js, packages/cozy-harvest-lib/src/__snapshots__/Harvest.spec.jsx.snap, yarn.lock
Add function to sanitize Manifest before send it to the form generation
=> Add sanitizer

packages/babel-preset-cozy-app/package.json
Change repo url for `babel-preset-cozy-app`
=> babel-preset-cozy-app: Update package URL 

packages/cozy-harvest-lib/.babelrc, packages/cozy-harvest-lib/README.md, packages/cozy-harvest-lib/babel.config.js, packages/cozy-harvest-lib/jest.config.js, packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/src/index.js, packages/cozy-harvest-lib/test/components/AccountForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap, yarn.lock
No password
No date
No dropdown
No i18n
Just the few basic features
=> Add Basic AccountForm

packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
`medium` prop for `Field` being added into https://github.com/cozy/cozy-ui/pull/774
=> Improve AccountForm UI

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/AccountForm.spec.js, yarn.lock
This PR handles an account as prop to show existing values in AccountForm.
Also, add propTypes.
=> Harvest: Edition in AccountForm ✨

packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/src/locales/en.json
Inject I18n in Cozy-UI/Field to use InputPassword ( waiting I18n Cozy-UI is ok )
=> Harvest: Add props labels to InputPassword

packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Use field name as last fallback. Forgotten in #212
=> Harvest: Add field label fallback

packages/cozy-harvest-lib/src/components/AccountForm.jsx
PropTypes were missing for those two components.
=> Harvest: Set PropTypes for AccountField and AccountFields

packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/AccountForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Two little fixes:
* Ensure t mock is resetted
* Unset required propTypes fields, not required for OAuth accounts
=> Harvest: fix tests

packages/cozy-harvest-lib/src/Manifest.js, packages/cozy-harvest-lib/src/Manifest.spec.js, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/AccountForm.spec.js
Inject default value when there is no initial value
=> Harvest: Handle default values specified in Manifest

packages/cozy-harvest-lib/README.md, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Add default placeholder based on the field name and with I18n
=> Harvest: Add default I18n placeholder

packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/AccountForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Date were ready in Cozy-UI but not yet handled in Cozy-Harvest-Lib.
=> Harvest: Handle dates

packages/cozy-harvest-lib/test/helpers/fields.spec.js
Fix did not make it in the PR #236
=> Harvest: Fix failed commit

packages/cozy-harvest-lib/src/Manifest.js, packages/cozy-harvest-lib/src/Manifest.spec.js, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/AccountForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Add "(optioonal)" indicator for non required fields
=> feat(harvest): Add "(optional)" indicator for non required fields

packages/cozy-doctypes/babel.config.js, packages/cozy-doctypes/package.json, packages/cozy-doctypes/src/index.js
Prevent browsers like Edge 17 to crash when parsing spread operator.
=> Doctypes : transpile

CODEOWNERS, README.md, packages/babel-preset-cozy-app/index.js, packages/babel-preset-cozy-app/package.json, packages/browserslist-config-cozy/README.md, packages/browserslist-config-cozy/__snapshots__/index.spec.js.snap, packages/browserslist-config-cozy/index.js, packages/browserslist-config-cozy/index.spec.js, packages/browserslist-config-cozy/package.json, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap, packages/cozy-realtime/test/__snapshots__/createWebSocket.spec.js.snap, yarn.lock
Use a shareable config for our browserslist config, will be useful for babel, postcss, autoprefixer or others
=> Add browserslist package

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm.jsx, packages/cozy-harvest-lib/src/helpers/fields.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap, yarn.lock
Keep the same mechanism as in cozy-home.
=> Prevent autocomplete on inputs

packages/cozy-app-publish/lib/git.js, packages/cozy-app-publish/lib/hooks/pre/downcloud.js, packages/cozy-app-publish/lib/manual.js, packages/cozy-app-publish/lib/prepublish.js, packages/cozy-app-publish/lib/tags.js, packages/cozy-app-publish/lib/tags.spec.js, packages/cozy-app-publish/lib/travis.js, packages/cozy-app-publish/test/__snapshots__/manual.spec.js.snap, packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap, packages/cozy-app-publish/test/manual.spec.js, packages/cozy-app-publish/test/travis.spec.js, packages/cozy-app-publish/utils/runhooks.js
- Automatic version even in manual mode
- Error handling for CLI handler
=> Publish : Improvements

packages/babel-preset-cozy-app/index.js
See https://github.com/facebook/create-react-app/pull/5278
=> feat: Disable a transform that makes React slower

packages/eslint-config-cozy-app/package.json, yarn.lock
Voir:
- https://github.com/cozy/cozy-libs/pull/257
- https://github.com/cozy/cozy-libs/pull/286
=> Update eslint config cozy app dependencies

CODEOWNERS, packages/cozy-ci/README.md, packages/cozy-ci/github-comment.sh, packages/cozy-ci/package.json, packages/cozy-ci/transifex.sh
See the readme file for an explanation of what this PR does.
Note that I'm not 100% the `bin` trick will work out, but best way to find out is to publish the package!
=> [ci-utils] New package: ci utility scripts

.gitignore, babel.config.js, docs/styleguidist.config.js, package.json, packages/cozy-harvest-lib/package.json, yarn.lock
At first I set up styleguidist for cozy-harvest-lib but with almost no effort I moved the configuration to set it up on the whole monorepo.
It sounded like a good idea to me; I don't see any inconvenient to do this but I could be missing some points. Moving back styleguist to cozy-harvest-lib would be cheap.
=> Configure styleguidist

packages/cozy-doctypes/src/banking/BankTransaction.js, packages/cozy-doctypes/src/banking/BankTransaction.spec.js, packages/cozy-doctypes/src/banking/BankingReconciliator.spec.js, packages/cozy-doctypes/src/banking/__snapshots__/BankingReconciliator.spec.js.snap
Filter out new transactions that are too old when reconciliating.
=> No old reconciliation

packages/cozy-authentication/src/steps/SelectServer.jsx
autofocus is not the right prop in React, it must be autoFocus.
=> fix: Use correct attribute for autoFocus

packages/cozy-authentication/src/Authentication.jsx
It's now possible to custom components
=> feat(auth): Should render custom components

packages/cozy-flags/package.json, packages/cozy-flags/src/browser/FlagSwitcher.jsx, packages/cozy-flags/src/browser/flag.js, packages/cozy-flags/src/tests.js, yarn.lock
You can connect a component to flags so that when a flag
is changed, the component is automatically refreshed.
=> feat: Flags are observable

packages/cozy-mjml/CHANGELOG.md, packages/cozy-mjml/README.md, packages/cozy-mjml/example.mjml, packages/cozy-mjml/package.json, packages/cozy-mjml/src/components/MJCozyTitle.js, packages/cozy-mjml/src/components/index.js, packages/cozy-mjml/src/hacks/datauri-index.js, packages/cozy-mjml/src/hacks/mimer-parser.js, packages/cozy-mjml/src/hacks/uglify-node.js, packages/cozy-mjml/src/index.js, packages/cozy-mjml/test/__snapshots__/components.spec.js.snap, packages/cozy-mjml/test/components.spec.js, packages/cozy-mjml/webpack.config.js, yarn.lock
Cozy-mjml is a new package for sharing MJML components between mail templates in several projects. Currently, I've just added a single custom component to show how it will work later.
=> Add a cozy-mjml package for email templating

packages/cozy-mjml/src/components/MJFooter.js, packages/cozy-mjml/src/components/MJHeader.js, packages/cozy-mjml/test/__snapshots__/components.spec.js.snap
It looks like we have some issues to send emails with embedded images with mailjet. So, let's fallback on external URLs for the images in emails.
=> feat(cozy-mjml): Use external URL for images in emails

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap, yarn.lock
A snapshot was failing. I updated it because I thought it was no big deal. Please tell me if it's important.
=> fix(deps): Update cozy-ui to v19.21.0

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/index.js
* Translated TriggerManager was missing stuff like contextTypes definition.
* KeyUp event (for ENTER key on form) was not handler in React
* `aria-disabled=false` on Field was actually enabling the CSS style for aria-disabled component.
=> Harvest: Make code React compliant

packages/cozy-harvest-lib/src/connections/triggers.js, packages/cozy-harvest-lib/test/connections/triggers.spec.js
Attempt to fix realtime usage on mobile.
=> Harvest: Better realtime initialisation

packages/cozy-harvest-lib/README.md, packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx, packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/test/components/AccountFields.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountFields.spec.js.snap, packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
Also two minor refactors in the first two commits.
=> Harvest: Update documentation and comments

packages/cozy-doctypes/package.json, packages/cozy-doctypes/src/contacts/Contact.js, packages/cozy-doctypes/src/contacts/Contact.spec.js, packages/cozy-doctypes/src/contacts/Group.js, packages/cozy-doctypes/src/index.js
Add Contact model in `cozy-doctypes` package. Most of this code comes from `cozy-drive`
=> Add Contact and Group models

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, packages/cozy-harvest-lib/src/connections/accounts.js, packages/cozy-harvest-lib/src/connections/triggers.js, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/models/konnector/KonnectorAccountWatcher.js, packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js, packages/cozy-harvest-lib/test/components/TwoFAForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap, packages/cozy-harvest-lib/test/components/__snapshots__/TwoFAForm.spec.js.snap, packages/cozy-harvest-lib/test/connections/__snapshots__/accounts.spec.js.snap, packages/cozy-harvest-lib/test/connections/__snapshots__/triggers.spec.js.snap, packages/cozy-harvest-lib/test/connections/accounts.spec.js, packages/cozy-harvest-lib/test/connections/triggers.spec.js, packages/cozy-harvest-lib/test/models/KonnectorAccountWatcher.spec.js, yarn.lock
Handle 2FA return with code form and saving to the account
Need to have a recent cozy-ui version ([v19.24.3](https://github.com/cozy/cozy-ui/releases/tag/v19.24.3))
* Handle conflict on account save
* Account realtime
* 2FA modal closing
Closes #382 since it's picked here
=> Harvest: 2FA basis

packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/models/konnector/KonnectorAccountWatcher.js, packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js, packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap, packages/cozy-harvest-lib/test/components/__snapshots__/TwoFAForm.spec.js.snap
* Sessions expired
* Wrong code error
* Code retries
=> Handle Two FA errors

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx, packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx, packages/cozy-harvest-lib/src/components/AccountForm/Error.jsx, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, yarn.lock
* s/react-proptypes/prop-types
* Transfer cozy libs from "dependencies" to `peer/dev`
Fixes #389
=> [Harvest] Better handling dependencies

packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
Set a `RESET_SESSION` state into account document if password/passphrase is changed on edition
=> Provide account state to reset session

packages/cozy-doctypes/src/contacts/Contact.js, packages/cozy-doctypes/src/contacts/Contact.spec.js
Use fullname if there is any, else use primary email
=> feat(cozy-doctypes): Add getDisplayName for contacts

packages/cozy-authentication/examples/index.jsx, packages/cozy-authentication/src/Authentication.spec.jsx, packages/cozy-authentication/src/MobileRouter.jsx, packages/cozy-authentication/src/utils/credentials.js, packages/cozy-authentication/src/utils/onboarding.js
- When user has logged in, save information from stackClient in localforage
for future reconnection
- When users logs out, clear this information
=> [authentication] feat: Automatic reconnection

packages/cozy-authentication/package.json, packages/cozy-authentication/src/MobileRouter.jsx, packages/cozy-authentication/src/MobileRouter.spec.jsx, yarn.lock
While logging out, an application can tell MobileRouter to
display a Component.
☢️ Need https://github.com/cozy/cozy-client/pull/430#event-2313884696 to be merged and cozy-client to bed updated
=> [authentication] feat: LogoutComponent

packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, packages/cozy-harvest-lib/src/locales/en.json
* Fix 2FA modal margin on mobile, we want the extra top margin only when this is not a full screen modal
* Improve 2FA errors messages
=> [Harvest] Minor fixes

packages/cozy-doctypes/src/contacts/Contact.js, packages/cozy-doctypes/src/contacts/Contact.spec.js
- fix getInitals when contact has only givenName or familyName
- use the primary email's first letter when contact has no name
=> [cozy-doctypes] Contacts: improve getInitials

packages/cozy-doctypes/src/contacts/Contact.js, packages/cozy-doctypes/src/contacts/Contact.spec.js
We can now use the model to determine if an object is a contact or not
=> feat(cozy-doctypes): Add isContact method to Contact model

packages/cozy-authentication/src/steps/ButtonLinkRegistration.jsx
Static method is easily overridable ;)
=> feat: Override url manager

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/models/konnector/KonnectorAccountWatcher.js, packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js, packages/cozy-harvest-lib/test/connections/__snapshots__/accounts.spec.js.snap, packages/cozy-harvest-lib/test/connections/accounts.spec.js, packages/cozy-harvest-lib/test/connections/triggers.spec.js, packages/cozy-harvest-lib/test/models/KonnectorAccountWatcher.spec.js, yarn.lock
Cette PR est lié à https://github.com/cozy/cozy-libs/pull/424
=> feat(Harvest): Upgrade cozy-realtime

packages/cozy-harvest-lib/src/components/AccountForm/Error.jsx, packages/cozy-harvest-lib/src/components/Markdown.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountFormError.spec.js.snap
Display errors using the Infos component from CozyUI
=> Harvest: Use <Infos/> for error messages

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap, yarn.lock
We need the last version for the fix https://github.com/cozy/cozy-ui/pull/989 in Harvest
=> Upgrade cozy-ui

packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx, packages/cozy-harvest-lib/src/connections/accounts.js, packages/cozy-harvest-lib/src/index.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/DeleteAccountButton.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/DeleteAccountButton.spec.js.snap, packages/cozy-harvest-lib/test/connections/__snapshots__/accounts.spec.js.snap, packages/cozy-harvest-lib/test/connections/accounts.spec.js
Export a button to handle account removal (seen as log out for the user)
Waiting to be correctly integrated into cozy-home
=> Account deconnection

packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx
PropTypes.node represents React elements
=> fix: AccountFields.props.container is an Element

packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/TwoFAForm.spec.js.snap
It appears that we are not able to submit the 2FA Form in React apps.
Adding an onClick handler on submit button fix both submit by clik and with keyboard.
An issue will be made to investigate this behaviour further.
=> Fix unsubmittable 2FA Form on react apps

docs/styleguidist.config.js, package.json, yarn.lock
Was missing stylus with cozy-ui plugin
=> Fix styleguidist with Harvest

packages/cozy-doctypes/src/File.js, packages/cozy-doctypes/src/File.spec.js
Move some logic from cozy-drive in the `File` model. See https://github.com/cozy/cozy-drive/pull/1695#discussion_r287782732
=> Add move method to File model

packages/cozy-harvest-lib/test/components/AccountField.spec.js, packages/cozy-harvest-lib/test/components/AccountForm.spec.js
In AccountForm and AccountField tests
=> Harvest: Avoid warnings in tests

packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
=> Harvest: Remove duplicated error block

packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
Add delete button to konnector edit modal
=> Add DeleteAccountButton in KonnectorModal

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx, packages/cozy-harvest-lib/src/components/AccountForm/Error.jsx, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx, packages/cozy-harvest-lib/src/components/KonnectorModal.jsx, packages/cozy-harvest-lib/src/components/OAuthForm.jsx, packages/cozy-harvest-lib/src/components/OAuthWindow.jsx, packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx, packages/cozy-harvest-lib/src/components/TwoFAModal.jsx, packages/cozy-harvest-lib/src/components/cards/DeleteAccountCard.jsx, packages/cozy-harvest-lib/test/components/TwoFAForm.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap
Fix `yarn watch:bar` when `cozy-harvest-lib` is linked. Could also fix mobile build.
=> Harvest: Import tranpiled Cozy-UI components

packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Some of the available values for those select were missing. I also updated/fixed translations
=> fix(procedures): Add missing values to employment and property statuses

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Small update to our procedure template to bring it in line with the latest changes. The `rules` for the documents will be written when we implement automatic fetching, I think it would be premature to do it now without testing them.
=> (procedure) feat: Update credit application template

packages/cozy-harvest-lib/src/components/hoc/utils.js, packages/cozy-harvest-lib/src/components/hoc/withKonnectorJob.jsx, packages/cozy-harvest-lib/src/components/hoc/withKonnectorModal.jsx
Will allow better debugging and test snapshots.
=> Harvest: Add display names to HOC

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/Amount.jsx, packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/Duration.jsx, packages/cozy-procedures/src/components/OtherComp.jsx, packages/cozy-procedures/src/components/Overview.jsx, packages/cozy-procedures/src/components/PersonalDataForm.jsx, packages/cozy-procedures/src/components/Topbar.jsx, packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/cozy-procedures/src/components/documents/LoadingDocumentHolder.jsx, packages/cozy-procedures/src/index.js, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/templates/creditApplicationTemplate.js, packages/playgrounds/package.json, packages/playgrounds/src/procedures.html, packages/playgrounds/src/procedures.jsx, yarn.lock
This PR includes :
- The topbar navigation — not super final
- The overview screen — pretty accurate
- The Documents screen — has all the individual components, but doesn't use the template yet
- Amounts and duration screens but with nothing in them
=> (Procedure) Lots of UI

packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/cozy-procedures/src/components/documents/LoadingDocumentHolder.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
The documents view is now using the template to generate the fields. Nothing is connected to the redux store yet.
=> (Procedures) Document UI

packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
- Change some French translations (use the one from the paper instead of those from the mock-up)
- Use `numberOfDependents` instead of `numberOfKids`
=> Fix some labels

packages/cozy-procedures/.eslintrc.json, packages/cozy-procedures/babel-transformer.js, packages/cozy-procedures/jestSetup.js, packages/cozy-procedures/package.json, yarn.lock
- Add enzyme-to-json to easily test components
- Add more jest config (babel transformer, etc)
- Add `mount` and `shallow` to globals in eslint config
=> chore(procedures): Add more jest/eslint setup and enzyme-to-json

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/form/FieldTemplate.jsx, packages/cozy-procedures/src/components/form/FieldTemplate.spec.jsx, packages/cozy-procedures/src/components/form/InputAdapter.jsx, packages/cozy-procedures/src/components/form/InputAdapter.spec.jsx, packages/cozy-procedures/src/components/form/InputWithUnit.jsx, packages/cozy-procedures/src/components/form/InputWithUnit.spec.jsx, packages/cozy-procedures/src/components/form/ObjectFieldTemplate.spec.jsx, packages/cozy-procedures/src/components/form/SelectBoxAdapter.jsx, packages/cozy-procedures/src/components/form/SelectBoxAdapter.spec.jsx, packages/cozy-procedures/src/components/form/__snapshots__/FieldTemplate.spec.jsx.snap, packages/cozy-procedures/src/components/form/__snapshots__/InputAdapter.spec.jsx.snap, packages/cozy-procedures/src/components/form/__snapshots__/InputWithUnit.spec.jsx.snap, packages/cozy-procedures/src/components/form/__snapshots__/ObjectFieldTemplate.spec.jsx.snap, packages/cozy-procedures/src/components/form/__snapshots__/SelectBoxAdapter.spec.jsx.snap, packages/cozy-procedures/src/redux/personalDataSlice.js, packages/cozy-procedures/src/redux/personalDataSlice.spec.js, packages/cozy-procedures/test/__mocks__/fileMock.js, packages/cozy-procedures/test/__mocks__/tMock.js
Add missing tests for components and reducers. And it fixes some stuff to (thanks to the tests!)
=> Procedures more tests

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx, packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx, packages/cozy-harvest-lib/src/connections/triggers.js, packages/cozy-harvest-lib/src/helpers/cron.js, packages/cozy-harvest-lib/src/helpers/triggers.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/TriggerLauncher.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/DeleteAccountButton.spec.js.snap, packages/cozy-harvest-lib/test/helpers/cron.spec.js, yarn.lock
LauncTriggerCard now show trigger's frequency and last success date.
Desktop:
Mobile:
=> Harvest: Better LaunchTriggerCard

packages/cozy-procedures/src/Procedure.jsx, packages/cozy-procedures/src/components/Topbar.jsx, packages/cozy-procedures/src/locales/en.json
Adds proper topbar and margins to the procedures layout.
=> (procedures) UI fixes

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Missing bank_identity ATM, but this is already a good start :)
=> feat: Almost a full template

packages/cozy-procedures/src/Procedure.jsx, packages/cozy-procedures/src/components/Amount.jsx, packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/Duration.jsx, packages/cozy-procedures/src/components/Overview.jsx, packages/cozy-procedures/src/components/PersonalDataForm.jsx, packages/cozy-procedures/src/index.js
Importing the template with a path like this is more flexible for *reasons* 👐
=> (procedures) fix: Import path for template

packages/cozy-procedures/src/components/Topbar.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
Adds a "back" button on non-mobile views.
=> (procedures) fix: Topbar back button

packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/components/documents/DocumentsGroup.jsx, packages/cozy-procedures/src/containers/DocumentsDataForm.jsx, packages/cozy-procedures/src/redux/documentsDataSlice.js
We can now unlink a doc.
picked from the other branch it was easier
=> feat: Unlink Docs

packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/documents/DocumentsGroup.jsx, packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/cozy-procedures/src/containers/DocumentsDataForm.jsx, packages/cozy-procedures/src/redux/documentsDataSlice.js, packages/playgrounds/package.json, yarn.lock
A simple implementation of the upload.
=> (procedures) Upload files

packages/cozy-doctypes/package.json, packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.js, packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.spec.js, packages/cozy-doctypes/src/administrativeProcedures/__snapshots__/AdministrativeProcedure.spec.js.snap, packages/cozy-procedures/src/components/Overview.jsx, packages/cozy-procedures/src/containers/Overview.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/playgrounds/src/common/App.jsx, packages/playgrounds/src/common/client.js, packages/playgrounds/src/index.jsx, yarn.lock
Submit the procedure on click on the button in Overview. 
What it does:
- create a json containing all data about the procedure (amount, duration, personal information, ...)
- put it somewhere in the drive
- create a zip with this json and the documents
- once the zip is ready (job), display a success message then remove the json file
Remarks:
- I think that `submitProcedure` should be sliced.
- Waiting for the documents management PR to be merged to have documents in state and to be able to add those to the zip.
- Some unit tests would be more than welcome and this process.
=> Procedures submit

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/Amount.jsx, packages/cozy-procedures/src/components/Duration.jsx, packages/cozy-procedures/src/components/Overview.jsx, packages/cozy-procedures/src/components/PersonalDataForm.jsx, packages/cozy-procedures/src/components/Topbar.jsx, packages/playgrounds/package.json, yarn.lock
Fixes a few UI bits all over the place, mostly margins.
=> Procedure ui fixes

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/cozy-procedures/src/components/documents/UploadInputLabel.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
- Not the right icons yet, we need an UI update
- Not added on the web version yet
=> feat: Upload Menu for Mobile

packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.js, packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.spec.js
Create relationships to documents when we create an administrative procedure
=> Add relationships to files in AdministrativeProcedure

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx
MenuActionItem doesn't provide any onClick props, so I have to use MenuItem.
Styles are not really good for now but at least it works
=> fix: Stop propagation onClick

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
- Subject in now an array => Subjects 
- Missed on `r` :'(
=> fix(cozy-procedure): Update template to reflect latest spec

packages/cozy-procedures/src/locales/fr.json
=> fix: Remove special char

packages/cozy-procedures/src/components/Overview.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Minor adjustments to translations and translate the main title.
=> Fix translate notice

packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.js, packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.spec.js, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
- use numberOfDependants to match id created by the konnectors
- fix default getter in `getPersonalData`
- `0` is a valid value, don't ignore it
=> Fix personal data

packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
To match the values retrieved by the konnectors
=> Fix maritalStatus values

packages/cozy-procedures/src/components/form/InputAdapter.jsx, packages/cozy-procedures/src/components/form/InputWithUnit.jsx, packages/cozy-procedures/src/components/form/__snapshots__/InputAdapter.spec.jsx.snap, packages/cozy-procedures/src/components/form/__snapshots__/InputWithUnit.spec.jsx.snap
=> feat: Hide nav footer bar on focus

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
I don't know how I didn't see that
=> fix: Template procedure

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
In order to display an error when something went wrong during upload. 
We have to manage the conflict case.
=> feat: Display error when conflict during upload

packages/cozy-procedures/src/components/CompletedFromDriveStatus.jsx, packages/cozy-procedures/src/components/CompletedFromMyselfStatus.jsx, packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/PersonalDataForm.jsx, packages/cozy-procedures/src/components/__snapshots__/CompletedFromDriveStatus.spec.jsx.snap, packages/cozy-procedures/src/components/__snapshots__/CompletedFromMyselfStatus.spec.jsx.snap
=> fix: Text alignement

packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
Display a modal before unlinking a document. 
Feel free to edit the english :D
=> feat: Display a modal before detaching a doc

packages/cozy-flags/src/flag-codemod.js
- Count JSX as React usage
- Do not remove imports without specifiers (must be side effects imports)
=> fix: Codemod fixes

packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadMobile.jsx, packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadWeb.jsx
Not yet the right icons, but hey, we get closer ;) (validated by our designer in chief)
=> feat: Disable MenuItem

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/components/documents/LoadingDocumentHolder.jsx, packages/cozy-procedures/src/locales/en.json, packages/playgrounds/package.json
See commit titles for details.
=> Various fixes

packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/cozy-procedures/src/components/documents/LoadingDocumentHolder.jsx
Importing it from the index causes problems with the override.
=> fix: Import card from standalone file

packages/cozy-procedures/src/components/form/SelectBoxAdapter.jsx, packages/cozy-procedures/src/components/form/SelectBoxAdapter.spec.jsx, packages/cozy-procedures/src/components/form/__snapshots__/SelectBoxAdapter.spec.jsx.snap, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Pass all options defined in the `uiSchema` to the `SelectBox`
Make all the selects in personal data form not searchables
=> SelectBoxAdapter pass options to SelectBox

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/documents/DocumentHolder.jsx, packages/playgrounds/package.json, yarn.lock
Also, it's difficult to test the PDF Viewer with the playground since the current entry works for webpack and not parcel. So you can test it with an Image or anything that is not a PDF.
It is tested on the end user Application
=> (procedures) : Feat/viewer

packages/cozy-procedures/src/components/Amount.jsx, packages/cozy-procedures/src/components/Documents.jsx, packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadMobile.jsx, packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadWeb.jsx
we had a few errors. Let's remove them.
=> fix: Remove some proptypes warning

packages/cozy-procedures/src/components/overview/PersonalDataFullyCompleted.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
- Put bold on  numberOfDependants 
- Better alignment on Overview
=> fix(cozy-procedures): Few visual issues

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/Duration.jsx, packages/playgrounds/package.json, yarn.lock
=> fix: Overflow scroll through utility class

packages/cozy-authentication/package.json, packages/cozy-authentication/src/steps/SelectServer.jsx, yarn.lock
* Properly align the back button with the title
* Properly align the logo badge with the logo
See https://github.com/cozy/cozy-ui/pull/1102
=> (Authentication) Fixes on welcome and select server steps

packages/cozy-procedures/package.json
This allows us to do `npm docs cozy-procedures` / `npm bugs
cozy-procedures` / `npm repo cozy-procedures` :)
=> chore(cozy-procedures): Add missing package.json properties

packages/cozy-procedures/src/locales/fr.json
We want to show « Revenu principal » instead of « Salaire net mensuel ».
=> feat(cozy-procedures): Update salary french title

packages/cozy-doctypes/src/File.js, packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx, packages/playgrounds/package.json, yarn.lock
We can override a file with the same name and attach metadata.
=> feat: Can override a file with the same name

packages/cozy-procedures/src/containers/Amount.jsx, packages/cozy-procedures/src/containers/CompletedFromDriveStatus.jsx, packages/cozy-procedures/src/containers/CompletedFromMyselfStatus.jsx, packages/cozy-procedures/src/containers/DocumentsDataForm.jsx, packages/cozy-procedures/src/containers/Duration.jsx, packages/cozy-procedures/src/containers/Overview.jsx, packages/cozy-procedures/src/containers/PersonalDataForm.jsx, packages/cozy-procedures/src/containers/Procedure.jsx, packages/cozy-procedures/src/redux/connectWithProcedures.js, packages/cozy-procedures/src/redux/connectWithProcedures.spec.js
Add a HOC to directly connect a component to the procedures store with the correct context
=> Add connectWithProcedures HOC

packages/cozy-doctypes/src/File.js, packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/__snapshots__/CompletedFromDriveStatus.spec.jsx.snap, packages/cozy-procedures/src/components/__snapshots__/CompletedFromMyselfStatus.spec.jsx.snap, packages/cozy-procedures/src/components/overview/Overview.jsx, packages/playgrounds/package.json, yarn.lock
Will require a cozy-client update
=> Delete files permanently after zip success or error

packages/cozy-doctypes/src/banking/BankAccountStats.js, packages/cozy-doctypes/src/banking/BankAccountStats.spec.js, packages/cozy-procedures/src/components/overview/PersonalDataFullyCompleted.jsx, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json, packages/cozy-procedures/src/redux/personalDataSlice.js, packages/cozy-procedures/src/templates/creditApplicationTemplate.js
There is two parts:
* In cozy-doctypes: add the `fixedCharges` sum computation
* In cozy-procedures: show this data in a new form field
For more infos about fixed charges, see https://github.com/cozy/cozy-banks/pull/1422
=> Add fixed charges to procedures personal data form

packages/cozy-codeshifts/src/transforms/remove-unused-imports.js, packages/cozy-codeshifts/src/utils/add-import.js
I used them at some point, thought it would be useful to have them here.
=> feat: Add two small utilities

.github/auto-merge.yml
- With label merge and 1 reviewer approval, the PRs gets merged
as soon as checks pass
=> Configure auto merge

packages/cozy-procedures/src/components/form/InputWithUnit.jsx, packages/cozy-procedures/src/components/form/__snapshots__/InputWithUnit.spec.jsx.snap, packages/cozy-procedures/src/locales/en.json, packages/cozy-procedures/src/locales/fr.json
Use InputGroup to enhance our UI.
=> feat(cozy-procedures): Use input group to display €/mois

packages/cozy-procedures/package.json, packages/cozy-procedures/src/components/overview/Overview.jsx, packages/cozy-procedures/src/components/overview/helpers.js, packages/cozy-procedures/src/components/overview/helpers.spec.js, packages/playgrounds/package.json, packages/playgrounds/src/common/client.js, yarn.lock
This fetches the last 3 months banking data and put it in a JSON file inside the ZIP archive generated at the end of a procedure.
I refactored a little the existing code to add some tests.
=> (Procedures) Add last 3 months banking data to a specific JSON file

yarn.lock
It looks like I introduced a problem in the lockfile in the previous commit, not sure how it happened but it's preventing new releases from coming out.
=> fix: Reset yarn lockfile

packages/cozy-doctypes/README.md
Add a bit of doc on how different code is used on browser or node and why.
=> docs: Add docs on environments

packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectControl.jsx, packages/cozy-harvest-lib/src/components/AccountsList/AccountsListItem.jsx, packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx
Makes sure long account names are properly displayed (+ minor fixes after upgrading cozy-ui)
=> fix: Handle long account names

packages/cozy-doctypes/package.json, yarn.lock
And especially:
* cozy-client : to get https://github.com/cozy/cozy-client/pull/494
* cozy-client-js : to have the same version as last cozy-konnector-libs
=> chore(cozy-doctypes): Upgrade dependencies

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap, packages/cozy-harvest-lib/test/components/__snapshots__/TwoFAForm.spec.js.snap, yarn.lock
=> chore(cozy-harvest-lib): Upgrade CozyUI

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorConfiguration.jsx, packages/cozy-harvest-lib/src/components/KonnectorModal.jsx, packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/components/TwoFAModal.jsx, packages/cozy-harvest-lib/src/helpers/triggers.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/TriggerLauncher.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/TriggerLauncher.spec.js.snap
This PR follows #736 and fixes a few issues.
We peered with @y-lohse and made also a few changes/refactoring to improve code quality. There is still a little work to simplify the whole process.
Plus a little cleaning and refactoring
=> Harvest: Make 2FA work again

packages/cozy-harvest-lib/src/components/AccountsListModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
`history` from react-router is an object, not a function.
=> fix: Erroneous proptypes

packages/cozy-doctypes/src/Application.js
Rather than having to namespace those methods, let's use our Doctype ;)
=> feat: Add methods to Application Doctype

packages/cozy-harvest-lib/jest.config.js, packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js, packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap, yarn.lock
Our base branch for the password manager work had broken tests, this should fix them.
=> Password manager tests

packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
- if a cipher is already linked to this account, try to use it
- otherwise, try to get a cipher with the same username and password
which match the requested uri
- otherwise, try to get the first cipher matching username and uri
- otherwise create a new cipher
=> feat: Deals with accounts edition

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, yarn.lock
So far, it wasn't possible to go away from the unlock screen.
=> [harvest] Dismiss vault unlock screen

packages/cozy-doctypes/src/File.js, packages/cozy-doctypes/src/File.spec.js
The idea is pretty simple, in our apps, we want to upload a file. But depending on the contexte, we want either a `rename` or an `erase`. 
Exemple: 
- In Drive, we want the scanner to rename the scanned file if there is a conflict 
- But within a procedures, we want to erase the content of the file since we want to keep the name 
The bug fix has to be done in cozy-client
=> feat(cozy-doctypes): Upload file with conflict strategy

packages/cozy-notifications/package.json, packages/cozy-notifications/src/__snapshots__/notifications.spec.js.snap, packages/cozy-notifications/src/__snapshots__/templates.spec.js.snap, packages/cozy-notifications/src/__tests__/email-layout.hbs, packages/cozy-notifications/src/cozy-layout.hbs, packages/cozy-notifications/src/index.js, packages/cozy-notifications/src/notifications.spec.js, packages/cozy-notifications/src/text.js, packages/cozy-notifications/src/view.js, yarn.lock
NotificationView implements a default toText method that converts the
HTML to text.
For more complex needs, a custom Notification can implement custom
logic.
=> feat: Automatic toText

packages/cozy-harvest-lib/package.json
This enables tree shaking.
See https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
for more information
=> feat: Mark the package as sideEffects free

packages/renovate-config-cozy/package.json
Have updates for non cozy packages be updated monthly.
=> feat: Schedule non-cozy packages updates monthly

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/helpers/konnectors.js, packages/cozy-harvest-lib/src/index.js, packages/cozy-harvest-lib/src/locales/index.js, packages/cozy-harvest-lib/src/locales/index.spec.js, packages/cozy-harvest-lib/test/helpers/konnectors.spec.js, yarn.lock
For easy usage in apps/konnectors, export a getErrorLocale bound
to the t of harvest-lib.
=> feat: Export a bound getErrorLocale

packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx, packages/cozy-harvest-lib/src/helpers/triggers.js, packages/cozy-harvest-lib/test/helpers/triggers.spec.js
Based on https://github.com/cozy/cozy-libs/pull/845#discussion_r336974353
=> refactor: Use model to determine if konnector is running

packages/cozy-harvest-lib/src/locales/en.json
new trads regarding connectors error
=> feat: Update konnector messages

packages/cozy-flags/src/FlagSwitcher.jsx, packages/cozy-flags/src/flag.js, packages/cozy-flags/src/index.spec.js, packages/cozy-flags/src/tests.js
=> feat: Sort flags

packages/cozy-app-publish/lib/hooks/post/mattermost.js, packages/cozy-app-publish/lib/hooks/post/mattermost.spec.js
This way, it is easier to know what a publish is about.
=> feat: Output commit link and travis link in publish message

packages/cozy-harvest-lib/src/components/TwoFAModal.jsx, packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/test/components/cards/LaunchTriggerCard.spec.js
- Different text whether it is first two fa code or second two fa code
- Test
=> feat: Texts in 2FA modal

packages/cozy-harvest-lib/README.md
Use fix instead of doc to trigger a new version with updated transifex
strings
=> fix: README

packages/cozy-doctypes/src/File.js, packages/cozy-doctypes/src/File.spec.js, packages/cozy-scanner/src/ScannerUpload.js
Two things : 
- Forgot to apply metadata / qualification during the upload... 
- Add an argument to pass contentType to the upload method
=> feat: We can pass contentType if needed

packages/cozy-harvest-lib/src/helpers/accounts.js
See https://github.com/cozy/cozy-doctypes/blob/master/docs/README.md#external-relationships
=> fix: Use data in vaultCipher relationship

packages/cozy-doctypes/src/Folder.js
We now have a new kind of magic folder: `Notes`
=> feat: Add notes folder

packages/cozy-sharing/package.json, packages/playgrounds/package.json, yarn.lock
Previous feature in cozy-sharing did require a new
cozy-client. I forgot to update the peer dep
=> feat(cozy-sharing): Updates cozy-client peer dep

packages/cozy-sharing/README.md
The readme is not very clear ATM and I don't want to rework it now. I just added a note about the import of the stylesheet import since we have to.
=> docs: Add a note about the stylesheet import

packages/eslint-config-cozy-app/package.json, packages/eslint-config-cozy-app/react.js, yarn.lock
=> [eslint-config-cozy-app] Add react-hooks plugin

packages/cozy-flags/package.json, packages/cozy-flags/src/flag.js, packages/cozy-flags/src/index.js, packages/cozy-flags/src/useFlag.js, packages/cozy-flags/src/useFlag.spec.js, yarn.lock
Pour ajouter un hook react qui réagit en dynamique quand on change la valeur du drapeau
=> feat: Adds a useFlag react hook

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/TriggerManager.jsx, packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.jsx, packages/cozy-harvest-lib/src/logger.js, packages/cozy-harvest-lib/src/services/biUtils.js, packages/cozy-harvest-lib/src/services/budget-insight.js, packages/cozy-harvest-lib/src/services/budget-insight.spec.js, packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
- UseMaintenance hook would trigger an infinite render loop due to incorrect
dependencies
- Incorrect mapping was used
- Added minilog for easier production debugging
=> Fix BI policy errors

packages/cozy-harvest-lib/src/services/biUtils.js, packages/cozy-harvest-lib/src/services/biUtils.spec.js
User-Agent header was triggering a CORS error
=> fix: Correctly handle BI errors

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/services/logger.js, packages/cozy-harvest-lib/src/services/updateAccountsPassword.js, packages/cozy-harvest-lib/test/services/updateAccountsPassword.spec.js
This service lacked some debug logs. This PR adds some.
=> feat(cozy-harvest-lib): Add logs to updateAccountsPassword service

packages/cozy-app-publish/lib/hooks/post/mattermost.js, packages/cozy-app-publish/lib/hooks/post/mattermost.spec.js
Post was broken when a commit message was containing
an & or unicode char since the content was not
encoded.
We now send it with the json format and it works
=> fix(cozy-app-publish): Mattermost post

packages/playgrounds/package.json, packages/playgrounds/src/common/Nav.jsx
Serve all html files, and add a link to procedures
=> feat: Serve all html files and add link to procedure

packages/cozy-mjml/package.json, packages/cozy-notifications/package.json, packages/cozy-procedures/package.json, packages/cozy-realtime/package.json, packages/cozy-scanner/package.json
If we want them it is easy to them in an adhoc manner
=> chore: Remove verbose and coverage flags

packages/cozy-app-publish/utils/runhooks.js
It should help us to diagnose errors more quickly
=> feat: Log precise error when failing to require hook

packages/cozy-harvest-lib/.gitignore, packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json, packages/cozy-harvest-lib/src/services/budget-insight.spec.js, yarn.lock
- Tell the right thing to the user in case of app two fa
- Update cozy-bi-auth to have the correct mapping for the
SCARequired error from BI
- Pull locales from transifex and store them in the repository
=> Fix two FA flows

packages/cozy-realtime/src/CozyRealtime.js, packages/cozy-realtime/src/CozyRealtime.spec.js, packages/cozy-realtime/src/RetryManager.js, packages/cozy-realtime/src/SubscriptionList.js, packages/cozy-realtime/src/SubscriptionList.spec.js
These are very quick and little patches. Some were seen Tuesday on the frontend meeting. Others are fixes and cleaning
=> Realtime various fixes

packages/babel-preset-cozy-app/README.md, packages/babel-preset-cozy-app/index.js, packages/babel-preset-cozy-app/package.json, packages/cozy-harvest-lib/package.json, yarn.lock
183ea557923acc40415218a29dae796030ab8274
we have some usecase like that : 
{...pick(this.props, Object.keys(DumbFlowProvider.propTypes))}
=> fix: Revert "Merge pull request #974 from cozy/feat/RemovePropTypes"

packages/cozy-sharing/src/helpers/contacts.js
=> fix: Use _id instead of id

packages/cozy-realtime/src/RealtimePlugin.js, packages/cozy-realtime/src/RealtimePlugin.spec.js
Important in cases where the client can login/logout,
in mobile for example.
=> Handle login/logout in CozyRealtime plugin

CODEOWNERS
=> chore: Re-dispatch codeowners

packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/test/helpers/accounts.spec.js
See https://github.com/cozy/cozy-stack/pull/2535#discussion_r433986611 for context
=> feat: Support old cipher relationship format

packages/cozy-flags/src/flag.js, packages/cozy-flags/src/tests.js
GET was not passed as first argument of fetchJSON :(
=> fix: Remove initialization of flag did not work

packages/cozy-realtime/README.md
Let's talk about the Realtime Plugin for CozyClient
=> Docs: Add doc about CozyClient Plugin

packages/cozy-doctypes/src/contacts/Contact.js
Add deprecated message on Contact methods : they are copied in cozy-client https://github.com/cozy/cozy-client/pull/749
...waiting to validate cozy-client PR...
=> WIP: fix: Add deprecated message on Contact methods

packages/cozy-harvest-lib/src/services/budget-insight.js, packages/cozy-harvest-lib/src/services/budget-insight.spec.js
One more reason to add unit tests (again)
=> fix(Harvest): Maif epa url association error + Unit test

packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
This new locale is needed in next home and banks apps to make the 2FA process clearer with
bank connectors.
=> feat(Harvest): Locale change for SCA_REQUIRED error message

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx, packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx, packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.spec.jsx, packages/cozy-harvest-lib/src/components/cards/__snapshots__/WebsiteLinkCard.spec.jsx.snap, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
This will make it easier to navigate from cozy-home
=> feat(Harvest): Add website link in connector data

packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx, packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.spec.jsx, packages/cozy-harvest-lib/src/components/cards/__snapshots__/WebsiteLinkCard.spec.jsx.snap
Following https://github.com/cozy/cozy-libs/pull/1066#discussion_r479137378 recommendations
=> fix(Harvest): Better unit tests for WebsiteLinkCard

packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx
=> fix(Harvest): Change hr separator height to 1px

packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json, packages/cozy-harvest-lib/test/components/KonnectorConfiguration/DataTab.spec.jsx
Needed to integrate Harvest in Banks.
=> Improvements (again)

packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountModal.spec.jsx.snap
- Ability to hide it
- Better styles on mobile
=> Small tweaks for new account button

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/components/KonnectorModalHeader.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
- Correct margins for configuration tab (no margin between tabs and subheader)
- Tweak DisconnectedAccountModal so that it is closer to the AccountModal
Other small graphic improvements whose description should suffice ;)
=> Improvements to harvest modal

packages/cozy-doctypes/src/Document.js, packages/cozy-doctypes/src/File.js, packages/cozy-doctypes/src/banking/matching-accounts.js, packages/cozy-doctypes/src/utils.js, packages/cozy-harvest-lib/src/models/ConnectionFlow.js, packages/cozy-harvest-lib/src/services/budget-insight.js, packages/cozy-realtime/src/CozyRealtime.spec.js, packages/cozy-realtime/src/SubscriptionList.js
Started to remove warnings for reassignment of function
params.
=> Remove lint warnings

packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json, packages/cozy-harvest-lib/src/models/getRelatedAppsSlugs.js
- Tweak wording containing "Cozy"
- Export relatedAppsConfiguration
=> 2 smallish improvements on harvest

packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx
Use primaryColor instead of dodgerBlue for link to site.
=> fix: Use primaryColor instead of dodgerBlue

packages/cozy-codemods/src/transform-imports.js, packages/cozy-codemods/src/transform-imports.spec.js
Useful to make imports match new paths. See the test for the
example.
=> feat: Add helper functions to transform imports

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx, packages/cozy-harvest-lib/src/models/ConnectionFlow.js, packages/cozy-scanner/src/DocumentQualification.jsx, yarn.lock
Update bi-auth so that it does not bring @cozy/cli-tree in the apps.
I'll merge when it's green.
=> Update bi-auth in cozy-harvest-lib

packages/cozy-harvest-lib/src/services/bi-http.js, packages/cozy-harvest-lib/src/services/bi-http.spec.js
I messed up the boolean vars. As I'm adding tests and since the change
is scoped and small, I'll merge when this is green.
=> fix: Setting the sync to true means disabled is false

packages/remark-preset-cozy/index.js, packages/remark-preset-cozy/package.json, yarn.lock
Used to share our remark config.
=> feat: Add remark-preset-cozy

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/CiphersListItem.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/OtherAccountListItem.jsx
=> fix: Track event call needs an object with name attribute

packages/cozy-harvest-lib/src/components/KonnectorIcon.jsx, packages/cozy-harvest-lib/src/components/KonnectorIcon.spec.jsx
Check if either konnector or konnectorSlug is passed
=> feat: Add PropType for konnector/konnectorSlug

packages/cozy-harvest-lib/package.json, yarn.lock
To get new Orange Bank connector
=> feat(Harvest): Upgrade cozy-bi-auth to 0.0.14

packages/cozy-scanner/package.json, packages/cozy-scanner/src/EditDocumentQualification.jsx, packages/cozy-scanner/src/Scanner.jsx, yarn.lock
Helpers are now in react/ folder
=> fix: Import withOffline after a BC in UI

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/src/components/ShareModal.jsx, packages/cozy-sharing/src/share.styl
Display the name of the document in the Dialog Title.
=> feat: Display the document name in the Sharing Modale

README.md
There is no explanation about how to run tests on packages
=> docs: Updates cozy-libs doc about testing

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/package.json, packages/cozy-sharing/src/components/EditableSharingModal.spec.jsx, packages/cozy-sharing/src/components/ShareByLink.jsx, packages/cozy-sharing/src/components/ShareModal.jsx, packages/cozy-sharing/src/share.styl, yarn.lock
After the implementation of the new Cozy modals in cozy-ui, we update the sharing modal with the new components
This is just the "iso" refactoring, not the fix to match the design. This issue is here https://github.com/cozy/cozy-libs/issues/1138
=> Refactor ShareModal to use FixedDialog

packages/cozy-scanner/package.json, packages/cozy-scanner/src/EditDocumentQualification.jsx, packages/cozy-scanner/src/ModalScannerQualification.jsx, yarn.lock
Use our new Dialog.
Still reference to a Modal, will work later on it
=> feat: Use CozyDialog

packages/cozy-sharing/package.json, packages/cozy-sharing/src/SharingDetailsModal.jsx, packages/cozy-sharing/src/components/ShareModal.jsx, yarn.lock
We now want to use the new CozyDialogs modals.
=> cozy-sharing refactor: Modal to CozyDialogs

packages/cozy-codemods/package.json, yarn.lock
Otherwise the app when using a codemod has to install jscodeshift.
=> fix: Add jscodeshift as @cozy/codemods dependency

packages/cozy-sharing/package.json, packages/cozy-sharing/src/components/AvatarPlusX.jsx, packages/cozy-sharing/src/components/Recipient.jsx, packages/cozy-sharing/src/components/__snapshots__/ContactSuggestion.spec.jsx.snap, packages/cozy-sharing/src/components/recipient.styl, packages/cozy-sharing/src/index.jsx, yarn.lock
We needed to correct the behavior of the sharing avatars in Drive
=> Fix sharing avatars

packages/cozy-app-publish/src/publisher.js, packages/cozy-authentication/src/MobileRouter.jsx, packages/cozy-codemods/src/imports.js, packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.output.js, packages/cozy-codemods/src/transforms/replace-icons-svgr.js, packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm/ReadOnlyIdentifier.jsx, packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectControl.jsx, packages/cozy-harvest-lib/src/components/AccountsList/AccountsList.jsx, packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx, packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx, packages/cozy-harvest-lib/test/components/AccountsList/__snapshots__/AccountsList.spec.js.snap, packages/cozy-interapp/src/service.js, packages/cozy-notifications/src/text.js, yarn.lock
- Use new Dialogs
- Use SVGr icons
=> Improve Harvest

packages/cozy-codemods/src/imports.js, packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.output.js, packages/cozy-codemods/src/transforms/replace-icons-svgr.js, packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm/ReadOnlyIdentifier.jsx, packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectControl.jsx, packages/cozy-harvest-lib/src/components/AccountsList/AccountsList.jsx, packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx, packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx, packages/cozy-harvest-lib/test/components/AccountsList/__snapshots__/AccountsList.spec.js.snap, yarn.lock
- Use new tabs in the configuration modal
- Use new dialogs for contracts part
- Use svgr icons, this way we do not need to include an svg sprite to have icons
=> Improvements to Harvest

packages/cozy-harvest-lib/package.json, packages/cozy-sharing/package.json, yarn.lock
mui/styles removed because of https://github.com/cozy/cozy-ui/pull/1658
=> feat: Update cozy-ui and remove @MUI/styles

packages/cozy-harvest-lib/package.json, yarn.lock
=> chore: Upgrade cozy-bi-auth in harvest to add Socram bank connector

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
Adapt the rules to match the new [qualifications](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/assets/qualifications.json)
=> feat: Use new qualifications

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
Use MUI tabs instead of our custom tabs.
=> refactor: Use MUI tabs

packages/cozy-harvest-lib/jest.config.js, packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorModal.jsx, packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.spec.jsx, packages/cozy-harvest-lib/src/components/__snapshots__/KonnectorModal.spec.jsx.snap, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json, packages/cozy-harvest-lib/test/AppLike.jsx, packages/cozy-harvest-lib/test/components/__snapshots__/AccountModal.spec.jsx.snap
- Trigger was not correctly passed
- Tab were not correctly labelled
=> Fix elements in Harvest

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx
Wrong prop was passed, preventing the drive app card to appear in the data tab.
=> Fix drive card in data tab

packages/cozy-scanner/src/DocumentTypeData.js, packages/cozy-scanner/src/EditDocumentQualification.jsx, packages/cozy-scanner/src/locales/en.json, packages/cozy-scanner/src/locales/fr.json
* Add tax receipt item
* Avoid crash when a theme is not found
=> Tax receipt item

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/CiphersListItem.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/OtherAccountListItem.jsx, packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.jsx
After update of cozy-ui to version 42, these props should be explicitly
set on ListItems
=> feat: Add button&divider props

packages/cozy-scanner/src/DocumentTypeData.js, packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap, packages/cozy-scanner/src/locales/en.json, packages/cozy-scanner/src/locales/fr.json
The finance theme merges the tax and bank documents. The latter was
missing in the previous categorization.
=> feat: Add finance theme

packages/cozy-doctypes/src/administrativeProcedures/AdministrativeProcedure.js
classification was renamed to qualification
=> fix: Procedure request index

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorModal.spec.jsx, packages/cozy-harvest-lib/src/components/NewAccountModal.jsx, packages/cozy-harvest-lib/src/components/Routes.jsx, packages/cozy-harvest-lib/src/components/useSafeState.js, packages/cozy-harvest-lib/src/components/vaultUnlockContext.jsx, packages/cozy-harvest-lib/src/jest.setup.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
After account deletion, route was not correctly reset and 
subsequent navigation was broken. To remedy this problem, the
modal is closed optmistically.
=> Fix deletion of account

packages/cozy-procedures/src/templates/creditApplicationTemplate.js
See [qualifications](https://github.com/cozy/cozy-client/blob/master/packages/cozy-client/src/assets/qualifications.json#L315-L319)
=> fix: Use correct subject for tax notice

packages/cozy-scanner/package.json, packages/cozy-scanner/src/DocumentTypeData.js, packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap, yarn.lock
The "Invoice" theme now uses a bill icon, instead of the euro icon, in order to make the theme more explicit. See both icons below
* bill: ![image](https://user-images.githubusercontent.com/7010087/104742156-67774c00-574a-11eb-8b6c-29a4c459b563.png)
* euro: ![image](https://user-images.githubusercontent.com/7010087/104742199-7231e100-574a-11eb-9704-59a4cda2f2bf.png)
=> feat: Update cozy-ui to use new bill icon

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx
Text was missing Typography component and thus was a bit too
black.
=> feat: Add Typography component

.gitignore, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
- Remove updateSwiperHeight func cause not used
- Add .idea folder in gitignore
=> Fix bottom content swipeable view for Harvest

packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
Adding a new 2FA method for connectors.
=> feat: Add in harvest a new 2FA mode (mobile app with code)

packages/cozy-harvest-lib/src/locales/fr.json
=> feat: Add FR translation for KonnectorBlock

packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx
=> feat: KonnectorBlock open konnector modal in new tab

packages/cozy-interapp/README.md
Récupération de la doc des intents de cozy-client-js pour la mettre dans cozy-interapp
=> docs: Get cozy-client-js intent doc

packages/cozy-harvest-lib/src/services/utils.js, packages/cozy-sharing/src/helpers/sharings.js
=> refactor: Replace client.get() by Q().getById()

packages/cozy-sharing/package.json, packages/cozy-sharing/src/SharingDetailsModal.jsx, packages/cozy-sharing/src/components/__snapshots__/ContactSuggestion.spec.jsx.snap, yarn.lock
=> Update cozy-ui to 44.10.1 in cozy-sharing

packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
- Change "synchronized in my cozy" to
"Synchronized account"
Vu avec flo.
=> fix: Change text Sync Contract Switch

packages/cozy-harvest-lib/package.json, yarn.lock
Upgrade cozy-bi-auth with new connector mapping (Natixis)
=> feat: Upgrade cozy-bi-auth in harvest

packages/cozy-scanner/src/__snapshots__/DocumentCategory.spec.jsx.snap, packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap, packages/cozy-sharing/package.json, packages/cozy-sharing/test/AppLike.jsx, yarn.lock
Update to muiv4 for cozy-sharing.
BREAKING CHANGE: The application needs to use MUI v4 to works properly with this version of cozy-sharing
=> cozy-sharing : muiv4

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/src/index.jsx
To show short label when "shared with me" or "shared by me". It shows only "shared" in those cases.
=> feat: Add shortLabel prop to ShareButton

packages/cozy-flags/src/FlagSwitcher.jsx, packages/cozy-flags/src/index.browser.js, packages/cozy-flags/src/index.js
See https://github.com/cozy/cozy-libs/issues/1272
=> fix: Remove useless block for node

packages/cozy-harvest-lib/src/datacards/GeoDataCard.jsx, packages/cozy-harvest-lib/src/datacards/trips.js, packages/cozy-harvest-lib/src/datacards/trips.spec.js, packages/cozy-harvest-lib/src/datacards/useCycle.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
- Show times at the level of the arrows (we navigate in time)
- Show duration / distance and transport mode
=> feat: Improve geo data card

packages/cozy-harvest-lib/src/datacards/GeoDataCard.jsx
- Increase trip caption font size
- Increase spacing between trip caption icons and the text
=> feat: Spacing and font size for geo data card

packages/cozy-harvest-lib/src/datacards/FileDataCard.jsx
Use Slide from @material-ui to animate list items that are
received from realtime while a konnector is running.
=> feat: Animate file list item when it is received via realtime

packages/cozy-harvest-lib/package.json
- Update cozy-ui peerDependencies
- Remove cozy-ui from dependencies
=> chore: Update cozy-ui peerDependencies

packages/cozy-harvest-lib/src/helpers/konnectors.js
We need to have the reconnect button inside the 2fa required
error.
https://trello.com/c/l1hDJ23b/1177-probl%C3%A8me-de-cin%C3%A9matique-lors-dun-sca-required
=> feat: Handle more reconnect cases for banking connectors

packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx, packages/cozy-harvest-lib/src/components/AccountForm/index.spec.jsx
When there is a new account to connect
We had stars when we wrote in identifier field
=> fix: Remove default value

packages/cozy-flags/package.json, packages/cozy-flags/src/flag.js, yarn.lock
Since https://github.com/cozy/cozy-libs/pull/1235 we import cozy-client without announcing it. Also, let's be specific for the path to import in order to avoid issues during test / build
=> Fix/flag: Cozy-Client import

packages/cozy-doctypes/src/banking/BankTransaction.js, packages/cozy-doctypes/src/banking/BankTransaction.spec.js
The nestor connector needs this options be sure to fetch
all nestor transactions, since the nestor account will be
removed after the import
=> feat(cozy-doctypes): Add useSplitDate option

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx, packages/cozy-harvest-lib/src/helpers/queries.js
=> feat: Harvest ContactPicker not shown if Contacts apps not installed

.travis.yml, scripts/travis.sh
We previously had issue only when deploying not merging since lerna makes a git diff before deploying. Let's do the same with the CI before merging.
=> chore: Let's exit 1 if there is changes after lint

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab.spec.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
Error message should not be displayed if the konnector is on maintenance
=> fix: Displaying error message

packages/cozy-sharing/src/SharingProvider.jsx
⚠️ this PR must not be merged on `feat/redesign_2steps_confirmation` but on `master`. The target branch will be edited after `feat/redesign_2steps_confirmation` merge
⚠️ this PR should not be merged before `feat/redesign_2steps_confirmation`
____
This callback event may be listened to be notified when a sharing has
been created
=> feat: Add onShared callback to SharingProvider

packages/cozy-device-helper/package.json, packages/cozy-device-helper/src/index.d.ts, packages/cozy-device-helper/tsconfig.json
This will be build upon as needs arise.
For now, I only need this method to be typed.
This is better to do it here rather than in my other app in my opinion.
=> feat: Add a manual typescript declaration file

packages/cozy-harvest-lib/src/cli/cli.js, packages/cozy-harvest-lib/src/components/OAuthForm.jsx, packages/cozy-harvest-lib/src/models/ConnectionFlow.js, packages/cozy-realtime/examples/chat/index.js, packages/cozy-realtime/src/RetryManager.spec.js, packages/cozy-sharing/src/SharingProvider.jsx, packages/cozy-sharing/src/components/ShareDialogTwoStepsConfirmationContainer.jsx, packages/eslint-config-cozy-app/basics.js, packages/eslint-config-cozy-app/package.json, yarn.lock
BREAKING CHANGE: Most errors are not auto fixable,
if needed, use `// disable-next-line`
Or insert in .eslintrc:
```
{
"rules": {
"promise/always-return": "warn",
"promise/no-return-wrap": "warn",
"promise/param-names": "warn",
"promise/catch-or-return": "warn",
"promise/no-native": "warn",
"promise/no-nesting": "warn",
"promise/no-promise-in-callback": "warn",
"promise/no-callback-in-promise": "warn",
"promise/avoid-new": "warn",
"promise/no-new-statics": "warn",
"promise/no-return-in-finally": "warn",
"promise/valid-params": "warn"
}
}
```
=> feat(eslint): Propose Eslint plugin promise

packages/cozy-intent/package.json, packages/cozy-intent/src/declarations.d.ts, packages/cozy-intent/src/tests/mocks.ts, packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx, packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx, packages/cozy-intent/tsconfig-build.json, yarn.lock
Provides multiple ways to instantiate the provider, either by props or by self-creating a service like before
=> feat: Add injection option for WebContext

packages/cozy-intent/package.json
Don't copy ignored files only compiled files and other files
which means json files here
=> feat: Copy json files

packages/cozy-intent/package.json, packages/cozy-intent/src/api/services/NativeMessenger.spec.ts, packages/cozy-intent/src/api/services/NativeService.spec.ts, packages/cozy-intent/src/api/services/NativeService.ts, packages/cozy-intent/src/api/services/TypeguardService.ts, packages/cozy-intent/src/api/services/WebviewMessenger.spec.ts, packages/cozy-intent/src/api/services/WebviewService.spec.ts, packages/cozy-intent/src/tests/jest.config.js, packages/cozy-intent/src/tests/mocks.ts, packages/cozy-intent/src/view/components/NativeIntentProvider.spec.tsx, packages/cozy-intent/src/view/hooks/useNativeIntent.spec.tsx, packages/cozy-intent/src/view/hooks/useWebviewIntent.spec.tsx, yarn.lock
Add a new test config that will fail if cozy-intent is not test covered below 80%.
Required to add new tests to reach this value. See image below
=> chore: Add jest coverage config

packages/cozy-sharing/src/SharingBanner/components/PublicBanner.jsx, packages/cozy-sharing/src/SharingBanner/components/PublicBanner.spec.jsx
fix vulnerability while sharing file between cozy to cozy
=> fix(sharing): Escape public name in public cozy2cozy view

packages/cozy-intent/src/api/models/methods.ts
Will be exposed by the native application to
allow changing interface color
=> feat(cozy-intent): Add new method signatures

packages/cozy-logger/index.d.ts, packages/cozy-logger/package.json, packages/cozy-logger/tsconfig.json
This will make using this module easier in TS envs
=> feat(cozy-logger): Add basic typing

packages/cozy-intent/package.json, packages/cozy-intent/src/api/models/applications.ts, packages/cozy-intent/src/api/models/methods.ts, packages/cozy-intent/src/utils/index.ts, packages/cozy-intent/src/view/components/WebviewIntentProvider.spec.tsx, packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx, yarn.lock
to handle React Native UI manipulations
Instead of having 4 methods to handle statusbar, icons etc, only expose one method with one argument (an object). 
Then react native has to handle all the possible calls but the API side stays simple
=> feat: Implement simpler API signature

.travis.yml, packages/repo-doctor/examples/repo-doctor.json, packages/repo-doctor/package.json, packages/repo-doctor/src/reporters/mattermost.js, packages/repo-doctor/src/reporters/mattermost.spec.js
Adding Message on Mattermost with result of Mattermost: 
https://mattermost.cozycloud.cc/cozycloud/pl/pxpswtqtfpgt8cambgc4qyduwa
=> fix(repo-doctor): Send mattermost notif to front

.github/auto-merge.yml
before: automerg not working:
https://github.com/cozy/cozy-libs/pull/1378/checks?check_run_id=5618633661
=> chore(automerge): Fix auto-merge job what unallowed used merge commits

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/scripts/check-locales.sh
pour avoir les fichiers buildé dans le package npm
le code vient de harvest
=> chore: Add prepublish script to build src

packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/AcquisitionResult.jsx
Bad conditions and forgotten renaming of Proptypes caused console warnings
=> fix: Clean useless warnings

packages/cozy-mespapiers-lib/README.md
All applications that consume the lib will need to import Sprite
=> docs: Add import Sprite

packages/eslint-config-cozy-app/package.json, yarn.lock
- Update everything to latest
- This is required for Amiral App, to fix a breaking change with eslint-plugin-react-hooks
=> fix(eslint-config): Upgrade dependencies

.gitignore, .travis.yml, packages/eslint-config-cozy-app/basics.js
Windows machine endOfLine can be "crlf". Git will handle it.
Also ordered alphabetically the configuration.
=> fix(eslint-config): Add rule for Windows user

packages/cozy-intent/readme.md
Upgrade cozy-intent in order to publish new cozy-libs
=> feat: Remove useless infos on readMe

packages/cozy-intent/src/api/constants/strings.ts, packages/cozy-intent/src/api/models/methods.ts, packages/cozy-intent/src/api/services/NativeMessenger.spec.ts, packages/cozy-intent/src/api/services/NativeService.ts
- Error handling on handshake
- New type definitions for setFlagshipUI Method
- Better mocks in test
=> feat: Handle handshake failure

packages/cozy-intent/src/api/constants/strings.ts, packages/cozy-intent/src/api/models/messengers.ts, packages/cozy-intent/src/api/services/NativeMessenger.spec.ts, packages/cozy-intent/src/api/services/NativeMessenger.ts, packages/cozy-intent/src/api/services/NativeService.spec.ts, packages/cozy-intent/src/api/services/NativeService.ts, packages/cozy-intent/src/utils/index.ts, packages/cozy-intent/src/view/components/WebviewIntentProvider.tsx, packages/cozy-intent/src/view/hooks/useNativeIntent.spec.tsx, packages/cozy-intent/src/view/hooks/useNativeIntent.ts
- This will handle scenarios that were unknown to this day (url casing)
- Updated tests
- Updated typings
- Replaced throw statements with debug statements
- Added more typeguards
- Removed unused strings
https://trello.com/c/yrgEYA6R/398-%F0%9F%90%9B-android-bloqu%C3%A9-sur-le-nuage
=> feat: Rework error handling flow

packages/cozy-mespapiers-lib/package.json, yarn.lock
To get the fix on the Forward button on the Viewer
=> feat: Update cozy-ui package

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
D'autres viendront certainement, mais pour des besoins de test nous avons besoin d'avoir au moins un papier qui utilise un mask
=> Add a mask for the ID card number field

packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx
Display the maskPlaceholder even if the input is not focused
Change the color of the maskPlaceholder if no value is set
=> feat(cozy-mespapiers-lib): Always Display the maskPlaceholder

packages/cozy-mespapiers-lib/package.json, yarn.lock
to fix bug on CircleButton and Buttons
=> feat: Upgrade cozy-ui to 66.2.4

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
revert https://github.com/cozy/cozy-libs/pull/1559/commits/6daa20f892a1e428f2a9bcd72140e7cf37bb1526
=> Remove useVaultClient call in LegacyTriggerManager

packages/cozy-mespapiers-lib/src/components/Placeholders/FeaturedPlaceholdersList.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/FeaturedPlaceholdersList.spec.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholderListModal.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholderThemesList.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.jsx
My bad, je serais plus vigilant sur les imports (d'autant plus relatifs) lors des prochains refacto...
=> fix: Imports of Placeholders components

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
The type of number of the residence permit card also
=> fix: Name of illustrations

packages/eslint-config-cozy-app/package.json, yarn.lock
to fix bug with react-hooks/exhaustive-deps
bug is : Rules with suggestions must set the meta.hasSuggestions
property to true
=> feat: Upgrade eslint-plugin-react-hooks

packages/cozy-mespapiers-lib/src/components/Icons/FileIcon.jsx, packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/Placeholder.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholderThemesList.jsx, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.jsx
on souhaite bien des couleurs en dur
=> Change color of file icon to pink

packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.jsx
We don't want to open an inApp browser in Amiral
Added a check for webviewIntent, use it if available
=> fix: Implement openApp() for Amiral

packages/cozy-mespapiers-lib/package.json, yarn.lock
After run [npx depcheck](https://github.com/depcheck/depcheck#readme), this packages are marked as unused
=> chore: Remove unused devDeps

packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.jsx, packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdownItems.jsx, packages/cozy-mespapiers-lib/src/helpers/getStoreWebLinkByKonnector.js, packages/cozy-mespapiers-lib/src/helpers/getStoreWebLinkByKonnector.test.js
A little refactor at the same time
=> Refactor: use AppLinker instead window.open

packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/ContractItem.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/ContractItemSecondaryText.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SecondaryText.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/helpers.js, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx, packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx, packages/cozy-harvest-lib/src/helpers/proptypes.js, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
Concernant l'override, on souhaite pouvoir depuis une app, modifier le label du 
bouton de déconnexion du compte, ainsi que le bouton de synchro.
=> Add sync date on ContractItem and overrides ability in AccountModal

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx
Also when trying to manage bi contracts
=> fix: Do not show popup when intentsApi is given

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx, packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/AccountSelectBox/CreateAccountButton.jsx, packages/cozy-harvest-lib/src/components/EditAccountModal.jsx, packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
It will allow the banks application to pass custom methods to show, hide inAppBrowser
=> feat: Allow EditAccountModal to have intentsApi prop

packages/cozy-mespapiers-lib/src/components/Home/Home.jsx, packages/cozy-mespapiers-lib/src/components/Home/Home.spec.jsx, packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx, packages/cozy-mespapiers-lib/src/components/SearchResult/SearchResult.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
Le composant est plus personnalisable et ces évolutions permettent de retrouver un champs controlé.
Le champs incontrôlé posait problème lorsque l'on revenait sur la Home, après avoir été dans la liste de la multi-sélection.
=> Improve search input

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/ContractItem.jsx
This allows users to remove bank accounts even when they are disabled.
=> feat: Now allow disabled bank accounts to be clickable

packages/cozy-mespapiers-lib/package.json
Upgrade `cozy-mespapiers-lib` to v1.0.0 🎉
=> chore(release): Publish v1.0.0

packages/cozy-harvest-lib/src/services/biWebView.js
This attributes was also sent with default BI policy (as BankId)
or else, the bi connector won't be able to identify the bank in sentry
=> fix: Add bankIds in createTemporaryToken params

packages/cozy-realtime/README.md
The readme wasn't very clear nor complete about the lib usage
=> docs: Improve setup explanations

packages/cozy-harvest-lib/src/services/biWebView.js
With BI webviews, account are create by the stack which does not handle
the creation of the relationship
=> feat: Add BI aggregator releationship to BI accounts

packages/cozy-harvest-lib/src/services/biWebView.js, packages/cozy-harvest-lib/src/services/biWebView.spec.js, packages/cozy-harvest-lib/src/types.js
The idea is to be careful about our type
and be confident about the change we make.
=> fix: Add ts-check on biWebview

packages/cozy-harvest-lib/src/components/OAuthForm.jsx, packages/cozy-harvest-lib/src/components/TriggerManager.spec.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
We now test if the konnector is a banking one before writing anything related to the banking world.
=> fix: Bank words are reserved for banking konnector

packages/renovate-config-cozy/package.json
waiting for test in https://github.com/cozy/cozy-drive/pull/2649
=> feat(renovate): Group cozy-client subpackages

packages/cozy-harvest-lib/src/services/biWebView.js, packages/cozy-harvest-lib/src/services/biWebView.spec.js
This also removes a getTemporaryToken request which can save a lot of
time visible by the user.
We only used the id of the connection which we already have.
=> fix: Remove unused request to BI connection

packages/cozy-mespapiers-lib/src/components/Actions/Items/rename.js, packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PaperLine.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, packages/cozy-mespapiers-lib/src/components/Papers/Renaming/RenameInput.jsx, packages/cozy-mespapiers-lib/src/components/Papers/Renaming/helpers.js, packages/cozy-mespapiers-lib/src/components/SearchResult/SearchResult.jsx, packages/cozy-mespapiers-lib/src/components/SearchResult/SearchResultLine.jsx, packages/cozy-mespapiers-lib/src/constants/const.js, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
The behavior and the appearance of the text field introduced by this PR are heavily inspired by the equivalent feature in `cozy-drive`.
=> Add a context menu action to rename a paper

packages/cozy-mespapiers-lib/src/components/Home/Home.jsx, packages/cozy-mespapiers-lib/src/components/Home/helpers.js, packages/cozy-mespapiers-lib/src/components/Home/helpers.spec.js, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
With this approach, the search is made on the "harmonized contact names", that is to say the "display names" of up to two contacts, possibly with the last name deduped.
=> Allow to search papers by owner

packages/cozy-codemods/src/transforms/__testfixtures__/transform-mui-styles-imports.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/transform-mui-styles-imports.output.js, packages/cozy-codemods/src/transforms/__tests__/transform-mui-styles-imports.spec.js, packages/cozy-codemods/src/transforms/transform-mui-styles-imports.js
=> feat: Add codemods for mui styles imports

packages/cozy-doctypes/src/Document.js
- Remove deprecated method (find). Will remove the "client.find(doctype, selector) is deprecated" message from bank service
- Use bookmark if present within the response
I copy / pasted the code from Cozy-Client and
managed to be backward compatible since
cozy-doctypes can be used with old CC version...
=> fix: Use bookmark if present

packages/eslint-config-cozy-app/package.json, yarn.lock
We were a bit behind in versions, bugs started to leak in our lints.
These version upgrades should fix them,
but they also have a small chance to detect new lint errors.
=> feat: Update eslint-config-cozy-app

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx
This is a bi webview only feature
=> fix: Hide BIContractActivationWindow begin the bi webview flag

packages/eslint-config-cozy-app/react.js
Allows better type checking, without throwing many errors,
mostly warnings.
This forces the developer to write better code
=> feat: Add new extend for TS files in lint conf

packages/cozy-intent/src/api/models/methods.ts
One method instead of n methods for n possible setting
=> feat(cozy-intent): Update cozy-settings switch API

packages/babel-preset-cozy-app/README.md, packages/browserslist-config-cozy/README.md, packages/commitlint-config-cozy/README.md, packages/cozy-authentication/README.md, packages/cozy-release/README.md, packages/eslint-config-cozy-app/README.md
Update outdated IRC link in `README.md` files
=> docs: Update IRC link

packages/cozy-mespapiers-lib/src/components/Placeholders/Placeholder.jsx, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
And add stranger driver license to suggestion list
=> fix: Wording of driver_license suggestion

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/BiContractActivationWindow.jsx, packages/cozy-harvest-lib/src/components/OAuthWindow.jsx, packages/cozy-harvest-lib/src/helpers/oauth.js, packages/cozy-harvest-lib/src/konnector-policies.js, packages/cozy-harvest-lib/src/services/biWebView.js, packages/cozy-harvest-lib/src/services/biWebView.spec.js, packages/cozy-harvest-lib/src/types.js
This PR needs some update in cozy-stack regarding manage route before being submitted
=> feat: Use BI manage url to update contract synchronization

packages/cozy-sharing/package.json, packages/cozy-sharing/src/SharingProvider.jsx, packages/cozy-sharing/src/fetchNextPermissions.js, yarn.lock
Fix a bug where we could not change permission after refreshing the modal with a lot of files.
We need this PR from cozy-client https://github.com/cozy/cozy-client/pull/1262
=> fix: Paginated permission were not normalized

packages/cozy-sharing/src/components/EditableSharingModal.spec.jsx, packages/cozy-sharing/src/components/ShareModal.jsx
It's protected by the flag : notes.sharing-cozy-to-cozy.
=> feat: Reactivate sharing cozy to cozy for notes

packages/cozy-harvest-lib/src/services/biWebView.js
`createTemporaryToken` is responsible for retrieving a temporary token from the Cozy, and if this token does not exist or is expired then it will create a new one
This method may be called from multiple different components
In some scenario, the call may be simultaneous. This is problematic because the cozy-stack would reject the 2nd update query as it would detect simultaneous database writes
To prevent this we wrap the method into a PromiseCache mechanism that would deduplicate calls
___
> **Warning**
> This PR fixes the bug that prevented the `HANDLE MY SYNCHRONISATION` button to be enabled
> This PR does not pre-load the token on dialog's opening
> This PR does not automatically refresh the token after 30min (which is partially mitigated by the first bullet point)
___
> **Note**
> Our …
=> fix: Prevent createTemporaryToken to updateCache twice at the same time

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
- Certains papiers étaient en double
- On enlève la possiblité d'ajouter des papiers pour certains documents de santé
=> Remove duplicate supported papers, and support for some papers

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
We also increase the length of the field to 3, to allow a number greater than 99 to be entered
=> feat: Add noticePeriod step on health_insurance_card & passport

packages/cozy-harvest-lib/README.md, packages/cozy-mespapiers-lib/README.md, packages/cozy-mespapiers-lib/src/components/Home/helpers.js
Hopefully this should unlock the CI
=> Fix some typos

packages/cozy-harvest-lib/src/components/AccountForm/__snapshots__/index.spec.jsx.snap, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/AccountForm/index.spec.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
Ajout d'un lien sur la modale de login ouvrant une seconde modale d'information, pour aider l'utilisateur en lui proposant un lien vers le site du connecteur en question.
=> Feat(Harvest): Add a modal to help the user to connect

packages/cozy-harvest-lib/src/components/AccountForm/CannotConnectModal.jsx, packages/cozy-harvest-lib/src/components/AccountForm/__snapshots__/index.spec.jsx.snap, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/Providers/ComponentsPropsProvider.jsx, packages/cozy-harvest-lib/src/components/Routes.jsx, yarn.lock
Cette PR ajoute un Provider pour surcharger (par ajout de contenu) le composant `CannotConnectModal`
C'est une implémentation très sommaire, qui pourra évoluer au besoin.
=> Feat(Harvest): Add ComponentsPropsProvider component

packages/cozy-scanner/src/EditDocumentQualification.jsx, packages/cozy-scanner/src/ModalScannerQualification.jsx
```
- Remove Matomo from cozy-scanner
```
=> feat: Remove Matomo from cozy-scanner

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.spec.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.spec.jsx, packages/cozy-mespapiers-lib/src/components/Views/HarvestRoutes.jsx, packages/cozy-mespapiers-lib/src/doctypes/index.js, packages/cozy-mespapiers-lib/src/helpers/queries.js
La manière dont l'import est fait dans PapersList est temporaire, c'est un 
premier jet pour mutualiser dans l'équipe. C'est clairement à refactor plus 
tard.
=> Add first harvest integration

packages/cozy-mespapiers-lib/src/components/Harvest/CannotConnectModal/ExtraContent.jsx, packages/cozy-mespapiers-lib/src/components/Views/HarvestRoutes.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
This component is used to add content to a Harvest modal
=> feat(mespapiers): Add ExtraContent component

packages/cozy-mespapiers-lib/src/components/Actions/Items/select.js, packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Viewer/SelectFileButton.jsx
The path of multi-selection must be absolute, otherwise we cannot choose papers belonging to different themes
=> fix(mespapiers): Multiselect route

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Actions/ActionsItems.jsx, packages/cozy-mespapiers-lib/src/components/Actions/DeleteConfirm.jsx, packages/cozy-mespapiers-lib/src/components/Actions/Items/trash.js, packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdownItems.jsx, packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PaperLine.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, packages/cozy-mespapiers-lib/src/components/Views/HarvestRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx, packages/cozy-mespapiers-lib/src/helpers/getStoreWebLinkByKonnector.js, packages/cozy-mespapiers-lib/src/helpers/getStoreWebLinkByKonnector.test.js
Voir l'implémentation et explication côté Store : https://github.com/cozy/cozy-store/pull/842
=> mespapiers: Use `redirectAfterInstall` to get  Store redirection

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/package.json, packages/cozy-sharing/src/components/ShareAutosuggest.jsx, packages/cozy-sharing/src/components/ShareByEmail.jsx, packages/cozy-sharing/src/components/ShareByEmail.spec.jsx, packages/cozy-sharing/src/components/ShareDialogCozyToCozy.jsx, packages/cozy-sharing/src/components/ShareDialogOnlyByLink.jsx, packages/cozy-sharing/src/components/ShareRecipientsInput.jsx, packages/cozy-sharing/src/components/__snapshots__/ShareRecipientsInput.spec.jsx.snap, packages/cozy-sharing/src/share.styl, yarn.lock
- Hide ShareByEmail controls when input not focused or empty
- Add "Who has access?" title in Dialog
=> Update share by email buttons

packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx
even if there were several groups to display
=> fix(mespapiers): A list's last paper's deletion came back on the home

packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx
=> fix(mespapiers): Lists header were on several lines

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
Link hérite des "variant" de Typography
=> fix(harvest): Font size of the help link in the account login modal

packages/cozy-sharing/src/components/ContactSuggestion.jsx, packages/cozy-sharing/src/components/ShareAutosuggest.jsx, packages/cozy-sharing/src/components/__snapshots__/ContactSuggestion.spec.jsx.snap, packages/cozy-sharing/src/components/autosuggest.styl
This PR improve design of Share Autosuggest by taking all the cozy-ui benefits. We use now Chips and ListItem to show suggestions.
=> Feat: use chips into share autosuggest

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, yarn.lock
lié à https://github.com/cozy/cozy-libs/pull/1973
il faut donc passer un argument pour pouvoir ouvrir la configuration d'un connecteur correctement
=> Update harvest and pass konnectorRoot to  LaunchTriggerCard

packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Views/FileViewerWithQuery.jsx, packages/cozy-mespapiers-lib/src/components/Views/Home.jsx, packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx
Suite à la décision prise au point Front et être raccord avec les autres applications! :)
=> refactor(mespapiers-lib): Minimize the use of Outlet outside the router

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Papers/HarvestBanner.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersList.jsx, packages/cozy-mespapiers-lib/src/doctypes/index.js, packages/cozy-mespapiers-lib/src/helpers/queries.js, yarn.lock
en lien avec https://github.com/cozy/cozy-libs/pull/2001
=> Ability of Harvest banner to deal with  disconnected account

packages/cozy-mespapiers-lib/README.md, packages/cozy-mespapiers-lib/docs/AddPaperGuidelines.md, packages/cozy-mespapiers-lib/docs/papersDefinitions.md, packages/cozy-mespapiers-lib/docs/placeholderIndex.md
and move Suggestions order section in a separate file
=> docs(mespapiers): Add a checklist to help the creation of a new paper configuration

packages/cozy-mespapiers-lib/src/components/Actions/Items/createPaperByTheme.js, packages/cozy-mespapiers-lib/src/components/PapersFab/PaperFabUI.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.spec.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
This new action is added to the paperFab menu if you are in a list of papers.
It allows you to create a paper of the theme where you find yourself more quickly.
=> Add new action to paper fab

packages/cozy-mespapiers-lib/src/components/Contexts/SearchProvider.jsx, packages/cozy-mespapiers-lib/src/components/Home/HomeLayout.jsx, packages/cozy-mespapiers-lib/src/components/MesPapiersLibLayout.jsx, packages/cozy-mespapiers-lib/src/components/MesPapiersLibLayout.test.jsx, packages/cozy-mespapiers-lib/src/components/MesPapiersLibProviders.jsx, packages/cozy-mespapiers-lib/src/components/Search/SearchProvider.jsx, packages/cozy-mespapiers-lib/src/components/Search/helpers.js, packages/cozy-mespapiers-lib/src/components/Search/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/Search/search.js, packages/cozy-mespapiers-lib/src/components/Search/search.spec.js, packages/cozy-mespapiers-lib/test/components/AppLike.jsx
suite aux remarques sur la PR initiale https://github.com/cozy/cozy-libs/pull/2029
je m'occupe du fix https://github.com/cozy/cozy-libs/issues/2023 côté realtime dans la foulée (voir PR https://github.com/cozy/cozy-libs/pull/2048) et je corrigerais le code ici ensuite. A ce stade, on peut donc garder le code temporaire afin d'avancer et d'isoler les sujets
=> Some refactor on search providers

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
Cette PR traite divers retours PO sur à l'évolution passée sur l'ajout de nouveaux papiers
=> Multiple fixes in the paperDefinitions.json

packages/cozy-mespapiers-lib/src/components/Viewer/SelectFileButton.jsx
Cette PR reprend juste le commit de https://github.com/cozy/cozy-libs/pull/1808 qui à l'heure actuelle est toujours pertinent :)
=> fix(mespapiers-lib): Apply breaking changes from cozy/cozy-ui#2215

packages/cozy-harvest-lib/src/locales/fr.json
The label was in English, it is now in French
=> feat(harvest): Add FR translation to installFlagship

packages/cozy-mespapiers-lib/package.json, yarn.lock
BREAKING CHANGE: You must have `cozy-ui >=81.6.1`
=> feat: Update `cozy-ui` to 81.6.1

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/components/FlowProvider.jsx
- Also delete other Backdrop renders
- This should fix all issues regarding backdrop being under harvest part
=> fix(harvest): Display backdrop in a portal

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Search/search.js, packages/cozy-mespapiers-lib/src/components/Search/search.spec.js, packages/cozy-mespapiers-lib/src/components/SearchResult/FlexsearchResult.jsx, packages/cozy-mespapiers-lib/src/components/SearchResult/FlexsearchResultLine.jsx, packages/cozy-mespapiers-lib/src/helpers/queries.js
Cela nécessite l'update de cozy-ui https://github.com/cozy/cozy-ui/pull/2393, mais la review peut être faite quand même
=> Adjustment for flexsearch result after PO test

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Contexts/SearchProvider.jsx, packages/cozy-mespapiers-lib/src/components/Search/SearchProvider.jsx, packages/cozy-mespapiers-lib/src/components/Search/helpers.js, packages/cozy-mespapiers-lib/src/components/Search/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/Search/search.js, packages/cozy-mespapiers-lib/src/components/Search/search.spec.js, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json, yarn.lock
need https://github.com/cozy/cozy-ui/pull/2394
=> mespapiers: adds the possibility to search on the translated metadata labels

packages/cozy-mespapiers-lib/README.md, packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/CompositeHeader/CompositeHeaderImage.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputDateAdapter.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/widgets/InputTextAdapter.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFab.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.jsx, packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx, yarn.lock
First pass to improve Mespapiers app accessibility
=> feat: Improve accessibility

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
Updated Dialog API to handle back button on editModal
=> feat(harvest): Handle backButton on editModal

packages/cozy-mespapiers-lib/src/components/Actions/Items/forward.js, packages/cozy-mespapiers-lib/src/components/ImportDropdown/ImportDropdown.spec.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/ContactEditDialog.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.spec.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
And add helper text to ContactEditDialog for helps user When it wants to edit the contact
=> Feat: Update wording

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Home/ContentWhenSearching.jsx, packages/cozy-mespapiers-lib/src/components/Search/helpers.js, packages/cozy-mespapiers-lib/src/components/Search/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/Search/search.js, packages/cozy-mespapiers-lib/src/components/Search/useSearchResult.jsx, yarn.lock
Le premier commit concerne la mise en place de la possibilité de faire une 
recherche multi-attribut.
L'autre commit est lié à https://github.com/cozy/cozy-ui/pull/2408
=> Multiple search and expanded attributes

packages/cozy-mespapiers-lib/src/components/MesPapiersLibProviders.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFab.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.spec.jsx
Ajout du flag `mespapiers.fabExtended.enabled` pour accéder au nouveau PapersFab étendu et au ForwardFab
=> feat: Add flag on extended PapersFab functionality

packages/cozy-flags/src/FlagSwitcher.jsx, packages/cozy-flags/src/connect.jsx, packages/cozy-flags/src/index.browser.js, packages/cozy-flags/src/useFlag.spec.js, packages/cozy-logger/src/dev-format.js, packages/cozy-logger/src/index.js, packages/cozy-logger/src/log-format.js, packages/cozy-logger/src/log-formats.spec.js, packages/playgrounds/package.json, packages/playgrounds/src/common/App.jsx, packages/playgrounds/src/common/client.js, packages/playgrounds/src/common/components.jsx, packages/playgrounds/src/existing-store.jsx, packages/playgrounds/src/procedures.jsx, packages/playgrounds/src/sharing.jsx, yarn.lock
=> fix: Lint issues for a few packages (not all yet)

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Home/helpers.js, packages/cozy-mespapiers-lib/src/components/Home/helpers.spec.js, yarn.lock
Sorting of the qualification labels listed on the homepage based on the creation date of the files
=> feat: Sort category of papers

packages/cozy-harvest-lib/src/components/AccountForm/ConnectionBackdrop.jsx
- Add a backdrop-filter
- Update font sizes and vertical rythm
- Desktop and Mobile
=> feat(harvest): Update ConnectionBackdrop styles

packages/cozy-mespapiers-lib/src/components/Home/FilterButton.jsx, packages/cozy-mespapiers-lib/src/components/Home/SearchHeader.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
And remove the badge if no theme is selected
=> feat(cozy-mespapiers-lib): Add accessibility attributes to FilterButton

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.js, packages/cozy-harvest-lib/src/helpers/useKonnectorWithTriggers.spec.js, yarn.lock
{data: []} structure was not used everywhere.
This caused realtime error messages and some trigger values where not
updated
=> fix: Regression in useKonnectorWithTrigger

packages/cozy-mespapiers-lib/src/components/Home/SearchHeader.jsx, packages/cozy-mespapiers-lib/src/components/SearchInput/SearchInput.jsx, packages/cozy-mespapiers-lib/src/components/Views/Home.spec.jsx
And keep the initial height of the SearchInput
(see 08e904d)
=> fix: Always show ThemeFilter on mobile

packages/cozy-scanner/package.json, packages/cozy-scanner/src/DocumentQualification.jsx, packages/cozy-scanner/src/DocumentQualification.spec.jsx, yarn.lock
On the condition of a flag (`hide.healthTheme.enabled`), we wish to be able to hide the Health theme.
=> feat(cozy-scanner): Hide health theme

packages/cozy-harvest-lib/src/helpers/konnectorBlock.js, packages/cozy-harvest-lib/src/helpers/queries.js
The request was not working for a client side konnectors since the type is not the same as the one for the server side.
We had an error within the KonnectorBlock Panel
=> fix: KonnectorBlock works with clientSide konnectors

packages/cozy-scanner/package.json, packages/cozy-scanner/src/DocumentQualification.jsx, packages/cozy-scanner/src/DocumentQualification.spec.jsx, packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap, yarn.lock
We no longer want to condition the display of the Health theme.
=> feat: Remove cozy-flags from cozy-scanner

packages/cozy-harvest-lib/src/helpers/konnectorBlock.js, packages/cozy-harvest-lib/src/helpers/konnectorBlock.spec.js, packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js, packages/cozy-harvest-lib/src/policies/clisk.js, packages/cozy-harvest-lib/src/policies/clisk.spec.js
If the cozy is in debug mode, then let's send DEBUG true to the Launcher in order to display the debug view
=> feat: Send debug if flag is set to true

packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.spec.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanMobileActions.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanMobileActions.spec.jsx
We want to be able to hide the features that offer to install the Cozy app
=> feat(mespapiers): Add `mespapiers.aa-suggestion.enabled` flag

packages/cozy-mespapiers-lib/src/components/Contexts/PaywallProvider.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanDesktopActions.spec.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/Scan/ScanActions/ScanMobileActions.spec.jsx
It was not using the correct flag
=> fix(mespapiers): Fix PaywallProvider

packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-deprecated-imports.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-deprecated-imports.output.js, packages/cozy-codemods/src/transforms/__tests__/transform-ui-deprecated-imports.spec.js, packages/cozy-codemods/src/transforms/transform-ui-deprecated-imports.js
PR du BC cozy-ui : https://github.com/cozy/cozy-ui/pull/2464
=> feat(codemods): Add transform-ui-deprecated-imports

packages/cozy-scanner/package.json, packages/cozy-scanner/src/CategoryGridItem.jsx, packages/cozy-scanner/src/CategoryGridItem.spec.jsx, packages/cozy-scanner/src/DocumentCategory.jsx, packages/cozy-scanner/src/DocumentCategory.spec.jsx, packages/cozy-scanner/src/DocumentQualification.jsx, packages/cozy-scanner/src/DocumentQualification.spec.jsx, packages/cozy-scanner/src/EditDocumentQualification.jsx, packages/cozy-scanner/src/ModalScannerQualification.jsx, packages/cozy-scanner/src/Scanner.jsx, packages/cozy-scanner/src/__snapshots__/CategoryGridItem.spec.jsx.snap, packages/cozy-scanner/src/__snapshots__/DocumentCategory.spec.jsx.snap, packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap, packages/cozy-scanner/src/withLocales.jsx, yarn.lock
BREAKING CHANGE:
- you need to update cozy-ui to 88.2.1
- you need to update cozy-client to 38.9.2
=> feat: Update cozy-ui to 88 and other deps

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
Fix issue with OAuth & Banking konnector from the store intent
Since https://github.com/cozy/cozy-libs/pull/2221
=> fix: We use the mountContext without mounting in

packages/cozy-mespapiers-lib/src/components/Actions/Items/createPaperByQualificationLabel.js, packages/cozy-mespapiers-lib/src/components/Actions/Items/index.js, packages/cozy-mespapiers-lib/src/components/Actions/Items/open.js, packages/cozy-mespapiers-lib/src/components/Contexts/MultiSelectionProvider.jsx, packages/cozy-mespapiers-lib/src/components/Harvest/CannotConnectModal/ExtraContent.jsx, packages/cozy-mespapiers-lib/src/components/MesPapiersLibRoutes.jsx, packages/cozy-mespapiers-lib/src/components/Multiselect/MultiselectPaperList.jsx, packages/cozy-mespapiers-lib/src/components/Papers/Empty/EmptyNoHeader.jsx, packages/cozy-mespapiers-lib/src/components/Papers/Empty/helpers.js, packages/cozy-mespapiers-lib/src/components/Papers/Empty/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/Papers/PaperGroup.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.spec.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListToolbar.jsx, packages/cozy-mespapiers-lib/src/components/Papers/helpers.js, packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/PapersFab/PapersFabWrapper.spec.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/useGeneralActions.jsx, packages/cozy-mespapiers-lib/src/components/PapersFab/useKonnectorsActions.jsx, packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx, packages/cozy-mespapiers-lib/src/helpers/createPdfAndSave.js, packages/cozy-mespapiers-lib/src/helpers/createPdfAndSave.spec.js, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
the qualification label and not to the theme label.
=> refactor(mespapiers): Correctly rename variables that correspond to

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/Home/ContentWhenNotSearching.jsx, packages/cozy-mespapiers-lib/src/components/Papers/CategoryItemByPaper.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx, packages/cozy-mespapiers-lib/src/components/Papers/helpers.js, packages/cozy-mespapiers-lib/src/components/Papers/helpers.spec.js, packages/cozy-mespapiers-lib/src/components/Placeholders/PlaceholderListModal/PlaceholdersList.jsx, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json, packages/cozy-mespapiers-lib/src/helpers/queries.js, yarn.lock
La méthode `generateReturnUrlToNotesIndex` utilisé pour les notes n'est pas forcément celle qu'on souhaite, une réflexion est en cours à ce sujet mais pour l'instant on part avec ça. La méthode est un copier/coller de l'app Notes
=> Add reminder-note support

packages/cozy-sharing/src/hooks/useSharingContext.jsx, packages/cozy-sharing/src/index.jsx
This helps using sharing context and mocking it
=> feat: Add useSharingContext

packages/cozy-intent/readme.md
- Separate into two parts : setup and usage
- Use very very explicit method name to be more understandable
- Add progress updates tutorial
Direct link : https://github.com/cozy/cozy-libs/blob/docs/cozy-intent/packages/cozy-intent/readme.md
=> docs: Update cozy-intent documentation with progress updates

packages/cozy-mespapiers-lib/package.json, packages/cozy-mespapiers-lib/src/components/InstallAppFromIntent/InstallAppFromIntent.jsx, packages/cozy-mespapiers-lib/src/doctypes/index.js, packages/cozy-mespapiers-lib/src/helpers/queries.js, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json, yarn.lock
The name of the Note application may change depending on the context,
it is preferable to go through the registry in these cases.
=> fix(mespapiers): Use the correct Note app icon and name

packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-providers-imports.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-providers-imports.output.js, packages/cozy-codemods/src/transforms/__tests__/transform-ui-providers-imports.spec.js, packages/cozy-codemods/src/transforms/transform-ui-providers-imports.js
relative to https://github.com/cozy/cozy-ui/pull/2501
=> feat(codemods): Add transform-ui-providers-imports

packages/cozy-mespapiers-lib/src/components/ModelSteps/Edit/helpers.js, packages/cozy-mespapiers-lib/src/components/Views/InformationEdit.jsx, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
This PR improves maxLength of the input so that it matches reality as closely as possible so user gets pertinents error feedback after OCR step
- https://github.com/cozy/cozy-libs/pull/2289
=> feat: Improve error management for OCR

packages/cozy-minilog/package.json
In order to have the right links from npm and other tools
=> fix: Change info in package.json

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/AccountForm/InstallFlagshipButton.jsx, packages/cozy-harvest-lib/src/components/AccountForm/InstallFlagshipButton.spec.jsx, packages/cozy-harvest-lib/src/components/AccountForm/__snapshots__/index.spec.jsx.snap, packages/cozy-harvest-lib/src/components/AccountForm/index.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json, yarn.lock
- https://github.com/cozy/cozy-client/pull/1404
=> fix: Minor adjustment before deploy ccc

packages/cozy-harvest-lib/package.json, packages/cozy-harvest-lib/src/components/DumbTriggerManager.jsx, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/helpers/accounts.spec.js, packages/cozy-harvest-lib/src/helpers/queries.js, yarn.lock
This PR is used to exclude konnectors under maintenance from the calculation for displaying the paywall about maximum accounts
- https://github.com/cozy/cozy-client/pull/1406
- https://github.com/cozy/cozy-client/pull/1407
=> feat(checkMaxAccounts): Exclude connectors under maintenance

packages/cozy-harvest-lib/src/components/AccountForm/ConnectionBackdrop.jsx, packages/cozy-harvest-lib/src/components/FlowProvider.jsx
This will clear up unstable states during and after the connectionBackdrop displays
=> fix(harvest): Set FlagshipUI on connectionBackdrop

packages/cozy-harvest-lib/src/components/AccountModal.jsx, packages/cozy-harvest-lib/src/components/EditAccountModal.jsx, packages/cozy-harvest-lib/src/components/NewAccountModal.jsx, packages/cozy-harvest-lib/src/components/RedirectToAccountFormButton.jsx, packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlert.jsx, packages/cozy-harvest-lib/src/components/cards/LaunchTriggerAlertMenu.jsx, packages/cozy-harvest-lib/src/connections/accounts.js, packages/cozy-harvest-lib/src/connections/triggers.js, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/helpers/triggers.js, packages/cozy-harvest-lib/src/helpers/triggers.spec.js
No need to have our own implem here
=> refactor: Use helpers from cozy-client

packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.js, packages/cozy-harvest-lib/src/components/AccountsPaywall/helpers.spec.js, packages/cozy-harvest-lib/src/helpers/accounts.js, packages/cozy-harvest-lib/src/helpers/accounts.spec.js
This PR fix the flag `harvest.accounts.offers` so credits can be offered to create an account on a konnector even if the maximum is exceeded. You can also offer accounts for all konnectors in order to temporarily reduce the maximum limit.
=> fix: Improve paywall accounts offers

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
- Add new paper diploma 
- Modif maxLength 40 to 255 for paper diploma & resume
=> feat: Add paper diploma et max 255 to diploma & resume.json

packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json
- Add step label given by user to paper other_invoice
=> Add label given by user to paper other_invoice.json

packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx
This will fix a display issue where the Dialog doesn't have top
padding from the native device
=> fix(harvest): Illustration as title in Suggestion

packages/cozy-mespapiers-lib/src/helpers/queries.js
=> fix: Add indexFields

packages/cozy-harvest-lib/.storybook/StoryContainer.tsx, packages/cozy-harvest-lib/src/components/AccountForm/ConnectionBackdrop.jsx, packages/cozy-harvest-lib/src/components/AccountForm/ConnectionBackdrop.stories.jsx
We have perf issue on this component. We suspect the LinerProgress component to take too much CPU. 
I added a story in order to be able to debug that later.
=> test: Add story ConnecionBackdrop

.travis.yml
Remove Travis cache because it's slower with the cache.
=> chore: Remove travis cache

packages/cozy-mespapiers-lib/src/components/Views/Home.spec.jsx, packages/cozy-mespapiers-lib/src/locales/en.json, packages/cozy-mespapiers-lib/src/locales/fr.json
The renaming is for a customer request originally.
We take advantage of this work to clean up unused translation keys.
=> Feat(mespapiers): Rename "paper" to "document"

packages/cozy-logger/index.d.ts
related https://github.com/cozy/cozy-libs/pull/2379
=> fix: Fix types of cozy-logger

packages/cozy-flags/src/flag.js
related https://github.com/cozy/cozy-libs/pull/2378
=> fix: Fix types of CozyClient on cozy-flags

packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PapersListByContact.spec.jsx, packages/cozy-mespapiers-lib/src/components/Papers/helpers.js, packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx, packages/cozy-mespapiers-lib/src/constants/const.js, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json, packages/cozy-mespapiers-lib/src/constants/papersDefinitions_health.json
Cette PR consiste à homogénéiser le nombre de documents affichés (avant l'affichage du "voir plus") selon 2 critères:
- Documents mono ou multi faces
- Nombre de contacts ou connecteurs dans la liste
Voir le commit pour plus de précision.
=> feat(mespapiers): Change number of doc displayed

packages/cozy-mespapiers-lib/src/components/Views/ContactEdit.jsx
In case there is only one contact referenced and one contact is selected
=> fix(mespapiers): Rename file when referenced contact change

packages/cozy-mespapiers-lib/src/components/Views/PapersList.jsx, packages/cozy-mespapiers-lib/src/helpers/queries.js
Deleting unused queries or those that could use other similar ones.
=> feat(mespapiers): Remove useless queries

packages/cozy-sharing/package.json, packages/cozy-sharing/src/components/SharingBanner/components/PublicBanner.jsx, packages/cozy-sharing/src/components/__snapshots__/ContactSuggestion.spec.jsx.snap, packages/cozy-sharing/src/styles/actionmenu.styl, packages/cozy-sharing/src/styles/autosuggest.styl, packages/cozy-sharing/src/styles/recipient.styl, packages/cozy-sharing/src/styles/share.styl, yarn.lock
must merge https://github.com/cozy/cozy-ui/pull/2583 and upgrade cozy-ui first
=> feat(sharing): Upgrade cozy-ui and cozy-client

packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-deprecated-table.input.js, packages/cozy-codemods/src/transforms/__testfixtures__/transform-ui-deprecated-table.output.js, packages/cozy-codemods/src/transforms/__tests__/transform-ui-deprecated-table.spec.js, packages/cozy-codemods/src/transforms/transform-ui-deprecated-table.js
=> feat(codemods): Add transform-ui-deprecated-table

packages/cozy-harvest-lib/src/connections/accounts.js
see https://github.com/cozy/cozy-libs/pull/2447#discussion_r1514112607
=> fix: Deep clone account

packages/cozy-sharing/.storybook/preview.jsx, packages/cozy-sharing/package.json, packages/cozy-sharing/src/SharingProvider.jsx, packages/cozy-sharing/src/components/Recipient/GroupRecipientPermissions.jsx, packages/cozy-sharing/src/components/Recipient/actions/permission.js, packages/cozy-sharing/src/state.js, yarn.lock
- https://github.com/cozy/cozy-client/pull/1454
=> [VO-435 & VO-438] feat: Allow to revoke recipient groups

packages/cozy-mespapiers-lib/src/components/InstallAppFromIntent/InstallAppFromIntent.jsx, packages/cozy-mespapiers-lib/src/components/Papers/PaperItem.jsx
- After successfully installing the Notes app in mespapiers, we redirect to the requested note
=> fix(mespapiers): Redirect to a note after install (VO-414)

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/src/components/ShareByEmail.jsx, packages/cozy-sharing/src/components/ShareRecipientsInput.jsx, packages/cozy-sharing/src/components/ShareRecipientsInput.spec.jsx
This PR adds back-end error handling and corrects some behaviour and bugs discovered during development of the dynamic shared group
=> [VO-436 & VO-626] feat: Handling errors when sharing

packages/cozy-mespapiers-lib/src/components/Contexts/FormDataProvider.jsx, packages/cozy-mespapiers-lib/src/components/Hooks/useFormData.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/InformationDialog.jsx, packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.js, packages/cozy-mespapiers-lib/src/components/ModelSteps/helpers.spec.js, packages/cozy-mespapiers-lib/src/constants/papersDefinitions.json, packages/cozy-mespapiers-lib/src/types.js
Following the recent modification to handle "deep" metadata (https://github.com/cozy/cozy-libs/commit/5ae24696d7a99bee73d3ceb28c07432680daaa40).
=> Fix(mespapiers): Merge all metadata when submit information step

packages/cozy-sharing/src/components/Recipient/GroupRecipient.jsx, packages/cozy-sharing/src/components/Recipient/GroupRecipientDetailWithAccess.jsx, packages/cozy-sharing/src/components/Recipient/GroupRecipientDetailWithoutAccess.jsx, packages/cozy-sharing/src/components/Recipient/LinkRecipient.jsx, packages/cozy-sharing/src/components/Recipient/MemberRecipient.jsx
Quick fixes after the review of your designer
=> fix(sharing): Improve size inside recipient list

packages/cozy-harvest-lib/src/components/cards/MaintenanceAlert.jsx
=> feat(harvest): Replace background color for MaintenanceAlert

packages/cozy-harvest-lib/src/components/KonnectorIcon.jsx
=> feat: Remove comment

packages/cozy-harvest-lib/src/components/Routes/RoutesV4.jsx, packages/cozy-harvest-lib/src/components/Routes/RoutesV6.jsx, packages/cozy-harvest-lib/src/locales/en.json, packages/cozy-harvest-lib/src/locales/fr.json
- **feat: Multiaccounts for clisk konnectors with clisk.multi-accounts flag**
- **feat: Handle WRONG_ACCOUNT_IDENTIFIER konnector status**
=> feat: Multiaccounts for clisk konnectors with clisk.multi-accounts flag (SCR-869)

packages/cozy-harvest-lib/.storybook/StoryContainer.tsx, packages/cozy-harvest-lib/.storybook/manager-head.html, packages/cozy-harvest-lib/jest.config.js, packages/cozy-harvest-lib/package.json, yarn.lock
**Related PRs :**
- https://github.com/cozy/cozy-ui/pull/2715
=> fix: Make storybook work again inside Harvest

packages/cozy-viewer/package.json
BREAKING CHANGE: You must have `cozy-harvest-lib >= 30.8.0`
=> feat(Viewer): Upgrade cozy-harvest-lib

CODEOWNERS, packages/cozy-viewer/package.json, packages/cozy-viewer/src/Panel/QualificationListItemText.jsx, packages/cozy-viewer/src/Panel/Summary.jsx, packages/cozy-viewer/src/Panel/SummaryDialog.jsx, packages/cozy-viewer/src/Panel/getPanelBlocks.jsx, packages/cozy-viewer/src/Panel/getPanelBlocks.spec.jsx, packages/cozy-viewer/src/locales/en.json, packages/cozy-viewer/src/locales/fr.json, yarn.lock
need https://github.com/cozy/cozy-ui/pull/2721
=> Viewer: Add summary block

config/rsbuild-config-cozy-app/LICENSE, config/rsbuild-config-cozy-app/README.md, config/rsbuild-config-cozy-app/getRsbuildConfig.js, config/rsbuild-config-cozy-app/helpers.js, config/rsbuild-config-cozy-app/index.js, config/rsbuild-config-cozy-app/package.json, package.json, yarn.lock
First step towards migrating our apps to Rsbuild. I'll be improving the documentation as I go along, but the first building blocks have enabled me to migrate `cozy-photos`. All that's missing now is the NPM package to finish the PR.
=> [VO-1195] feat: Add rsbuild config for cozy app

packages/cozy-sharing/locales/en.json, packages/cozy-sharing/locales/fr.json, packages/cozy-sharing/src/components/SharingBanner/components/PublicBanner.jsx, packages/cozy-sharing/src/components/SharingBanner/components/PublicBanner.spec.jsx, packages/cozy-sharing/src/styles/publicBanner.styl
We no longer want to bold all the banner text.
=> feat(Sharing): Change style of PublicBanner wording

packages/cozy-viewer/src/components/PublicToolbarMoreMenu.jsx, packages/cozy-viewer/src/components/Toolbar.jsx
=> feat(cozy-viewer): Add Sharing buttons in the public viewer

packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
When a file or directory is removed by the user, the received realtime event is an update and not a delete, as the document is moved in the trash, not actually removed.
Thus, we handle deletion from search index after an update.
=> fix: Remove file from search after realtime event

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx
This was causing issues on flagship app
=> fix: Do not instanciate iframe for RN env

package.json
Ignore cozy-viewer tests temporarily
=> chore: Fix libs tests

packages/cozy-viewer/package.json, yarn.lock
BREAKING CHANGE: You must have `cozy-harvest-lib >= 32.2.5`
=> feat(Viewer): Upgrade packages

packages/cozy-realtime/src/RealtimePlugin.js
The JSdoc was not compliant with the code
=> fix: Correctly declare RealtimePlugin's `option` parameter as optional

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx, packages/cozy-dataproxy-lib/src/search/SearchEngine.spec.js, packages/cozy-dataproxy-lib/src/search/SearchEngine.ts
- [fix: Index documents only after login](https://github.com/cozy/cozy-libs/commit/965c61d186ea8d2a98f483efa3b17265b8488b1d)
- [fix: Improve indexing time](https://github.com/cozy/cozy-libs/commit/08e0808219bf74e6d78a94e0fa4f1aa84bc59635)
=> Fixes on indexing

packages/cozy-viewer/package.json, packages/cozy-viewer/src/ViewerContainer.jsx, yarn.lock
Avec Modal la propagation du clic fonctionnait mal notamment sur la barre de recherche dans la modification des Qualifications
=> Viewer: Replace Modal by Dialog and add better click propagation

packages/cozy-viewer/src/ViewerContainer.jsx
introduced by https://github.com/cozy/cozy-libs/pull/2756/commits/b40f8a2aa34755a7dce3abe252b8268bc2687791
=> fix(Viewer): Props have been omitted on Viewer component

packages/cozy-viewer/package.json, packages/cozy-viewer/src/Panel/Sharing.jsx, yarn.lock
see https://github.com/cozy/cozy-libs/pull/2758
=> Viewer: Don't rely anymore on parent to show file recipients

packages/cozy-search/src/components/Conversations/ChatUserItem.jsx, packages/cozy-search/src/locales/en.json, packages/cozy-search/src/locales/fr.json
When myself is not found for some reason, the assistant was crashing. Thus, we now provide a fake Anonymous contact.
=> fix: Do not crash on missing myself contact

packages/cozy-dataproxy-lib/src/dataproxy/DataProxyProvider.jsx
We now render the `DataProxyProvider` children only when the DataProxy
is  correctly initialized on the web.
To know this, we rely on the cozy-web-dataproxy app to send a "ready"
message once it is indeed ready.
This is meant to avoid some timing issues, where the app is ready to
request the DataProxy, but the DataProxy is not initialized yet.
=> feat: Correctly init DataProxy

packages/cozy-external-bridge/src/container/useListenBridgeRequests.ts
The Docs update was broken as it was expecting name and metadata
=> fix: Docs update

packages/cli-tree/package.json, packages/cozy-app-publish/package.json, packages/cozy-devtools/package.json, packages/cozy-doctypes/package.json, packages/cozy-harvest-lib/package.json, packages/cozy-procedures/package.json, packages/cozy-search/package.json, packages/cozy-sharing/package.json, packages/cozy-viewer/package.json, packages/playgrounds/package.json, yarn.lock
I am starting to play with packages in cozy-libs to reduce install time and size.
=> Dedup classnames and lodash packages

packages/cozy-sharing/src/components/ShareModal/ShareModal.jsx
Add revoke success callback.
[cozy/cozy-drive#3532](https://github.com/cozy/cozy-drive/pull/3532)
=> feat: Add onRevokeSuccess callback :sparkles:
