packages/cozy-device-helper/package.json
packages/cozy-device-helper/src/apps.js
packages/cozy-device-helper/src/apps.spec.js

The plugin having the same name as the function, it was
incorrectly referenced.
```
const exported = { checkApp, startApp }
export default exported
```
is incorrect with this form of importing
```
import { checkApp, startApp } from 'cozy-device-helper'
```

fix: incorrect plugin reference and exports

---

packages/commitlint-config/index.js
packages/commitlint-config/index.spec.js

We would like limit max length of each line, not all body part
We have to wait  to be introduced to commitlint
[See this PR](https://github.com/marionebl/commitlint/pull/400)

fix: Remove 72 chars limit on body description 🔥

---

packages/interapp/src/intents.js
packages/interapp/src/intents.spec.js
packages/interapp/src/request.js
packages/interapp/src/request.spec.js

Cette PR permet de retourner directement les documents lorsque l'on fetch avec cozy client.
Au lieu de faire `request.get(13).then(resp => resp.data).then(intent => intent....)`, il est possible de faire `request.get(13).then(intent => intent....)`

Fix some bugs

---

packages/doctypes/src/BankAccount.js
packages/doctypes/src/BankTransaction.js

The logs and comments are clearer now. The log that said we were on a new vendor
was at the wrong place and led to false positives.

feat: Better logs

---

packages/cozy-app-publish/README.md

When using Travis, explicit the role of id_rsa_downcloud_myapp.enc file and when it can be moved.

Explicit usage of encrypted private key

---

packages/cozy-app-publish/lib/prepublish.js
packages/cozy-app-publish/test/__mocks__/prepublish-bad-value-options-hook.js
packages/cozy-app-publish/test/__mocks__/prepublish-missing-manifest-options-hook.js
packages/cozy-app-publish/test/__mocks__/prepublish-missing-options-hook.js
packages/cozy-app-publish/test/__snapshots__/prepublish.spec.js.snap
packages/cozy-app-publish/test/prepublish.spec.js

The main idea is to be clearer when an options like `appType` or `appSlug` is missing.
This PR adds a dedicated error message for attributes retrieved from manifest file.
Also it checks that the appType has the correct value (`webapp` or `konnector`).

Better options check

---

packages/commitlint-config/package.json
packages/cozy-device-helper/package.json
packages/doctypes/package.json
packages/flags/package.json
packages/interapp/package.json
packages/realtime/package.json

The auto fix can send Travis + Lerna into a loop if some files are
commited to master with linting errors. Since the --fix does not warn
that there are linting errors, Travis will report green even in the
Pull request : linting errors can be integrated into
master without any warning.
Since --fix changes files, Lerna thinks something has changed and
publishes the application. The publishing of the application will
result in a commit, which will in turn launch a new Travis job
and the whole story starts again.

chore: Remove eslint auto fix

---

packages/doctypes/src/Document.js
packages/doctypes/src/Document.spec.js

Do not try to create an undefined document when updateAll is
called with an empty list.

fix: No update all if no documents

---

packages/cozy-app-publish/lib/hooks/pre/downcloud.js

For stable and beta version, buildCommit is not defined and the folder name was something like `x.x.x-undefined`.

Avoid `undefined` in archive folder

---

packages/flags/src/flag.js

We were returning `JSON.stringify(null)`, which returns a string. So if the flag didn't exist, we get a truthy value instead of a falsy one.
Now we return `null` :+1:

fix(flags): Return null if flag doesn't exist

---

packages/renovate-config-cozy-app/package.json

Once published to npm, this package should allow all our apps to use or at least extend the same renovate configuration.
[Here are the docs](https://renovatebot.com/docs/config-presets/) about how this works.
The configuration itself is very basic right now — it just prevents travis to be swamped during working hours. We'll be happy to consider more individual rules once the first version is published.

feat: Create cozy-app renovate config

---

packages/cozy-release/package.json

Without that the `cozy-release` command/binary won't be available for usage after installing the module

Define missing cozy-release binary

---

packages/cozy-app-publish/cozy-app-publish.js
packages/cozy-app-publish/lib/publish.js
packages/cozy-app-publish/lib/travis.js
packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
packages/cozy-app-publish/test/travis.spec.js

Travis is not failing when an error occurs during prepublish, publish, or postpublish. It causes "false positive" build, where the registry publication can fail but Travis is still green and a message is sent to Mattermost.
This PR prevents this behaviour.

Make Travis fail on publish, prepublish or postpublish error

---

packages/cozy-release/scripts/cozy-release.sh

Travis shell throws errors if we use `shift` without remaining arguments.
This PR check before using it.

Use shift in cozy-release only if remaining args

---

.travis.yml

When lerna publish Travis launch a new build so it can loop. This PR add `[skip ci]` to remove it.

fix: After publish don't execute ci

---

packages/cozy-release/scripts/cozy-release.sh

If no remote is passed as argument, cozy-release now tries to detects wich remote is the cozy one.
If no cozy remote is found, cozy-release just use origin.

cozy-release: Detect cozy remote

---

packages/cozy-release/scripts/cozy-release.sh

Without that, Travis CI will use the `dash` shell from ubuntu. 
So we can force using `bash` with this shebang

Update shebang to use bash

---

packages/cozy-doctypes/src/BankTransaction.js

This log used too many params, resulting in a `Could not parse stdout as JSON` error in the log files.

fix(doctypes): Format log properly

---

packages/cozy-release/scripts/cozy-release.sh

Pulling avoids push errors and make sure everything is up to date before tagging a new beta or stable version.

Git pull before tagging beta or stable version

---

packages/cozy-release/scripts/cozy-release.sh

Syntax was wrong. I did not detect this because I was using the globally installed yarn version. Sorry about that.

cozy-release: Fix git pull

---

packages/cozy-realtime/README.md
packages/cozy-realtime/src/index.js

Following #21
We have been dealing with [an unpleasant case in the cozy-bar where we had to build a fake URL to pass it as a config parameter](https://github.com/cozy/cozy-bar/commit/eba3eb2420ee87c8eaa54102a0452f851f6d2d46#diff-73642d587163f2eb4d72f0fa6ebfba02R179).
In this PR, we allow two new config parameters : `domain` and `secure`.
`domain` can be directly extracted from the data set of the `[role=application]` element in every app.
`secure` is set to `true` by default, but can be overriden at realtime initialization with something like
```js
realtime.subcribeAll({
domain: data.cozyDomain,
secure: __SSL__,
token: data.cozyToken
},
// [...]
)
```

Add domain an secure config parameters

---

packages/cozy-doctypes/src/BankTransaction.js
packages/cozy-doctypes/src/BankTransaction.spec.js
packages/cozy-doctypes/src/utils/BankingReconciliator.js
packages/cozy-doctypes/src/utils/BankingReconciliator.spec.js
packages/cozy-doctypes/src/utils/__snapshots__/BankingReconciliator.spec.js.snap

We had a duplicates bug in some specific cases. We decided to use the same algorithm whichever the transactions are fetched by a « old » connector, or a newly configured one.
So now we use the algorithm based on the date everytime:
* We get the date of the most recent transaction already saved
* We create all the newly fetched transactions that are after this date
* For each newly fetched transaction that is before this date, we check if some of them don't exist in the DB yet (by comparing their `{ amount, originalLabel, date }` triplet)
This way, we don't need to know if the connector is a new one or not, we always do the same work.
Before merging this PR, I think we must try it on a real world case, even if I added some unit test to add more confidence.

Update BankTransaction::reconciliate algorithm

---

packages/commitlint-config-cozy/index.js
packages/commitlint-config-cozy/index.spec.js

This issue brought up in a meeting recently, but I'm formally proposing we raise the limit for commit message titles to 72 chars instead of 50.
From what I can see (in [this article](https://chris.beams.io/posts/git-commit/#limit-50) and in various git tools):
- 50 character is the desired length
- 72 is the hard limit after which things gets truncated
Since `commitlint` is rejecting commits that don't match the configuration it's enforcing a *hard* limit, and should be 72 and not 50. But we as humans should still try to shoot for 50.
Does that sound ok? Especially pinging people who mentioned this issue @CPatchane @kosssi @enguerran 
edit: Don't mind Travis, I'll update the tests if/when we get consensus on this.

[commitlint] Raise max commit message length

---

packages/cozy-doctypes/src/BankTransaction.js
packages/cozy-doctypes/src/BankTransaction.spec.js
packages/cozy-doctypes/src/utils/BankingReconciliator.js

Add `onCatchupNonExistentTransaction`, `onCatchupMoreNew` and `onCatchupLessNew` so we can track the following events in Piwik in the Linxo connector:
* We fetch a transaction that is before the date split, but it doesn't exist in the Cozy
* We fetch a transaction that is before the date split, but for the same `{ amount, date, label }` triplet we have less transactions in the cozy than we have fetched
* We fetch a transaction that is before the date split, but for the same `{ amount, date, label }` triplet we have more transactions in the cozy than we have fetched

Add new options to Transaction::reconciliate

---

packages/cozy-release/scripts/cozy-release.sh

If the current version has already been released (old workflow or error),
cozy-release now ask if it should bump master first.
`--auto-bump` option avoid prompt when the current master version has already
been released as stable, and bump it automatically before starting the
release. (So the version will be bumped before AND after the creation of
the release branch.

Add check for  existing stable version before starting new release

---

packages/cozy-release/scripts/cozy-release.sh

--no-confirm option allows to bypass prompt by automatically confirming actions.
It should be use with care, in scripting context for example.

Add --yes option

---

packages/cozy-doctypes/src/BankTransaction.js
packages/cozy-doctypes/src/BankTransaction.spec.js

The identifier was made using `originalLabel` which doesn't exist.

fix(doctypes): Identifier use originalBankLabel

---

packages/cozy-release/scripts/cozy-release.sh

A push for master was missing in the end release process.

Add missing push in `end` command

---

packages/eslint-config-cozy-app/react.js

Get rid of the `Warning: React version not specified in eslint-plugin-react settings` message

[eslint-config-cozy-app] Use latest react version

---

packages/cozy-doctypes/src/BankTransaction.js

This way transactions are effectively updated by `createOrUpdate` when their account is updated.

feat(doctypes): Add account to Transaction checkedAttributes

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

The fact that Document is using a global variable introduces subtle bugs when used concurrently (it can be re-registered behind your back). By not allowing it to be re-registered, we make it obvious that it is not possible to use it concurrently.

feat: Make it obvious that Document cannot be used concurrently

---

packages/cozy-doctypes/src/BankTransaction.js

There was two problems with these logs:
* The normal case (Linxo has 1 transaction and have 0) was logged as a warning. It caused a lot of unnecessary warning lines in the logs. It is now logged as debug.
* Sensitive data was logged. Now we only log the vendor ID of a transaction.

[doctypes] BankTransaction logs enhancements

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

Add support to add query parameters to the _changes route. It is useful for example to set the `limit` and `descending` parameters to only fetch the last changes.

feat: Support _changes query params

---

packages/cozy-flags/src/index.js

Since we use `require`, we need to get the `default` property of the module.

fix(flags): Add default property to require

---

packages/cozy-doctypes/src/Application.js
packages/cozy-doctypes/src/index.js

The goal of this PR is to make the Application doctype's schema available
from anywhere. We need it to instanciate CozyClient at least in Home,
Store, and the Bar.
The idea is to just write :
```js
import Application from 'cozy-doctypes/Application'
// ...
const client = new CozyClient({
schema: {
app: Application.schema
}
}
```

Add Application

---

packages/cozy-flags/src/index.js

Using `global` was not enough in all cases to detect if we are in a node process or not.

fix(flags): Node and browser detection

---

packages/cozy-device-helper/src/index.js
packages/cozy-device-helper/src/link.js

L'idée c'est de pouvoir assez facilement ouvrir des liens, depuis nos applications mobiles, dans safariViewController, ou dans le inAppBrowser (Android) ou dans le browser si rien n'est dispo (standalone). 
On va utiliser ça sur l'onboarding pour avoir une certaines cohérences car certains liens ouvrent actuellement Safari, d'autre SafariView etc. 
```
<Button 
onClick={() => {
nativeLinkOpen({ url })
}}
/>
```

feat: Add an nativeLinkOpen helper

---

packages/cozy-app-publish/lib/manual.js
packages/cozy-app-publish/lib/prepublish.js
packages/cozy-app-publish/lib/publish.js
packages/cozy-app-publish/test/__snapshots__/publish.spec.js.snap
packages/cozy-app-publish/test/prepublish.spec.js

When publishing on a non-existent space, the error was not handled.
Also, do sha sum handling in NodeJS.
I find the code in manual a bit hard to understand since it deals with prompt and also with the fetch logic and error handling.

Handle 404 from registry

---

packages/cozy-harvest-lib/.gitignore
packages/cozy-harvest-lib/.transifexrc.tpl
packages/cozy-harvest-lib/.tx/config
packages/cozy-harvest-lib/README.md
packages/cozy-harvest-lib/jest.config.js
packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

This PR add I18n handling in cozy-harvest-lib.
It use the cozy I18N wrapper to create a local scope around the AccountForm.
I18n phrases are updated with konnector manifest locales object.
The main <I18n /> wrapper is set directly into `index.js` file, to not interfer with unit tests and keep the component like AccountForm as pure as dumb as possible.

Harvest: Handle I18n

---

packages/cozy-flags/README.md
packages/cozy-flags/src/index.js

If some flags were enabled at build time, enable them as soon as `cozy-flags` is imported.

feat(flags): Handle flags enabled at build time

---

packages/cozy-app-publish/lib/publish.js

This is causing JS error `body already used for`

Don't read publish response stream twice

---

packages/cozy-harvest-lib/src/Manifest.js
packages/cozy-harvest-lib/src/Manifest.spec.js
packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

We cannot read encrypted value in apps so we display a dedicated
placeholder to show that the field has a value.

Harvest: Use placeholders when editing encrypted value

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/test/components/AccountForm.spec.js

We aim to limit the logic related to account into accountForm, and deal only with values.

Use initialValues prop instead of account

---

packages/cozy-app-publish/lib/prepublish.js
packages/cozy-app-publish/package.json
packages/cozy-app-publish/test/prepublish.spec.js
yarn.lock

NodeJS standard `http` and `https` do not follow redirects. GitHub archive urls are redirections. We were shasumming the redirection page and not the archive. I changed to use `request` which automatically follow redirects (like a good boy 🐶 ).
For info `curl` does not follow redirects by default, it needs the `-L` option.

fix: Shasum was not following redirects

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/helpers/fields.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
packages/cozy-harvest-lib/test/helpers/fields.spec.js

The goal is to avoid passing an empty string as value, as it make React-Select show no value selected.

Harvest: Sanitize select props

---

packages/babel-preset-cozy-app/index.js

Fix #215 
~~We wasn't previously transforming the polyfills with [`useBuiltIns`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) so we was required all the core-js I think, now it will be better handled by requiring only the ones needed for targeted browsers.~~
Edit: Only update the supported browsers list for now

feat(babel): Update supported browsers list for Cozy platform

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

Automatically add `cozyMetadata.createdByApp` when `createOrUpdate`ing a `Document`. The property is added if it doesn't exist and if the `Document` has a static property `createdByApp`.
I had to relocate the `createOrUpdate` function as a method of `Document` otherwise we would lose the reference to static properties like `createdByApp` between the call to `createOrUpdate` and the call to `Document::addCozyMetadata`.

feat(Document): Automatically add cozyMetadata.createdByApp

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

When a field having role set to `identifier` has an initial value, it cannot be editable.

Harvest: Disable identifier with initial value

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/helpers/fields.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
packages/cozy-harvest-lib/test/helpers/fields.spec.js

Previous pattern was too ambiguous and was working almost by chance.
With this PR, every AccountField is now aware of its own encryption and if it
has an initial value.
Mapping field name with its encrypted name is done one level above, into AccountFields.

Harvest: Improve placeholder for encrypted fields mechanism

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

Almost everything is in the title.
The idead is to avoid overflow.
BEFORE
AFTER

Harvest: Use SelectBox container prop to avoid overflow

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

When registering the client on Document, we set it on a global variable. But in banks we have a case in which we register the client somewhere, then want to access it in a class that extends `Document`. Currently we can't to that since we don't have access to the global variable. With this PR, the client is also registered on the `Document` class, so we can access it via `this.cozyClient` in a subclass.

feat(doctypes): Register client statically on Document

---

packages/cozy-doctypes/src/banking/BankTransaction.js
packages/cozy-doctypes/src/banking/BankTransaction.spec.js

Previously, the reconciliation mechanism would send stats back to the konnector and the latter would send it to piwik. Here we change it so that the reconciliation process can directly send
the piwik events.
Sending directly the event from the reconciliation mechanism decouples the konnector from the reconciliation mechanism and allows for more flexibility should we want to send more/different
events.

Bank{Reconciliator,Transaction} accept a trackEvent option

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/test/components/OAuthForm.spec.js

We should not show the Connect button for an existing OAuth account.

Harvest: Do not show OAuth button in edit form

---

packages/babel-preset-cozy-app/index.js

We need to target Android 5 and iOS 10 for our mobile apps. 
- I have to target Android 4.4 since Android 5 doesn't exist because Webview and OS version are different since Android 5.
- I didn't find any query targeting Android 5 with a very old browser (ie no updated), we can consider targeting Samsung browser since it should follow Android Browser but I'm not sure this is the right way to do.
- I changed to `3 last majors version of iOS` because I think `2` is pretty dangerous specially when a new iOS version is released.

fix: Add Android 5 and iOS 10

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

Some previous locales for field labels are now out of cozy-harvest-lib scope.
This PR got them back, identified as legacy, until the manifest of
concerned konnectors evolves.

Harvest: Handle legacy locales for field label

---

packages/cozy-doctypes/src/banking/matching-transactions.js
packages/cozy-doctypes/src/banking/matching-transactions.spec.js

Scoring should work even if there is not originalBankLabel.

fix: Defensive programming

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx

`branchName` is still used by Bank konnectors

Handle legacy locale label

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/test/components/OAuthForm.spec.js

The previous conditional property, `oauth` was actually provided from the konnector.
AccountForm should now be called this way:
```
<AccountForm initialValues={account.auth || account.oauth} />
```

Fix OAuth form condition for button display

---

packages/cozy-doctypes/README.md

A contributor wanted to use this class, but was a bit lost because no documentation existed. This intends to fix this situation.

docs: Add docs about Document class

---

packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/test/connections/accounts.spec.js

`client.get()` was not working and never returning aggregator account,
making any account creation fail.

Harvest: Correct call to get aggregator account

---

packages/cozy-harvest-lib/src/connections/triggers.js
packages/cozy-harvest-lib/test/connections/triggers.spec.js

Promise was resolved on first job update, even if job
state was not done or errored. Handlers were triggered too early.

Harvest: Fix job promise fullfilment

---

packages/cozy-app-publish/lib/travis.js
packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap

We have to use the short commit otherwise the dev version is too long.

fix: Use short commit for travis version

---

packages/cozy-harvest-lib/src/connections/triggers.js
packages/cozy-harvest-lib/test/connections/triggers.spec.js

The first goal of this PR was to improve tests relying on timeout
and execution time.
But (new Date()).getTime() was not accurate enough and was sometimes
causing errored elapsed time (99ms instead of 100ms), and was
making the whole test fail.
After a try with `process.hrtime()`, I eventually realized that
dealing with timeout and elapsed time was absolutely not the
right solution, as often when there is a `setTimeout` implied.
So I just rewrote the tests with expected returned job and
it now works much better. It also lead me to detect a flaw
in the implementation : only the job passed as argument was
returned, never the one updated from realtime.

Harvest: Better tests with a fix

---

packages/cozy-harvest-lib/src/Manifest.js
packages/cozy-harvest-lib/src/Manifest.spec.js
packages/cozy-harvest-lib/src/components/AccountCreator.jsx
packages/cozy-harvest-lib/src/components/AccountEditor.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/connections/files.js
packages/cozy-harvest-lib/src/connections/permissions.js
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/helpers/cron.js
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/helpers/slug.js
packages/cozy-harvest-lib/src/helpers/triggers.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
packages/cozy-harvest-lib/test/connections/files.spec.js
packages/cozy-harvest-lib/test/connections/permission.spec.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js
packages/cozy-harvest-lib/test/helpers/cron.spec.js
packages/cozy-harvest-lib/test/helpers/konnectors.spec.js
packages/cozy-harvest-lib/test/helpers/slug.spec.js
packages/cozy-harvest-lib/test/helpers/triggers.spec.js

It appeared that trigger still need a `message.folder_to_save` property.
This PR fixes this, but it comes with the full package:
* Folder fetching and/or creation
* Permission on folder for konnector
* Reference to files in konnector
The goal is to be iso with Cozy-Home, and it actually fixes
the issue we encountered.
I tried to make atomic commits, I did not start developing
with the idea to make so much commits. But good news they
are all pretty tiny and contains a lot of tests.

Harvest: Force folder_to_save for trigger

---

packages/cozy-app-publish/cozy-app-publish.js
packages/cozy-app-publish/lib/confirm.js
packages/cozy-app-publish/lib/manual.js
packages/cozy-app-publish/test/manual.spec.js

On Jenkins, we must not have a confirmation prompt.
- Refactored the prompt outside the main `manual` function.
Convert the prompt based callback to Promise based confirmation
prompt.
- Bypass the prompt if --yes is provided via the CLI flags

feat: --yes flag for cozy-app-publish manual

---

packages/cozy-harvest-lib/src/helpers/daytime.js
packages/cozy-harvest-lib/test/helpers/daytime.spec.js

Banking konnectors are declaring float values in their time_interval
attribute.

Harvest: allow float in randomDayTime() helper

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js
packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/slug-account.js

In the banking connector, we send events to Matomo if we detect
accounts with incoherent data. The `hasIncoherentCreatedByApp`
method was previously there, but it is better if it is shared.

feat: Add method to detect incoherent createdByApp

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

Automatically add the slug of the application updating the
document when creating/updating the document.
Contrary to the docs [here](https://github.com/cozy/cozy-doctypes/#document-metadata),
`updatedByApps` is not a list but an object with slug -> update date. We think it
would be more useful and it's clearer than the convention "last app updating is first".
If this PR is accepted, I will update the docs there.
```
{
cozyMetadata: {
updatedByApps: {
boursorama: new Date()
}
}
}
```
EDIT: Fixed example

feat: Add updatedByApps

---

packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js
packages/cozy-doctypes/src/banking/slug-account.js
packages/cozy-doctypes/src/banking/slug-account.spec.js

On my local cozy, I had some accounts without institutionLabel but I had not run into this case "into the wild".

fix: Support unexisting institutionLabel

---

packages/cozy-harvest-lib/src/components/AccountFormError.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

After a creation error, re-submitting the form was
throwing an error, because the trigger in TriggerManager
was not saved in state. This PR solves this point in
the second commit.
Then it ensures that the trigger exists on update, in the
case of an error between account creation and trigger
creation.
At last, it merge `handleAccountCreationSuccess` and
`handleAccountUpdateSucces` into a single one handler
as they are now identical.
**NB: This PR concern a logic part being still in `TriggerManager`, but which need to be extracted in a dedicated logic component (a Model for example).**

Harvest: Ensure trigger can be launched, even after creation error

---

packages/cozy-harvest-lib/src/helpers/konnectors.js

`Error.captureStackTrace()` is not available in all engines.
Firefox is throwing an error when calling this method.
More info: https://www.bennadel.com/blog/2828-creating-custom-error-objects-in-node-js-with-error-capturestacktrace.htm

Harvest: Prevent undefined Error.captureStackTrace()

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
packages/cozy-harvest-lib/test/connections/accounts.spec.js

This PR cleans tests and fix a few typos to avoid warning in tests.

Harvest: avoid warnings in tests

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx

~~The underlying component in our SelectBox (ReactSelect) does
not allow handler for KeyUp events. The cheapest way to handle
them is to wrap our SelectBox into a div element to capture
keyUp events.~~
Move the onKeyUp handler to the AccountFields component main container.
EDIT:
Why keyUp ? To prevent browser for filling password in Cozy-Home, the "best" solution we found so far is to:
* Set the password autocomplete property to `new-password`.
* Do not provide a form wrapper and use a div isntead.
Using a div is forcing us to implement some form native behaviour, [like submitting on `Enter`](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/components/AccountForm.jsx#L209) key, and for this we need to handle the `onKeyUp` event.
We are aware that replacing a …

Harvest: Handle onKeyUp on whole AccountFields component

---

packages/cozy-interapp/src/intents.spec.js
packages/cozy-interapp/src/request.js
packages/cozy-interapp/src/request.spec.js

To remove warning:
> Using cozyClient.client is deprecated, please use cozyClient.stackClient.
[Cozy Client code](https://github.com/cozy/cozy-client/blob/e8b03cd8005470f5b267b8191666a12bd273effb/packages/cozy-client/src/CozyClient.js#L682-L688)

feat: Use stackClient to not print deprecated warning

---

packages/babel-preset-cozy-app/README.md
packages/babel-preset-cozy-app/index.js
packages/babel-preset-cozy-app/package.json
packages/babel-preset-cozy-app/validate.js

In this PR, more flexibility is given to users of babel-preset-cozy-app to configure presets and plugins that babel-preset-cozy-apps uses.
To use webpack tree shaking features, we need to have our modules shipped on npm using es6 imports.
For `babel-preset-env` not to transpile import/exports, we have to pass `modules: false` https://babeljs.io/docs/en/babel-preset-env#modules.
`babel-preset-env` was not configurable when using `babel-preset-cozy-app` so this PR adds an option `presetEnv` to the options of `babel-preset-cozy-app`.
I wanted to experiment with `helpers: true` and cozy-ui and babel-preset-cozy-app did not give enough flexibility on the options pased. `transformRuntime` options are passed directly to `transform-runtime` plugin (they are merged with the defaults `{ …

Babel preset app options for presets and plugins

---

packages/cozy-harvest-lib/src/components/AccountForm.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/triggers.js
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
packages/cozy-harvest-lib/test/helpers/triggers.spec.js

Errors were not shown in Cozy-Home when editing.
This PR: handle directly trigger error from trigger prop.
`error` is still passed to `<AccountForm />`.
As when editing only login errors are shown on `<AccountForm />`, Cozy-Home need to pass a prop `showError` to `<TriggerManager />` to indicate if errors have to be shown (See https://github.com/cozy/cozy-home/pull/1151). Login errors are bypassing this props and are always shown.

Harvest: Show error when editing

---

packages/cozy-app-publish/cozy-app-publish.js
packages/cozy-app-publish/lib/manual.js
packages/cozy-app-publish/lib/tags.js
packages/cozy-app-publish/lib/tags.spec.js
packages/cozy-app-publish/lib/travis.js
packages/cozy-app-publish/package.json
packages/cozy-app-publish/test/__snapshots__/manual.spec.js.snap
packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
packages/cozy-app-publish/test/manual.spec.js
packages/cozy-app-publish/test/travis.spec.js

Since we have to be able to publish beta versions of customized
banks, from the customization repository, without publishing
other components, we introduce here the notion of prefix for
tags.
When publishing from a monorepo, instead of tagging only
with a version `1.0.0`, you tag with a prefix `cozy-banks/1.0.0`
and then you tell cozy-app-publish to only consider tags
with this prefix `cozy-app-publish --tag-prefix cozy-banks`.

feat: Support tag prefix

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

`TriggerManager.ensureTrigger()` was always creating a new trigger on account update, causing duplication on Cozy-Home.

Harvest: Use existing trigger and avoir trigger duplication

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

When editing an Account in Cozy-Home, the account form is still displayed without any other change in UI, so in this case we do not need need to provide any success callback.
Following https://github.com/cozy/cozy-home/pull/1171

Harvest: Success callbacks may be undefined

---

packages/cozy-app-publish/package.json

Lodash is needed by cozy-app-publish

fix: Add lodash as dependency

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/helpers/manifest.js

A quick refactoring to make AccountField lighter and store logic about predefined labels into manifest helper.

Harvest: Split concern between AccountField and manifest

---

packages/babel-preset-cozy-app/package.json

Since this file is imported by `index.js` but not published, we get the
following error when we use it in apps:
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module './validate'
```

fix(babel-preset-cozy-app): Publish validate.js file

---

packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/test/helpers/konnectors.spec.js
packages/cozy-harvest-lib/test/index.spec.js

To facilitate error detection on konnector triggers, KonnectorJobError is now exported by the module.
It also have a new method `isUserError()` to detect user errors like in Cozy-Home.
Example:
```js
const error = new KonnectorJobError('LOGIN_FAILED')
console.log(error.isUserError())
// true
```

Harvest: detect user errors

---

packages/cozy-app-publish/lib/hooks/pre/helpers.js
packages/cozy-app-publish/lib/hooks/pre/helpers.spec.js

Use the space name in the remote upload path to avoid overwriting files
when publishing an app with the same version and same slug to two
different spaces.
Currently, if I publish "app" v1.2.3 without specifying a space name,
it's uploaded to `www-upload/app/1.2.3/app.tar.gz`. Then if I publish
"app" v1.2.3 and I specify the space name "space", it's uploaded to the
same directory on downcloud. So it overwrites "app" v1.2.3 archive for
the default registry space.
With this commit, if a space name is provided, it's used to determine
the directory in which the archive should be uploaded. So I will upload
to `www-upload/app/1.2.3/app.tar.gz` and
`www-upload/space/app/1.2.3/app.tar.gz`.

feat(app-publish/downcloud): Use space name in remote path

---

packages/cozy-device-helper/src/deeplink.js
packages/cozy-device-helper/src/index.js

I don't know how to test this part since it's already a bit hacky by itself. 
This code is currently served by the stack, but we plan to use it also in the bar.

feat: Add an utility to open or redirect for a deeplink

---

packages/cozy-interapp/src/index.js

As said in the readme, we should be able to do `import Intents from 'cozy-interapp'`

Interapp: Export correctly as default module

---

packages/cozy-harvest-lib/src/connections/triggers.js

It seems that recent updates on CozyClient uri broke realtime in Cozy-Harvest.

Initialize realtime with uri from CozyClient

---

packages/cozy-mjml/src/components/MJDefaults.js
packages/cozy-mjml/test/__snapshots__/components.spec.js.snap

Added same `highlight` & `primary-link` CSS classes for HTML elements.
It's already defined by `mj-class` tags but you can't use those with HTML elements so you need css classes for that and you can't use those css classes for MJML elements as the DOM doesn't fit.
Not very happy about this duplication but… I can't find something else.

feat(mjml): Add css classes for HTML elements

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/connections/triggers.js
yarn.lock

Harvest was using an old version of realtime that was make all apps that use Harvest using this old realtime package

Use the correct realtime version

---

packages/cozy-release/README.md

Add some info about deps, how to and some warnings about stuff I had to do when I used cozy-release for `cozy-contacts`.
It may be nice to have a way to create releases for apps that are still in beta (`0.x.y`, see the warning about patch).

docs: Add some docs to cozy-release's README

---

packages/cozy-device-helper/src/deeplink.js

It seems that at least iOS 12 2 has a new behavior while redirecting to a not supported custom scheme :(. the native popup seems blocker now.

fix(cozy-device-helper): Don't deeplink on iOS 12_2 or 12_3

---

packages/cozy-realtime/src/index.js

Si le socket est fermée pour une raison ou une autre, l'application qui appelle le realtime ne peut pas être au courant. Et donc il est possible qu'elle appelle le unsubsribe alors que le socket est déjà fermé. Et ça va faire null.unsubscribe() 
C'est un fix temporaire parce que @gregorylegarec est en train de ré-écrire l'ensemble du code de ce projet ;)

fix(cozy-realtime): Imperfect fix for unsubscribe

---

packages/cozy-mjml/src/components/MJFooter.js

The URL object is available without any requires only in node 9+.

fix: Fix compatibility with node 8

---

packages/cozy-mjml/src/index.js

In our scripts to launch node via nsjail, the COZY_JOB_ID env variable is not forwarded to node. Let's use COZY_URL instead.

fix: Fix cozy-mjml with nsjail

---

packages/cozy-doctypes/src/contacts/Contact.js
packages/cozy-doctypes/src/contacts/Group.js

trashed prop is not required for contacts and groups

fix(cozy-doctypes): Remove isRequired for trashed props

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js

Since the konnector and Harvest use the account state to communicate about the connector running process, it's better to be sure to reset it each time before running a konnector, so let's Harvest doing it.

[Harvest] Reset the account state before running the konnector

---

packages/cozy-authentication/examples/index.jsx
packages/cozy-authentication/package.json
packages/cozy-authentication/src/Authentication.jsx
packages/cozy-authentication/src/Authentication.spec.jsx
packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/Revoked.jsx
packages/cozy-authentication/src/locales/fr.json
packages/cozy-authentication/src/withLocales.jsx
yarn.lock

- MobileRouter brings its own translation strings so that the application
does not have to copy/paste and maintain translation strings that are not
part of the application
- The example has buttons to change the language
- Fixed missing translation strings in French
Only English and French translation strings are available at the moment. This will change when we plug the transifex project here.

[authentication] feat: Translation context wraps MobileRouter

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
yarn.lock

This PR change how the account form reacts to keyboard key events on mobile.
When Enter key is pressed, the default behaviour is to submit the form.
Now on mobile, it focus the next input, and submit the form is no more input can be focused.
Managing focus could be made in different way, as the AccountForm component structure is as follow:
```
AccountForm
|- AccountFields
 |- AccountField
|- AccountField
```
My firt guess was to implement a `focus()` method directly in `AccountField` component and manage to call it on expected AccountField. But this solution implied to use many refs and was not feeling really compatible with the React philosophy. It was also implying many callbacks, and dealing with `onFocus` events both on Input Fields and SelectBoxes.
So I eventually ended querying the …

Harvest: Improve keyboard nav on mobile

---

packages/cozy-authentication/src/utils/onboarding.js
packages/cozy-authentication/src/utils/onboarding.spec.js

Now the test checks that the client is correctly configured after
doOnboardingLogin

fix: doOnboardingLogin called client.login with url instead of uri

---

packages/cozy-authentication/package.json
packages/cozy-authentication/src/Authentication.jsx
packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/steps/ButtonLinkRegistration.jsx
yarn.lock

MobileRouter and Authentication take their components from
a defaultProps for easy overriding.
Ex:
```
import { DumbAuthentication } from 'cozy-authentication/dist/Authentication'
DumbAuthentication.defaultProps.components.SelectServer = CustomSelectServer
```

feat: Override components

---

packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/MobileRouter.spec.jsx

To differentiate between a normal login and an onboarding login we can check the presence of two query arguments:
- cozy_url
- code
Both of them should only be present while onboarding. Unfortunately, code is also present due to presumably a bug of the stack when through universal links, we have a redirect uri. Thus cozy_url is the only reliable query arg for now. The bug of the stack seem to be already fixed in staging.
This bug was introduced when refactoring the authentication code, it is not present in drive.

fix: Do not try to onboarding if required query argument are absent

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js

This helper is used only in Banks at the moment, but this way it's
reusable anywhere and it is easier to find it than in a `helpers` file
in Banks.
The banking konnector now saves the date on which BI updated the account
on its side in `metadata.updatedAt`. Since this is usually a more accurate
data that than our `cozyMetadata.updatedAt`, we now use it if it exists,
then fallback on `cozyMetadata.updatedAt` if it does not.

feat(doctypes): Add getUpdatedAt helper to BankAccount

---

packages/cozy-flags/src/index.js
packages/cozy-flags/src/index.spec.js

Exposing FlagSwitcher on node context was causing an error in Node
context because it's importing the flags browser implementation and
`localStorage` doesn't exist in this context.
Fixes #402 
This was making the banks' service crash.

fix: Expose FlagSwitcher only in browser context

---

packages/cozy-doctypes/src/contacts/Contact.js

Some proptypes were not right in Contact model: 
- `me` should not be required since it is not present on all contacts (or we should add it to the migration script)
- unfortunately `{...}` is not a valid propType format, we have to use `PropTypes.shape({...})` :cry:

Fix PropTypes in Contact model

---

packages/cozy-authentication/Procfile
packages/cozy-authentication/examples/index.jsx
packages/cozy-authentication/package.json
packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/MobileRouter.spec.jsx
packages/cozy-authentication/src/locales/fr.json
yarn.lock

When the MobileRouter mounts, it tries to reconnect, based on information it has saved in localStorage.
`client.login` being async (since it instantiates the links, and some of them can be asynced, for example PouchLink), it can take a while to `login()` (hopefully not so much).
In the past, while logging in, we would show the `AuthenticationView`. This was a problem since the user had already logged in, and it is not expected to see a login form when you have already logged in.
Now, we show a component showing a spinner. It can be customized via the LogInComponent prop.
Another problem was a flash of AuthenticationView since the `tryToReconnect` is done after mouting. To mitigate the problem, the component shows null while it has not tried to reconnect yet. It will be during a very short …

feat: Show LogIn view while logging in

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/models/KonnectorJob.js
packages/cozy-harvest-lib/src/models/konnector/KonnectorAccountWatcher.js

When the konnector handle the new `LOGIN_SUCCESS` feature, it will set the state `HANDLE_LOGIN_SUCCESS_STATE ` to disable the login timeout in Harvest

Harvest: Handle login success state to disable login success timeout

---

packages/cozy-mjml/src/components/MJFooter.js
packages/cozy-mjml/src/components/MJHeader.js

Cozy-mjml will default to the english locale, without a warning, when using a locale other fr or en.

feat(mjml): Avoid warnings on es,ja,pl... locales

---

packages/cozy-harvest-lib/src/components/TwoFAForm/index.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.jsx

To quickly avoid users being blocked by closing the 2FA modal (we don't have the resume feature yet)

Harvest: Make 2FA modals not closeable

---

packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/models/KonnectorJob.js
packages/cozy-harvest-lib/src/models/konnector/KonnectorAccountWatcher.js
packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js
yarn.lock

We will have to unsubscribe at term to handle correctly not used Realtime instances, but for now this unsubscribeAll just close the Job real-time instance and makes it unusable

fix(harvest): Remove unsubscribingAll for realtime

---

packages/cozy-harvest-lib/src/components/TwoFAModal.jsx

~~Returning false in a form submit function allow to disable refreshing the page on submitting with enter key~~
Edit: Finally, after testing, a `e.preventDefault` is doing the job

Harvest: Prevent refresh on 2FA submit with enter

---

packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js

We used to have camelCase in documents properties

Harvest: s/twofa_code/twoFACode

---

packages/cozy-harvest-lib/src/index.js

The previous version was not working on React, only on preact

fix: :ambulance: Use static attribute for withLocales contextTypes

---

packages/cozy-doctypes/package.json
packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js
packages/cozy-doctypes/src/banking/BalanceHistory.spec.js
packages/cozy-doctypes/src/testUtils.js
yarn.lock

This is a first step to allow users to choose between `cozy-client` and `cozy-client-js` when they register a client for their models.
~~This is still at draft state since I would like to do the following before merge:~~
- ~~rename `  newCozyClient` :arrow_right: `cozyClient` and `cozyClient` :arrow_right: `cozyClientJS` in `testUtils.js`~~
- ~~add tests for methods that use "the `stackClient` trick" (`getAll`, `fetchChanges`, `fetchAll`, `updateAll`). To do this, I need to be able to mock the stack client that `CozyClient` uses, it may not be easy.~~
- ~~we could also be more explicit in the methods names (e.g `_ccjs_getIndex` instead of `_getIndex` ?)~~

feat(cozy-doctypes): Allow Document to use a CozyClient

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

See discussion here: https://github.com/cozy/cozy-libs/pull/455#discussion_r287279803
We don't want `Document.dangerousUnregisterClient` method. Just set the `cozyClient` to `null` manually when we need to in the tests.

fix(cozy-doctypes): Remove Document.dangerousUnregisterClient method

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/hoc/withLocales.js
packages/cozy-harvest-lib/src/index.js
yarn.lock

This PR uses `withLocales` from Cozy-UI.
Default exports from components are now directly translated.
It will allow us to export HOC wrapping component with translated component.

Harvest: quick refactor for a better translation mechanism

---

packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/hoc/withKonnectorModal.jsx
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/src/locales/en.json

For now this modal just fetch the first account related to given konnector and then rely on TriggerManager, like it's done in Cozy-Home.
~~Blocked by https://github.com/cozy/cozy-libs/pull/467, both `KonnectorModal` and `withKonnectorModal` should be exported in index.js.~~
Replace both https://github.com/cozy/cozy-libs/pull/440 and https://github.com/cozy/cozy-libs/pull/461

Harvest: Add a konnector modal to edit existing accounts

---

packages/cozy-realtime/src/index.js
packages/cozy-realtime/src/index.spec.js

Intents / Bar etc..  use options.client for the CozyClient, it will be
easier to have the plugin system if all classes depending on the client
use the same attribute to initialize.
Fixes https://github.com/cozy/cozy-libs/pull/456

feat: Deprecate options.cozyClient, use options.client

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

Throw error during the process if not provided, and this prop is optional

Prevent undefined success callback

---

packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/test/components/KonnectorModal.spec.js

The trigger was not stored into the state to be used correctly by the component

[harvest]: Correctly set fetched trigger in state in KonnectorModal

---

packages/cozy-device-helper/src/cordova.js

Some of the helpers of AppLinker can be used in NodeJS environments (to build
emails for example). In nodeJS, window is absent from globals so I added a 
small check.

fix(device): Check if window in the globals

---

packages/cozy-harvest-lib/test/components/AccountField.spec.js

Testing child component avoid side effects on original AccountField component.

Harvest: Better pattern for propTypes override

---

lerna.json
package.json
yarn.lock

Lerna can create a GitHub release with all the changes of the release.
It can then be used by renovate in its PRs.

chore: Publish GitHub release with changes through lerna

---

packages/cozy-flags/bin/cozy-flags
packages/cozy-flags/package.json
packages/cozy-flags/src/flag-codemod.js

Automatically applies a flag.
- replaces instances of `flag(FLAG_NAME)` by true
- resolves resulting logical expressions, unary expressions and ternary expressions.
- remove unused imports
```bash
$ yarn add cozy-flags
$ cozy-flags apply 'reimbursement-tag' src/ducks
```
Input
```js
class Blabla {
render () {
return flag('reimbursement-tag') ? <NewStuff /> : <OldStuff />
}
}
flag('reimbursement-tag') ? 'ternary condition true': null
!flag('reimbursement-tag') ? false: 'ternary condition false'
if (flag('reimbursement-tag')) {
console.log('if reimbursement-tag')
} else if (removed) {
} else {
}
if (!flag('reimbursement-tag')) {
console.log('removed')
} else {
console.log('else reimbursement-tag')
}
!true
!false
true && "True and"
false && "False and"
false || "False or"
true || "True or" …
```

feat: Add codemod for flags accessible via "cozy-flags apply"

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/cards/DeleteAccountCard.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/cards/DeleteAccountCard.spec.js
packages/cozy-harvest-lib/test/components/cards/__snapshots__/DeleteAccountCard.spec.js.snap
yarn.lock

~~🚫 Blocked by https://github.com/cozy/cozy-ui/pull/1032~~
DeleteAccountCard is based on Cozy UI's `Card` component. It group title, description and `DeleteAccountButton` component.
It is used in `KonnectorModal`.
Web:
Mobile:

Harvest: Add DeleteAccountCard component

---

packages/cozy-mjml/webpack.config.js

Before, when building on Mac OS we got an error : 
```
Module not found: Error: Cannot resolve module 'aws-sdk' in my-project/app/node_modules/fsevents/node_modules/node-pre-gyp/lib
```
Latest solution: 
- We say that `fsevents` is an external : from the webpack doc : 
> Prevent bundling of certain imported packages and instead retrieve these external dependencies at runtime.
First solution : 
The solution : we simply tell to webpack to not handle require()
cozy-mjml `require(mjml)` and mjml use fsevents > node-pre-gyp.
See this comment for more information : https://github.com/mapbox/node-pre-gyp/issues/238#issuecomment-267889753

fix(cozy-mjml): Tell to webpack to not handle require

---

packages/cozy-authentication/src/steps/SelectServer.jsx
packages/playgrounds/README.md

If you don't have https enabled on your stack, you can set ALLOW_HTTP
to allow the connexion though http

docs(playground): Add note about http/https

---

packages/cozy-harvest-lib/src/components/Popup.jsx

When receiving OAuth message from popup, we need to ensure that the popup is the source of the message. Previously it was done by checking the origin of the popup location. But it cannot work in https, as the opener window cannot access to popup's `window.location`.
This PR relies instead on `messageEvent.source` to ensure that the message is coming from the OAuth popup.

fix(harvest): Rely on messageEvent.source for OAuth message 📝

---

packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx
packages/cozy-harvest-lib/test/components/DeleteAccountButton.spec.js

We get some warnings if we use onSuccess/onError to unmount the component or a parent of containing this component

fix(harvest): Call Delete button callbacks after setState

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx
packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/hoc/withLocales.js
packages/cozy-harvest-lib/src/helpers/proptypes.js

* Don't pass too many props to Button from DeleteAccountButton
* Expose mutations prop-types

Better proptypes handling to avoid React warnings

---

packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/test/helpers/oauth.spec.js

It's eventually convenient to know if an OAuth response has been handled.
For example in Cozy-Home we will be able to not render anything when an OAuth response is handled.

Harvest: Make HandleOAuthResponse return boolean value

---

packages/cozy-procedures/src/Procedure.jsx
packages/cozy-procedures/src/components/PersonalDataForm.jsx
packages/cozy-procedures/src/components/form/FieldTemplate.jsx
packages/cozy-procedures/src/components/form/InputAdapter.jsx
packages/cozy-procedures/src/components/form/InputWithUnit.jsx
packages/cozy-procedures/src/components/form/SelectBoxAdapter.jsx

Only the top level component needs to be wrapped in `withLocales`, everything else further down the tree only needs `translate`.

fix: Better procedure translations

---

packages/cozy-app-publish/cozy-app-publish.js
packages/cozy-app-publish/package.json
yarn.lock

Change CLI args parser from commander to argparse.
1. reacts better when an argument is not present. The most important is the fact that commander fails on 
```
./script --flag-accepting-argument --other-flag
```
And puts `"other-flag"` in `args['flag-accepting-argument']` which is IMHO a bad thing to do since in cases where shell variables are used for CLI args, the failure mode is confusing.
```
./script --token $REGISTRY_TOKEN --other-flag
```
Here, when using commander, if `REGISTRY_TOKEN` is not set, `--other-flag` is not set and `args.token == '--other-flag'` 😱 .
---
2. Previous help (more compact but less readable)
```
Usage: cozy-app-publish [options]
Options:
-V, --version                 output the version number
--token <editor-token>        Registry token matching the provided …
```

feat: Use argparse

---

packages/cozy-harvest-lib/src/components/KonnectorModal.jsx

When scrolling in Firefox, bottom margin was missing.
Before
After

Harvest: Improve margin bottom in KonnectorModal

---

packages/playgrounds/README.md

When I use `yarn start --global ALLOW_HTTP`, it does not work. Instead, I have to use : `yarn start --global __ALLOW_HTTP__`

docs(playgrounds): Fix ALLOW_HTTP example in README

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js
yarn.lock

In rare case the job was updated - with an error - just before realtime subscribing was done, so no update was sent throuhought realtime and KonnectorJobWatcher could never know that the job errored - or succeed.

Harvest: Fetch job right after subscribing realtime

---

packages/cozy-procedures/src/components/PersonalDataForm.jsx

The paddings will be set globally at some point, either by the host app, or in a wrapping component for all views, not sure which one yet.

(Procedures) fix: Remove custom margins on personnal data form

---

packages/cozy-app-publish/cozy-app-publish.js

After 0.16.0 version, options like --build-dir did not work anymore

fix(cozy-app-publish): Handle snake case cli options

---

packages/playgrounds/package.json

Since playground is an app, it has to come with : 
- cozy-ui
- cozy-client 
- react
As dep and not as devDep

fix: Playground dependencies

---

packages/cozy-app-publish/cozy-app-publish.js

And lodash.defaults only handle undefined values as "not defined values"
Fixes it by ignoring null values returned from argparse.
As an example, if you do not pass the --build-dir option, cozy-app-publish will not replace it with the default value (./build) which make cozy-app-publish fail for the connectors like [here](https://travis-ci.com/konnectors/edf/builds/116412016)

fix(cozy-app-publish): Argparse generates null default values

---

packages/cozy-procedures/src/components/FormFillingStatus.jsx
packages/cozy-procedures/src/components/FormFillingStatus.spec.jsx
packages/cozy-procedures/src/components/Overview.jsx
packages/cozy-procedures/src/components/PersonalDataForm.jsx
packages/cozy-procedures/src/components/__snapshots__/FormFillingStatus.spec.jsx.snap
packages/cozy-procedures/src/containers/FormFillingStatus.jsx
packages/cozy-procedures/src/containers/FormFillingStatus.spec.jsx
packages/cozy-procedures/src/containers/Overview.jsx
packages/cozy-procedures/src/locales/en.json
packages/cozy-procedures/src/locales/fr.json
packages/cozy-procedures/src/redux/personalDataSlice.js
packages/cozy-procedures/src/redux/personalDataSlice.spec.js

- add x/y status to the form `FormFillingStatus` component and container
- refactor selectors
- add tests for selectors
- use these selectors in `Overview`
`FormFillingStatus` is probably not a good name. I wanted to rename it to `FormStatus`, `FormFieldsStatus` or `FormCompletedStatus` but let's discuss it here before to do the changes.

Add status to form

---

packages/cozy-authentication/package.json
packages/cozy-authentication/src/steps/Welcome.jsx

If an app use the newest version of cozy-ui, with new icons, cozy-authentication does not work anymore.
- Update cozy-ui dependency in cozy-authentication
- Ran the codemod to update icons path

feat(auth): Update cozy-ui

---

packages/cozy-procedures/src/redux/personalDataSlice.js
packages/cozy-procedures/src/redux/personalDataSlice.spec.js

Don't fail if there is no contact with `me: true`.

(procedures) fix: Handle missing ME contact

---

packages/playgrounds/package.json

For example, we need this to be able to use cozy-ui's `Alerter` component without having strange preact errors ;-)

fix(playgrounds): Use react

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx

This simple proptype error developed under a preact Cozy-Home was making the whole cozy-bar to crash on React apps. This little error cost me a half day.
Ping @GoOz for information.

Harvest: Fix style prop to not make React crash

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/components/hoc/withKonnectorLocales.jsx
packages/cozy-harvest-lib/src/components/infos/TriggerErrorInfo.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap
packages/cozy-harvest-lib/test/components/infos/TriggerErrorInfo.spec.js
packages/cozy-harvest-lib/test/components/infos/__snapshots__/TriggerErrorInfo.spec.js.snap

To do so we need to:
* Extract Errors from AccountForm, don't show them in AccountForm from KonnectorModal
* Include directly error in KonnectorModal
* Listen to TriggerLauncher lifecycle to show/hide errors
Also, error is now shown at top of Konnector Modal.

Harvest: Do not show error on KonnectorModal when konnector job is running

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/test/components/AccountForm.spec.js

AccountForm was designed to enable the submit button after an error occured, to allow user to re-submit the form.
When editing an account, we do not need the form to be submittable when an error already exists.

Harvest: Disable button when editing if an error exists

---

packages/cozy-procedures/src/templates/creditApplicationTemplate.js

We don't need to check the mime or the class ATM.

fix: Remove conditions on mime and class ATM

---

packages/cozy-procedures/package.json

After build, I expect dist/ to be ready. I added --copy-files to the babel task.

fix: Copy files after build

---

packages/cozy-procedures/src/components/PersonalDataForm.jsx

There's a weird bug when we use the credit template outside of the render function.

(procedures) fix: Use credit template only in render

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/infos/TriggerErrorInfo.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

When extracting TriggerErrorInfo, margin bottom has been lost.

Harvest: Fix TriggerErrorInfo bottom margin

---

packages/cozy-procedures/package.json

We can't do `yarn build --watch` anymore because of the copy-files task that has been appended, but we need to keep the copy file. So this PR creates a dedicated watch command. In watch mode, copy files still needs to be done manually but I think that's ok.

(procedures) chore: Added a watch task

---

packages/cozy-procedures/src/components/Duration.jsx

Avoids being able to select 3.45 months.

(procedures) fix: Set the slider step value

---

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx

It appears that some file can have this prop missing (specially for the file coming from my ios simulator) . So if it's the case, we set the datetime to the current date

fix: A file can not have the lastModifiedInformation

---

packages/cozy-doctypes/src/File.js

This syntax is only usable since Node 12 (see https://node.green/#ESNEXT-candidate--stage-3--instance-class-fields). Since this is not required for the method to work here, we can just drop it and use a classic static method definition that works since Node 6 (see https://node.green/#ES2015-functions-class-static-methods).
More practically, this is causing the cozy-banks build to fail (see https://travis-ci.org/cozy/cozy-banks/builds/551944775?utm_source=github_status&utm_medium=notification).
Since the original and transpiled versions are shipped or npm (we have `main` and `browser` properties in the package.json), having it compatible with the widest range of node versions possible is the best. But I wonder if doing this is really necessary, since:
* If used in apps: the `browser` …

fix(cozy-doctypes): Don't use class property

---

packages/cozy-procedures/src/components/Duration.jsx

The Material-UI slider makes the page scrollable without overflow rule. There is currently no overflow utility class in Cozy UI.

fix: Overflow on slider view

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx

Once transpiled, accessing `Object.keys(Card.propTypes)` was throwing an error : Card.propTypes seems undefined.
As we don't really need to expose all Card props in LaunchTriggerCard, let's remove this stuff.

Harvest: Fix undefined proptypes when transpiled

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/cards/DeleteAccountCard.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

This PR make all the components in KonnectorModal up to date when a job is launched, succeed or throw error.
* AccountErrorInfo si displayed if TriggerManager get errors
* Both TriggerManager and LaunchTriggerCard are rendered as running when a job is launched
* DeleteAccountCard is disabled when a job is launched
As this PR is almost an UX quickfix, it will be followed by another one unifying prop names like running/submitting/isJobRunning and error/konnectorJobError

Harvest: Better synchronisation between components in KonnectorModal

---

packages/cozy-procedures/src/redux/personalDataSlice.js
packages/cozy-procedures/src/redux/personalDataSlice.spec.js

We had to fix the completed fields count in the overview, to do so, `we use an empty string as default value for all fields. 
Note that `getDefaultValue` has become not very useful but in case we want to handle array values someday, it will be. I can remove it for now if you prefer

Fix completed fields count (personal data)

---

packages/cozy-procedures/src/components/Overview.jsx

I use `.catch` to avoid to `await` the queries

Catch errors on file delete

---

packages/cozy-procedures/src/components/Duration.jsx

fix: Bigger margin for the duration slider

---

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx

ATM it's pretty confusing for an user to upload a file and set the metadata datetime to the lastEdited date. 
We should work again on this subject pretty soon

fix: Use now() to set the metadata datetime during upload

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

TriggerManager must retrieve trigger from state before refetching.

Harvest: When refetching, trigger must be retrieved from state

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx
packages/cozy-harvest-lib/src/helpers/fields.js
packages/cozy-harvest-lib/test/helpers/fields.spec.js

Some connectors don't keep the password, with this fix, if an account is already configured but encrypted fields are missing, we force the placeholder

Handle missing password for encrypted placeholder

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountFields.jsx

`initialValues` is an empty object if there is no account

Correctly check initialValues if exists

---

packages/cozy-procedures/src/components/documents/UploadInputLabel.jsx

Fastclick is causing issue on our iOS App. We need to use `needsclick` to tell fastclick to go away

fix: Use needclick on the fileinput label

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/scripts/check-locales.sh

Reused the script from https://github.com/cozy/cozy-home/pull/1076.
This PR adds a locales check after a tx pull.
The build will fail if locales files do not match.
It will prevent releases with missing fr translations.

Harvest: Check after tx pull ☑

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js
packages/cozy-doctypes/src/__snapshots__/Document.spec.js.snap

While implementing a new service in banks, I wanted to use models with the new cozy-client, and the implementation of this method was missing.
Other missing methods may come in next PRs.

feat(cozy-doctypes): Implement Document::queryAll with cozy-client

---

packages/cozy-procedures/src/Procedure.jsx
packages/cozy-procedures/src/components/Documents.jsx
packages/cozy-procedures/src/components/documents/DocumentHolder.jsx
packages/cozy-procedures/src/components/documents/DocumentsGroup.jsx
packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx
packages/cozy-procedures/src/components/documents/LoadingDocumentHolder.jsx
packages/cozy-procedures/src/containers/DocumentsDataForm.jsx
packages/cozy-procedures/src/containers/Procedure.jsx
packages/cozy-procedures/src/redux/documentsDataSlice.js
packages/cozy-procedures/src/templates/creditApplicationTemplate.js

a few things in this PR : 
- having an "importing" state in order to display a "loading" component. 
- dealing with error during import 
- no need to pass loading: true / false, we already know what we're doing 
In order to have a loading state, we need to init the documents store with the same numbers of document required in the template. Like that, we can use the  `index` to populate at the right place

feat: Loading state

---

packages/cozy-doctypes/src/banking/BankAccountStats.js
packages/cozy-doctypes/src/index.js

For now this model does nothing special. It is just usable with methods inherited from `Document`. But I prefer to create it here directly instead of in banks.

feat(cozy-doctypes): Add BankAccountStats model

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

Related to https://github.com/cozy/cozy-ui/pull/1094
For OAuth konnectors, LaunchTriggerCard did not have bottom margin with DeleteButtonCard.
We using a dirty hack here while waiting Cozy-UI to introduce breaking changes for Field label issue.
BEFORE
AFTER

Harvest: Manage margin issues

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

These two methods were not usable with cozy-client. Now they are. They will be used in banks' accounts stats service.

Implement Document::create and Document::createOrUpdate with cozy-client

---

packages/cozy-procedures/src/components/overview/DocumentsFullyCompleted.jsx
packages/cozy-procedures/src/components/overview/DocumentsNotFullyCompleted.jsx
packages/cozy-procedures/src/components/overview/Overview.jsx
packages/cozy-procedures/src/containers/Overview.jsx

When we have the right numbers of linked documents, we change the display

feat: Display fully completed component when docs are ok

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx

Autofocus is buggy on iPhone, it focuses the input but the keyboard is not shown.
D

feat(harvest): Do not autofocus identifier field on iPhone

---

packages/cozy-doctypes/src/banking/BankAccountStats.js
packages/cozy-doctypes/src/banking/BankAccountStats.spec.js
packages/cozy-procedures/src/Procedure.jsx
packages/cozy-procedures/src/containers/Procedure.jsx
packages/cozy-procedures/src/redux/personalDataSlice.js
packages/cozy-procedures/src/redux/personalDataSlice.spec.js
packages/playgrounds/src/common/client.js

Fetch `io.cozy.bank.accounts.stats` documents, then sum them to automatically fill banking data fields.
`io.cozy.bank.accounts.stats` documents are created by a banks service (see https://github.com/cozy/cozy-banks/pull/1393).

(Procedures) Automatically fill banking data

---

packages/cozy-interapp/src/request.js

Since the interapp lib used to be based on `_id` attribute of documents, we add it if it's missing.
Missing `_id` here was causing `invalid event id` or `unexpected handshake message from intent service` errors
For now we don't know why this attribute is now missing or not sent by the stack anymore.
Edit: We should use `id` only for documents using jsonapi from the cozy-stack. For now we keep the both but the `_id` usage should be removed at term.

Interapp: Fix missing _id from intent documents

---

packages/webpack-expose-package-info-plugin/README.md
packages/webpack-expose-package-info-plugin/package.json
packages/webpack-expose-package-info-plugin/src/index.js

Putting this in WIP, I have the feeling that the plugin could be a bit
more useful if it could supply to the application a bit more than the
version.
```patch
- webpack-expose-package-versions-plugin
+ webpack-expose-package-information-plugin
```
with an usage like this ?
```js
new PackageInformationPlugin({
packages: ['cozy-bar', 'cozy-ui'],
fields: ['version']
})
```

feat: Add webpack-expose-package-info-plugin

---

packages/webpack-expose-package-info-plugin/package.json
packages/webpack-expose-package-info-plugin/src/index.js

I forgot to change the name of the package in the package.json.
Also includes the `alias` fix.

Change name of package PackageInfoPlugin

---

packages/cozy-doctypes/src/banking/BankAccountStats.js
packages/cozy-doctypes/src/banking/BankAccountStats.spec.js
packages/cozy-procedures/src/redux/currency.js
packages/cozy-procedures/src/redux/currency.spec.js
packages/cozy-procedures/src/redux/personalDataSlice.js

When automatically filled banking data is shown, we don't want to show more than 2 decimals. So we round it.

feat(cozy-procedures): Round bank account stats

---

packages/cozy-authentication/src/styles.styl

On mobile app, the cozy-bar's cozy-ui styles are overriding the custom
button's styles. So they are not applied and the back button is
misplaced.

fix(cozy-authentication): Force apply the back button styles

---

packages/cozy-authentication/src/steps/SelectServer.jsx

We were showing an Icon in a busy button, so the spinner and the icon were on top of each other. We actually don't want to show the icon when the button is busy.
|Before|After|
|------|-----|
|![image](https://user-images.githubusercontent.com/1606068/61114196-1ec53f80-a490-11e9-8ed7-b69729325429.png)|![image](https://user-images.githubusercontent.com/1606068/61114649-1588a280-a491-11e9-9781-4bf87830e74d.png)|

fix(cozy-authentication): Don't show icon and spinner at the same time

---

packages/cozy-procedures/src/components/documents/DocumentHolder.jsx

- Add shrink-0 to icons in order to manage long filename

fix(cozy-procedures): Shrink icons in DocumentHolder

---

packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/MobileRouter.spec.jsx

In banks, we want to do some things when the user is successfuly logged in, but before redirecting him to `loginPath` (initialize the cozy-bar, actually). I moved `onAuthenticated` before the redirection. I think this is the right place for doing this: if something needs to be done just before redirecting, this looks like the best place to do it; and if something needs to be done after redirecting, it can be done via the component that will be rendered on the `loginPath`.
I had to use a dirty `setTimeout` to make tests pass. Without it, `history.replace` is reported as not called, but it's because the expectation seems to be executed before the code itself.
Any thoughts?

(Authentication) Execute `onAuthenticated` before redirecting

---

packages/cozy-harvest-lib/package.json
yarn.lock

cozy-realtime was present in dependencies, devDependencies and
peerDependencies with different version. Keeping only the highest
version in dependencies should by sufficient
This fixes the following warning: https://travis-ci.org/cozy/cozy-libs/builds/556705656#L793

fix(cozy-harvest-lib): Remove cozy-realtime from dependencies

---

packages/cozy-doctypes/src/banking/BankingReconciliator.js

We want in the near future to be able to saveAccounts as soon as possible, without waiting
for all the transactions to come back. This will help us do that as it splits the saveAccounts
from the saveTransactions so that we can do only the saveAccounts part.

refactor: Extract saveAccounts part

---

packages/cozy-procedures/src/components/documents/EmptyDocumentHolder.jsx
packages/cozy-procedures/src/containers/DocumentsDataForm.jsx

We didn't set `loading` to `false` after linking a document. It results, that during the `unlink` action, our ui state was alway to `loading: true` and we got a loader after unlinking.

fix(cozy-procedures): Set loading to false after linking a document

---

packages/playgrounds/src/procedures.jsx

When we try to add a property (here `displayName`) to a component instance, React throws the following error:
```
TypeError: Cannot add property displayName, object is not extensible
```
This refactor fixes this problem in the procedures playground.

fix(playgrounds): Component instance can't be extended

---

packages/cozy-procedures/package.json
packages/cozy-procedures/src/ProcedureOptions.jsx
packages/cozy-procedures/src/ProcedureOptions.spec.jsx
yarn.lock

Since `injectProcedureRoutes` gets a `...rest` from an object for the
options, it's always an object. So, when passing this to
`optionsProvider`, the default value was never used since
`procedureOptions` was never `undefined`

fix(cozy-procedures): Default options handling

---

README.md
packages/cozy-logger/README.md
packages/cozy-logger/package.json
packages/cozy-logger/src/Secret.js
packages/cozy-logger/src/dev-format.js
packages/cozy-logger/src/index.js
packages/cozy-logger/src/log-filters.js
packages/cozy-logger/src/log-format.js
packages/cozy-logger/src/log-formats.spec.js
packages/cozy-logger/src/prod-format.js

Move from cozy-konnector-libs
cozy-konnector-libs does not have automatic publication, so by moving cozy-logger we get automatic publication for free.
Since cozy-logger is used by apps, it makes more sense to move it here.

Cozy logger in cozy-libs

---

lerna.json

Seen in Travis
https://travis-ci.org/cozy/cozy-libs/builds/560942783#L1974
```
lerna WARN project Deprecated key "command.version.githubRelease" found in lerna.json
lerna WARN project Please update "command.version.githubRelease":true => "command.version.createRelease":"github"
```

chore: Update deprecated config

---

packages/cozy-doctypes/src/banking/BankAccountStats.js
packages/cozy-doctypes/src/banking/BankAccountStats.spec.js

We previously returned `undefined` if a property was missing in a bank
account stats object. This led to getting some `NaN` when doing
computations on this result. Now we return `0` so we can safely
manipulate the result.

fix(cozy-doctypes): Handle missing properties in account stats

---

.travis.yml
packages/babel-preset-cozy-app/README.md
packages/babel-preset-cozy-app/index.js
packages/cozy-authentication/babel.config.js
packages/cozy-procedures/babel.config.js

- No transform of imports
- Use of babel helpers (should we have that by default by the way ?)

feat: Lib option to babel-preset-cozy-app

---

yarn.lock

The CI is currently failing because there's a problem with the `yarn.lock`: https://travis-ci.org/cozy/cozy-libs/builds/561003842#L1965

chore: Fix yarn.lock

---

packages/cozy-doctypes/src/Application.js
packages/cozy-doctypes/src/Folder.js
packages/cozy-doctypes/src/Folder.spec.js
packages/cozy-doctypes/src/index.js

The Folder class mutualize our logic related to folder.
The first two methods added in this PR allow to retrieve referenced folders.
It's based and the code from Drive (https://github.com/cozy/cozy-drive/pull/1243/files#diff-8f9d41bc1595335b09bde52219ed7844R7)
We would need to use it in Harvest to deal with baseDir declared in konnector manifests, for example to retrieve the `$photo` folder even if its path has changed. See https://github.com/cozy/cozy-libs/pull/638
UPDATE: After discussion, it appears that we could expose the concept of magic folders directly in the API, and create a method `ensureMagicFolder`

Doctypes: Add Folder class

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/test/connections/__snapshots__/accounts.spec.js.snap
packages/cozy-harvest-lib/test/connections/accounts.spec.js

We had a few issues with Oauth konnector : 
- Collection.get do not use as wanted for Trigger since the stack doesn't return `data: {} ` for this end point (PR not finished yet here : https://github.com/cozy/cozy-client/compare/fix/get?expand=1) 
- We should avoid `client.collection` and use `client.query` instead 
- We had a typo in the successCallback

fix(cozy-harvest-lib): Fix OAuth login 

---

packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap

We want to be able to edit the login of a connector, even if the connector is already configured.

[Harvest] feat: Allow editing the login, always

---

packages/cozy-logger/babel.config.js
packages/cozy-logger/package.json
yarn.lock

At the moment, cozy-logger will break builds when included in a non-node project, mainly because it requires `chalk` which is node-only. This breakage happens more and more because cozy-logger is used in cozy-doctypes.
This PR creates adds a built step for the cozy-logger package, which uses babel to create a web-friendly version of cozy-logger, where the file using chalk is by-passed.
Webpack web builds should automatically use this. I also had the problem in a jest env, where I needed to tell jest to use `cozy-logger/dist/index.js` using the `moduleNameMapper` option.
The node version is identical.

cozy-logger — web edition 

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

Related to https://github.com/cozy/cozy-libs/pull/690/files#r308832827 and after discussion with @ptbrowne : at the moment the Documents class is a singleton, and it's only possible to register the client once and for all. This is an issue when we use the class in libraries where we are not sure what other pieces of code might use the singleton, if there is a registered client or not, if it's cozy-client or cozy-client-js…
The proposed fix is a new static method that returns a new, independent class, to which we can bind a client, without affecting any other `Document` classes that might be used elsewhere.

feat: Allow multiple Document classes

---

packages/cozy-harvest-lib/jest.config.js
packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
yarn.lock

We want connectors to save their files in the special folders (like `Administrative`), even if these folders are moved or renamed. So this PR uses the special references they have instead hardcoding their path.
This PR will probably fail the CI because of a problem in cozy-logger, I'm looking into it.

[Harvest] Use referenced folders

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

Using `copyWithClient` from another class than Document would return a Document class object, instead of the correct class.

fix: CopyWithClient returns the correct class

---

packages/cozy-doctypes/src/Folder.js
packages/cozy-doctypes/src/Folder.spec.js

When using `copyWithClient `, we can't use the classname to call other static methods, otherwise the client's binding is lost (whereas it's kept with `registerClient`). I had a quick look and apparently only CozyFolder did that.
Using `this` works in both cases, but it shows that `copyWithClient` is just a stopgap solution and #696 might be more urgent than expected.

fix: Folder doctypes keeps the same class

---

packages/cozy-doctypes/src/Account.js

This syntax is only available since node 12. Since we mainly use node
10, this is causing some errors. In banks' services build for example:
```
ERROR in ./node_modules/cozy-doctypes/src/Account.js 14:24
Module parse failed: Unexpected token (14:24)
You may need an appropriate loader to handle this file type, currently
no loaders are configured to process this file. See
https://webpack.js.org/concepts#loaders
|
| class Account extends Document {
>   static getAccountName = account => {
|     if (!account) return null
|     if (account.auth) {
@ ./node_modules/cozy-doctypes/src/index.js 1:16-36
@ ./src/targets/services/stats.js
}
}
}
```
This is somehow the same problem as we had in
https://github.com/cozy/cozy-libs/pull/557

fix(cozy-doctypes): Don't use arrow functions in Account model

---

.travis.yml

The majority of our apps and libs are using node 10.

chore: Use Node 10 in travis

---

packages/cozy-doctypes/src/banking/BankTransaction.js
packages/cozy-doctypes/src/banking/BankTransaction.spec.js
packages/cozy-procedures/src/components/overview/helpers.js
packages/playgrounds/src/common/client.js

In the transactions history JSON file, we want to add the category of each transaction. We don't want to put all the categories of a given transaction (`automaticCategoryId`, `manualCategoryId`, `cozyCategoryId`, `localCategoryId`) but only the one we would show in banks. That's why I extracted the [`getCategoryId`](https://github.com/cozy/cozy-banks/blob/master/src/ducks/categories/helpers.js#L30-L62) helper from banks.

(Procedures) Get transactions category

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/testUtils.js

This avoid including the react dependency from cozy-client
by only including cozy-client.

feat(cozy-doctypes): Include subset of cozy-client

---

packages/cozy-app-publish/README.md
packages/cozy-app-publish/lib/hooks/post/mattermost.js

A default channel can be specified in the mattermost hook.
This is especially useful for connectors when we want to change the channel (which is the same for all connectors) and don't want to change the travis configuration file for all of them.

feat(cozy-app-publish): Make mattermost channel optional

---

packages/cozy-app-publish/lib/hooks/post/mattermost.js

Now you can get the following messages in mattermost on new publication :
Application __drive__ version 1.2.3 has been published.
or
Connector __cic__ version 1.0.3 has been published on space __selfhosted__

feat(cozy-app-publish): Add space and application type in mattermost

---

packages/eslint-config-cozy-app/package.json

The package has been moved from CPatchane/create-cozy-app to
cozy/cozy-libs but we didn't update the corresponding fields in the
package.json. So renovate PRs links were not correct anymore.

chore(eslint-config-cozy-app): Update package.json fields

---

packages/cozy-app-publish/package.json

These fields are useful in various situations: renovate PRs, `npm docs`, `npm bugs` and so on.

chore(cozy-app-publish): Add repository, homepage, bugs to package.json

---

packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx

WIth large content, the icons would shrink because of flexbox rules.

fix: Status icon sizes

---

renovate-config-cozy-libs/package.json

This will create a new renovate configuration to use in our libs. It's based on our main config (so PRs won't happen during working hours etc), but:
- we use ranges for our dependencies, so that we don't end up with duplicate dependencies in our apps
- dev deps are kept pinned
Once published, we will update our `renovate.json` files in our lib repos to extend `cozy-libs` instead of `cozy`.

feat(renovate): Configuration for our libs

---

packages/cozy-doctypes/src/banking/BankTransaction.js
packages/cozy-doctypes/src/banking/BankTransaction.spec.js

Transactions older than the split date are ignored as a fail safe
against duplicates when switching from Linxo to BI. Future transactions
should be ignored in the computation of this split date.

feat: Fix split date

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountForm.spec.js.snap

We're using an up-to-date version of cozy-ui now, so this hack isn't necessary anymore as far as I can tell.

fix: Removed outdated style

---

CODEOWNERS
packages/cozy-logger/src/log-format.js

If NODE_ENV env var was not defined, no log formater would be defined and this could cause fatal error.
I also set myself as code owner for this package. Anybody is welcome of course :-)

fix(cozy-logger): Set production mode as default mode

---

packages/cozy-realtime/README.md

Better to base ourselves on the CODEOWNERS.

chore: Remove out of date Maintainers sections

---

packages/cozy-harvest-lib/src/components/AccountsList/AccountsListItem.jsx
packages/cozy-harvest-lib/test/components/AccountsList/AccountsListItem.spec.js
packages/cozy-harvest-lib/test/components/AccountsList/__snapshots__/AccountsListItem.spec.js.snap

Before checking if the accountName differs from the login, we have to check if the login is not undefined ;). It's the case on a few OAuth konnector

fix(cozy-harvest-lib): Check if accountLogin is not undefined

---

renovate.json

Switch to a configuration where we don't pin our dependencies in this repo. i'm not sure if renovate will automatically unpin everything, if not I'll do it manually later.

chore: Switch to cozy-libs renovate config

---

packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/test/components/TriggerLauncher.spec.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorModal.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerLauncher.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

The code to launch a trigger was more or less duplicated, once in TriggerManager and once in TriggerLauncher. This made the data flow in Harvest more complicated than it needed to be (a lot of prop drilling and callback chains to keep a single source of  truth).
This PR removes the duplicated code from TriggerManager and uses TriggerLauncher instead. We also added support for an `onLoginSuccess` callback in TriggerLauncher.
We tried to keep the breaking changes to a minimum, but there is one. TriggerLauncher now needs to work without an initial trigger, since it's also used when we are adding a new account. To accomodate this:
- The `trigger` prop has been renamed to `initialTrigger`
- The `launch` prop that TriggerLauncher passes to it's children must be called with a `trigger` parameter

[Harvest] refactor: Deduplicate trigger launch logic

---

packages/cozy-realtime/README.md

cozyclient param is deprecated https://github.com/cozy/cozy-libs/blob/master/packages/cozy-realtime/src/index.js#L131, so let's recommend the good way to use the realtime

docs: Use client instead of cozyclient

---

packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js

We have a case in which the account's `number` property is undefined on production, so we must handle this case.

fix(cozy-doctypes): Check that account number exist before matching it

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorConfiguration.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorUpdateLinker.jsx
packages/cozy-harvest-lib/src/components/infos/KonnectorUpdateInfos.jsx
packages/cozy-harvest-lib/src/helpers/apps.js
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/models/KonnectorJob.js
packages/cozy-harvest-lib/test/components/KonnectorUpdateInfos.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorModal.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorUpdateInfos.spec.js.snap
packages/cozy-harvest-lib/test/helpers/konnectors.spec.js

This PR get back the information panel to update a konnector.
It's displayed when a konnector has `available_version` attribute to `true`.
I kept the behavior from Home when a `TERMS_VERSION_MISMATCH` error occurs : the Infos panel theme switch to `danger`.
During tests I encountered issues when dealing with Intents mocking, so I choose to inject them with a `withIntents HOC`. If reviewers agree with its implementation we will then move it to the `cozy-interapp` package, it will just need a little babel configuration. For now it was convenient to have it directly in `cozy-harvest-lib`.
We talked about using AppLinker for redirections via intents, but actually it is `cozy-interapp` responsability so I will update directly the package with this feature.
I look after adding the "available …

Add konnector new version informatin in Konnector Configuration

---

packages/cozy-authentication/package.json
yarn.lock

In cozy-auth, we're using very simple known Markdown. We don't need a full parser with custom renderers and no need for sanitization. 
As a reminder: 
- react-markdown: 58kb 
- snarkdown: 2kb 
I wanted to use it also in harvest, but we can't since we've a custom renderers.

feat: Use snarkdown instead of react markdown

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/CreateAccountButton.jsx

Not all components are in the right translation context at the moment, so using the `translate` HOC doesn't always work.

fix: Missing translations

---

packages/cozy-doctypes/src/File.js
packages/cozy-doctypes/src/File.spec.js

Sometimes, we need to erase on conflict, but sometimes we need to rename. 
This is the method we will use on rename.

feat(cozy-doctypes): Add a generic filename generation on conflict

---

packages/cozy-doctypes/src/Account.js
packages/cozy-doctypes/src/Account.spec.js
packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/CiphersListItem.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/index.jsx
packages/cozy-harvest-lib/src/helpers/manifest.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
yarn.lock

When the user clicks on a cipher, it is used in the account form.
There are two cases:
* If all required fields are present in the cipher, then the account form is automatically submitted
* Otherwise, the user can edit the missing fields and submit the form manually

[Harvest] Handle cipher selection

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

We should share the cipher with cozy even when editing an existing cipher, this fixe the behaviour

feat(harvest): share ciphers on edit

---

packages/cozy-harvest-lib/jest.config.js
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/src/services/updateAccountsPassword.js
packages/cozy-harvest-lib/src/services/updateAccountsPassword.spec.js

This is the main function for the service that will update `io.cozy.accounts` passwords when a change is detected in the vault. 
It takes a cipher document from couch, decrypts the password using the org key, and updates any `io.cozy.accounts` that use this cipher.
Requires https://github.com/pulls but can already be reviewed :)

[Harvest] feat: Update accounts service

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/locales/en.json

When the user selects a cipher that have all the required values to connect the account, we show a spinner instead of the account form with all fields disabled.

feat: Show a spinner when selected cipher has all required values

---

packages/cozy-harvest-lib/src/index.js

getErrorLocale will be part of the public API of cozy-harvest-lib.

feat: Export get error locale

---

packages/cozy-harvest-lib/src/services/updateAccountsPassword.js
packages/cozy-harvest-lib/test/services/updateAccountsPassword.spec.js

When there is an error while decrypting username and/or password in the service, we throw an error so we stop as soon as possible and avoid useless requests.
A decrypting error can happen when the user updates a cipher which is not shared with the cozy organization, so we can't decrypt it using the organization key.
The bitwarden js lib handles errors with `console.error(message)` and `return null`. That's why we check the returned value to throw the error. It means that we can't pass a lot of context to the error, because we just know that something went wrong, but not what exactly.

feat(cozy-harvest-lib): Handle decrypt errors in service

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

When the user selects a cipher with incorrect or missing data, he has to
fill the missing fields. We were not updating the cipher in this scenario.

fix(cozy-harvest-lib): Update selected cipher if needed

---

packages/cozy-doctypes/src/Account.js
packages/cozy-harvest-lib/src/components/AccountForm/AccountField.jsx
packages/cozy-harvest-lib/src/components/AccountForm/ReadOnlyIdentifier.jsx
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

When a cipher has been selected, if the user updates the identifier field, we can't be sure if it's a correction on the identifier or if the user wants to use a totally different account.
To avoid errors, we prevent the user from updating the identifier by showing a read-only field. When the user clicks on this fields, we go back to the ciphers list.

Show a read-only field for identifier when a cipher has been selected

---

packages/cozy-notifications/README.md
packages/cozy-notifications/src/webpack/config.js
packages/cozy-notifications/src/webpack/mimer-parser.js
packages/cozy-notifications/src/webpack/uglify-node.js

Unfortunately, `mjml` and its dependents are not supposed to be built
for nodejs, we have to apply aliases and resolves.
Configuration is provided for dependents on `cozy-notifications` not
to reimplement it themselves every time.
Took some bits from https://github.com/cozy/cozy-libs/blob/master/packages/cozy-mjml/webpack.config.js but I did not need everything there to have a functional konnector.

feat: Provide webpack config for users of cozy-notifications

---

packages/cozy-harvest-lib/src/components/AccountsListModal.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx

If there's only one account, we don't want to show the account selection screen.

[Harvest] Redirect to the only account

---

packages/cozy-harvest-lib/src/components/AccountSelectBox/AccountSelectControl.jsx

Makes the account name container a bit larger, so text isn't truncated too early. Can be a bit cramped on small screens, but it still fits!

[Harvest] fix: Make account selection control larger

---

packages/cozy-harvest-lib/README.md
packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/components/AccountSelectBox/CreateAccountButton.jsx
packages/cozy-harvest-lib/src/components/AccountsList/AccountsList.jsx
packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx
packages/cozy-harvest-lib/src/components/DeleteAccountButton.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/DriveLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorSuccess.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/test/components/AccountsList/AccountsList.spec.js
packages/cozy-harvest-lib/test/components/AccountsList/__snapshots__/AccountsList.spec.js.snap
packages/cozy-harvest-lib/test/components/KonnectorSuccess.spec.js

There was some confusion going on regarding translations in harvest, where we would use `translate` and `withLocales`.
- `translate` only works if there is a `withLocales` further up the tree
- `withLocales` loads the translation strings, so it should only be needed once
- however harvest exposes multiple components — in order for the to work standalone, they need to use `withLocales`
So now, every component exporter by harvest is wrapped in `withLocales`, and all the others are wrapped in `translate`. I left 2 or 3 exceptions because they are components that I'm not sure how they are used and where, so we'll have to get back to them later.

fix: Translating components

---

packages/cozy-doctypes/src/Account.js
packages/cozy-doctypes/src/Account.spec.js
packages/cozy-harvest-lib/src/components/TriggerManager.jsx

We had a bug when we edited an account, then go back to ciphers list and select "from another account". In that case, we showed the account form with a read-only identifier since there is an `account` prop.
This fixes this behavior so we always have an empty account form when we select "from another account".

[Harvest] Show an empty form when editing an account and selected "from another account"

---

packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/AccountForm.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

Currently, we used a read-only identifier field to prevent the user from overwriting its identifier and losing some credentials. This was causing problems in some situations. For example, when the user entered a bad identifier, he couldn't update it afterwards.
To fix this issue, we decided to show a read-only identifier only when the user selected a cipher in which all required fields are not present.
It means that :
* on account creation
* if the user selects "from another account" : we never show a read-only field during the creation process
* if the user selected a cipher that contains all required fields : we don't show the form, so no problem
* if the user selected an incomplete cipher : we show the form with a read-only identifier
* on account update
* we never show a read-only …

[Harvest] Update identifier overwrite prevention mechanism

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx

We passed nothing to the `TriggerManager`'s `onVaultDismiss` prop, so nothing happened when we tried to close the `VaultUnlocker` without unlocking it.

fix(cozy-harvest-lib): Go back when dismissing the vault unlocker

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx

In the account modal, when clicking on the "configuration" tab, we could select to update credentials for an oauth konnector. This shouldn't be possible because we don't store the credentials for this kind of konnector. So we only show account deletion and creation buttons.

fix(cozy-harvest-lib): Prevent credentials update for oauth konnectors

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx

Our modals have rounded edges, but they are defined on the `Modal` component. The `ModalHeader` has square edges, and giving it a background color makes them stand out. Same goes for the `BrandedModalHeader`. 
I've added this issue to our list of things-to-specify with @joel-costa for our Modal rework and found a workaround for this case (giving the whole modal a background color)

Harvest/fix: Make modal top edges round

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/components/AccountsListModal.jsx
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/HarvestModalRoot.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/MountPointContext.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/test/components/AccountModal.spec.jsx
packages/cozy-harvest-lib/test/components/MountPointContext.spec.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountModal.spec.jsx.snap
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorModal.spec.js.snap

In order for the relative routes to work properly in harvest, we had to make sure that we are always on a URL ending with a trailing slash (otherwise redirecting from `/one/to` using `history.push('./three')` ends up on `/one/three`). We had a redirect in place that handled this, but whenever it was triggered, it returned `null`. This in turn unmounted the harvest react tree, and upon being remounted, we were fetching data from the network that we already had.
Instead of further trying to work around the limitations of react-router and relative routes, I implemented a solution discussed in #832. It takes the form of a react context applied to harvest that exposes a `pushHistory` function. This function makes sure we end up on the correct route, regardless of slashes.

Harvest/fix: Avoid extra renders and fetches

---

packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/test/components/TriggerLauncher.spec.js

Until a trigger is launched, the `TriggerLauncher` component uses the `initialTrigger` prop to pass down the correct information. However we were ignoring the current status, so if the `initialTrigger` said that the job was running, we were suppressing this information.

fix: Use initial trigger running status

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorIcon.jsx
packages/cozy-harvest-lib/src/components/TriggerLauncher.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerLauncher.spec.js.snap

This is called the decoupled flow because the 2FA is done on another device
than the one where the user logs in. This means that we do not need to show
a user input and a submit button in the 2FA modal.

feat: Support 2fa flow done on mobile/app

---

packages/cozy-realtime/package.json
yarn.lock

Previous version of minilog have some issues with octal literal in strict mode. We fixed that in our fork. 
context: https://travis-ci.org/cozy/cozy-drive/jobs/601326027#L430

fix: Use cozy-minilog to fix octal

---

packages/cozy-doctypes/src/File.js
packages/cozy-doctypes/src/File.spec.js

Since this method is in cozy-doctypes, it seems the case has changed...

fix(doctypes): Better test error

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/AccountsListModal.jsx
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/TwoFAForm.spec.js.snap
yarn.lock

Some UI tweaks with @joel-costa 👍 
- The modal header on the account modification view is back to a standard header
- The buttons inside the configuration tab stay next to each other onmobile

Harvest/UI Tweaks

---

packages/cozy-harvest-lib/__mocks__/cozy-ui/transpiled/react/utils/color.js
packages/cozy-harvest-lib/src/components/MountPointContext.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

In cozy-home intents, we use the TriggerManager in a standalone manner
(ie outside of harvest routes). So it must embed the providers (like
HarvestVaultProvider and MuiCozyTheme) that are required for it to work.

feat(cozy-harvest-lib): Make TriggerManager usable standalone

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.jsx

This PR prevents harvest from flashing the new account form until we are sure that the konnector is not in maintenance mode.

fix: Delay maintenance information

---

packages/cozy-harvest-lib/src/components/TwoFAModal.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx

removeEventListener does not return the original object contrarly to
on.

fix: Correctly unmount TwoFAModal

---

packages/cozy-authentication/src/MobileRouter.jsx
packages/cozy-authentication/src/MobileRouter.spec.jsx

Commits should speak for themselves. 
It's a breaking change for the second one, but can be easily fixed in banks by doing the `props.router.replace('/balance')` in `onAuthenticated` callback https://github.com/cozy/cozy-banks/blob/master/src/ducks/mobile/MobileRouter.jsx#L24

cozy-auth: Few fixes

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/NewAccountModal.jsx
packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.jsx

We were always trying to fetch the maintenance status for konnectors, even those that aren't from the registry (eg. manually installed).
Also, if we failed to fetch the maintenance status, we would keep displaying the loading spinner instead of falling back tom some content. Now we just show the form if that happens.
Kind of urgent to get this out of the door, I'm adding tests in a separate PR.

Custom konnector maintenance

---

packages/cozy-scanner/package.json

The current published version of Cozy-Scanner doesn't have both en and fr.json files (https://unpkg.com/browse/cozy-scanner@0.1.0/dist/locales/) 
I'm wondering if this is not because of the prepublish command. Let's use the same thing as `cozy-procedure` to see if it works.

fix(scanner): Fix publish lang

---

packages/cozy-doctypes/__mocks__/cozy-logger/index.js
packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js
packages/cozy-doctypes/src/banking/BankingReconciliator.js
packages/cozy-scanner/CHANGELOG.md
packages/cozy-scanner/package.json

Before, create or update would throw if more than 1 existing document was
found through the idAttributes selector. It results in errors for konnectors
for which 2 documents have been inserted by error (for example if the vendor returned two documents with the same vendorId).
After discussion with @edas, we resolved to removing those duplicates. To kept backward compatibility and to explicit this behavior, I went with user configurable strategies in case of duplicates.
- The default strategy is to throw an error when a duplicate is found (same behavior as before)
- The "remove" strategy `createOrUpdate(doc, { handleDuplicate: "remove" })` will remove the most ancient duplicate documents and will keep only the most recent

feat: Create or update can handle duplicates via strategies

---

packages/cozy-doctypes/src/File.js
packages/cozy-doctypes/src/File.spec.js

cozy-stack now handles file's version. 
cozy-client adds now the ability to download a specific version (https://github.com/cozy/cozy-client/pull/564) 
This PR add a new helper to generate the default Filename for a specific version aka : 
`filename-revisionDate.extension`

feat(cozy-doctypes): Add generateFileName for a version

---

packages/cozy-harvest-lib/package.json
packages/cozy-notifications/package.json
packages/cozy-procedures/package.json
packages/cozy-procedures/src/components/form/__snapshots__/SelectBoxAdapter.spec.jsx.snap
packages/cozy-scanner/package.json
yarn.lock

Preact and preact-modal were indicated as dependencies here.
Preact and preact-modal are used by cozy-ui as peer dependencies,
so they do not need to be included here. Saw the bug in Banks
where preact-portal was installed even if it's been a long time
that we do not use preact-portal.
It would actually cause a build bug since the new version of cozy-ui that inverted the USE_REACT flag to USE_PREACT. 
1. Since process.env.USE_PREACT is not changed to
false, the require('preact-portal') was executed
2. It would be found in the node_modules but would fail on its require('preact').
3. So even a try/catch around the require('preact-portal') would not
prevent the build error (since preact-portal could be found).
So if you have preact or preact-portal in your node_modules, you MUST use …

chore: Remove preact

---

packages/cozy-flags/src/connect.jsx

Breaking change as snapshots will fail.

feat: Use conventional display name for HOC

---

packages/cozy-sharing/src/components/ShareModal.jsx

It was required for drive in order to use searchParams in Edge
because of https://github.com/y-lohse/cozy-drive/blob/845c483e9be791544e44fa4c02037f4fc8ff9619/src/sharing/ShareModal.jsx#L41
but has no use in cozy-sharing anymore

feat: URL polyfill is useless

---

packages/cozy-sharing/locales/fr.json

We were missing the `Notes` key in the translations, so i18n was falling back on the english version.

fix: Translation key for notes

---

packages/cozy-sharing/src/index.jsx

In a previous change, we forgot to add PATH as default permissions when sharing a note in cozy-sharing.

fix(cozy-sharing): Patch is necessary for cozy-notes

---

packages/cozy-harvest-lib/src/components/KonnectorSuggestionModal/index.jsx

When there was no element to explain the reason why a suggestion has
been made, the container of the actions was not taking the entire
available width. So the actions were not properly aligned. Forcing it to
take the full width fixes this issue.
Before:
After:

fix(cozy-harvest-lib): KonnectorSuggestionModal actions alignement

---

packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/withLocales.jsx

This is needed to avoid code importing directly from /dist

feat: Export withLocales from cozy-sharing

---

packages/cozy-authentication/src/locales/en.json
packages/cozy-authentication/src/locales/fr.json

We forgot to take those strings when extracting from Drive resulting of trying to create few folders without the right keys...

fix: Add string to create sync folder

---

packages/cozy-sharing/package.json

Since we need to import the css file provided by cozy-sharing by doing : 
`iimport 'cozy-sharing/dist/stylesheet.css'` we need to declare that the package has a side effect on this css file. If we don't, webpack will treeshake it since we "don't use the file".
For more info about side effect: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

fix: Sharing has side effect on css files

---

packages/cozy-realtime/src/CozyRealtime.js

Doing `Object.keys(this._events)` thrown an error when `this._events`
was undefined. We already had a `_getEventKeys` method that handles
this. So I just used it.

fix(cozy-realtime): Don't crash if no event exist

---

packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/test/helpers/oauth.spec.js

The goal here is to avoid the generated oauth popup url to get : scope=undefined parameter, which is not supported by enedis webservice for example.

fix: Allow oauth without scope

---

packages/cozy-notifications/src/notifications.js
packages/cozy-notifications/src/notifications.spec.js

This error would be thrown if a notification would not return
data inside buildData, this is a convention so that the notification
is not sent.

fix: Do not set lang inside templateData if it does not exist

---

packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/helpers/konnectors.spec.js

Add two errors originating from banking connectors.
- SCA_REQUIRED: the vendor demands a new authentification on its app or website
- WEBAUTH_REQUIRED: the vendors demands a new authentification on its website

feat: Support SCA_REQUIRED and WEBAUTH_REQUIRED

---

packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/services/utils.js
packages/cozy-harvest-lib/test/services/utils.spec.js

Two things here.
The service was broken because we have updated the vaultCipher relationships format, but didn't reflect it in the query made in the service to fetch accounts from their linked ciphers.
We saw that the relationship should not be an array (see https://github.com/cozy/cozy-doctypes/pull/126), so in this PR I removed the array, and I updated the query in the service to make it work again.

Fix harvest's updateAccountsPassword service

---

packages/cozy-sharing/package.json
yarn.lock

We use cozy's fork since we have a few issues with the official munilog repo (https://github.com/cozy/minilog/pull/1)

fix: Use minilog cozy fork

---

packages/cozy-app-publish/lib/constants.js
packages/cozy-app-publish/lib/publish.js
packages/cozy-app-publish/lib/publisher.js
packages/cozy-app-publish/test/__snapshots__/manual.spec.js.snap
packages/cozy-app-publish/test/__snapshots__/travis.spec.js.snap
packages/cozy-app-publish/test/publish.spec.js

When the --space option is not provided, then it's undefined and not
used in the resulting registry url being fetched. But when we usee
--space default, then "default" was added to the URL, causing an error.
Both implicit and explicit default space options should work. This fixes
the explicit one.

fix(cozy-app-publish): Handle explicit default space

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

Break functions and move them out of the component. Having them inside the components makes it
harder to reason about since every method can use the internal state of the component class.
This should also make testing easier since we od not have to instantiate a component to call
those functions.
It makes the logic inside handleSubmit more understandable IMHO. It is a first step towards 
having custom logic inside TriggerManager to support BI connection creation flow.

Refactor TriggerManager handleSubmit

---

packages/cozy-harvest-lib/__mocks__/cozy-keys-lib/index.js
packages/cozy-harvest-lib/src/components/AccountForm/Field.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/AccountField.spec.js.snap
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

This fixes two things on TriggerManager:
* Don't show an empty ciphers list briefly before showing the new account form when there is no ciphers
* Correctly pass the aria-label to the obfuscated labels
It also contains basic tests.
In a next PR, I am going to:
* Add other tests
* Clean warnings in tests

[cozy-harvest-lib]: Fixes and basic tests on TriggerManager

---

packages/cozy-sharing/src/components/ContactSuggestion.spec.jsx
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/index.spec.jsx

In a few use case, we need to refresh the sharingProvider to update the infos about sharings. It's needed for instance when we delete a file or when we move a file. 
Since the stack does complicated stuffs for the sharings, we do not want ATM to mimic its behavior from a front point of view. So the refresh only call the fetch from the stack

feat: Add RefreshableSharings to expose a way to refresh sharings

---

packages/cozy-harvest-lib/src/components/KonnectorAccounts.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/test/components/KonnectorAccounts.spec.jsx
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorAccounts.spec.jsx.snap

`KonnectorAccounts` is one of the root components of harvest, it injects a list of triggers down the tree. The problem is that this list of triggers is never updated, which means that if a konnector changes state from "error" to "ok", harvest is not aware of it (technically some components *are* aware of it because they use realtime, but they forget as soon as we chance route).
We could handle this in the (`componentDidUpdate`](https://github.com/cozy/cozy-libs/blob/master/packages/cozy-harvest-lib/src/components/KonnectorAccounts.jsx#L44-L52) but we want to get rid of it eventually. The goal is more for harvest to be standalone, so `KonnectorAccounts` now also listens to the realtime to update itself.

Handle trigger updates

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/assert.js
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.spec.jsx
packages/cozy-harvest-lib/src/components/hooks/useMaintenanceStatus.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/models/KonnectorJob.spec.js
packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/services/bi-public-key-prod.json
packages/cozy-harvest-lib/src/services/biUtils.js
packages/cozy-harvest-lib/src/services/biUtils.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
packages/cozy-harvest-lib/src/services/jobUtils.js
packages/cozy-harvest-lib/test/components/TriggerLauncher.spec.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
packages/playgrounds/src/sharing.jsx
yarn.lock

For the needs of the banking konnectors, a konnector must be able to insert itself
inside the connection process. A konnectorPolicy is introduced that can :
- insert custom behavior before account saving
- control whether credentials are saved into the vault

feat: Add custom konnector policy

---

packages/cozy-app-publish/lib/hooks/pre/downcloud.js
packages/cozy-app-publish/lib/prepublish.js
packages/cozy-app-publish/lib/publisher.js
packages/cozy-app-publish/package.json
packages/cozy-app-publish/test/jestLibs/setupJest.js
packages/cozy-app-publish/utils/logger.js
packages/cozy-app-publish/utils/runhooks.js

Use a logger object to be able to mock out console logs during tests

Less logs during CI

---

packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.spec.jsx

The extra `I18n` was  introduced in c80e6efd45414a32f8186c41484068bc7987e7e4 and caused all child components to be in english. I assume the intention was to provide the I18n context during tests only (at least that's what my brain read during the review 😅)

fix: Remove extra translation context

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
packages/cozy-harvest-lib/src/services/jobUtils.js

- Consider only "result" event when waiting for temporary token.
Since we will receive other events from the konnector in the future,
for example "progress" events, we filter on the "type" attribute 
received in the "data" part of the event.
- Send the bankId as part of the temporary token job options. This is
necessary for multi branch banks, where the bankId is not baked in
the manifest.konnector.

Small fixes

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

The submit button for account creation  would not return to idle state
if there was an error.

fix: Submitting button returns to idle state after error

---

packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/models/cipherUtils.spec.js

WebVaultClient.isLocked returns a promise. So checking it's return value
without await is always true. Adding await ensures we get the real vault
locked state.

fix(cozy-harvest-lib): Correctly check vault locked state

---

packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/index.js
packages/cozy-harvest-lib/src/services/deleteAccounts.js
packages/cozy-harvest-lib/test/connections/accounts.spec.js
packages/cozy-harvest-lib/test/services/deleteAccounts.spec.js

This finds the accounts that have a relationship with a given cipher,
and delete it. It will be used in a service to delete accounts when a
cipher has been deleted by the user.

feat(cozy-harvest-lib): Add deleteAccounts service

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx

This prop is not required in all TriggerManager use cases. We don't
always want to do something when the vault is dismissed.

fix(cozy-harvest-lib): The onVaultDismiss prop is not required

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

When the user tries to edit an account, we show the form directly. But
ciphers are being fetched in background, and we were redirecting to the
ciphers list step as soon as we detect that some cipher exists.
Actually, when the user is on the account form step, we shouldn't
automatically redirect. If the user wants to see the ciphers list, he
can by clicking the "back" arrow.

fix(cozy-harvest-lib): Always show account form when editing an account

---

packages/cozy-harvest-lib/__mocks__/cozy-keys-lib/index.js
packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/models/cipherUtils.spec.js

When creating a new account with an existing cipher, it was duplicated. This PR fixes this. Now, the cipher is linked to the created account, but not duplicated.
Also added tests.

[cozy-harvest-lib] Don't duplicate ciphers when selecting an existing one

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

When the user selected a cipher, he should be able to go back to the
ciphers list by clicking on the back button on the left modal corner.
This was broken, so this PR fixes it.

fix(cozy-harvest-lib): Back button on account form

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

This is quite similar to https://github.com/cozy/cozy-libs/pull/949.
Actually I broke it in https://github.com/cozy/cozy-libs/pull/952
because I reverted a commit that contained tests. Thus the tests
disappeared, but I thought they were passing.
So here I bring back the tests from the reverted commit and really fix
the issue...

fix(cozy-harvest-lib): Show account form on account edition

---

packages/eslint-config-cozy-app/basics.js

We want to raise errors in case of `console.log` in our source codes.
The upgrade of eslint to 5.x to 6.x changed the default for no-console. This PR is to restore the previous behaviour.
See https://github.com/eslint/eslint/blob/24ca088fdc901feef8f10b050414fbde64b55c7d/docs/user-guide/migrating-to-6.0.0.md#eslint-recommended-changes

feat: Adds no-console as eslint errors

---

packages/cozy-app-publish/lib/hooks/post/mattermost.js
packages/cozy-app-publish/lib/hooks/post/mattermost.spec.js

Following a discussion on mattermost where it was reminded that publication messages should be published on the Publication channel.
For beta and stable channels, it is useful to have them published
on the publication channel. It remains useful to also have them
in the app channel (for dev and PO following the channel of the app).
Dev versions on the contrary should not be published on the publication channel as it would be too noisy.
The MATTERMOST_CHANNEL env variable now supports a JSON objects (additionally to a simple string), to configure different channels based on registry channel.
```
export MATTERMOST_CHANNEL='{"beta":"publication,team", "dev": "team", "stable":"publication,team"}'
```

Publication channel can depend on registry channel

---

packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx

Something that slipped through the big PR — `FlowProvider` no longer directly injects `error` and similar props, instead they need to be retrieved from the `flow` object.

fix: Load current konnector error

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/BanksLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/DriveLink.jsx
packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx
packages/cozy-harvest-lib/src/components/hooks/useAppLinkWithStoreFallback.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/test/components/__snapshots__/KonnectorSuccess.spec.js.snap
packages/cozy-harvest-lib/test/components/hooks/useAppLinkWithStoreFallback.spec.js

In #933 I added links to contacts and banks from the harvest modal. This PR makes sure that when the apps are not installed, a link to the store is displayed instead.

[Harvest] Feat: Fallback for app links

---

packages/cozy-harvest-lib/test/components/FlowProvider.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/FlowProvider.spec.js.snap

This is a follow up on #961… but I found it hard to add a lot of new tests. Actually `FlowProvider` and `ConnectionFlow` have both a decent test coverage already. I ended up reworking the current tests so that they are more sensible and added one that explicitly tests the error case fixed in the previous PR.

test: Check FlowProvider state prop

---

packages/cozy-harvest-lib/src/cli/cli.js
packages/cozy-harvest-lib/src/components/AccountForm/index.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

Since the TriggerManger would pass an empty object as account, the
ConnectionFlow executed the update path, that would not put the
account_type property inside the io.cozy.accounts
Without an account_type, the stack would not trigger the on_deletion
mechanism which is particularly important for banking connectors.

fix: Account correctly created with the account_type property

---

packages/cozy-harvest-lib/src/services/bi-http.js
packages/cozy-harvest-lib/src/services/bi-http.spec.js

Budget Insight sometimes "errors" when it cannot force update the connection
to the banking vendor (for example if the connection has been refreshed
not too long ago). In this case, the response schema is different than the
normal Connection ressource that we expected.

fix: Support Budget Insight alternate schema for update connection

---

packages/cozy-flags/src/flag.js
packages/cozy-flags/src/tests.js

There was a small typo causing a crash when we tried to load flags from the `data-cozy-flags` DOM node.

fix: Load flags from legacy DOM

---

packages/cozy-device-helper/src/index.js
packages/cozy-device-helper/src/index.spec.js
packages/cozy-device-helper/src/plugins.js

This addition is needed for cozy-realtime. It will
allow to send a warning when the plugin is not
loaded. If so, cozy-realtime won't be able to react
to online and offline events.

feat: Checks for cordova's network info plugin

---

packages/cozy-app-publish/lib/hooks/post/mattermost.js

The former would not work in node 8

fix: Must declare error variable in catch block

---

packages/cozy-flags/src/flag.js
packages/cozy-flags/src/tests.js

The flags plugin for cozy-client waits for the `login` event to load the flags. We often do something like:
```
const client = new CozyClient({ token, url })
client.registerPlugin(flag.plugin)
```
… but when the plugin is registered, the `login` event has already been fired and the flags are never loaded.
This PR solves the problem by loading the flags iff it detects that the client is already logged in. SInce loading the flags is `async`, there is now also an exposed promise on `client.plugins.flags.initializing` to know when they are ready.

fix: Init flags when client is already logged in

---

packages/babel-preset-cozy-app/README.md
packages/babel-preset-cozy-app/index.js
packages/babel-preset-cozy-app/package.json
packages/cozy-harvest-lib/package.json
yarn.lock

It's the follow up of https://github.com/cozy/cozy-libs/pull/711. Easier to create a new branch than rebasing the lock file ^^". 
On harvest: 
Before:
```
dist git:(feat/RemovePropTypes) ✗ du -h .
40K	./locales
124K	./models
24K	./cli
32K	./connections
652K	./components
200K	./assets
84K	./helpers
76K	./services
1,2M	.
```
After: 
```
dist git:(feat/RemovePropTypes) ✗ du -h .
40K	./locales
124K	./models
24K	./cli
32K	./connections
640K	./components
200K	./assets
84K	./helpers
76K	./services
1,2M	.
```
We have a gain of 12K for the component folder. 
For UI: 
Before: 
```
➜  transpiled git:(tests/propTypes) ✗ du -h .
...
2,4M	.
```
After: 
```
➜  transpiled git:(tests/propTypes) ✗ du -h .
...
2,3M	.
```

feat: Remove proptype in production mode

---

packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/CozyRealtime.spec.js
packages/cozy-realtime/src/RetryManager.js

Previously, an event could call for a reconnect
while the previous one was waiting before
creating  a new socket. This would create
a two socket in a row.
This change adds a protection against concurrency
when creating a socket.

fix(realtime): Connect concurrency

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/appLinksProps.jsx
packages/cozy-harvest-lib/test/components/KonnectorConfiguration/DataTab.spec.jsx

The link to drive was missing a `#` at the start of the path.

fix: Drive link from harvest

---

packages/cozy-harvest-lib/src/components/AccountForm/Field.jsx
packages/cozy-harvest-lib/test/components/AccountField.spec.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

When editing an account in harvest, we show a password field that is empty (because the password is encrypted and not available to the front-end) — but that password field has a reveal/hide button along it. This seems to confuse people who don't understand why the field is empty once they click the "reveal" button.
A redesign is underway but in the meantime, this PR hides the "reveal" button until there is something in the field.

feat: Hide password toggle when field is empty

---

packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap
packages/cozy-realtime/src/CozyRealtime.js
packages/cozy-realtime/src/CozyRealtime.spec.js
packages/cozy-realtime/src/RetryManager.js
packages/cozy-realtime/src/RetryManager.spec.js

This changes allows an immediate reconnect by passing the immediate waiting time for some events like when we are back online. It also immediatly reconnect if we set the page on top and there is a reconnection waiting.
On the user point of view, it avoids some lag in getting updates from the server when possible.

Realtime: Adds onvisibilitychange

---

packages/cozy-scanner/src/Scanner.jsx
packages/cozy-sharing/src/components/SharedBadge.jsx

It currently brings a bug in a jest env. Plus it's more efficient to use from the full path in order to let the magic happen (tree shaking)

fix: Don't import from index

---

packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/withConnectionFlow.jsx
packages/cozy-harvest-lib/src/models/withConnectionFlow.spec.jsx

LaunchTriggerCard bases its render on ConnectionFlow so it must
be explicit about that otherwise updaes from above could be 
"bailed out".

fix: Last execution time is correctly refreshed

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/models/cipherUtils.spec.js
yarn.lock

Since the sort does not specify a number, false or true are used and falsy
values come first, this mean the search can find a cipher with a different
password that what is searched. Another check is necessary if no cipher
with the same password have ever been added.
For a reason I still ignore, this resulted in ciphers with null values 
after both ciphers with different password were merged because the 
deciphering would not work (mac failed error)

fix: Bad password matching would result in null fields

---

packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/models/cipherUtils.spec.js

We cannot decrypt a null cipher, so the condition was improved

fix: Decrypt called on null

---

packages/cozy-sharing/src/SharingDetailsModal.jsx
packages/cozy-sharing/src/components/EditableSharingModal.jsx
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/Recipient.spec.jsx
packages/cozy-sharing/src/components/ShareModal.jsx
packages/cozy-sharing/src/components/WhoHasAccess.jsx

Currently we're not doing the right thing when we try to remove a sharing from the ActionMenu. 
We display the "Remove action" with the right conditions aka "I'm the owner" or "I've accepted the cozy to cozy sharing", but after that, when we call the revoke() we don't make any difference between if I'm the owner or not. 
If I'm the owner, I can revoke members I want for the sharing and so, I need to call /revoke/:id. 
If I'm the "accepted sharing", I can only remove myself and then I need to call /revoke/self

fix: Call revokeSelf if not the owner of the sharing

---

packages/cozy-scanner/src/DocumentQualification.jsx
packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap

Drive was using MUI V4. We downgraded it to use V3 as UI. V3 and V4 don't have the same implementation.
In v4 spacing = 8 means 8*8, in v3 spacing 8 means what we want

fix: Grid spacing

---

packages/cozy-sharing/README.md
packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/index.spec.jsx

At the moment cozy-sharings exposes a variety of components that in turn expose a subset of the context. That's cool but doesn't work with hooks at all.
This PR exposes the `SharingContext` so that it can be called with `useContext`.  
It also exposes the `hasWriteAccess` function in the context so that it can be used outside of `<SharedDocument />`.

Sharing hooks

---

packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/test/components/FlowProvider.spec.jsx
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js
packages/cozy-harvest-lib/test/components/__snapshots__/TriggerManager.spec.js.snap

Keep watching connection flow when connector execution is finished
Give connector information to the flow in all the contexts to allow it to get the associated policies

fix(Harvest): Some regressions which affected the 2FA flow

---

packages/cozy-sharing/locales/en.json
packages/cozy-sharing/locales/fr.json
packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/EditableSharingModal.jsx
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/ShareByLink.jsx
packages/cozy-sharing/src/components/ShareModal.jsx
packages/cozy-sharing/src/components/__snapshots__/Recipient.spec.jsx.snap
packages/cozy-sharing/src/components/__snapshots__/SharedStatus.spec.js.snap
packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/share.styl
packages/cozy-sharing/src/state.js
packages/cozy-sharing/src/state.spec.js
yarn.lock

This PR updates the link sharing UI. Instead of a simple toggle, it's now a 2 step process:
- A button to activate the sharing
- An ActionMenu to change the permissions

Sharing link with write permissions

---

packages/cozy-scanner/package.json
packages/cozy-scanner/src/DocumentCategory.jsx
packages/cozy-scanner/src/__snapshots__/DocumentCategory.spec.jsx.snap
yarn.lock

This PR updates the scanner ActionMenu to use the autoclosing feature from https://github.com/cozy/cozy-ui/pull/1452.
The existing test is literally about opening and closing the menu so I'm not sure what to add, but let me know if you have suggestions!

fix: Upgrade to latest cozy-ui

---

packages/cozy-sharing/src/index.jsx

This commit essentially reverts 300e88dab97fe95dd63fde2a667cd444b3df11ed. The notes app is about to get an upgrade where it will behave the same as drive, eg. the user can chose when sharing by link whether the sharing should be read-only or not.

fix: No special case for sharing notes

---

packages/cli-tree/README.md
packages/cli-tree/examples/users.js
packages/cli-tree/package.json
packages/cli-tree/src/completion.js
packages/cli-tree/src/completion.spec.js
packages/cli-tree/src/index.js
yarn.lock

This adds completion to cli-tree using [tabtab](https://www.npmjs.com/package/tabtab).
Completion installation commands are automatically present.
Need to add the `completionHandler` in the program.
I would have liked to make it transparent and not need any change in the program using cli-tree but the `completionHandler` needs to be async (because of tabtab implementation) and `build` is sync.
Other possibility I saw is to add a new `completeAndBuild` function at the same level as build, which would be async.
This PR may be the occasion for other ideas.

feat: add command completion feature with cli-tree with tabtab

---

packages/cozy-harvest-lib/src/cli/cli.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/test/components/TriggerManager.spec.js

It has been set to true for a long time in the home and we do not
need the rollback capability anymore.

feat: Remove harvest.bi-konnector-policy flag

---

packages/cozy-harvest-lib/src/components/HarvestVaultProvider/index.jsx

Introduced in d0a119a09bd8bf79b26a088e66ed9b040b49123a, I am not sure
that this is needed anymore. It triggers a warning in cozy-home since
local.config.json does not exist.

feat: Remove undocumented local.config.json

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

We previously detected production environment with production/staging
domains (mycozy.cloud, cozy.rocks) and defaulted to sandbox.
The detection is now inverted, we detect dev,int domains and set them
to sandbox and default to production.
This is a temporary fix, waiting for an api allowing an app to
properly detect it's environment.

fix(Harvest): Change prod/sandbox environment detection

---

packages/cozy-harvest-lib/src/models/cipherUtils.js
packages/cozy-harvest-lib/src/models/cipherUtils.spec.js

Updating a non shared with cozy cipher would cause the cipher to
be encrypted with the cozy organisation key. But the stack does
not support a cipher to be updated into an organisation, it needs
a separate call for sharing (to conform with the Bitwarden
implementation)

fix: Update a not shared-with-cozy cipher from harvest

---

packages/cozy-realtime/src/RealtimePlugin.js
packages/cozy-realtime/src/RealtimePlugin.spec.js

When calling `cozy.plugins.realtime.subscribe()` while cozy-client is **not** logged in, a misleading error was produced — "Cannot call subscribe on null" or something like that, but `cozy.plugins.realtime` was not null so it was quite confusing. With this PR we still throw an error, but makes it clear what the actual problem is.

fix: Better error message when using a logged off client with realtime

---

packages/cozy-flags/src/flag.js
packages/cozy-flags/src/tests.js
packages/cozy-realtime/src/RealtimePlugin.js
packages/cozy-realtime/src/RealtimePlugin.spec.js

We want to use cozy-client plugins, but it may be hard to know when they are ready to be used. We can't rely on `client.on('login')` because the call order of the listeners is not guaranteed. Instead, plugins can now emit events through cozy-client to notify other parts of an app when  they are ready.

feat: Emit events when realtime is ready

---

packages/cozy-sharing/package.json
packages/cozy-sharing/src/index.jsx
packages/cozy-sharing/src/index.spec.jsx
yarn.lock

The SharingProvider loads data on `componentDidMount` — this may lead to errors when cozy-client is not connected, for example on a mobile app.

fix: Don't load data if the client isn't ready

---

packages/babel-preset-cozy-app/package.json
packages/cli-tree/package.json
packages/cozy-app-publish/package.json
packages/cozy-device-helper/package.json
packages/cozy-doctypes/package.json
packages/cozy-harvest-lib/package.json
packages/cozy-notifications/package.json
packages/cozy-procedures/package.json
packages/cozy-sharing/package.json
yarn.lock

This will fix security vulnerability like this one : https://github.com/konnectors/libs/network/alert/yarn.lock/lodash/open

feat: Update lodash accross all packages

---

packages/cozy-app-publish/src/cozy-app-publish.js
packages/cozy-app-publish/src/git.js
packages/cozy-app-publish/src/hooks/post/mattermost.js
packages/cozy-app-publish/src/hooks/pre/downcloud.js
packages/cozy-app-publish/src/hooks/pre/helpers.js
packages/cozy-app-publish/src/manual.js
packages/cozy-app-publish/src/test/jest.setup.js
packages/cozy-app-publish/src/utils/logger.js

- Helps to distinguish normal publish output from console.logs
- Can be used to increase / decrease verbosity level via CLI args
in the future

refactor: Use logger for logs

---

packages/cozy-harvest-lib/src/logger.js

Logging can be turned on on a case by case basis
See https://docs.cozy.io/en/cozy-client/details/#how-to-activate-logging
for more information
T

feat: Turn off logging by default on harvest

---

packages/cozy-harvest-lib/src/components/Popup.jsx

This avoids a blank screen in OAuth steps on some version of safari on IPhone and desktop.
At least Safari 13 on IPhone XS (browserstack).

fix: Manually add window.opener in OAuth popup

---

packages/cozy-sharing/src/components/EditableSharingModal.jsx

client.all is deprecated ! Just ran into this while investigating a bug.

refactor: Use Q instead of client.all

---

packages/cozy-harvest-lib/src/services/budget-insight.js

It is not possible to create a sublogger with logger(namespace),
it would only emit a log. It returned the logger so it looked
like it worked

feat: Use logger from harvest for BI

---

packages/cozy-app-publish/src/__snapshots__/travis.spec.js.snap
packages/cozy-app-publish/src/publish.js
packages/cozy-app-publish/src/publisher.js

`verror` is a library from joyent to facilitate error handling. It makes it
easy to chain errors (keeping stack traces along the way), or to deal with
MultiErrors. This makes it easier to understand where an error comes from.
Additionally, when handling the .json() decoding error, we would reuse the
body from the response to do .text(); this is not possible, we need to
clone the Response.

feat: Use VError to chain stack traces

---

packages/cozy-sharing/src/components/EditableSharingModal.jsx
packages/cozy-sharing/src/components/EditableSharingModal.spec.js
packages/cozy-sharing/src/components/useFetchDocumentPath.jsx
packages/cozy-sharing/src/helpers/files.js
packages/cozy-sharing/src/helpers/sharings.js
packages/cozy-sharing/src/index.jsx

We assumed that a document has a path or at least that
we can fetch it. It works well with an io.cozy.files but
not with an io.cozy.albums since an album doesn't have a
path.
Instead of displaying nothing if there is no path, let's just
not make the call to the methods that need the path to work.

fix: Shared Element when the document has no path

---

packages/cozy-notifications/src/mjmlUtils.js

Otherwise, we may send empty / malformed emails. MJML validation errors
can pop up when the JS minification is too strong, preventing MJML
to have its components correctly registered resulting in "Element a
doesn't exist or is not registered" errors

feat: Apply strict validation

---

packages/cozy-app-publish/src/publisher.js
packages/repo-doctor/src/rules/index.js

Having the prompt after prepublishing causes several problems
- it means that we have to remember to go and say yes after the app has
been uploaded to downcloud
- if there is an error in the detected slug / version, the app already
has been uploaded with an error on downcloud
Here the prompt is shown as early as possible, meaning the developer can go
about its business afterwards. Since we do not know the appBuildUrl before
prepublishing if it has not been passed, the logging of its value is kept
after prepublishing, along with the shasum.

feat: Show confirmation prompt before prepublishing

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js
packages/cozy-doctypes/src/banking/matching-accounts.js

When matching incoming accounts from a vendor to existing accounts,
we need to merge relationships to existing relationships.

Keep relationships field when matching accounts

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

To fix an url mistake in the previous related commit. This commit is not
needed by the home application

fix(Harvest): Change maif bi api url

---

packages/cozy-scanner/package.json
packages/cozy-scanner/src/DocumentCategory.jsx
packages/cozy-scanner/src/__snapshots__/DocumentCategory.spec.jsx.snap
yarn.lock

Depends on https://github.com/cozy/cozy-ui/pull/1518
The ActionMenu in the qualification modal was displayed *under* the modal, because we're using ExperimentalModal and that was missing a PopperContext. WIth https://github.com/cozy/cozy-ui/pull/1518 the context is no longer required and the menu is above the modal.
However the menu is very large and parts of it are sometimes cut off by the modal, so we use the fixed positioning strategy of popper.js.

fix: Qualification sub menu on desktop

---

packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx

fix(Harvest): Add margin on top of the website link

---

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

If all contracts have been deleted, we still need to show
the icon of the konnector.

fix: Handle case when all contracts have been deleted

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx
packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.spec.jsx
packages/cozy-harvest-lib/src/components/cards/__snapshots__/WebsiteLinkCard.spec.jsx.snap
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json

This branch takes its root from the 2.2.0 version of harvest (used
in last 1.30.5 version of cozy-home) and only adds cherry-picked
commits related to WebSiteLink component.
This will allow to deliver the next 1.30.6 version of cozy-home with
the WebSiteLink component and without more impactful and still to
be validated changes.
I also added a fix to not throw a error when the vendor_link is not
a valid url.
Do not throw error on invalid url in manifest

fix(Harvest): deliver an harvest 2.2.0 with only WebsiteLink component addition

---

packages/eslint-config-cozy-app/basics.js

See the doc here: https://eslint.org/docs/rules/no-param-reassign
Fix #1073

feat: Activate the no-param-reassign rule

---

packages/cozy-sharing/src/components/ShareByLink.jsx
packages/cozy-sharing/src/components/ShareModal.jsx

By default, MUI Dialog keeps the focus on Dialogs for accessibility reasons. Most of the time that's good, but here our copy to clipboard lib needs control over the focus to do it's job.

fix: Ability to copy links

---

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx
packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.spec.jsx
packages/cozy-harvest-lib/test/jest.setup.js

Without aria-label we have a warning and this is problematic
for apps that do no want warnings in their console.
Here I also make it so that console.warn throws during tests.

Add aria-label + test on DisconnectedAccountModal

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
yarn.lock

To get new banking connectors ids into master
A new 2.2.2 version of harvest is already available with this new version of cozy-bi-auth to avoid unneeded feature collisions in home.

chore(Harvest): Update bi-auth to 0.0.8

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.spec.jsx

After extracting the methods from harvest and putting them in cozy-client,
I had forgotten to replace the call points. I took the opportunity to
add tests for SyncContractSwitch since having them would have prevented
this error.

fix: Use model helpers and add test for SyncContractSwitch

---

packages/babel-preset-cozy-app/index.js

A default options object was modified. This could cause race problems
when building a service and an app, the service configuring the
default options to have { node: true } in the babel-preset-cozy-app
default options, preventing the code from the app to be correctly
parsed.
Example of error:
"Support for the experimental syntax 'jsx' isn't currently enabled"
This error would disappear on subsequent builds, because of caching
(not sure why caching helps though). It was particularly problematic on
the CI where there's no cache and where builds must work the 1st time.
Fixes https://github.com/cozy/create-cozy-app/issues/1342

fix: Flaky builds due to SyntaxError

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.spec.jsx
packages/cozy-harvest-lib/test/jest.setup.js

If an account does not have any contract (for example because its konnector
does not fill its contracts relationship), we should not fail completely.
Here the code has been refactored so that the SyncAccountSwitch also
renders its label, and so that it renders null if the related contract
cannot be found in the account.

fix: Handle cases where io.cozy.accounts does not have contract

---

packages/cozy-harvest-lib/src/connections/triggers.js
packages/cozy-harvest-lib/src/services/softDeleteOrRestoreAccounts.js
packages/cozy-harvest-lib/src/services/softDeleteOrRestoreAccounts.spec.js
packages/cozy-harvest-lib/src/services/updateAccountsFromCipher.js
packages/cozy-harvest-lib/src/services/updateAccountsFromCipher.spec.js
packages/cozy-harvest-lib/src/services/utils.js

This service is useful to deal with soft delete and restore from
bitwarden, used for a trash feature. See [the stack PR](https://github.com/cozy/cozy-stack/pull/2633).
When a cipher is soft deleted, a `deletedDate` field is added to the
cipher. Then, the service removes the encrypted credentials from the
referenced account and delete the associated trigger.
When the cipher is restored, the `deletedDate` is removed: the service
recreates the account's trigger. The account's credentials are then
restored through the `updateAccountsFromCipher` service.

Add softDeleteOrRestoreAccounts service

---

packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/components/Popup.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/test/helpers/oauth.spec.js

We now use cozy-realtime to send the accountId from the OAuth popup
to the origin harvest window.
postMessage api is more and more restricted depending on browser or
platform.

fix(Harvest): Use cozy-realtime for OAuth popup communication

---

packages/cozy-harvest-lib/package.json

Currently Harvest have a few old version in peerDep. We should kept them synched with the devDep?

fix: Set peerDep same as devDep

---

packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/test/helpers/oauth.spec.js

Since https://github.com/cozy/cozy-stack/pull/2674, the stack accepts
a new "slug" parameter. This param is used to redirect the user on the
specified slug after the end of the OAuth flow.
Before, the user was always redirected to the Home app, but now that
several apps (internal & external) use Harvest directly, we want to
redirect the user on the right app to provide a good UX.
By good UX, I mean : on web mobile, we open a new tab / window to start the OAuth flow. Before this modification we ended on the Home app all the time. But since we can starts this process from an other app, we ended on the Home without the right informations (state for instance) resulting in a blank screen while the process in the opener tab was finished successfully. 
Context: One of the GL app imports directly …

feat: Add redirectSlug to OAuthWindow

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.js

At the moment, this disconnect button is hidden for OAuth connectors since the contract selection feature

fix(Harvest): Display disconnect button for OAuth connectors

---

packages/cozy-flags/src/flag.js

Useful for example to refresh the flags on mobile after the
app has resumed

feat: Add refresh method on plugin

---

packages/cozy-harvest-lib/package.json

It's problematic when libs have not the same version of cozy-flags
as the host app since cozy-flags keeps a internal cache of flags.
If the app's cozy-flags is not the same as the libs' flag, the
lib's cozy-flags will not populated with the flags that are 
fetched at login time (on mobile) or at page resume time (both
on mobile and browser).

fix: Put cozy-flags as peer-dep

---

packages/repo-doctor/src/rules/depSameVersion.js

Across our repositories, we have dependency that should be at
the same version no matter what. It can be the case for cozy-client
dependencies, jest dependencies or babel dependencies.
Here, a rule is added that checks if a list of dependencies are
at the same version.
Result:
```
Repository: cozy/cozy-drive
DepSameVersion: Different versions for cozy-client@13.14.2, cozy-stack-client@13.15.1, cozy-pouch-link@13.13.1
Repository: cozy/cozy-banks
DepSameVersion: Different versions for cozy-client@13.15.1, cozy-stack-client@13.8.3, cozy-pouch-link@13.15.1
```

feat: Check if deps are at the same version

---

packages/cozy-codemods/src/find-nearest.js
packages/cozy-harvest-lib/README.md
packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/hoc/tracking.jsx
packages/cozy-harvest-lib/src/index.js
packages/cozy-notifications/src/urls.js

Adds trackPage and trackEvent calls to several components inside
harvest.
Those functions are taken from the context. This is the responsibility
of the app to provide the correct context, connecting the app tracker
to harvest.
If the context is not present, track calls will still work but won't
do nothing.

Tracking inside harvest

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthWindow.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/helpers/oauth.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js
packages/cozy-harvest-lib/test/helpers/oauth.spec.js
yarn.lock

Webauth is a protocol similar to OAuth but specific Budget Insight.
This PR needs https://github.com/cozy/cozy-stack/pull/2667 to be deployed in the stack to work properly + some specific secrets to be available.
For us, what is specific to webauth is that OAuth url must contain a temporary token generated by the connector and the resulting callback url, returned by BI will contain a new connection id which must be saved in the account.

feat(Harvest): Handle webauth connectors

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

The linxo bankId is the one saved into the account.
I renamed linxo bankId to linxoBankId et BI bankId to BiBankId

fix(Harvest): Better diffentiate bankId

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/Popup.jsx
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

The browser popup blocker blocked the webauth popup because it appeared after an
asynchronous action (to get the temporary token) Now, the submit button is
displayed only when the token is already available and when the user clicks
on the submit button, the popup is displayed synchronously."

fix(Harvest): No more permission needed to open the popup

---

packages/cozy-flags/README.md

fix Broken links on flags page

docs: Broken links on flags page

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/cli/cli.js
packages/cozy-harvest-lib/src/logger.js
packages/cozy-harvest-lib/test/jest.setup.js
packages/cozy-realtime/package.json
packages/cozy-realtime/src/CozyRealtime.legacy.spec.js
packages/cozy-realtime/src/logger.js
packages/cozy-sharing/package.json
packages/cozy-sharing/src/logger.js
yarn.lock

Our own fork solves a problem with octal literals in strict mode

feat: Use @cozy/minilog instead of minilog

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/CiphersListItem.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/OtherAccountListItem.jsx
yarn.lock

The two arguments were deprecated and cause warnings in test.

refactor: Use primary and secondary instead of primaryText/secondaryText

---

packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/RecipientsAvatars.spec.jsx
packages/cozy-sharing/src/components/__snapshots__/ContactSuggestion.spec.jsx.snap
packages/cozy-sharing/src/index.jsx
yarn.lock

**Need to update cozy-ui before merging**
Précédemment on affichait les destinataires d'un partage dans la colonne statut via un texte et un tooltip. On affiche maintenant directement les avatars (en me retirant de la liste si je suis le propriétaire) comme on le fait déjà sur mobile, ou dans la vue d'un dossier.

SharedStatus shows avatars

---

packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js

This is a case I met with the paypal bi connector

fix(cozy-doctypes): CreditCardMatch handle acount without number

---

packages/cozy-harvest-lib/src/services/bi-http.js
packages/cozy-harvest-lib/src/services/budget-insight.js

User config is used to store user data before a transfer (KYC
regulations)

feat: Ability to update user config

---

packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.jsx
packages/cozy-harvest-lib/src/components/VaultCiphersList/VaultCiphersList.spec.jsx

Ignore ciphers deleted by cozy-pass when proposing import on new account creation

feat(Harvest): Ignore soft deleted ciphers

---

packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/recipient.styl

Keep class and stylus (not using utilitary classes) to be consistent

fix: No margin on first recipient when no AvatarPlusX

---

packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/recipient.styl

On ne veut pas que l'icone de lien soit décalé par rapport aux autres. Correction de la taille des avatars qui doit faire 24px hors bordure (et non avec bordure).

fix: SharingAvatar link is not separated + avatar size

---

packages/cozy-sharing/src/components/AvatarPlusX.jsx
packages/cozy-sharing/src/components/Recipient.jsx

**Before** : All tooltips of all lines are displayed.
---
**After**

fix: Tooltip on sharingAvatars show only the row recipients

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/bankAccountHelpers.js
packages/cozy-harvest-lib/src/components/TwoFAModal.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx

TwoFaModal was not wrapped in withlocales, thus it could not
find its translations. I am at a loss at when the bug appeared.

Fix untranslated locale strings

---

packages/cozy-harvest-lib/package.json
packages/cozy-scanner/package.json
packages/cozy-scanner/src/DocumentCategory.spec.jsx
scripts/check-packages-constraints.js
yarn.lock

When executing yarn test in cozy-harvest-lib, there was a
warning about two different versions of @testing-library/react
in dependencies and devDependencies.
- Removed @testing-library/react from dependencies
- Upgrade @testing-library/react in cozy-scanner to have the
same version
- Fix the small issues that the upgrade caused

Solve dependency warning

---

packages/cozy-authentication/src/index.js

Stylesheet transpiling was removed since there was no stylus files
transpiled anymore. But, the import had not been removed resulting in
an import error when importing cozy-authentication. The stylesheet that
was imported before was empty (cozy-authentication@2.3.3), so this is
not a breaking change.

fix: Remove import to stylesheet

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

https://github.com/cozy/cozy-libs/pull/1118 caused a regression where harvest is not able to find the bankId in the user account anymore.
This PR fixes this.
BUT, since getUserConfig and updateUserConfig need the bankId
the applications using it will need to pass the user account.

fix(Harvest): Regression on handling banking connectors where bankId is chosen by the user

---

packages/cozy-harvest-lib/package.json
yarn.lock

A quick Pr to update cozy-bi-auth to v 0.16.0
It brings a new complete BI mapping for 35 new banking connectors

feat(harvest): Upgrade cozy-bi-auth

---

packages/cozy-authentication/package.json
packages/cozy-authentication/src/steps/SelectServer.jsx
packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.input.js
packages/cozy-codemods/src/transforms/__testfixtures__/replace-icons-svgr.output.js
packages/cozy-codemods/src/transforms/replace-icons-svgr.js
packages/cozy-doctypes/package.json
packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/BanksLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/Success/DriveLink.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorUpdateLinker.jsx
packages/cozy-notifications/package.json
packages/cozy-procedures/package.json
packages/cozy-procedures/src/components/Topbar.jsx
packages/cozy-procedures/src/components/documents/DocumentHolder.jsx
packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadMobile.jsx
packages/cozy-procedures/src/components/documents/menuUpload/MenuUploadWeb.jsx
packages/cozy-procedures/src/components/overview/DocumentsFullyCompleted.jsx
packages/cozy-procedures/src/components/overview/DocumentsNotFullyCompleted.jsx
packages/cozy-procedures/src/components/overview/PersonalDataNotFullyCompleted.jsx
packages/cozy-scanner/package.json
packages/cozy-scanner/src/DocumentQualification.jsx
packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap
packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/Recipient.jsx
packages/cozy-sharing/src/components/ShareButton.jsx
packages/cozy-sharing/src/components/ShareByLink.jsx
packages/cozy-sharing/src/components/SharedBadge.jsx
packages/cozy-sharing/src/components/Sharetypeselect.jsx
packages/playgrounds/package.json

This way, apps do not have to include the full icon sprite.

SVGr icons in cozy-authentications and cozy-sharing

---

packages/cli-tree/examples/users.js
packages/cozy-codemods/README.md
packages/cozy-codemods/package.json
packages/cozy-codemods/src/cli.js
packages/cozy-codemods/src/hoc.js
packages/cozy-codemods/src/imports.js
packages/cozy-codemods/src/transforms/apply-flag.js
packages/cozy-codemods/src/transforms/button-new-api.js
packages/cozy-codemods/src/transforms/new-icons.js
packages/cozy-codemods/src/transforms/remove-boolean-vars.js
packages/cozy-codemods/src/transforms/remove-unused-imports.js
packages/cozy-codemods/src/transforms/replace-icons-svgr.js
packages/cozy-codemods/src/transforms/transform-list-item-attributes.js
packages/cozy-codemods/src/transforms/transform-typography.js
packages/cozy-codemods/src/transforms/use-breakpoints.js
packages/cozy-codemods/src/transforms/use-client.js
packages/cozy-codemods/src/transforms/use-i18n.js
packages/cozy-codemods/src/transforms/use-q.js
yarn.lock

Makes it much easier to use.
See README for instructions.
This makes it possible to run a codemod without manually wiring jscodeshift and a @cozy/codemods transform file from node_modules. 
```patch
- $ jscodeshit -t node_modules/@cozy/codemods/src/transforms/apply-flag.js --flag=my-flag
+ $ cozy-codemods run apply-flag -- --flag=my-flag
- $ ls node_modules/@cozy/codemods/src/transforms/
+ $ cozy-codemods list # List available transforms
- $ git diff node_modules/@cozy/codemods/src/transforms/__testfixtures__/apply-flag.{input,output}.js
+ $ cozy-codemods showExample apply-flag # Show an example of what a transform does
```

Add CLI for @cozy/codemods

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx

After an update of cozy-ui, it is necessary to put the `open` prop
on Dialogs.

Fix dialog not opening

---

packages/cozy-sharing/package.json
packages/cozy-sharing/src/components/EditableSharingModal.jsx
yarn.lock

This can greatly speed up contact search for sharing.
With 5K contacts, including only 1 relevant contact (having an email for instance) : 
* Without partial index : ~4700 ms
* With partial index : ~20 ms 
In any case, the query will be faster as the partial index filter out contacts without email/url and deleted contacts.

feat: Use partial index to speed up contact search

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/SyncContractSwitch.spec.jsx
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

Toggling syncing of a contract did not work because of a renamed variable.

Fix: Contract sync

---

packages/cozy-harvest-lib/src/connections/accounts.js
packages/cozy-harvest-lib/src/connections/accounts.spec.js
packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js

Some accounts are not linked to any trigger anymore.
This is due to old bugs or when the user closes his window
too soon.
This PR will reuse these accounts, related to the same connector (via
account_type), fill them with new identifiers and link them to a new
trigger.

feat(Harvest): Reuse unlinked accounts

---

packages/cozy-harvest-lib/src/helpers/accounts.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/test/helpers/accounts.spec.js

When account is soft deleted by cozy pass, identifiers are removed on
the account and checking identifier to restore an account has no
meaning since identifiers will be overwritten just after.

fix(Harvest): Remove check on identifiers for account rescue

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx

When the connector policy does not need to save the cipher in the vault, we
do not need to display the vault unlocker when deleting the concerned
cipher from the vault. This is the case for example for banking connectors.
The problem here was that without the fix, the VaultUnlocker would be
displayed, but it returned null because of the saveInVault condition in the
VaultUnlocker render code, thus we could not delete a banking connector account from harvest.

Fix banking connector deletion

---

packages/cozy-harvest-lib/src/components/AccountModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/Routes.jsx
packages/cozy-harvest-lib/src/components/hooks/useDOMMutations.jsx

- Do not center the modal to prevent jumps due to tab change
- Update modal height after subtree change

Improvements to harvest modal

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/EditContract.jsx

onClose was overriden by the dialogProps, we need to pass onClose to
useCozyDialog

fix: Close edit contract modal on escape

---

packages/cozy-harvest-lib/src/components/DisconnectedAccountModal.jsx
packages/cozy-harvest-lib/src/locales/fr.json

- Make wording Cozy agnostic, this is easier to do that than to do an override in Harvest when dealing with a vendored banks.
- Use new tabs in disconnected account modal

Improvements

---

packages/cozy-scanner/src/locales/en.json

The previous label had a typo + was missing precision about the vehicle

fix: Rename vehicle registration

---

packages/cozy-procedures/package.json
packages/cozy-procedures/src/Procedure.jsx
packages/cozy-procedures/src/redux/documentsDataSlice.js
yarn.lock

We moved this fetching in cozy-client as it is where the qualification
model is handled. This also fix a bug where documents without
`metadata.datetime` were filtered out.

feat: Fetch documents through cozy-client helper

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/sentry.js
yarn.lock

First step in the integration of Sentry. Next step would be to
integrate a React error boundary connected to the hub, wrapping all
the Harvest routes. Since sentry React integration uses the global hub,
we cannot use directly.
We use a Hub instead of a global Sentry since harvest is used by other apps.

feat: Add sentry integration to harvest connection flow

---

packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js

There is already a default 8s value and 80s to wait for a login success is too long.

fix(Harvest): Remove wrong 80s job watcher delay

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.spec.js
packages/cozy-harvest-lib/src/sentry.js

- Correctly send events in production
- Send original error instead of the konnector job error that is more for users

Sentry fixes

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx
packages/cozy-harvest-lib/src/components/KonnectorBlock.spec.jsx
packages/cozy-harvest-lib/src/helpers/queries.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
yarn.lock

On souhaite avoir un composant standalone qui permet d'afficher un bloc d'information sur le connecteur, afin entre autre d'agrémenter le Viewer augmenté.
Ceci est une première étape qui consiste à afficher le nom du connecteur avec un lien vers la popup d'harvest (il n'y a donc pas l'email ni le téléphone), ainsi que le compte client.

feat: Add KonnectorBlock to show konnector informations

---

packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/BankAccount.spec.js

When merging relationships, we would kept the relationships items
of the old document due to an ordering typo.
This caused a bug where when updating the relationships.connection of a banking account, it would keep the old connection. This means that if a user disconnects and reconnects a banking connection, its accounts would show as "Disconnected" in Banks UI since the connection id in the banking accounts was not updated.

feat: Correctly update relationships when reconciliating accounts

---

packages/cozy-harvest-lib/README.md
packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/RedirectToAccountFormButton.jsx
packages/cozy-harvest-lib/src/components/cards/AppLinkCard.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/components/infos/TriggerErrorInfo.jsx
packages/cozy-harvest-lib/src/helpers/konnectors.js
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/logger.js
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/konnector/KonnectorJobWatcher.js

- Add a button for the user to reconnect easily in case of LOGIN_FAILED
or CHALLENGE_ASKED
The button is displayed in the error info card. This way, the user
is brought to the form to reconnect, and will not be mistaken into
clicking the "launch" button that only restarts the job without
doing the client-side process with budget-insight.
- Deactivate auto success when clicking the launch button
We do not want auto success in this case, auto success is only
when connecting for the first time.
- Add logs
Logs are helpful when debugging. A good next step would be to store
the logs in memory and for the user to have a way to send them easily in case
of a problem. Could this be done via Sentry ?

Improve 2FA process

---

packages/cozy-doctypes/package.json
packages/cozy-doctypes/src/banking/BankAccount.js
packages/cozy-doctypes/src/banking/label-slugs.js
packages/cozy-doctypes/src/banking/matching-accounts.js
packages/cozy-doctypes/src/banking/matching-accounts.spec.js
packages/cozy-doctypes/src/banking/slug-account.js

After a connector has fetched banking accounts, we use heuristics to match downloaded accounts with
the ones that are already stored. Here the heuristic led to a false positive and two unrelated
accounts were considered a match.
Say we have 1 account in database, { number: '01234567890' } and 1 downloaded account { number: '89' }.
Previously a="01234567890" would match b="89" since a.length == 11 and b is contained in a. This can lead to false positives: an account being matched with another account where they should not be matched.
We add a rule on the minimum length of account numbers for the approx-number rule.
To remedy this problem, we impose a minimum length on b, if its
length is inferior to 4, we do not generate a match.

Approx number match improved

---

packages/cozy-harvest-lib/src/services/budget-insight.js

Previously, we would target ask a temporary token to the banking
connector. The banking connector would reply with a *maif* BI enpoint
compatible token since it is configured via stack secrets. Then, our
front-end would try to talk to *our* BI prod on the front-end with the
previously fetched token. Since the token is specific to a BI endpoint,
the front-end had 401 responses.

feat: Support for MAIF staging cozys to talk with the right BI endpoint

---

packages/cozy-sharing/__tests__/fixtures.js
packages/cozy-sharing/src/state.js
packages/cozy-sharing/src/state.spec.js

We have an use case when a permission looks like the one added
in the fixture. Resulting by trying to iterate on undefined...
So if there is no value, there is no need to iterate on it since we
can't sort documents by id... 
Since we don't know exactly how to deal with this issue yet, I 
returned an empty [] as a quick fix.

fix: Don't crash if there is no value inside a permission

---

packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx
packages/cozy-harvest-lib/src/components/KonnectorBlock.spec.jsx
packages/cozy-harvest-lib/src/helpers/konnectorBlock.js
packages/cozy-harvest-lib/src/helpers/konnectorBlock.spec.js
packages/cozy-harvest-lib/src/helpers/queries.js
packages/cozy-harvest-lib/src/locales/en.json

On souhaite gérer dans KonnectorBlock les erreurs renvoyées par le connecteur et afficher différents messages selon différents cas : 
- connecteur désinstallé
- compte déconnecté
- connecteur en maintenance
- compte en erreur
- mise à jour disponible
Chaque cas renvoie un résultat différent et affiche donc le bloc de connecteur selon un certaine manière.

feat: KonnectorBlock handles konnector errors

---

packages/cozy-harvest-lib/src/components/TriggerManager.jsx
packages/cozy-harvest-lib/src/components/TriggerManager.spec.jsx

We had an exception when the TriggerManager was not wrapped in a vault
context. It did not matter when the konnector that was dealt with did
not need to be saved in the vault (banking connectors for example).
After the fix, we do not need to wrap the TriggerManager in a vault ctx
if we are only dealing with konnectors that do not need to save in the
vault.
At the same time, crash with a helpful error if we deal with konnectors
that need to be saved in the vault while the TriggerManager has not
been wrapped in a VaultContext

fix: Only check if vault is locked if konnectorPolicy says to save in vault

---

packages/cozy-harvest-lib/package.json
yarn.lock

Upgrade the cozy-bi-auth package to 0.0.17 with some new mapping for 14 futures connectors.

feat: Upgrade cozy-bi-auth with some new banking connectors

---

packages/cozy-flags/src/flag.js

Prefer Q().getById() over deprecated client.get

fix: Do not use deprecated client.get

---

packages/cozy-harvest-lib/src/helpers/oauth.js

After the OAuth dance, the stack redirects to the home application by
default.
This sets the current application as the default redirect

feat(Harvest): Set the current app as default redirect slug for OAuth

---

.remarkignore
.remarkrc
.travis.yml
package.json
packages/babel-preset-cozy-app/README.md
packages/browserslist-config-cozy/README.md
packages/cli-tree/README.md
packages/commitlint-config-cozy/README.md
packages/cozy-app-publish/README.md
packages/cozy-authentication/README.md
packages/cozy-codemods/README.md
packages/cozy-doctypes/README.md
packages/cozy-doctypes/src/banking/README.md
packages/cozy-flags/README.md
packages/cozy-harvest-lib/README.md
packages/cozy-interapp/README.md
packages/cozy-logger/README.md
packages/cozy-mjml/README.md
packages/cozy-notifications/README.md
packages/cozy-procedures/README.md
packages/cozy-realtime/README.md
packages/cozy-release/README.md
packages/cozy-sharing/README.md
packages/eslint-config-cozy-app/README.md
packages/playgrounds/README.md
packages/renovate-config-cozy/README.md
packages/repo-doctor/README.md
packages/webpack-expose-package-info-plugin/README.md
yarn.lock

- Brings coherence to the way we write markdown
- Catches easy to miss errors like missing break lines before a
code block (works on GitHub, not on mkdocs)

Add linter for docs

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx

Context:
1. the slides of the harvest konnector modal are in a swipeable
views.
2. content of slides can be dynamically computed
3. for slides of swipeable views to take the height of the current
child, we need to set animateHeight to true and watch for
subtree dom modifications
Bug:
A big white block was visible in the data tab when the content
of the configuration tab was much bigger (4). This is because a previous
commit removed the dom watching (necessary for 2) and thus the height
was not set dynamically (see 3).
The previous commit had removed updateHeight and animateHeight to
solve a bug where the content of the configuration was cropped
only when there was an error for the konnector. The fix meant
that the swipeable wrapper took the height of the tallest
slide, solving the …

Fix : correctly update slide height of harvest modal

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
packages/cozy-harvest-lib/src/services/jobUtils.js

Instead of waiting 15s, we wait 30s, we've seen an instance of
reatime job taking 15s.
Fix https://github.com/cozy/cozy-libs/issues/1250

Wait a little longer for realtime event

---

packages/cozy-harvest-lib/src/components/OAuthForm.jsx
packages/cozy-harvest-lib/src/components/OAuthForm.spec.js
packages/cozy-harvest-lib/src/components/__snapshots__/OAuthForm.spec.js.snap

This caused an assert to fail in createTemporaryToken function in
BI service.
This error was visible with webauth connectors.

fix(Harvest): Missing account param for fetchExtraOAuthUrlParams

---

packages/cozy-sharing/__tests__/fixtures.js
packages/cozy-sharing/src/state.js
packages/cozy-sharing/src/state.spec.js

Lors d'un partage en "can change" c'est à dire "two-way", le destinataire était affiché étant en "can view" c'est à dire "one-way" dans la liste des destinataires.
C'est maintenant corrigé.
**Attention** on ne change pas le comportement pour le destinataire lors sur un lien de partage non approuvé. Dans ce cas, on a toujours "one-way" pour le destinataire, même si l'expéditeur a choisi "two-way". Car on se base sur les rules pour définir si on est en "one-way" ou "two-way", or il n'y a pas de rule pur un partage non approuvé. Pour ça il faudrait se baser sur les `read_only` des membres plutôt que les rules. Issue https://github.com/cozy/cozy-libs/issues/1229#issuecomment-780410677

fix: Sharing type for recipients in sharing modal

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

createTemporaryToken results with cozy bank id (old linxo bank id). This bi
bank id is needed to calculate the webauth redirect url.
remove account assert in createTemporaryToken:
This function can be called without any account to calculate the webauth
redirect url, before any account creation.

fix(Harvest): Get bi bank id in fetchExtraOAuthUrlParams

---

packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

Correctly retrieve the bi config that has been saved in the
connection flow, after getTemporaryToken. The code has not
been modified to use biConfig after the update of 
getTemporaryToken to retrieve bi configuration along the
temporary token.

Fix OTP + 2FA flows

---

packages/cozy-doctypes/src/banking/BankingReconciliator.js

In some cases (ex nestor connector with many transactions), the banking
reconciliator can generate a lot of logs, which is suspected to case
memory errors in connector's worker.
This logProgress added option allows to not log each transaction with
the `null` value and this option can be chosen by the connector.

feat(cozy-doctypes): Avoid a log for each transaction

---

packages/cozy-harvest-lib/src/services/bi-http.js
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

In case of outdated, non existing connection id defined in the account.
The connection would fail with an unknown error caused by harvest trying
to update a non existing bi connection -> 404
This case is not supposed to happen but still happend because we do not
handle a double decoupled 2FA, which will be fixed in another PR. And
the user is blocked trying to authenticate his bank account and failing
miserably.
Now, we first check if the connection id is valid and create a new
connection if the connection id is not valid

fix(Harvest): Recreate non existing BI connection saved in account

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

Some BI connectors may have multiple sources and sometimes, both sources
may need a decoupled 2FA. Ex Crédit Mutuel.
In case of a double decoupled 2FA before, harvest would send LOGIN_OK
event after the first decoupled 2FA.
Now, harvest will loop until the connection state is different from
'decoupled' or 'additionalInformationNeeded'

feat(Harvest): Handle multiple decoupled states

---

packages/cozy-harvest-lib/package.json
packages/cozy-harvest-lib/src/components/TwoFAModal.spec.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js
yarn.lock

BI does not allow to update fields of a decoupled connection
+ decoupled locales update
+ upgrade cozy-bi-auth

fix(Harvest): Do not try to update decoupled bi connections

---

packages/cozy-harvest-lib/src/components/EditAccountModal.jsx
packages/cozy-harvest-lib/src/components/hooks/useTimeout.jsx

Not too proud of this but I cannot see any other quick solution.
Since the TriggerManager when mounted will check to see if 
vault needs to be unlocked, we could have a jarring effect where
the edit modal is opened, then it disappears and the vault unlocker
is shown. To prevent this problem, we delay a bit the appearing
of the edit modal, this way if the vault needs to be unlocked, the
edit modal will not have appeared yet.

feat: Remove jarring effect when opening edit account modal

---

packages/cozy-sharing/src/components/ShareAutosuggest.jsx
packages/cozy-sharing/src/suggestionMatchers.js
packages/cozy-sharing/src/suggestionMatchers.spec.js

On souhaite pouvoir récupérer un contact grâce à son fullname (nom, prénom, pré et suffixe de nom) dans la modale de partage

feat: ShareAutosuggest can now handle with contact fullname

---

packages/cozy-scanner/src/DocumentQualification.jsx
packages/cozy-scanner/src/__snapshots__/DocumentQualification.spec.jsx.snap

to better fit with muiv4
**BEFORE :**
**AFTER :**

fix: Adjust DocumentQualification grid spacing

---

packages/cozy-harvest-lib/src/components/KonnectorBlock.jsx

Les icons n’apparaissent pas en mobile avec le composant AppIcon.
Pour ne pas bloquer la release de Drive qu'on aimerait déployer asap, on applique ici le même patch qu'on a appliqué dans Drive : https://github.com/cozy/cozy-drive/pull/2229/files
Une autre PR va voir le jour pour corriger le souci dans UI : https://github.com/cozy/cozy-ui/pull/1775

feat: KonnectorBlock use its own fetchIcon func for AppIcon comp

---

packages/cozy-doctypes/src/Document.js
packages/cozy-doctypes/src/Document.spec.js

This allows the user of bulkSave to decide what do to do with errors.
The onCreateOrUpdate callback receives (error, doc) as arguments and
its result will be put in the result array returned by bulkSave.
This way, the user can extract errors after the save and decide what
to do with them (maybe retry them)

feat: Allow to pass onCreateOrUpdate error to bulkSave

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/Contracts.jsx

We need to fetch the owner when fetching the contracts.
Otherwise the owner is not correctly shown in the contract edit
screen.

feat: Include owners in Contracts query

---

packages/cozy-harvest-lib/src/components/AccountsList/Status.jsx

Since in a next version, cozy-ui will rename u-valid into u-success,
we add both classes to be compatible with every version of cozy-ui.
* There were no u-warn used (renamed to u-warning)
* There were no u-danger used (deprecated inf favor of u-error)

feat: Add u-success className to be forward compatible with cozy-ui

---

packages/cozy-harvest-lib/src/components/FlowProvider.jsx
packages/cozy-harvest-lib/src/components/FlowProvider.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.jsx
packages/cozy-harvest-lib/src/components/KonnectorModal.spec.jsx
packages/cozy-harvest-lib/src/components/TwoFAModal.jsx
packages/cozy-harvest-lib/src/components/cards/LaunchTriggerCard.jsx
packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.jsx
packages/cozy-harvest-lib/src/components/cards/WebsiteLinkCard.spec.jsx
packages/cozy-harvest-lib/src/components/infos/KonnectorUpdateInfos.jsx
packages/cozy-harvest-lib/src/models/ConnectionFlow.js
packages/cozy-harvest-lib/src/models/flowEvents.js
packages/cozy-harvest-lib/src/models/withConnectionFlow.jsx
packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

Now, a user can launch the connector via the launch button and have the
two fa modals.
When launching the konnector, since we do not have the BI connection
cached (we do not launch a temporary token job, the front cannot access
budget-insight), we send the two fa codes to the konnector job via
the regular two fa APIs.

feat: Support two fa in launch mode

---

packages/cozy-sharing/src/components/ShareByLink.jsx

Le bouton "générer un lien" se met par-dessus le bottomDrawer de l'action menu sur iOS.
Le bug n'est présent que sur iOS, cela fonctionnait sur Safari web (tout comme avec les autres browser).
La modification n'impacte pas les autres navigateurs. Je n'ai pas trouvé d'autre solution pour corriger le problème.
J'ai essayé de jouer avec les z-index et position sur les overlay/dialog/action menu, j'ai essayé de modifier le type de button également...
Une autre approche serait de ne pas utiliser de `Button` mais un `<button>` plus classique, mais on perd le bénéfice de l'api (notamment le busy) et de la cohérence du style - ça ferait un composant spécifique à maintenir, je n'ai donc pas retenu cette approche.

fix: ShareByLink z-index on iOS

---

packages/cozy-harvest-lib/src/services/budget-insight.js
packages/cozy-harvest-lib/src/services/budget-insight.spec.js

BI expects field validation to be done front-side. If input does not
match the regex from BI, a "config" error is sent back to us, this is
why we map it to LOGIN_FAILED.
Ideally we would want to dynamically load validation rules from BI
side but it is complex since we have to handle
- Loading validation rules for agencies (biBankId not known until the user
has chosen an agency)
- Converting BI field names to cozy field names
Work on this has been started [here](https://github.com/cozy/cozy-libs/tree/dynamic-validation-rules) but it seems overly complicated and we're not sure with @fffflo that we want to manage this complexity, especially when we are thinking to use BI's webview to manage the lifecycle of connections in the future.

feat: Map config errors to LOGIN_FAILED

---

packages/cozy-authentication/src/locales/en.json
packages/cozy-authentication/src/locales/fr.json

When using cozy-drive in french and connecting to your cozy, the address placeholder contains domain despite there is a separate domain input box, show the domain twice.
This PR updates french translation to fix this behaviour.
I also updated some unrelated english strings to make them coherent with french translation.
And I fixed missing space before question mark (french typography rules)

fix: Update cozy-authentication address placeholder in french

---

packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/ConfigurationTab/index.spec.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/DataTab/index.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.jsx
packages/cozy-harvest-lib/src/components/KonnectorConfiguration/KonnectorAccountTabs.spec.jsx
packages/cozy-harvest-lib/src/components/Markdown.jsx
packages/cozy-harvest-lib/src/locales/en.json
packages/cozy-harvest-lib/src/locales/fr.json
packages/cozy-harvest-lib/src/services/budget-insight.js

feat: Remove references to "cozy" in harvest locales
Makes it easier to customize and whitelabel the UI
Show konnector error in both data and configuration tab in harvest
Open external links in a new tab not to lose the Cozy context

Small improvements for Harvest
